### ISSUE TITLE
Convention: Misplay cm to 2 separate players

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#101]
![2019-11-17_0003_(Double_chop_move_maybe)](https://user-images.githubusercontent.com/48993588/69005036-adc7e580-08d0-11ea-9cb7-e2bf4fd00ebb.png)

Saw this idea in this game of duck.  I am not submitting this as only a duck convention.  What if Kakashi did 1's to Valetta initiating a UTD.  It is not a Trash Double Bluff because this is a game of duck.  The idea is that Kopen would bomb R2 doing the UTD.  Valetta will know her cards are trash and she will trash chop move all the cards to the right of trash.  Kopen would treat this as an extension of misplay chop move and chop move all the cards to the right of the misplay card.  What do you guys think?

**Comment by alercah** [comment]
Who's Valetta?

**Comment by Zamiell** [comment]
sounds like a context read. in other words, if valetta trusts kakashi, then she will chop move her cards in the absense of any pre-stated conventions. thus, it probably doesn't need to be officially codified, since the application of this would be quite rare.

**Comment by Dr-Kakashi** [comment]
I know it's been 6 days since a response has been given from me, but I'm not closing this as I'll try to see if I can find more examples.

**Comment by Zamiell** [comment]
since no-one else has chimed in, lets just keep this as a context read for now
/deny
