### ISSUE TITLE
Convention Rework: Duck Trash Ejection

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#102]
Played duck today and realized this convention needs to be reworked due to the introduction of 5CE.  

I think it needs to be reworked to this:
Slot 1: Cards that are true finessed (bluff is off in duck) or known bluff
Slot 2: Standard Ejections
Slot 3: Duck Trash Discharge
Slot 4: Unknown Trash Double Discharge

**Comment by Zamiell** [comment]
i agree that 5CE (2-for-1) is better than a trash finesse/trash bluff (1-for-1)

i deleted the *The Duck Trash Ejection* section out of the doc for now

**Comment by Zamiell** [comment]
there does not need to be an explicit convention for Duck Trash Discharge, i believe it is the same thing as a normal UTD

what on earth is a Unknown Trash Double Discharge

**Comment by Dr-Kakashi** [comment]
Discharge means slot 3, we don't have a term for slot 4, so I just called it double discharge

**Comment by Zamiell** [comment]
yeah but can you type out an alice and bob story for slot 3 and slot 4?

**Comment by Zamiell** [comment]
closing this since kakashi isn't responding
/stale
