### ISSUE TITLE
Exception to Duck Chop Saves

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#105]
I believe we should add an exception to duck chop saves.  If 3+ cards are touched in early game, where the focus is chop, it is highly unlikely that they are all 5's or 2's and should be treated as a play.

**Comment by Zamiell** [comment]
what do you propose to do when a player has a 5 on chop and they have three 5's in their hand

**Comment by Dr-Kakashi** [comment]
If no other player clues are available and that was given, then it's a save on 2's or 5's.  If you touch 3+ cards in someone's hand and they see that there are 2 or more plays to give, then it should be treated as a play clue.  

Turn Number: 1 (First Turn of the Game)
Table State: No cards played
Alice's hand: x - x - x - x - x
Bob's Hand: x - x - B5 - G5 - Y5
Cathy's Hand: x - B1 - R1 - x - x

In a situation like this if Alice clue's Cathy then Bob will discard.  Alice clue's Bob's 5's.  Since 1's could've been given to Cathy, Bob should think this is a play clue.  However, since from Alice's point of view only 1 play could be given to Cathy, Bob should assume it's a save on 2's or 5's.  

The goal is to have a way to play chop.  If this exception isn't good enough and/or requires too much headspace, maybe we could propose a new convention like....if you reclue a 5 and it can not be a triple bluff and/or a true finesse since 2+ cards are required to be played, then it should be a charm for a play on the right most card.  Not necessarily for the card on chop as a card may be chop moved.

**Comment by Zamiell** [comment]
```
If no other player clues are available and that was given, then it's a save on 2's or 5's. If you touch 3+ cards in someone's hand and they see that there are 2 or more plays to give, then it should be treated as a play clue.
```
that is already how we play. no further convention needs to be defined for this
