### ISSUE TITLE
5CE in Duck

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#106]
All 5's touched by color and/or rank should be treated as 5CE if the 5CE's rules are satisfied.  i.e. if 2+ cards are needed to finesse the 5, it is highly unlikely.

**Comment by Dr-Kakashi** [comment]
Table State: No Cards Played
Bob's Hand:  x - Y1 - x - x - x 
Cathy's Hand: R2 - R5 - B1 - x - x

Alice clue's 5's to Cathy.  Since 5 pulls are off, it isn't a 5 Pull.  Clearly rank was given; however, Cathy can't interpret that in Duck.  It must be a 5CE on Bob.  Bob plays Y1

**Comment by Zamiell** [comment]
seems fine

**Comment by Zamiell** [comment]
**5 Ejection** (in Duck) (by Kakashi)

* *5 Color Ejection* is turned on in Duck variants, as you would expect.
* Additionally, players can also perform *5 Number Ejection* and it will generally work in the exact same way.
* Thus, players should keep in mind that clues that cause *Ejection* might have been either a color clue or a number clue.

**Comment by Dr-Kakashi** [comment]
Thank Zam.  I'll let you do the accept command to close this
