### ISSUE TITLE
Example Submission 

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#107]
![2019-11-18_0321](https://user-images.githubusercontent.com/48993588/69048592-b55fbb00-09b2-11ea-93ef-9378b71be88b.png)

Interesting example.  Asaelr's B4 was finessed earlier.  I believe this is an Unnecessary Trash Push that turns into a Trash Double Bluff.  What do you guys think?

**Comment by iamwhoiamhahaha** [comment]
I would call it as "jump trash double bluff"

**Comment by Dr-Kakashi** [comment]
You mean OOP Trash Double Bluff?

**Comment by Zamiell** [comment]
by convention asael bombs r1

**Comment by Zamiell** [comment]
in a hypothetical where asael is already locked into playing b4, then the move can work

**Comment by Dr-Kakashi** [comment]
Yes, asaelr is locked into playing B4 as it was layered in.  Since that is the case and it is indeed a legal move.  What is the name of this convention?  I'm thinking it is an OOP Trash Double Bluff.

**Comment by Zamiell** [comment]
i dont think it needs to be added to the doc, as it is an edge case
