### ISSUE TITLE
Duck 4 Charm (Positional Clue)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#108]
![4 Charm](https://user-images.githubusercontent.com/50160641/69063484-86e7eb80-0a57-11ea-947d-d5b1d032ba83.png)

If the player gives a play clue on a 4 in duck variant, and the next player needs to blind-play two or more cards to fulfill the finesse, then they should blind-play slot 4 as a Duck 4 Charm.

This convention is awesome. Have used so many times with Kakashi and Valetta. (We made all perfect scores in 3-player duck variants)

**Comment by iamwhoiamhahaha** [comment]
In general, in duck variants,

Slot 2: 5CE (and also be given with number clue in some cases)

Slot 3: UTD (only the focus is a trash)

Slot 4: This new position clue (by touching a 4)

**Comment by iamwhoiamhahaha** [comment]
And how about,

Slot 5: Unknown Trash slot-five-thing (touching 2+ Trash at the same time)

And only turn on in 3-player duck variants

**Comment by Zamiell** [comment]
> Slot 2: 5CE (can also be given with number clue in some cases)
> Slot 3: UTD (only the focus is a trash)
> Slot 4: This new position clue (by touching a 4)

seems fine

**Comment by Zamiell** [comment]
**4 Charm** (in Duck)

```
* This convention only applies to Duck variants.
* *Charm* is defined as a move that makes a player play their *Fourth Finesse Position*.
* Similar to *5 Ejection*, if a player gives a *Play Clue* to an unplayable 4 that would require two or more blind-plays in order to fulfill the *Finesse*, then a *Finesse* is unlikely.
* Players agree that this communicates a *Charm*.
* Similar to *5 Ejection*, *4 Charm* can be initiated with either a color clue or a number clue.
```
