### ISSUE TITLE
Convention Proposal: Duck Positional Clues

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#109]
![2019-11-18_0654](https://user-images.githubusercontent.com/48993588/69063291-15fdf080-09d1-11ea-9565-7c5f96879d87.png)
![2019-11-18_0655](https://user-images.githubusercontent.com/48993588/69063293-16968700-09d1-11ea-8720-e2bbfcb2ab58.png)
![2019-11-18_0656](https://user-images.githubusercontent.com/48993588/69063296-16968700-09d1-11ea-9772-ac4e16a0b7fe.png)

Jeff made this proposal during a game.  The idea is if the conditions of 5CE are satisfied, i.e. 2+ blind cards needed to play, then it should be treated as a positional clue.  In these examples 4's are used.  I believe since 3 bluffs are turned off in Duck, 3's can be used as a positional clue.  The problems I see with this is that it can conflict with double bluff's.  If that is the case, maybe we can set it to be 3+ cards to play, so only 4's (with no 1's played) are valid.

**Comment by Zamiell** [comment]
overlaps with the rules that jeff outlines in #108
