### ISSUE TITLE
Request: Variant Specific Conventions 

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#110]
I was looking through the doc and realized how....long and lengthy it is.  What do you guys think about having Variant Specific Conventions having their own separate section?  We can move all the variant-specific conventions to their own doc as one or we can make a separate section for each variant.

**Comment by Zamiell** [comment]
the point of having it in one doc is so that you can just ctrl+f to go to the place you need instantly

**Comment by Dr-Kakashi** [comment]
That's fine too, whichever way is more user friendly.
