### ISSUE TITLE
Convention Proposal: Early Game Positional Misplay

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#111]
I know positional misplaying in early game is so risky, considering you could be bombing a 5.  However, I've been doing it for situations where cards are hard to get.  For example in brown to get n1 and n2 to play, which otherwise would just be a pain to get.  In pink I do it for i1 and i2.  Of course in both situations, those brown and/or pink cards are stuck in the middle of a normal clue.  So, basically it would take 3-4 clues to get 2 cards to play.  I was thinking if it would be wise to formalize this into a convention?  

I was also thinking that in a no variant, we can have it such that it gets 3 players to play instead of just 2, since it is so risky and to prevent many players from doing this, if it even gets formalized.  Basically, it's a way to get a triple bluff by just misplaying.  

Dump truck has been deleted, so a misplay from chop could just signal 2-3 players to blind play their chop for example.  Depending on how we define this.  Which honestly wouldn't be so bad, considering it's hard to get cards on chop to play (brown for example) or having to spend 2-3 clues to individually clue each player.  

Cons to this is of course bombing a 5.

**Comment by jakestiles** [comment]
I think the other con is that it can turn an accidental misplay into 2 strikes instead of 1 (unless the team knows which mistake you’re making or that it’s not a positional misplay since no else has hard to get playable cards on that position).

But in high trust, difficult to win variants, early positional misplays for two cards seems reasonable. 

I don’t like it in no variant or other simple variants. How often are you losing a no variant game so badly that you need this? Also no variant is often a teaching environment where mistakes aren’t unheard of.

**Comment by Romain672** [comment]
For bounce on this idea : you have even need a missplay.
Imagine searly game, some card have been played. And you receive a 5 clue : x-5-x-x, and now you see some usefull card on third position.
There is actually no 'no-5' critical cards.
You finish the early game by discarding slot 3.
What does that mean?

**Comment by Zamiell** [comment]
> I know positional misplaying in early game is so risky, considering you could be bombing a 5. However, I've been doing it for situations where cards are hard to get. 

in most brown or pink variants this would almost certainly be a bad risk to take and almost certainly be a mistake. the reward would only be worth the risk in only the most difficult variants, and even then such a choice would be questionable.

**Comment by Zamiell** [comment]
> You finish the early game by discarding slot 3.

this would be the same risk as blind-playing, making the move equally as risky / stupid

**Comment by Romain672** [comment]
If you have negative 5, you only take the risk of discarding a 2 (20%? and perhaps 15%? where this discard matter) instead of an few usefull/useless 4/1.
So it doesn't seem bad even if it get only one blind play for free.

**Comment by Dr-Kakashi** [comment]
I'm not sure about that move Romain....I'm assuming you got 5 pulled with the 5...so you'll be discarding a playable card, which you really don't know what it could be without context.  

I don't really have much to add to my initial post.  Since Zam is saying that even in the most difficult variants a move like this is questionable, I'm taking it that this shouldn't be considered.  I won't close this as I'll give time for others to give their input.

**Comment by Zamiell** [comment]
if you have negative 5 then the move is a lot safer, but i am still not a fan, because often times players get accidentally chop moved, so this can cause cascading failure
