### ISSUE TITLE
Cow & Pig - Rank Saves

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#112]
* This convention only applies to *Cow & Pig* variants.
* Rank clues (oink) are always used to perform a *Save Clue*.
* Color clues (moo) must always be *Play Clues*.

**Comment by Dr-Kakashi** [comment]
I don't think so....I've done color clues on chop if it both saves and picks up another card like a 5

**Comment by NoMercyO** [comment]
In Im favor of disabling color saves for Cow and Pig.

**Comment by Zamiell** [comment]
you mean rank saves?
