### ISSUE TITLE
Example Submission: Turn 3 Trash Push

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#113]
![2019-11-23_0129_(Turn_3_trash_push)](https://user-images.githubusercontent.com/48993588/69476604-d2b8ce80-0d90-11ea-991d-4a0cef78d144.png)

Earliest Trash Push I've ever seen....Livia does Blue's to Micerang

**Comment by Zamiell** [comment]
is the blue 3 chop moved?

**Comment by Dr-Kakashi** [comment]
B2 was clued to get Livia's B1
Rakxer then clues me 4 finessing out the B3
At this point in the game all the blue cards are accounted for B1-B4 have been play clued and Livia can see that micerang can see the B5.

**Comment by Zamiell** [comment]
4's to you is focused on the green 4

**Comment by Zamiell** [comment]
number 2 to livia looks like a 2 save
