### ISSUE TITLE
New Convention: Up & Down 1CE or 5CE

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#114]
In a game of Up & Down let's say that the R5 has been played.  If a R1 is color clued, then it signals an ejection on the next player, assuming the 5CE conditions are satisfied.  Vice versa if going the opposite way.  R1 played and a R5 is color clued for example.

**Comment by Zamiell** [comment]
seems fine

**Comment by Dr-Kakashi** [comment]
Awesome! 1CE convention is born.  I'll let you close this one, since you have an automated setup to indicate an add to the document.

**Comment by Zamiell** [comment]
i dont get to decide whether or not 1ce is born

**Comment by Zamiell** [comment]
**1's Color Ejection (1CE)**

* Similar to *5 Color Ejection*, it is also possible to perform a *1 Color Ejection* in an *Up or Down* variant. This works in the exact same way, e.g. players use the "2 or more blind-plays" rule.
