### ISSUE TITLE
Muddy/Cocoa Rainbow Positional Clues 

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#116]
Proposal: Positional clues in Muddy/Cocoa Rainbow variants.

3 for m3
![muddy rainbow positional clues 1](https://user-images.githubusercontent.com/50160641/69493586-66061700-0eeb-11ea-9533-174e675575b1.png)

5 for m4
![muddy rainbow positional clues 2](https://user-images.githubusercontent.com/50160641/69493588-66061700-0eeb-11ea-83fc-c0be8658645b.png)

4 for m3
![muddy rainbow positional clues 3](https://user-images.githubusercontent.com/50160641/69493589-669ead80-0eeb-11ea-9250-3141093d9dfe.png)

3 for m4 (on slot 5)
![muddy rainbow positional clues 4](https://user-images.githubusercontent.com/50160641/69493590-669ead80-0eeb-11ea-94bf-cd1b0cf98303.png)

4 for m5
![muddy rainbow positional clues 5](https://user-images.githubusercontent.com/50160641/69493591-669ead80-0eeb-11ea-8223-0e08c89093cb.png)

**Comment by Zamiell** [comment]
come up with specific rules for when something is supposed to be interpreted as a positional clue

**Comment by iamwhoiamhahaha** [comment]
Rules: You can only perform a positional clue by touching a trash (if it doesn't look like a trash bluff/finesse) or a known playable card.

**Comment by Zamiell** [comment]
so trash chop moves are turned off?

**Comment by iamwhoiamhahaha** [comment]
trash chop moves are turned on and take precedence over positional clue. however, if the chop is trash (or doesn't look like a chop move) then it should be interpreted as a positional clue.

**Comment by Zamiell** [comment]
so that means that trash pushes are turned off

**Comment by iamwhoiamhahaha** [comment]
turned off

**Comment by Zamiell** [comment]
**Muddy/Cocoa Positional Clues** (by Jeff)

* This convention only applies to variants with a Muddy Rainbow suit or a Cocoa Rainbow suit.
* Any clue that looks like one of the following is instead considered to be a *Muddy/Cocoa Positional Clue* (that promises the slot number of the Muddy/Cocoa card to play):
  * *Double Play Ejection* (re-cluing a playable card)
  * *Known Trash Ejection* (re-cluing a known trash card)
  * *Trash Pushes* (cluing a known trash card on chop for the first time)
  * a rank clue that has no conventional interpretation
* Note that *Trash Chop Moves* are still "turned on".
