### ISSUE TITLE
Edit to Pink Convention on Trash Order CM

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#117]
I've noticed during a game of pink that you are almost unable to Trash Order CM.  Like if you get a 1's clue to do a trash push, the 1 on chop is promised to be 1, while the other 1 could be a pink 5 for example.  So I think there needs to be an edit in the doc somewhere to explain this.  It's still possible to do a Trash order CM, but you have to know you have multiple trash to do so.

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by Dr-Kakashi** [comment]
I don't know what a pr is....but I'm guessing you want an example?  

Variant: Omni
Card's Played: all 1's

Bob's hand: o3 - x - x - R2 - o1
Alice clues Bob 1
Bob plays R2 from the trash push
On Bob's next turn which card should he discard? 
Bob knows that the 1 on chop must be a 1 or some known trash, since it was the focus of the trash push.  However the other card picked up from the 1's clue could still be good or bad, due to the nature of pink.

**Comment by Zamiell** [comment]
a pr is a pull request

**Comment by Zamiell** [comment]
**Trash Pushes in Pink**

* When a *Trash Push* happens in a normal variant, if more than one card is touched, then all of the touched cards are known to be trash.
* When a *Trash Push* happens with a rank clue in a variant with a pink suit, if more than one card is touched, it is possible that only the card on chop was trash and that the other cards touched are useful / critical pink cards.
* In this situation, after blind-playing the *Trash Pushed* card, the player should first discard the card that initiated the *Trash Push* (the oldest card) and then hold on to the other touched cards.
