### ISSUE TITLE
Remove 3 Bluff

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#118]
So...I've been playing quite a few games and I'm starting to notice that maybe it would be beneficial to remove 3 bluffs.  We can have 3's be used as natural double bluffs and 4's as natural triple bluffs.  For the 4's triple bluff, this would cover situations where in the past the 2 blind played cards matched the 4.  It essentially clarifies the finesse as a true finesse.  3's will cover situations where giving a 4 to do a double bluff would be illegal, since 3's are now double bluffs. 

It might even simplify the game a bit to do this.  As now players will know the exact identity of the cards used to bluff.  Players will also understand that they are double or triple bluffed.  Currently, many players are confused with even using a clued 5 to start the triple bluff.   

Additionally, we have many ways to do chop moves, unnecessary trash conventions's for example.  I believe our conventions has evolved to the point where the pros favors this proposal.  As 5CE has changed the game significantly and even almost eliminated the possibility to do triple bluff's with 5's.  It's actually less efficient to do a triple bluff since recluing a 5 just gets a 3 for 1 instead of 4 for 1 in the past before 5 CE.  It's even debatable to just pass on giving the triple bluff to just do a normal double bluff as it's the same efficiency, while also a higher chance of players understanding a double bluff vs a triple bluff.  Though, I feel it would be best to have an open discussion on what you guys think.  

Another point is that 3 bluff is an artificial convention....all players have to agree before starting the game that 3 clues may call for just 1 card.  There's really no logical reason for it, besides understanding that we want to save 3's to increase the chances of not being bottom decked by a 3.   5CE is also an aritifical convention; however, I feel that 5CE's are a better artificial convention than 3 bluffs.  It might be best to just accept 5CE and remove 3 bluffs for the reason that we don't want our conventions and future conventions to be work arounds to artificial ones.  Like right now if I wanted to do a true 3 finesse from bluff seat, I need to intentionally dupe.  Cluing 2 R3's for example.

**Comment by iamwhoiamhahaha** [comment]
Yes, 3 double bluffs are much more efficient than 3 single bluffs, but the problem is: do we always have two playable cards on finessed positions? The answer is no. I prefer the original 3 bluffs that we can "save" a 3 all the time and also get a free card to play.

**Comment by Zamiell** [comment]
3 bluffs have generally proven over time to be much butter than double bluffs / double finesses

**Comment by Zamiell** [comment]
i dont think 5ce changes the calculus really, as it is easier to get a 3-for-1 with a 3 bluff than a 3-for-1 with a 5ce

**Comment by Dr-Kakashi** [comment]
3's can be used as a single bluff once a 1 has been played.  Basically, the window for a 3 bluff is early to early-mid game.

**Comment by Zamiell** [comment]
but notice that the exact time period that we want to "lock in" saves on 3's before they are discarded is often in the Early Game / on the first turn
