### ISSUE TITLE
Convention: Triple 5 pull

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#121]
Similar to a Double 5 pull only the next player knows that the card CM was playable.  

Cards played: None
Bob's Hand: R1 - x - x - x - x
Cathy's Hand: G1 - x - x - x- x
Donald's Hand: x - x - x - B5 - G2

Alice clues Donald 5 showing to the team that she's 5 chop moving the G2

Bob can see that Alice could've just given greens to Donald to finesse Cathy's G1.  The only reason why Alice would do this is because Alice is initiating a Triple 5 pull.  Bob plays R1. 
Similarily Cathy should be surprised that Bob played from just a 5 cm.  Cathy should realize the G2 must be playable and she must play otherwise Donald will bomb G2 thinking it's a double 5 pull. Cathy plays G1.

This convention can even go beyond.  Like if a 5 cm was done on a playable 3.  Though it would be rare, since you would need 5 players and the next 3 players must have all the connecting cards. Bob must have some playable card, Cathy must have R1, Donald must have R2, Ed R3 was 5 cm for example.

**Comment by Zamiell** [comment]
too edgecase to bother adding to the doc, but feel free to try the move in expert-only games

**Comment by Dr-Kakashi** [comment]
ok I'll close this then.
