### ISSUE TITLE
Example: Priority Elimination Finesse

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#122]
![2019-11-25_0343_(Elimination_Priority_Finesse)](https://user-images.githubusercontent.com/48993588/69538922-3cbfa800-0f38-11ea-961f-28c9f147ea84.png)

Props to kopen for seeing and doing this.  It's an example of a Priority Elimination Finesse.  
Asaelr has elimination notes on B2
kopen plays B1 instead of Y5

**Comment by Zamiell** [comment]
it is generally understood that any type of finesse (with the exception of the *Certain Finesse*) can be triggered by either giving a clue or playing a card without *Priority*.

thus, we don't really need to document all of the specific "priority" versions of the various types of finesses.
