### ISSUE TITLE
Example: No Information Finesse

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#123]
![2019-11-24_0202_(Two_no_information_finesse's_in_a_row)](https://user-images.githubusercontent.com/48993588/69540892-ae99f080-0f3c-11ea-8e54-4500081e693e.png)

![2019-11-24_0202_(Two_no_information_finesse's_in_a_row2)](https://user-images.githubusercontent.com/48993588/69541019-ffa9e480-0f3c-11ea-883a-b9b225ec7ee5.png)

This replay shows two no information finesse's given in a row.  So there's technically 2 examples of it here.

**Comment by Zamiell** [comment]
the first screenshot is just recluing a 5 to get a layered (single) finesse on a y3. that does not meet the definition of a *No-Information Double Finesse*.

**Comment by Zamiell** [comment]
the second screen is just recluing a 5 to get a single finesse on a r4. that does not meet the definition of a *No-Information Double Finesse*.

**Comment by Dr-Kakashi** [comment]
Oh! My mistake!
