### ISSUE TITLE
Jump Unknown Trash Discharge or Pass Discharge

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#124]
### Proposal A: Jump Unknown Trash Discharge

- Alice clues Donald an unknown trash. Bob sees Cathy has a playable card on her _Third Finessed Position_ and he discards. Cathy is surprised, if she does nothing, Donald would misplay the trash, then she blind-play her _Third Finessed Position_ as a **_Jump Unknown Trash Discharge_**. Donald knows his unknown card is trash.

- Note: **It doesn't matter (promise) if Bob has a playable card on his _Third Finessed Position_.**

- Pros: We can get a playable card from two-seat-away player.

- Cons: Lose the chance to get an uncluable card from Bob's hand, if he thinks Alice was doing a _Jump UTD_ instead of a normal _UTD_.

### Proposal B: Pass Discharge

- Alice clues Donald an unknown trash. Bob sees Cathy has a playable card on her _Third Finessed Position_ and he discards. Cathy is surprised, if she does nothing, Donald would misplay the trash, then she blind-play her _Third Finessed Position_ as a **_Pass Discharge_**. Donald knows his unknown card is trash. On Bob's next turn, he blind-plays his discharged card.

- Note: Like a _Pass Bluff_, Bob has a playable card on his _Third Finessed Position_, he just "passes" to Cathy to get a free card.

- Pros: Get a free card to play.

- Cons: Bob and Cathy might have same copies of cards on their _Third Finessed Position_, and Bob would bomb next turn if Alice doesn't fix. (Solution: Alice shouldn't steal Bob's clue in this case.)

**Comment by Zamiell** [comment]
not a big fan of these to be honest.

## Problem 1 - Bob Can Defer

* All of the 1's are played on the stacks.
* Alice clues Donald an unknown trash.
* Bob has a playable card on his slot 3.
* Bob clues Alice's red 3 on slot 1 as a *Play Clue*.
* Now it is Cathy's turn.
* If this is a *Finesse*, Alice should play the red 2 from her slot 1 as a *Finesse*.
* If this is a *Jump UTD*, Alice should play the red 3 from her slot 3 (and Bob's clue is just a normal *Play Clue*).
* Cathy has no way of determining which one it is so she just chooses the *Finesse* option. Cathy plays her slot 1 and it is the red 5 and it misplays and the team loses.

## Problem 2 - We Already Play with Ambiguous Positional Clues in Null and They Routinely Fail

I think the obvious analog here is *Positional Clues* in null variants. e.g. you see the slot 3 playable on someone else's hand, so you don't play. But *Positional Clues* have a **high tendency to fail**, especially when two players have null cards on the same slot. Games can get really complicated, so it is often times never as simple as your Alice & Bob story in Proposal A.

**Comment by iamwhoiamhahaha** [comment]
Agreed. I see the problems.
