### ISSUE TITLE
Clarify *No-Information Double Finesse* and *Layered Finesse* interaction.

### ISSUE THREAD

**Issue by alercah** [Zamiell/hanabi-conventions#127]
In #123, the first screenshot is a *Layered Finesse* to y3 that was misintepreted as a *No-Information Double Finesse*. When I looked at this convention, though, it wasn't clear that it should be a *Layered Finesse* until I read very carefully.

This screenshot is actually a *No-Information Layered Finesse*, based on the following reasoning:
- This looks like a *Bluff* or *Finesse*.
- Livia is in *Bluff Seat*, so ordinarily after the r2 plays, nobody would assume they had any promises made, and that would be the end of that.
- However, the *No-Information* convention "turns off" the *Bluff* interpretation. Therefore, this is a *Finesse*.
- This is a one-away card, so it cannot be a *Double Finesse*. It must be a *Layered Finesse*.

Incidentally, this could be an effective way to create *Purge Bluffs*.

**Comment by Zamiell** [comment]
i agree that technically it is a no information double finesse because it could be a bluff.
(i maintain that it probably is not good screenshot to showcase the move though.)
what exactly needs to be clarified?

**Comment by alercah** [comment]
The *No-Information Double Finesse* convention, as written, doesn't say that it actually has to result in a double blind-play. It just says that it turns off the *Bluff* interpretation.

The clued card is two-away (I said one-away above, but I meant two-away; my bad), which can by definition never cause a *Double Finesse* or a regular *Double Bluff*. But the *Layered Finesse* convention says "It follows from this that if an unrelated card is blind-played, and it cannot be a Bluff, then it must be a special kind of *Finesse*." This is exactly what happens here. It cannot be a regular *Bluff* because it is *No-Information*, and it cannot be a *Double Bluff* since that cannot come out of a two-away card.

Thus, it must be a special kind of *Finesse*, i.e., a *Layered Finesse*.

If the intent behind the *No-Information* contention is that the next two players should blind-play, even when a *Double Finesse*/*Bluff* couldn't happen ordinarily, that should be spelled out explicitly.

If the convention is as per my read, and it can lead to *Layered Finesses*, then it should make that clear, as it's currently misleading.

**Comment by Zamiell** [comment]
the following statement is at the top of the "No-Information Double Finesse* section:

> * Thus, by convention, a "no information" clue **must** "get" at least 2 new cards (as opposed to a single *Bluff* that only gets 1 brand new card).

so i think it directly follows from this that it could a be two blind plays in a row, two blind plays on 1 player, etc.

**Comment by alercah** [comment]
I agree, and that's why I think that it should be clear that the convention is not always a *Double Finesse*. The current wording is what confused Kakashi to misinterpret the screenshot.

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by alercah** [comment]
What would you like to see? Renaming to *No-Information Finesse*? Adding *No-Information Layered Finesse* as a separate convention?

**Comment by Zamiell** [comment]
I added this:

> * The "no-information" principle can also be used to perform a *Layered Finesse* on the next player. (The next player will know that it is a *Layered Finesse* instead of a *Bluff* because some other more-useful clue could have been given to initiate the *Bluff*.)
