### ISSUE TITLE
Null Conventions (change) (by Razvogor)

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#131]
* It is considered illegal to perform any kind of *Chop Move* on a non-critical null 3 or a non-critical null 4.
  * This rule counts for both *Positional Saves* and normal *Chop Moves* (such as the *5's Chop Move*).
* Thus, when a player is *Chop Moved* for a null card, they can know for sure that it is either a null 2 or a null 5.

**Comment by jakestiles** [comment]
Order chop moving a null 3 or 4 when it’s in someone else’s hand too (maybe close to chop or maybe even on chop) seems bad to make illegal. Can we make an explicit exception?

**Comment by jakestiles** [comment]
Order chop moving a null 3 or 4 when it’s in someone else’s hand too (maybe close to chop or maybe even on chop) seems bad to make illegal. Can we make an explicit exception?

**Comment by Zamiell** [comment]
I think in those situations, you can do just it anyway and then the other player will figure out that an illegal chop move was performed when the u5 is visible.

**Comment by NoMercyO** [comment]
Null 1

**Comment by Zamiell** [comment]
huh
