### ISSUE TITLE
Gentleman Discard Double Bluff and Chop Move

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#133]
### Proposal: Gentleman Discard Double Bluff

If someone does a _Gentleman Discard_, but the gentlemaned card is not on someone else's _Finessed Position_, and he has a two or more away playable card on the _Finessed Position_. Then the next two players should blind-play their _Finessed Position_ as a _**Gentleman Discard Double Bluff**_ . The gentlemaned card is promised on his _Second Finessed Position_ or layered behind.

Optional: The player should _Chop Move_ the card on his Finessed Position. (Might be the first convention to chop move an off-chop finessed position card.)

**Comment by Zamiell** [comment]
(this is the corollary to the gentleman's ejection)

seems fairly contrived, can you link a game where it would be good

**Comment by Zamiell** [comment]
unless anyone has any other thoughts then this seems too contrived to bother adding it to the doc, unless it is a move that you are actually using in games

**Comment by iamwhoiamhahaha** [comment]
okay
