### ISSUE TITLE
Anxiety play - Request to revert wording and retain as-written meaning

### ISSUE THREAD

**Issue by jakestiles** [Zamiell/hanabi-conventions#134]
**Problem statement:** I would like players to play predictably when put into an anxiety play, so that I know whether to put a player into anxiety.

**Example:** https://hanabi.live/replay/69218/29

**Old wording:**
The Anxiety Play (Forcing a Locked Player to Play)
A better way to signal this information is to deliberately leave them at 0 clues. By convention, this means that one of their cards is actually playable. _If there is more than one option, then they should know that the left-most is playable. (This follows from Left-Most Playable Principle.)_

**New wording by Zamiel Dec 9:**
The Anxiety Play (Forcing a Locked Player to Play)
A better way to signal this information is to deliberately leave them at 0 clues. By convention, this means that one of their cards is actually playable. _The player should play the card in their hand that is most likely to be playable. If there is more than one option, then they should know that the left-most is playable. (This follows from Left-Most Playable Principle.)_

**Conversation history:**

If Good touch principle does apply to pink, then fireheart's slot 2 is pink 3, green 5, yellow 5, or red 5. And fireheart's slot 3 is green 5, yellow 5, or red 5. Good so far? 

Anxiety play says "By convention, this means that one of their cards is actually playable. If there is more than one option, then they should know that the left-most is playable". 

There is in fact more than one option: slot 2 could be playable, and slot 3 could be playable. Anxiety play explicitly says, choose the leftmost option.
 
ZamielToday at 9:32 PM
anxiety play explicitly says play the card most likely to be playable
the fact that pink promise exists makes a strong case for playing the card that is guaranteed to be a 5
 
JakeToday at 9:33 PM
where does it say "most likely"?
The Anxiety Play (Forcing a Locked Player to Play)
Sometimes, someone with a Locked Hand has a playable card, but they do not know that they can play it yet. Re-cluing the card would signal this, but that would waste a clue and not be very efficient.
A better way to signal this information is to deliberately leave them at 0 clues. By convention, this means that one of their cards is actually playable. If there is more than one option, then they should know that the left-most is playable. (This follows from Left-Most Playable Principle.)
This is called an Anxiety Play because you are putting the Locked player in a "do or die" situation.
 
ZamielToday at 9:35 PM
* A better way to signal this information is to deliberately leave them at 0 clues. By convention, this means that one of their cards is actually playable. The player should play the card in their hand that is most likely to be playable. If there is more than one option, then they should know that the left-most is playable. (This follows from *Left-Most Playable Principle*.)
 
JakeToday at 9:35 PM
I am strongly in favor of NOT editing the doc to say most likely, and it doesn't now. If we change it, then we cannot accurately know what card a player will play if we lock them. And thus anxiety plays become much more risky when they don't need to be.

And in fact, in this specific example, the second card has 2 out of 4 possibilities playable. The third has 1 out of 3 which is lower.
 
ZamielToday at 9:35 PM
If we change it, then we cannot accurately know what card a player will play if we lock them.

this is already how we play, so it isn't changing anything
 
JakeToday at 9:36 PM
Please do not say the doc says something, then edit the doc to say that. I think this is big enough for a github thread.
 
ZamielToday at 9:36 PM
use context to figure out which card they will play
If there is more than one option, then they should know that the left-most is playable.

a more verbose way of saying this is that "if there is more than one option that is exactly equally likely to be playable"
so i do believe the doc said this already
 
JakeToday at 9:37 PM
Ok, so in this situtation, slot 2 is 50% playable and slot 3 is 33% playable so fire should choose slot 2
 
ZamielToday at 9:38 PM
those percentages are made up
fire obviously calculated the percentages differently than you
 
StephenToday at 9:38 PM
An equally reasonable interpretation of the wording is "if two cards are potential candidates for being playable, play the leftmost of those two"
the exactly equal probability aspect of it is far from clear and not obviously desirable
 
JakeToday at 9:39 PM
There are 4 possibilies for slot 2 card and 3 for slot 3. There are 2 playable possibilities for slot 2 card and 1 for slot 3. 2 divided by 4 is not made up, neither is 1 divided by three.
 
ZamielToday at 9:40 PM
fire also knows that the team would be forced to duplicate a pink card in order to save a 5 (and satisfy pink promise in the process), so i don't believe those numbers are correct
 
JakeToday at 9:40 PM
So good touch is allowed to be assumed violated?
How should fire's teammates decide whether to force them into an anxiety play if there's going to be this much confusion around which slot fire is allowed to play out of anxiety?
 
ZamielToday at 9:41 PM
please stop thinking of this so axiomatically. players violate good touch principal all the time, for a variety of reasons. in general, players should assume that good touch principle is satisfied, so it is a pretty good heuristic to go by. but players are also expected to use their brains and analyze context to account for and determine when good touch principle is violated
how should teammates decide? use your brain and use context
 
StephenToday at 9:44 PM
I would like to draw attention back to the point that the doc's previous contents are absolutely not semantically equivalent to the change @Zamiel  just made, and that there are pretty reasonable grounds to go with an interpretation that leads to more predictable behavior under Anxiety
Players are far less likely to have different estimates of "reasonable candidates" than they are of "candidates with exactly the same probability"
 
ZamielToday at 9:46 PM
again, the doc is a reflection of how we play, and the way we already play (and have been for many years, to the best of my knowledge), is that players play the card most likely to be playable, and only play the leftmost one if they are two or more equally likely candidates
if you want to change this, then lets open a github issue

**Comment by Zamiell** [comment]
In the middle of a 3-player game:
* Alice clues blue to Bob, touching a blue card on Bob's slot 5 (his chop).
* Both blue 3 and blue 4 are in the discard pile, so Bob marks his slot 5 card as either blue 3 or blue 4.
* Later on in the game, red 4 is played on the stacks, and all the 2's are played on the stacks.
* Bob is put into an *Anxiety* situation with the following hand, from left to right:
  * b(5), r(5), p(5), y(5), (b)3
* Bob knows that:
  * There is a roughly 50% chance of the blue card being playable (as either blue 3 or blue 4).
  * There is a roughly 25% chance of the left-most 5 being red 5 (as either blue 5, green 5, yellow 5, red 5, or purple 5).

In the current conventions, Bob would successfully play the blue 3. In the proposal, Bob would misplay the blue 5 and the game would be lost. This is an example of how the proposal is harmful.

Overall, in locked-hand situations, it is relatively important for players to be able to play the card that is most-likely to be playable, because there are a wide-variety of locked-hand situations that come up, and the current policy deals with all of them in a pretty good way.

One benefit of prescribing "always play leftmost" is that it leads to more predictive behavior. However, in turn it then reduces the utility of *Anxiety* as a move. I think it is important to keep in mind that not **everything** in our group has to be strongly-defined.

**Comment by jakestiles** [comment]
And if it’s worded the original way, and red 5 is on the left, we get to get the red 5 for free. Whereas we don’t with the new definition. 

And if it’s worded the new way, and blue 4 is on the right and red 5 is on the left, you have to clue the red 5 directly. Which is a waste of a clue. 

And if anyone else on the team wonders if Bob is going to assume blue 4 on slot 5 (as he maybe will assume since it should have been 3 saved since the threes were close to being all playable), they’ll have to directly clue red 5 to make sure Bob doesn’t bomb blue 5.

**Comment by jakestiles** [comment]
And in the example turn linked, if you want to do things the calculate %s way, the middle card is 50% playable (2 of 4 possibilities) and the right card is 33% playable (1 of 3 possibilities). Which means the middle card is a better play choice than slot 3 unless fire estimates the % chance of a good touch violation to be quite high. And if we can’t agree to that after a game is over, how are players going to silently agree on what a player will play under anxiety during a game? 

I think our real-game example seems more likely than your written example, that required red 4 to get red 4 played without red 5 being clued as a red 4 prompt/finesse, and that required neither blue 3 nor blue 4 drawn in someone else’s hand yet, and that required an initial save of rank to not make more sense, and that required someone to draw four 5s.

**Comment by Zamiell** [comment]
> And if it’s worded the original way, and red 5 is on the left, we get to get the red 5 for free. Whereas we don’t with the new definition.
> And if it’s worded the new way, and blue 4 is on the right and red 5 is on the left, you have to clue the red 5 directly. Which is a waste of a clue.

I think you may be missing the point of the example. The actual card configuration isn't super relevant - the probabilities involved are what is important. In a simulation of N games that play all possible superpositions of this scenario with our current conventions and a simulation of N games that play all possible superpositions of this scenario with the proposed convention, there would be over twice as many situations where *Anxiety* would work in the former.
