### ISSUE TITLE
Throw it in a hole priority

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-conventions#135]
We should decide on priority in Throw it in a hole.

* It makes sense to remove the higher priority for 5s. After all, 5s don't give a clue back, so 5s should have the lowest priority. Fireheart mentioned that he and Zamiel already mentioned this
* However, we could artificially keep the special priority for 5s. This allows us to do priority finesses with lower-ranked cards, at very little cost. If we make 5s the lowest priority, we can never do priority finesses when someone has a 5 and a non-5 to play (I guess we can do known priory bluffs instead, but they're probably a bad idea in Throw it in a hole).

**Comment by Zamiell** [comment]
> Fireheart mentioned that he and Zamiel already mentioned this

this is the way we currently play but it is undocumented, so i've added the following line to the doc:

* Since 5's do not give a clue back, then they do not have *Priority* over other cards in the same way that they normally do.

> This allows us to do priority finesses with lower-ranked cards, at very little cost.

this doesn't seem worth it to me personally

**Comment by Zamiell** [comment]
i think throw it in a hole is easy enough (with respect to efficiency) such that tuning the conventions to minimize complexity will result in an overall better win rate
