### ISSUE TITLE
2-Player Conventions Proposal

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#137]
### [2-Player Conventions Proposal]

After completing 200 perfect scores in 2-player (Fireheart has more perfect scores than me by the way), I believe we need to change some of the current 2-player conventions to make it more efficient and also increase the win rate.

![200 perfect scores in 2-player](https://user-images.githubusercontent.com/50160641/71335509-fdf43080-257d-11ea-8cab-d1d91b934596.png)

Current 2-Player Conventions:
https://github.com/Zamiell/hanabi-conventions/blob/master/misc/2-Player.md

### Delete One-Away Save

This convention gives you the ability to save two critical cards in a row, however, it is quite inefficient and sometimes confusing. In order to save two cards in a row, here are some other better conventions to use: 
- **5's Chop Move**: Deleting _One-Away Saves_ returns the power to perform a _5's Chop Move_.
- **Trash Chop Move**: _Trash Chop Move_ (with a stale 1) is usually the MVP to win the perfect score.
- **Double Scream Blind-Play**: For emergency, just bomb your chop as a _Double Scream Blind-Play_. I believe this convention is the best way to save two cards in a row even it got a strike.
- **Misplay Chop Move**: Do this if you want to save three cards in a row while no _Trash Chop Move_ available.

### Turn on 5's Chop Move
This convention is quite powerful. One of the main reason we should delete _One-Away Saves_ to turn on _5's Chop Move_.

### Turn off 5 Stall and Turn on 5 Pull in the Early Game
Except _First Turn Stalls_, you are not allowed to perform a _5 Stall_ in the _Early Game_: Every one-away 5 clue is treated as a _5's Chop Move_, while two or more away 5 clue is treated as a _5 Pull_.

### Second Turn Stall is Optional
We don't need Second Turn Stalls from my experience.

### Scream Discard Modification
You are allowed to perform a _Scream Discard_ in any clues (even in 6 clues). It is risky but gives you the ability to save a critical card without violating _Good Touch Principle_ or some other good reasons. And the player who is screamed at doesn't need to stall (if you have two critical cards in a row, your teammate would just perform a _Double Scream Blind-Play_ instead of a _Scream Discard_.)

### Turn off Double Discard Avoidance
It wastes too many clues to stall.

### Skipped Discard Chop Move Modification
If you refuse to take a strike to perform a _Scream Blind-Play_ (in 0 clues), you are allowed to perform a _Skipped Discard Chop Move_ (even you are not in 2 strikes), if your teammate have so many important cards in hand and you need 2 clues after your teammate discard. However, it is risky and might confuse your teammate for he might think you chop move somehow.

### Positional Discard and Positional Misplay
You are allowed to perform a _Positional Discard_ or a _Positional Misplay_ anytime (even in the _Early Game_). However, discarding one-away from chop card should be treated as a _Skipped Discard Chop Move_. In this case, you should perform a _Positional Misplay_ instead.

### Delete Double Skipped Discard Chop Move
This should be treated as a _Positional Discard_.

**Comment by jakestiles** [comment]
Addressing some of the changes proposed but not all:

Count of perfect scores is a not-great statistic to flout since it doesn't say your win rate on the way to those perfect scores. 

I have played 2 player games with many players and never have played one away saves except with Zamiel. I don't like them.

I like 5s cm in 2 player.

Deleting all 5 stalls in early game except first time seems needlessly aggressive, but maybe it's good for harder variants?

Playing with dda on is usually pretty miserable so most players I play with agree to play without it.

**Comment by NoMercyO** [comment]
Playing without DD avoid is ridiculous. Are you fishing for max scores in each variant or actually trying to get the maximum score with each draw?

**Comment by iamwhoiamhahaha** [comment]
Fishing. But playing with DDA doesn't help too much to get the maximum score in each draw. You spend too many clues on stalling.

**Comment by Zamiell** [comment]
i think you might not understand the purpose of the 2-player conventions page that you are linking, it is not meant to be "one set" of conventions for all 298 variants - that would be quite silly. it is meant to be a set of conventions that is designed to get the maximum score as much as possible for the "basic" variants of No Variant, Rainbow, and so forth. if you are playing a more difficult variant with another player and you want to play more optimally, then you will have to turn off and turn on various conventions on top of what is listed in the 2-player document that you are listing, as you have obviously already realized. as an action item for me, I'll edit the top of this page and add a passage to make that more clear. 

> Delete One-Away Save

this should be turned off for any hard variant and doing so should probably be self-evident without a handholding passage that instructs players to do so

> Turn on 5's Chop Move

5's chop moves are already turned on for any hard variant and doing so should probably be self-evident without a handholding passage that instructs players to do so

> Turn off 5 Stall and Turn on 5 Pull in the Early Game

5 stalls are already turned off in any hard variant and doing so should probably be self-evident without a handholding passage that instructs players to do so

> Second Turn Stall is Optional

second turn stalls are already turned off in any hard variant and doing so should probably be self-evident without a handholding passage that instructs players to do so

> Scream Discard Modification

you can already scream discard whenever you want in any hard variant and doing so should probably be self-evident without a handholding passage that instructs players to do so

> Turn off Double Discard Avoidance

DDA is already turned off in any hard variant and doing so should probably be self-evident without a handholding passage that instructs players to do so

> Skipped Discard Chop Move Modification

the situation you describe is logical. in practice, players already perform a mixture of scream blind-plays and skipped-discard-chop-moves to suit the needs of the specific situation, so I'm not sure we need to explicitly outline what to do in every situation

> Positional Discard and Positional Misplay

players already perform positional discards and positional misplays in hard variants, and doing so should probably be self-evident without a handholding passage that instructs players to do so

> Delete Double Skipped Discard Chop Move

if you are playing a null variant or some other variant in which a positional discard is better than the ability to chop move multiple cards, then doing so should probably be self-evident without a handholding passage that instructs players to do so

**Comment by iamwhoiamhahaha** [comment]
okay i see. thank you for explaining!
