### ISSUE TITLE
Pseudo Saves (in Chiaroscuro Pink and Dark Omni Variants)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#139]
### Chiaroscuro Pink 5 Saves (We can call it "Pseudo-5 Saves")
Chiaroscuro Pink on chop should be saved with number 5 clue. _Pink Promise_ doesn't apply to this variant. (Since we can always use _Pink Choice_ to get the pink card to play.)

### Chiaroscuro Pink Fake Saves (We can call it "Pseudo-Rank Saves")
In some situation, where there are critical cards behind Chiaroscuro Pink cards, you are also allowed to "**fake save**" the pink cards with any number (either 2, 3, or 4), and it doesn't trigger _Finesses_ or _Bluffs_. (Again, _Pink Promise_ doesn't apply to this variant.)

**Comment by iamwhoiamhahaha** [comment]
extend this to **Dark Onmi** Variant

**Comment by Zamiell** [comment]
seems fine
