### ISSUE TITLE
move advanced conventions from README

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-conventions#14]
To beginning players our conventions often seem overwhelming, and there is the perceived idea that you have to learn all conventions before you start playing.

Suggestion: We could alleviate this problem by moving all conventions, except the First Principles and the Beginner Strategies to a new file called "reference" or something.

**Comment by Zamiell** [comment]
i rewrote a ton of stuff today, you can tell me if you like the new organization
