### ISSUE TITLE
Example: The Bad Touch Double Bluff (For 3's)

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#140]
![2019-12-24_1826_(The_Bad_Touch_Double_Bluff_(For_3's))](https://user-images.githubusercontent.com/48993588/71429451-8c9aa780-267b-11ea-9d27-a7b4a8947591.png)
 
3's to Rakxer Bad touch Double Bluff (For 3's)
2 to Rakxer is a Disease Bluff, Kyle does Yellow or 2 to MasN
2 to Rakxer is a Pestilent Bluff assuming MasN does not have Y2

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-conventions/blob/master/examples/Bad_Touch_Double_Bluff.md

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-conventions/blob/master/examples/Pestilent_Double_Bluff.md

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-conventions/blob/master/examples/Disease_Bluff.md
