### ISSUE TITLE
Example: Finesse with a lie component

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-conventions#143]
https://imgur.com/Rpmx9FX

- Dr Kakashi clues Rainbow 4 to Micerang.

- Kopen sees Rainbow 1 in Valetta6789's hand and decides to do something else.

- Valetta6789 sees Blue 2, Rainbow 3, Red 5 and Rainbow 3 in Kopen's hand. Valetta realizes that a layered finesse with a lie component is happening as it takes only a single fix clue (which is 5 anyway) to get three cards in Kopen's hand to be blind-played.

- Valetta6789 blind-plays Rainbow 1.

- Kopen blind-plays Blue 2, then Rainbow 2.

- Before red 5 is misplayed, the team intervenes and gives a fix clue with a 5. Kopen realizes, after receiving 5 as a fix clue, that the finesse is still "on", skipping Red 5 and blind-plays Rainbow 3.

- After that, Micerang plays Rainbow 4.

**Comment by Zamiell** [comment]
i think an example for this should be from a no-variant or rainbow game, having it be from a dark pink game adds unnecessary complexity

**Comment by Zamiell** [comment]
actually this doesn't work because micerang will bomb m4 as m3
