### ISSUE TITLE
Example: Unnecrssary trash bluff/finesse chop move

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-conventions#144]
https://i.imgur.com/f5R0DJb.png

- Jake_Stiles clues 1s to IAMJEFF.

- Fireheart thinks that without blind-play, IAMJEFF will misplay as he is not sure if he has gray 1 on his finesse position. Grey 1 successfully blind-plays.

- IAMJEFF realizes that trash bluff on him was unnecessary as Jake_Stiles could have cleanly touched Fireheart's Gray 1.

- IAMJEFF chop moves the cards right of his 1s.

**Comment by Zamiell** [comment]
can you submit the same example in a no-variant game? having it be in gray adds unnecessary complexity

**Comment by Zamiell** [comment]
closing this since you aren't responding
