### ISSUE TITLE
Color Positional Clues in Null (Changed)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#145]
### Color Positional Clues in Null (Changed)

> _Current convention: A color positional clue corresponds to a slot number that is based on the order of the stacks. Stacks correspond to the slot numbers from right to left._

Proposal: A color positional clue corresponds to a slot number that is based on the order of the stacks. Stacks correspond to the slot numbers from right to left, **but skip the card which has positive information on it.**

- The reason why I want to change this convention is because we would never be able to use color positional clue with a blue clue to get slot 1 if there are 5 slots and only 4 colors available. Skipping the known non-null cards is logical and reasonable.

- I beat a lot of null variants with Fireheart with this convention. It is very useful and easy to understand in 2-player game for sure.

- However, I am not sure if it would cause too much confusing in 3 or more player game, but if we get used to it, it might be a powerful convention to use I guess.

- **Note: The Chop Moved card doesn't have positive information on it, so it might be the slot needed to be blind-played from a color positional clue.**

> _Example 1:
> Fireheart has a card with positive information on it, a blue 3 on slot 5 in this case. If color positional clues are available to give: red means play slot 4; yellow means play slot 3; green means play slot 2; and blue means play slot 1. Here, Fireheart should blind-play slot 1 as a positional clue._

![Positional Clues with color](https://user-images.githubusercontent.com/50160641/71484438-6b86b200-2847-11ea-8726-e36b08cd0c83.png)

> _Example 2:
> Fireheart has two cards with positive information on them, a green 4 on slot 4 and a blue start on slot 2. If color positional clues are available to give: red means play slot 5; yellow means play slot 3; green and blue means play slot 1. Here, Fireheart should blind-play slot 1 as a positional clue._

![color positional clues example 2](https://user-images.githubusercontent.com/50160641/71485028-3596fd00-284a-11ea-931d-f00a3939e69d.png)

> _Example 3:
> IAMJEFF has two cards with positive information on them, a red 4 on slot 5 and a yellow 5 on slot 4. If color positional clues are available to give: red means play slot 3; yellow means play slot 2; green and blue means play slot 1. Here, IAMJEFF should blind-play slot 2 as a positional clue._

![color positional clues example 3](https://user-images.githubusercontent.com/50160641/71485473-21ec9600-284c-11ea-8a1c-9d8e98b31127.png)

**Comment by iamwhoiamhahaha** [comment]
### Color Positional Clues in Null (Exception)

If there are four color clues available and if the player only has two slots without positive information on them, then the first and second color positional clues means play leftmost card, while the third and  fourth color positional clues means play rightmost card.

> Example 4:
> IAMJEFF has three cards with positive information on them, a green 4 on slot 2, a yellow 2 on slot 4, and a yellow 4 on slot 5. If color positional clues are available to give: red and yellow mean play slot 3; green and blue mean play slot 1. Here, IAMJEFF should blind-play slot 3 as a positional clue.
> 

![color positional clues example 4 (Exception)](https://user-images.githubusercontent.com/50160641/71500578-889b9f00-28a0-11ea-9fbe-add6cd382095.png)

**Comment by iamwhoiamhahaha** [comment]
### Color Positional Clues (in Details) - version 1
(multiple colors get the leftmost slot, always on slot 1)

> **3 Colors and 2 Slots**
> 1st and 2nd Colors → 1st Slot
> 3rd Color → 2nd Slot
> 
> **4 Colors and 3 Slots**
> 1st and 2nd Colors → 1st Slot
> 3rd Color → 2nd Slot
> 4th Color → 3rd Slot
> 
> **4 Colors and 2 Slots**
> 1st and 2nd Colors → 1st Slot
> 3rd and 4th Colors → 2nd Slot
> 
> **5 Colors and 4 Slots**
> 1st and 2nd Colors → 1st Slot
> 3rd Color → 2nd Slot
> 4th Color → 3rd Slot
> 5th Color → 4th Slot
> 
> **5 Colors and 3 Slots**
> 1st and 2nd Colors → 1st Slot
> 3rd and 4th Colors → 2nd Slot
> 5th Color → 3rd Slot
> 
> **5 Colors and 2 Slots**
> 1st, 2nd and 3rd Colors → 1st Slot
> 4th and 5th Colors → 2nd Slot
> 
> **N Colors and N Slots**
> nth Color → nth Slot
> 
> **N Colors and 1 Slot**
> nth Color → 1st Slot

### Color Positional Clues (in Details) - version 2
(multiple colors get the rightmost slot, always on chop)

> **3 Colors and 2 Slots**
> 1st Color → 1st Slot
> 2nd and 3rd Colors → 2nd Slot
> 
> **4 Colors and 3 Slots**
> 1st Color → 1st Slot
> 2nd Color → 2nd Slot
> 3rd and 4th Colors → 3rd Slot
> 
> **4 Colors and 2 Slots**
> 1st and 2nd Colors → 1st Slot
> 3rd and 4th Colors → 2nd Slot
> 
> **5 Colors and 4 Slots**
> 1st Color → 1st Slot
> 2nd Color → 2nd Slot
> 3rd Color → 3rd Slot
> 4th and 5th Colors → 4th Slot
> 
> **5 Colors and 3 Slots**
> 1st → 1st Slot
> 2nd and 3rd Colors → 2nd Slot
> 4th and 5th Colors → 3rd Slot
> 
> **5 Colors and 2 Slots**
> 1st and 2nd Colors → 1st Slot
> 3rd and 4th and 5th Colors → 2nd Slot
> 
> **N Colors and N Slots**
> nth Color → nth Slot
> 
> **N Colors and 1 Slot**
> nth Color → 1st Slot

**_REMEMBER: Only count the slots without positive information_**
_(Note: Chop moved cards don't have positive information, so they should be counted)_

**Comment by iamwhoiamhahaha** [comment]
In 2-player games, I prefer version 1 since it is usually hard to do a self-bluff. In 3 or more player games, intuitively, version 2 is better than version 1 since it is usually easy to bluff a card from slot 1 and hard to call someone's chop card.

**Comment by iamwhoiamhahaha** [comment]
The main difference between the original color positional clues and my proposal is: mine gives the ability to **call** a card from slot 1 (and sometimes slot 2) with a color positional clue, if we only have N color clues to give and there are M cards in hands, where N < M. In this situation, the original color positional clues can only be able to call a card from the slot which is greater than M-N, but now we can easily call any slot with my new proposal, since I skip the cards with positive information (i.e. globally known non-Null cards).

**Comment by Zamiell** [comment]
seems fine

**Comment by Zamiell** [comment]
i prefer version 2 since we can use non-positional Bluffs to get slot 1

**Comment by Dr-Kakashi** [comment]
So Jeff tells me to post this here as it's my idea.  We were playing Null + Black and there was some confusion as to what a black clue would mean if used as a positional clue.  I suggested that logically we can't set Black to be dedicated to chop as there are only 5 unique cards in the deck.  

Realistically, for black cards to even be interpreted as a positional clue they must be 3 away and 3's can be used for 3 bluffs.  Thus, only black 4 and black 5 can be used.  Additionally, the window for these cards disappears as the black suit is being built up.

There's just not enough black cards for them to be useful to do play clues or cm to chop.  In fact, what we really want is more opportunities to clue chop.  Thus, we should just add the black pool to the blue pool and say that Black + Blue color positional clues represent chop.

**Comment by Zamiell** [comment]
@Dr-Kakashi open a new issue about black color clues, that is a new proposal that is distinct from jeff's
