### ISSUE TITLE
Trash chop move discharge

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-conventions#146]
**Trash chop move discharge**
Derived from 5 double pull.

Normally, you don't want to trash chop move a card that is playable right now. But what if someone does it anyway?

With trash chop move discharge, it signifies that the trash chop moved card is playable right now.

For an example:

- All 1s have been played from stacks.

- Alice clues 1s to Cathy. It touches red 1 one away from chop.

-  Cathy chop moves her card.

- However, Bob notices that a card on Cathy's chop is green 2 which is playable right now. He also notices that there are no cards that could have prevented Alice from giving Cathy a direct play clue instead.

- Bob plays his third finesse position. It is blue 2.

- Cathy, surprised to see Bob doing a discharge, now knows that the card on her chop playable. She plays the green 2.

**Comment by hanabirnoob** [comment]
That's junk ejection where the chop moved card is trash instead of playable.

**Comment by Zamiell** [comment]
oh

**Comment by Zamiell** [comment]
why not finesse position instead of third finesse position

**Comment by hanabirnoob** [comment]
I was considering that. 

What about this:

Finesse position - chop moved cards are all playable right now.

Second finesse position - chop moved cards are all trash.

Third finesse position - chop moved card could have been save directly with a save clue.

**Comment by Zamiell** [comment]
seems unlikely to be useful
