### ISSUE TITLE
4-double bluff but the clue is on Cathy and not Donald

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-conventions#148]
Hi,
Played: r1.
Bob's hand: b1-x-x-x
Cathy's hand: x-r4-x-x
Donald's hand: r3-x-x-x

Alice clue red on r4 to Cathy.

------------------------------------------------------------------------------
So, first of all, when you do a 'two away bluff', there is on my knowledge, three differents way to interpret it:
 - 4 double bluff, two bluffs are played immediately: one normal, and one known bluff
 - something we called Implied bluff or Distant bluff on bga: another player is promesse the remaining card for the finesse in finesse position
 - nothing, and a fix clue is needed one day

What I propose here is a mix between the first two, when the first one is not possible.
So, on my example:
 - Bob saw the clue, assume r2, and play slot 1 as r2 and it's b1.
 - Cathy assume r3 as a normal bluff, but saw Donald's finesse position. So she should assume both possibility r3/r4 until something else happen.
 - Donald saw the clue, and know it can't be a double bluff: Cathy could have easily mess up everything by clueing Donald finesse position. This mean something weird is going on: he have r3.

**Comment by Romain672** [comment]
I think about this convention, and it could have some interresting applications:

1)
Played: r1
Bob's hand: b1-r3-x-x
Cathy's hand: g1-x-x-x
Donald's hand: x-r4-x-x
Alice clues red to Donald.
Bob assume r2+r3 and play b1 as r2 (could be double half bluff, so can't delay).
Cathy conventionnally should assume r3. But she saw Bob's r3, and she know Donald saw it too. So she discard.
Donald assume r3/r4 since r3 was on finesse position.
It's just a matter of priorities between conventions here, but this example seem more logic to be an 'Implied bluff' than a 'Double bluff'.

2)
On my first example, Cathy can't know if r3 is saved or not. This mean, if Donald has a critical card after his r3, Cathy can't save it. She can 5-chop move it (which is funny because as soon as r2 is played, Cathy should tempo, and Donald will either play it, or either wonder why Cathy doesn't play), but that's all, most of the saves on Donald's hand should be done by Bob.

3)
This move should be distincted from the 'out-of-position double bluff'.
Played: r1.
Bob's hand: b1-x-x-x
Cathy's hand: x-r4-x-x
Donald's hand: g1-x-x-x
Alice has 1 clue left.
Alice clues red to Cathy.
When Alice gave the clue, Cathy assume r3. But she have no clue, so she can't interfere with what happen.
So on this situation, Donald should assume an 'out-of-position double bluff' which work like an 'out-of-position bluff'.

4)
Let's talk about 3-bluffs :D
Played: nothing
Bob's hand: b1-x-x-x
Cathy's hand: x-r4-x-x
Donald's hand: rX-x-x-x
Alice clue red to Cathy.
Bob plays b1. Cathy discard.
What does the clue mean with that convention?
I immediately think about 3 possibilities: assuming r2, assuming r3, OR assuming r2 or r3.
Alice decided to clue a 4 for getting an 1, and a red card. Can this red be r3? 3 is two away from playable. 4 is two away too. It seem odd.
So maybe Cathy should only assume r2, even if initially I find it more 'logical' to assume r2 or r3.

**Comment by NoMercyO** [comment]
Its not worth the complexity of find edge cases to use a convention that directly conflicts with one we have.

**Comment by Romain672** [comment]
Yeah, I talked about Valetta about it after, and Bob is promesse b1-r2-r3-x on this case, which is less likely than what I actually propose.

But yeah, complexity cost is maybe high.

**Comment by Zamiell** [comment]
agree with mercy

**Comment by Romain672** [comment]
Does folks still disagree with that proposition?
