### ISSUE TITLE
Number Mute Conventions

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#149]
This is for 2-player (I'll post 3 or more player conventions later)

### About Turn 1 Stalls

> Any clue touches slot 5 means a _Save Clue_; otherwise, just a _Stall Clue_. (No _Play Clue_ in turn 1)

### About Play Clues: Number Mute Positional Clue Rules
**3 Suits**

> Blue: Play slot 1
> Green: Play slot 3
> Yellow: Play slot 5

**4 Suits**

> Blue: Play slot 1
> Green: Play slot 1 (Play slot 2 while Blue clue is available)
> Yellow: Play slot 3
> Red: Play slot 5

**5 Suits**

> Blue: Play slot 1
> Green: Play slot 1 (Play slot 2 while Blue clue is available)
> Yellow: Play slot 3
> Red: Play slot 4
> Purple: Play slot 5

**6 Suits**

> Blue: Play slot 1
> Green: Play slot 1 (Play slot 2 while Blue clue is available)
> Yellow: Play slot 3
> Red: Play slot 4
> Purple: Play slot 5
> Teal: Play slot 1 (Chop move while Blue OR Green clue is available)

### About 8 Clue Stalls

> If the next player has no clued cards, then it is treated as _Turn 1 Stalls_.

> If the next player has clued cards with only one color, then you should clue the same color as a _Stall Clue_; otherwise, it is treated as a _Play Clue_.

> If the next player has clued cards with two or more colors, then you should give the "rightmost" color clue as a _Stall Clue_; otherwise, it is treated as a _Play Clue_.

For example, in 5 suits, Bob has unknown red and green cards in hand. Alice is in 8 clues situation, if she clues red to Bob, it is just a stall clue; however, if she gives a clue with other color, then it is treated as a play clue.

### About Saves

> In 2-player, just use _Scream Discard_, _The Scream Blind-Play_, or _The Skipped Discard Chop Move_ to save cards on chop. Or clue teal in some specific situations.

### About Discards

> Good Touch Principle is not applied in Number Mutes, which means you should always discard right-most card unless it was got chop moved.

### Other Advanced Strategies

- Delayed Play Clues:

> Like Null Conventions, the target of "delayed play clues" slides over and targets the slot one position to the right.

For example: Alice discards. Bob clues something to Alice. Then Alice clues Bobs "blue" touching a card on slot 1 (telling him to play "slot 1"). If that blue card was playable, Alice would just clue Bob last turn, which means he has a playable card on slot 2 instead of slot 1. Bob blind-plays slot 2.

- Stacked Play Clues

> If the same color is clued again before you play the target that was gotten last turn, it means there is another playable card "stacked" behind the gotten card.

For example: Alice clues blue to Bob (means play slot 1). Bob clues something to Alice. Alice clues Bobs "blue" again, which means Bob has another playable card on slot 2.

**Comment by iamwhoiamhahaha** [comment]
Example: ID 77664
https://hanabi.live/replay/77664/1

Turn 1 Stall (Turn 1)
Delayed Play Clue (Turn 4)
The Scream Blind-Play (Turn 23)
The Skipped Discard Chop Move (Turn 26)
Delayed Play Clue (Turn 58)

**Comment by iamwhoiamhahaha** [comment]
6 Suits Example: ID 77666
https://hanabi.live/replay/77666/1

Turn 1 Stall (Turn 1)
Play Clue in 8 Clue Situation (Turn 3)
Gentleman's Discard (Turn 4)
Green Clue as Play slot 1 (Turn 5)
8 Clue Stall (Turn 10)
Play Clue in 8 Clue Situation (Turn 12)
Stacked Play Clues on red 2 (Turn 14)
Teal Clue as Play slot 1 (Turn 18)
Scream Discard on purple 5 (Turn 22)
Teal Clue as Play slot 1 (Turn 23)
Stacked Play Clues on purple 4 (Turn 39)
Scream Blind-Play (Turn 45)

**Comment by iamwhoiamhahaha** [comment]
### Number Mute Conventions (for 3 or more players)

### ● General Principles

1. This is a hard variant, which means no DDA, no 5 Stall (of course, lol), etc.
2. Good Touch Principle does not apply to this variant. You should always discard your rightmost card unless it's got cm'ed or saved.

### ● About Turn 1 Stalls

1. Any clue given to the **next player** is either a Save Clue (touching the chop) or a Stall Clue (touching the other cards) in turn 1. 
2. Any other clue is treated as a _Play Clue_.
> Notes: No _Play Clue_ in 2-player game in turn 1.

### ● About Play Clues: Number Mute Positional Clue Rules

> To minimize confusion: The player who receives the clue is usually (not always) the person who needs to play a card from the positional clue.

**Number Mute (3 Suits)**
- Blue: Play slot 1
- Green: Play slot 3
- Yellow: Play slot 5

**Number Mute (4 Suits)**
- Blue: Play slot 1
- Green: Play slot 1 (Play slot 2 while Blue clue is available)
- Yellow: Play slot 3
- Red: Play slot 5

**Number Mute (5 Suits)**
- Blue: Play slot 1
- Green: Play slot 1 (Play slot 2 while Blue clue is available)
- Yellow: Play slot 3
- Red: Play slot 4
- Purple: Play slot 5

**Number Mute (6 Suits)**
- Blue: Play slot 1
- Green: Play slot 1 (Play slot 2 while Blue clue is available)
- Yellow: Play slot 3
- Red: Play slot 4
- Purple: Play slot 5
- Teal: Play slot 1 (Chop move while Blue OR Green clue is available)

### ● About Stall Clues (8 Clue Stalls or DDA Stalls if the team agreed to play with that)

Notes: You must give a clue to the **next player** to perform a _Stall Clue_; or it is always treated as a _Play Clue_ (if you give a clue to other players).
1. If the next player has no clued cards in hands, then the case is treated as _Turn 1 Stalls_. (i.e. a _Save Clue_ touching the card on chop or a _Stall Clue_ touching the other cards)
2. If the next player has clued cards in hands but with only one color, then you should clue the same color as a _Stall Clue_; otherwise, it is treated as a _Play Clue_.
3. If the next player has clued cards with two or more colors, then you should give the "rightmost" color clue as a _Stall Clue_; otherwise, it is treated as a _Play Clue_.
> For example, in 5 suits, Bob has unknown red and green cards in hand. Alice is in 8 clues situation, if she clues red to Bob, it is just a stall clue; however, if she gives a clue with any other color (to Bob), including a green clue, it is a play clue.

### ● About Saves

1. Any clue touching the _Chop_ on the **next player** is always a _Save Clue_.
2. You are only allowed to give a _Save Clue_ when you are on the _**Save Seat**_ (the person directly before the player who receives a _Save Clue_).
3. Notes: To save two critical cards in a row, use _Misplay Chop Move_.
> For example, in 5 suits in 3-player, all 1 has played on the stacks. Bob has a yellow 1 (on slot 3), a purple 5 (on slot 4), and a critical red 4 (on slot 5). Alice clues yellow to Bob. Bob misplays the yellow 1 from slot 3, then he chop moves slot 4 and 5. 

### ● About Discards

1. Good Touch Principle is not applied in Number Mutes, which means you should always discard right-most card unless it has got chop moved or saved.

### ● Other Advanced Strategies

### 1. Delayed Play Clues (we might call it "Focus Slides")
Like Null Conventions, the target of "delayed play clues" slides over and targets the slot one position to the right.

> For example: Alice discards. Bob clues Cathy "blue" touching a card on slot 1 (telling her to play "slot 1"). If that blue card was playable, Alice would clue Cathy on Alice's turn, which implies Cathy doesn't have a playable card on slot 1, then she realizes it is a _Focus Slides_ and blind-plays her slot 2.

### 2. Stacked Play Clues (useful in 2-player)
If the same color is clued again before you play the target that was gotten last turn, it means there is another playable card "stacked" behind the gotten card.

> For example: Alice clues blue to Bob (means play slot 1). Bob clues something to Alice. Alice clues Bobs "blue" again, which means Bob has another playable card on slot 2.

**Comment by Zamiell** [comment]
since it is only about a specific variant, this should be in a separate doc from the 2-player doc, why dont you just submit a pull request

**Comment by iamwhoiamhahaha** [comment]
what's the difference b/w issues and pull requests

**Comment by Zamiell** [comment]
a pull request is like, when you click on the "fork" button at the top, which makes a copy of the repo.
then you add the file you want. then you click "make pull request". then, it shows the changes to me, i click "i accept these changes", and your changes get merged with the main repo

**Comment by iamwhoiamhahaha** [comment]
Seems like we should play this with hat-guessing in 4 or more player

**Comment by Zamiell** [comment]
```
# mod 6       action             type of clue
0 (6, 12)     clue or discard    slot 1 on next player
1 (7, 13)     play 1             other slot on next player
2 (8, 14)     play 2             slot 1 on 2 players away
3 (9, 15)     play 3             other slot on 2 players away
4 (10, 16)    play 4             slot 1 on 3 players away
5 (11, 17)    chop move          other slot on 3 players away
```

**Comment by Zamiell** [comment]
ok going to close this in favor of hat guessing clues

**Comment by iamwhoiamhahaha** [comment]
but it is still the best solution for 2p. i think you should add them to the 2p doc

**Comment by iamwhoiamhahaha** [comment]
and we don't have hat-guessing table for 3p

**Comment by Zamiell** [comment]
can you just make a document for 2 player number mute and i will link to it

**Comment by Zamiell** [comment]
can you make a hat guessing table for 3p?

**Comment by iamwhoiamhahaha** [comment]
okay i'll make a doc for 2p. intuitively, there's no good hat-guessing table for 3p

**Comment by Zamiell** [comment]
ok i will leave this issue open until you create the doc

**Comment by iamwhoiamhahaha** [comment]
https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Number_Mute_Conventions.md

**Comment by Zamiell** [comment]
should be linked now
