### ISSUE TITLE
5 Number Discharge Example

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#150]
![5 number discharge example](https://user-images.githubusercontent.com/50160641/74582291-0c4a5000-4ff5-11ea-9de5-87210a39d31c.png)

**Comment by Zamiell** [comment]
can you post a screenshot in BGA format

**Comment by iamwhoiamhahaha** [comment]
![5ND](https://user-images.githubusercontent.com/50160641/74900008-6b370d00-53d9-11ea-84c3-2a4b5336bc14.png)

**Comment by Zamiell** [comment]
in the future, post screenshots on the turn **before** the move happens
