### ISSUE TITLE
Dark Null Conventions

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#152]
### Dark Null Conventions

- Positional clue is allowed to get **any** card to play but **only** get one blind-card since there are few playable Null cards most of the time in this variant (which means you don't need to look for a Null card from the positional clue).

- 5 clue is **always** a _Save Clue_ on someone's chop. And you are allowed to **fake save** a non-Null critical card by cluing an off-chop 5.

**Comment by Zamiell** [comment]
seems confusing with not that much benefit

**Comment by iamwhoiamhahaha** [comment]
okay i edited the second description

**Comment by iamwhoiamhahaha** [comment]
### Dark Null Conventions

- Positional clue is allowed to get **any** card to play but **only** get one blind-card since there are few playable Null cards most of the time in this variant (which means you don't need to look for a Null card from the positional clue).

- 5 clue is **always** a _Save Clue_ on someone's chop.

- In a 2-player game, you are allowed to **fake save** a non-Null critical card by cluing an off-chop 5.

**Comment by iamwhoiamhahaha** [comment]
this proposal is based on my experience but not in theory. i've played ove 500+ dark null games

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/Dark_Null.md

**Comment by Zamiell** [comment]
make a new issue if we want any additional changes to this page
