### ISSUE TITLE
An 'out of position bluff' where the bluff target can be two differents thing

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-conventions#154]
Played : y1

Bob's hand : x-r3-x-x
Cathy's hand : r1-x-x-x
Donald's hand : b1-y2-x-x

Alice clues red to Bob.
.
Alice doesn't know what will do Bob, but whatever Bob will choose, the bluff should work, except if he clues Alice's b1/b2/y3, but it's unlikely.

**Comment by Zamiell** [comment]
violates good lie principle
