### ISSUE TITLE
Priority Pass Prompt/Bluff

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#156]
### Priority Pass Prompt

- This convention can only be used in an expert-game, where everyone knows the _Priority Finesse/Bluff_.

- If the player before you perform a _Priority Finesse/Bluff_ on you, and you see the next player has a playable clued card matches the card which triggers the _Priority Finesse/Bluff_. Instead of playing your Finessed Position, you are allowed to defer and "trick" your next player to play into the _"Priority Prompt"_ as a _**Priority Pass Prompt**_.

_Example 1:_
![priority pass finesse](https://user-images.githubusercontent.com/50160641/75506090-e1f68a80-5a17-11ea-85de-782dde39688e.png)

1. magikarp has a known blue 1 (with a blue clue) on slot 4 and a known green 2 (with a 2 clue) on slot 3. 

2. magikarp sees charmander has a green 3 (or some other playable card) on _Finessed Position_. Instead of playing the blue 1, he plays the green 2 to trigger the _Priority Finesse/Bluff_.

3. charmander now knows he has some playable card on _Finessed Position_. However, charmander sees bulbasaur has a playable yellow 3 (with a 3 clue) on slot 3; instead of playing his Finessed Position, he discards.

4. bulbasaur is surprised, he thought that was a _Priority Finesse_ on charmander. Then he realizes his unknown 3 is a green 3 and plays his slot 3 as a _Priority Prompt_, and a yellow 3 is successfully played (thinking that is a green 3).

5. Now, it's charmander's turn he blind-plays his _Second Finessed Position_ (since he discards last turn) and a green 3 is successfully played.

6. bulbasur is surprised again. Now he realizes that was a _**Priority Pass Prompt**_ and stops looking for the green 3 (if charmander blind-plays another playable card instead of a green 3).

### Priority Pass Bluff

- This convention can only be used in an expert-game, where everyone knows the _Priority Finesse/Bluff_.

- If the player before you perform a _Priority Finesse/Bluff_ on you, and you see the next player has a playable card on _Finessed Position_. Instead of playing your _Finessed Position_, you are allowed to defer and "trick" your next player to play into the _"Priority Finesse"_ as a _**Priority Pass Bluff**_.

_Example 2:_
![priority pass bluff](https://user-images.githubusercontent.com/50160641/75506816-2a16ac80-5a1a-11ea-8be5-2be055d6dc95.png)

1. magikarp has a known blue 1 (with a blue clue) on slot 4 and a known green 2 (with a 2 clue) on slot 3. 

2. magikarp sees charmander has a red 1 (or a green 3, it doesn't matter) on _Finessed Position_. Instead of playing the blue 1, he plays the green 2 to trigger the _Priority Finesse/Bluff_.

3. charmander now knows he has some playable card on _Finessed Position_. However, charmander sees bulbasaur has a playable yellow 3 on _Finessed Position_; instead of playing his _Finessed Position_, he discards.

4. bulbasaur is surprised, he thought that was a _Priority Bluff_ on charmander. Then he realizes he really has a green 3 and plays his _Finessed Position_ as a _Priority Finesse_, and a yellow 3 is successfully played (thinking that is a green 3).

5. Now, it's charmander's turn, he blind-plays his _Second Finessed Position_ (since he discards last turn) and a red 1 is successfully played.

6. bulbasur is surprised again. Now he realizes that was a _**Priority Pass Bluff**_ and stops looking for a green 3.

**Comment by Zamiell** [comment]
breaks *Good Lie Principle*.
if its an expert game and there is enough context to know what is happening, then this doesn't need to be a convention
