### ISSUE TITLE
4 Single Bluff (in 2-player)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#159]
### 4 Single Bluff (in 2-player)

- This convention only applies to 2-player games in hard variants.

- You are allowed to perform a _**4 Single Bluff**_ by using a two-away 4 with a rank clue, if the 4 looks like one-away and it only gets one blind-card. 

- The 4 that was used as a _4 Single Bluff_ is not promised to be one-away.

(I haven't found an example in my replay. Will post it if I find one.)

**Comment by iamwhoiamhahaha** [comment]
Example:
![4 Single Bluff](https://user-images.githubusercontent.com/50160641/76168432-c2dfc180-61aa-11ea-9d90-e20a51758887.png)
This 4 clue only gets one blind-play since it looks like a yellow 4 (which is one-away) from IAMJEFF's perspective. However, by definition of the _**4 Single Bluff**_ mentioned above, it is not promised to be a yellow 4.

> Reason:
> - No one would misplay from the 4 clue (as a _4 Double Bluff_ or something) since it is a 2-player game.
> - 2-for-1 (by touching a 4 and getting a blind-card) is more efficient than a 1-for-1 clue (direct clue on the slot 1).
> - The 4 might be critical and you can "save" it earlier by this way.

**Comment by Dr-Kakashi** [comment]
I am for this, I did this without knowing this proposal

**Comment by Zamiell** [comment]
> No one would misplay from the 4 clue (as a 4 Double Bluff or something) since it is a 2-player game.

that's not true, they would potentially misplay later on right? unless another fix clue is given

**Comment by iamwhoiamhahaha** [comment]
see my definition for 4 single bluff
- You are allowed to perform a 4 Single Bluff by using a two-away 4 with a rank clue, if the 4 looks like one-away and it only gets one blind-card.
- The 4 that was used as a 4 Single Bluff is not promised to be one-away.

**Comment by Zamiell** [comment]
im aware that that is the convention you are proposing. but the justification for your convention is that "no-one would misplay from the 4 clue anyway", which is false

**Comment by iamwhoiamhahaha** [comment]
why? it has same logic as _3 Bluffs_

**Comment by iamwhoiamhahaha** [comment]
> unless another fix clue is given

what fix clue should be given?

**Comment by iamwhoiamhahaha** [comment]
"no-one would misplay from the 4 clue anyway" is false if you are playing a 3 or more player game. in 2p, it's true

**Comment by Zamiell** [comment]
no, its false in 4p, because it bombs as y4

**Comment by iamwhoiamhahaha** [comment]
as i said, see my definition:
"The 4 that was used as a 4 Single Bluff is not promised to be one-away."

it is not promised as a y4

**Comment by Zamiell** [comment]
> im aware that that is the convention you are proposing. but the justification for your convention is that "no-one would misplay from the 4 clue anyway", which is false

**Comment by iamwhoiamhahaha** [comment]
what do you mean...

**Comment by Zamiell** [comment]
> Reason:
> No one would misplay from the 4 clue (as a 4 Double Bluff or something) since it is a 2-player game.

this is false

**Comment by iamwhoiamhahaha** [comment]
why? if the player who receives the 4 clue knows that it is not promised as a one-away 4 then no one would bomb

**Comment by Zamiell** [comment]
thats correct but thats not the current convention

**Comment by iamwhoiamhahaha** [comment]
that's the reason i made this proposal

**Comment by iamwhoiamhahaha** [comment]
> This convention only applies to 2-player games in hard variants.

it is quite useful in 2p hard variants from my experience

**Comment by Zamiell** [comment]
yes, but you aren't allowed to list that as an reason for the proposal lol

**Comment by Zamiell** [comment]
its a consequence, but not a reason

**Comment by iamwhoiamhahaha** [comment]
ohhhhhhhhhhhhh my jesus
okay i got you lmao

**Comment by iamwhoiamhahaha** [comment]
### 4 Bluffs

* In non-2-player games, you are not allowed to use a 4 to perform a *Bluff*. (*Bluffs* must be on one-away-from-playable cards or on 3's.)
* ~In 2-player games, you are allowed to perform a *Bluff* by using a 4.~
* In 2-player games, you are allowed to perform a *Bluff* by using a 4, if that 4 looks like a one-away card.
* Note that the 4 is promised nothing.

**Comment by iamwhoiamhahaha** [comment]
See [here](https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Score_Hunting_Guide.md#4-single-bluff) for my definition.

**Comment by iamwhoiamhahaha** [comment]
Or you can delete it from the 2-player doc, since 4 Bluffs are way more complicated for conservative conventions. Now my score hunting guide is official, people can use this convention through my document.

**Comment by Zamiell** [comment]
ok, i deleted 4 bluff
