### ISSUE TITLE
(Occupied) Selfish Color Bluff / (Occupied) Selfish Number Ejection

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#160]
### Introduction

- Normally, when a player is Occupied and they give a clue to someone else, they are usually doing something important that can't be easily done by anyone else on the team.

- In the situation where the players with a playable card perform a _Finesse_ through their own hand, it is known to be a _**Selfish Finesse**_ since no other player can do so or just "lock in" the _Finesse_.

- In another situation where the players with a playable card perform a _Normal Play Clue_ on a bunch of cards, it should be treated as _**Occupied Focus Inversion**_.

- However, what if the players with a playable card give a _Play Clue_ by touching a "playable" card which is leading from their own hand? (For example, Alice has a known playable yellow 1. Instead of playing her yellow 1, she gives a clue touching a yellow 2 on Cathy's hand.) In this situation, they are trying to communicate something extra.

### (Occupied) Selfish Color Bluff

- If the players with a playable card give a **Color Clue** touching the card which satisfies the situation mentioned above (touching **only** one card), they are trying to perform an **_(Occupied) Selfish Color Bluff_** on the next player. 

- In this situation, the next player should blind-play their _Finessed Position_ to fulfill the _Bluff_. And the player who receives the clue should mark their card as a playable card, and it is leading from the players who give the clue.

> For example: 
> - It is the first turn, Alice gives a blue clue touching a blue 1 on Bob's slot 3.
> - Instead of playing his blue 1, Bob gives a **blue clue** touching a blue 2 on Donald's slot 2.
> - Now, it's Cathy's turn, she is surprised that Bob didn't play his blue 1 and gives a blue clue on Donald. If that blue card is one-or-more-away, then it is a _Selfish Finesse_. If the blue clue touches a bunch of cards, then it is an _Occupied Focus Inversion_. However, it is a blue 2 (and only the blue 2 is touched by the clue). Then she realizes it is a _Selfish Color Bluff_ and blind-plays her _Finessed Position_, and a green 1 is successfully played.
> - Now, it's Donald's turn. If the blue card is a 1 then Cathy would respond her _Third Finessed Position_ as an _Unknown Trash Discharge_. If the blue card is a 5, then Cathy would respond her _Second Finessed Position_ as a _5 Color Ejection_. If the blue card is a 3 or 4, Cathy won't play her _Finessed Position_ immediately. Then he realizes his blue card is a 2 since Cathy blind-play her _Finessed Position_ as a _**Selfish Color Bluff**_.

### (Occupied) Selfish Number Ejection

- If the players with a playable card give a **Rank Clue** touching a card (or a bunch of cards) which satisfies the situation mentioned above (only the **focus**), they are trying to perform an **_(Occupied) Selfish Number Ejection_** on the next player. 

- In this situation, the next player should blind-play their _Second Finessed Position_ to fulfill the _Ejection_. And the player who receives the clue should mark their card as a playable card, and it is leading from the players who give the clue.

> For example: 
> - Red 2 is played on the stacks.
> - Alice gives a blue clue touching a blue 1 on Bob's slot 3.
> - Instead of playing his blue 1, Bob gives a **2 clue** touching a blue 2 on Donald's slot 2. (Or touching a bunch of 2s and the focus is on the blue 2)
> - Now, it's Cathy's turn, she is surprised that Bob didn't play his blue 1 and gives a 2 clue on Donald. If that 2 is one-away, then it is a _Finesse/Bluff_. If the 2 is a Trash (red 2), then it is an _Unknown Trash Discharge_. However, it is a blue 2. Then she realizes it is a _Selfish Number Ejection_ and blind-plays her _Second Finessed Position_, and a green 1 is successfully played.
> - Now, it's Donald's turn. Since Cathy blind-plays her _Second Finessed Position_ and the only convention satisfies this scenario is a _**Selfish Number Ejection**_, then he marks his 2 as a blue 2.

**Comment by Zamiell** [comment]
way to edge case to be useful

**Comment by iamwhoiamhahaha** [comment]
### Selfish Color Bluff Examples

#### Example 1

* piper's y1 is known from the *Gentleman's Discard*
* piano's b1 is gotten from the *Finesse*
* piper gives a yellow clue to kimbi as an *OOP Selfish Color Bluff*

https://hanab.live/replay/357420/7

![oop selfish bluff](https://user-images.githubusercontent.com/50160641/100576648-86945880-3319-11eb-8147-5c925c75ed22.png)

### Selfish Number Ejection Examples

#### Example 1

* piano's y2 and kimbi's y3 are known
* piano gives 4 to piper as a *Selfish Number Ejection*

https://hanab.live/replay/357420/14

![Selfish Number Ejection](https://user-images.githubusercontent.com/50160641/100576799-cce9b780-3319-11eb-8ac1-a4f5fdec45fe.png)

**Comment by pianoblook** [comment]
We discussed Example 2 pretty extensively in the review and concluded that it shouldn't really feel particularly strange or like 'bad teamwork' for piano to give the 4s clue versus kimbi. 

In this case we're *both* Occupied, so the only real benefit we noted for piano to let kimbi do it would be if he draws a playable card that kimbi could trust piper to get. But piano cluing 4s here could also just let kimbi safely discard, which seems better for the team if piano *doesn't* draw a card: imagine piano plays, kimbi clues 4, piper discards, piano discards...which has resulted in both *other* teammates discarding instead of kimbi, which feels off.

The hypothetical you shared - where y2 is already down, piano holds y3, and kimbi isn't Occupied - makes it a lot more interesting. I'd probably agree that piper should assume a non-y4 in that case, meaning an ejection is an interesting remedy.

**Comment by pianoblook** [comment]
In example 1, would y3 not be promised? The value of the clue definitely did come from lining up the g1 to be bluffed, so this is a pretty cool idea. 

Ideally y3 should be still promised - in fact I wonder if this should actually _Pull_, versus SCB?

**Comment by iamwhoiamhahaha** [comment]
> In this case we're both Occupied

Note that it should be "In this case we're both *Selfish*" instead of *Occupied*.
A *Selfish* player is always *Occupied* while an *Occupied* player is not always *Selfish*.


> The hypothetical you shared - where y2 is already down, piano holds y3, and kimbi isn't Occupied - makes it a lot more interesting. I'd probably agree that piper should assume a non-y4 in that case, meaning an ejection is an interesting remedy.

So this is the hypo piano mentioned:

![Selfish Number Ejection (hypo)](https://user-images.githubusercontent.com/50160641/100687555-79c84100-33bb-11eb-96ff-520a24a583c0.png)

> In example 1, would y3 not be promised?

It is promised. See [*Selfish Bluff*](https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Selfish_Conventions.md#selfish-bluff).

**Comment by iamwhoiamhahaha** [comment]
> in fact I wonder if this should actually Pull

No. Imagine green 1 is on slot 1 and yellow 3 is on slot 2. It still works as an *Selfish Bluff*.

**Comment by iamwhoiamhahaha** [comment]
*Selfish Bluff* is a form of *Self Color Bluff* btw

**Comment by Zamiell** [comment]
> In another situation where the players with a playable card perform a Normal Play Clue on a bunch of cards, it should be treated as Occupied Focus Inversion.

this is SFI now, not OFI

**Comment by iamwhoiamhahaha** [comment]
this issue was written before the name changed

**Comment by Zamiell** [comment]
doesn't this overlap with #161

**Comment by iamwhoiamhahaha** [comment]
no. selfish number ejection can only be done with rank clues while selfish color chop move can only be done with color clues

**Comment by Zamiell** [comment]
> (Occupied) Selfish Color Bluff

wouldn't they just chop move instead of self bluff

**Comment by iamwhoiamhahaha** [comment]
ohh that's your question
then read this: [*Selfish Bluff*](https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Selfish_Conventions.md#selfish-bluff)

**Comment by Zamiell** [comment]
this was initially denied because it was way too edge case to be useful
since then, only one example has been posted for each thing.
that isn't changing the story of this being edge case - you will need way more examples than that.
