### ISSUE TITLE
(Occupied) Selfish Color Chop Move

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#161]
### (Occupied) Selfish Color Chop Move

- This convention is invented based on the idea from the Selfish Color Bluff described in the issue: [(Occupied) Selfish Color Bluff / (Occupied) Selfish Number Ejection](https://github.com/Zamiell/hanabi-conventions/issues/160)

- What if the players give a color clue touching (**only**) one card on the next player (which is not on chop), and the card is leading from their own hand? In this situation, they are trying to perform a **_Selfish Color Chop Move_**, and the player who receives the color clue should _Chop Move_ all the cards to the right of the clued card.

> For example, in a 3-player game: 
> - Alice gives a blue clue touching a blue 1 on Bob's slot 3.
> - Instead of playing his blue 1, Bob gives a **blue clue** touching a blue 2 on Cathy's slot 4 (which is one-away-from-chop).
> - This is quite strange, since someone can just get the blue 2 after Bob plays his blue 1. If the blue card is on chop, it is reasonable, for Cathy is going to discard a playable card. However, it is not on chop.
> - Imagine the situation where Cathy has a critical card on chop, and Bob sees Cathy has nothing to do from his perspective. If he saves the critical card on chop, the team might lose a playable card, which is quite bad. That's how this convention works.
> - Now, it's Cathy's turn, she is surprised that Bob didn't play his blue 1 and gave a blue clue on her. She sees no playable blue cards on Alice's _Finessed Position_, knowing that it is not a _Selfish Finesse_. It is not an _Occupied Focus Inversion_ either, since it only touches one blue card. Then she realizes her blue card is exactly a blue 2 and also _Chop Moves_ her slot 5 as a **_Selfish Color Chop Move_**.

**Comment by iamwhoiamhahaha** [comment]
### Modification

- You are allowed to perform a _Selfish Color Chop Move_ on any player.

- If the next player sees all the card(s) to the right of the clued card are critical and blind-plays nothing. Now, the team is going to agree it is a _**Selfish Color Chop Move**_ instead of a _**Selfish Color Bluff**_. And the player who receives the clue should _Chop Move_ their card(s).

**Comment by Zamiell** [comment]
seems too edge case to be useful

**Comment by pianoblook** [comment]
This came up in discussion tonight and Jeff linked this proposal.

https://hanab.live/shared-replay/357251#8

piper wanted to find a way to efficiently chop move kimbi, and we agreed yellow should probably work the same way as in 2p: as a Selfish CM.


<img width="1151" alt="Screen Shot 2020-11-29 at 11 03 11 PM" src="https://user-images.githubusercontent.com/32303453/100567857-89e70000-3297-11eb-9758-0b4d90abaf2d.png">

**Comment by Zamiell** [comment]
lets show 3+ examples of it being used in a real game

**Comment by Zamiell** [comment]
i'll also point out that this overlaps with the mistake of giving a play clue to a card that is in your own hand.
if alice clues me red, and alice is supposed to have 2, do i sarcastic discard red 2 or keep it and chop move?
if alice intended the former, then i can chop move trash and discard a 5 and lose the game

**Comment by iamwhoiamhahaha** [comment]
> if alice clues me red, and alice is supposed to have 2, do i sarcastic discard red 2 or keep it and chop move?

it depends on if alice's red 2 is globally known

**Comment by Zamiell** [comment]
i would assume so, my point is that alice can be making a mistake and not realizing that her red 2 is globally known

**Comment by Zamiell** [comment]
in other words:

1) alice can make a big mistake - she does not know her red 2 is playable, even though it was given a *Play Clue* or whatever.
the selfish color chop move convention now makes the team lose the game because bob discards a 5.

2) alice can make a small mistake - she knows that her red 2 is playable, but she forget that it is not globally known that she knows it is playable.
the selfish color chop move convention now makes the team lose the game because bob sarcastic discards the red 3.

**Comment by iamwhoiamhahaha** [comment]
yeah you're right but it's something like alice forgets she is occupied and saves a 5 on chop which causes bob to bomb a critical card from slot 1

**Comment by iamwhoiamhahaha** [comment]
and this convention works pretty well in 2p btw

**Comment by iamwhoiamhahaha** [comment]
Can we have *Selfish Chop Moves* in multi-player for now?
https://hanab.live/replay/727821#19
