### ISSUE TITLE
Selfish Color Clues (in 2-player)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#162]
### Selfish Color Clues (in 2-player)

- This is an instruction how you should respond to a _Selfish Color Clue_ while playing a 2-player game.

- Here are some Selfish Color Clues you might use in the games:

1. [Selfish Finesse (with color clue)](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-selfish-finesse-a-finesse-through-your-own-hand): Turn off in 2-player.
2. [Selfish Color Focus Inversion (Occupied Focus Inversion](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#occupied-focus-inversion-ofi--ofi)): Turn on in 2-player.
3. [Selfish Color Bluff](https://github.com/Zamiell/hanabi-conventions/issues/160): Turn on in 2-player.
4. [Selfish Color Chop Move](https://github.com/Zamiell/hanabi-conventions/issues/161): Turn on in 2-player.

> I personally would like to name the _Occupied Focus Inversion_ as the _Selfish Color Focus Inversion_.

### Case A: The clue only gets one card.

> Case A1: The clued card is on chop → **_Normal Play Clue_**

> Case A2: The clued card is one-away-from-chop → **_Selfish Color Chop Move_**

> Case A3: The clued card is two-away-from-chop → **_Selfish Color (Double) Chop Move_**
(Players can define this as a **_Selfish Color Bluff_** if they want. However, from me experience playing some hard variants like dark suits, it is better to define as a _Double Chop Move_.)

> Case A4: The clued card is three or more away from chop → **_Selfish Color Bluff_**

### Case B: The clue gets multiple cards.

> Case B1: One of the cards is on chop  → _**Normal Play Clue** (Chop Focus)_

> Case B2: None of the cards is on chop and one of the cards is one-away-from-chop → _**Normal Play Clue** (Focus on the leftmost)_

> Case B3: None of the cards is on chop and none of the cards is one-away-from-chop → _**Selfish Color Focus Inversion** (Occupied Focus Inversion)_

**Comment by iamwhoiamhahaha** [comment]
### Explanation

Case A1: Your teammate is going to discard the playable card.

Case A2: Your teammate has a critical card on chop.

> Notes:
> 1. Why do your teammate has a critical card on chop? The most common situation is you just discarded another copy of the card and makes your teammate's chop become critical.
> 2. Before this convention has invented, I usually use _Double Scream Blind-Play_ or _Misplay Chop Move_ to solve this problem. However, getting a strike to protect some cards is always the last resort, this convention provides another better option to solve the problem in this scenario.

Case A3: Your teammate has two critical cards on chop.

> Notes:
> 1. Players can define whichever they want: _**Selfish Color (Double) Chop Move**_ or _**Selfish Color Bluff**_.
> 2. My suggestion is: If you are playing some hard variants like Dark Mixes, playing with _Selfish Color Chop Move_ is optimal, since there is a very high chance that your teammate has a lot of critical cards needed to be saved. However, if you are playing some easier variants, chop moving two critical cards in a row seems unlikely to happen; which means _Selfish Color Bluff_ is a better choice.

Case A4: Chop moving 3 cards in a row seems to be unlikely, even in hard variants. And your teammate has a very high chance having a playable card on _Finessed Position_.

Case B1: Your teammate is going to discard the playable card.

Case B2: If you don't do it this turn, and if your teammate discards after you play the card, the team loses the focus.

> For example:
> - You have a known blue 1. Your teammate has a blue 2 on slot 2 and a blue 4 on slot 4.
> - If you don't give a blue clue to your teammate right now and play the blue 1, and if your teammate has nothing to do and discards their chop; now, you are not able to give a 2-for-1 blue clue since it turns out to be a _Chop Focus_ clue and the focus is no longer on the blue 2.

Case B3: It follows the current convention.

> Notes: I personally never do this in a 2-player game. So I'm not sure if we need O.F.I. during the game.

**Comment by Zamiell** [comment]
> Selfish Color Focus Inversion (Occupied Focus Inversion): Turn on in 2-player.

this doesn't sound very good to me. often times in 2-player you want to "lock in" a 2 for 1 clue before it reaches chop. or, if it is a brown card or a pink card, often times you want to "lock in" the 1 for 1, especially if they have a useless chop.

**Comment by iamwhoiamhahaha** [comment]
> "lock in" a 2 for 1 clue before it reaches chop
see Case B2
> "lock in" the 1 for 1
it is obvious this convention doesn't apply to pink or brown cards

**Comment by Zamiell** [comment]
make a 2p selfish doc and ill link to it

**Comment by iamwhoiamhahaha** [comment]
okay

**Comment by iamwhoiamhahaha** [comment]
https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Selfish_Color_Clues.md

**Comment by iamwhoiamhahaha** [comment]
https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Selfish_Conventions.md

**Comment by iamwhoiamhahaha** [comment]
Example:
IAMJEFF has known b1
![selfish cm](https://user-images.githubusercontent.com/50160641/80937586-58dd4480-8e08-11ea-8ac6-897bc7d77b33.png)

**Comment by Zamiell** [comment]
its linked from the 2p doc now, make a new issue if we need to do anything else
