### ISSUE TITLE
Priority of cards that lead into one's own hand

### ISSUE THREAD

**Issue by sjdrodge** [Zamiell/hanabi-conventions#163]
There's been some discussion on the discord about changing the rules to one of either:

A. Delete the "cards lead into own hand" rule. Lower ranked cards (or 5's) now always have priority.
B. Players have free choice between a lower ranked card (or 5) and a card which leads into their own hand.

Let's consider a situation where a player has known p1y2y3 and must decide which card to play. Option A is an improvement on the current priority rules if the current player draws p2 themselves, or if they will be spending their next turn(s) giving a clue instead of playing. The current rules have the edge if another player draws y4 or if another copy of y3 might be used in a layered finesse.

Option B has the advantage of letting players decide which of these scenario(s) they wish to optimize for, but it has the disadvantage of losing priority finesse/bluff opportunities relative to both  option A and the current rules.

Another thing worth noting is that when a priority finesse is occuring, the current rules allow the finesse of an immediately playable card, whereas option A would only allow players to finesse cards that will take at least one round to become playable. That said, the status quo and option A are equally good when it comes to priority bluffs.

My personal opinion is that more data is required to make a decision, and I'll therefore be tracking these situations in my own games. I encourage other players to do the same, and I also look forward to hearing other opinions.

**Comment by sjdrodge** [comment]
Another point that I failed to mention is that both of these new options would render the **4's Priority Exception** obsolete.

**Comment by Zamiell** [comment]
- A sounds nice in that it makes the priority flowchart simpler
- not a fan of B because it (potentially?) introduces even more complexity into the already-horrible *Priority* system that we have

don't you feel that having A hurts us overall though.
given all hand permutations, it is much more likely that it is optimal to play into your own hand than otherwise.

**Comment by sjdrodge** [comment]
Yes, I believe at this point that option A and option B are both worse than the status quo.
