### ISSUE TITLE
Unnecessary Trash Chop Move Bluff

### ISSUE THREAD

**Issue by sjdrodge** [Zamiell/hanabi-conventions#164]
If a single card that could have been cleanly clued directly is Trash Chop Moved instead, the next player should play their finesse position. The player who was chop moved also then knows that the chop moved card could have been given a normal play/save clue.

**Comment by hanabirnoob** [comment]
Previously brought up here.

https://github.com/Zamiell/hanabi-conventions/issues/146

**Comment by Zamiell** [comment]
> seems unlikely to be useful

**Comment by sjdrodge** [comment]
This convention fits better than it used to given the addition of Junk Ejections and various Discharges. There's very little possibility of confusing it with another convention now, and I saw an opportunity to use it in a game I played the other night, so I urge you to reconsider your opinion.

**Comment by Zamiell** [comment]
link the game

**Comment by iamwhoiamhahaha** [comment]
I believe this is better than Junk Ejection. Tbh, as an inventor of Junk Ejection, I never did it before (or I did it once and my teammate missed that). However, does Unnecessary Trash Chop Move Bluff conflict with Trash Double Bluff? In addition, Trash Chop Move is sometimes better than saving the critical card directly. Imagine Bob has b1, b4, g1, and g3 (where g3 is critical and all the 1 has played on the stacked), giving a 1 clue (chop moving the g3) somehow protects the b4 longer.

**Comment by Zamiell** [comment]
its been over a month, so going to close this for now until we have it being used in at least 1 non-hypothetical game
