### ISSUE TITLE
Three Suits 5-player Conventions

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#168]
### Introduction

- The required  **_efficiency_** (1.67) is way too high in three suits 5-player game; nevertheless, the problem is it has **_0 starting pace_** in which you are not able to discard during the entire game.

- To solve this problem, we need a convention that provides high efficient clues. So here's the [Advanced Hat-guessing Conventions](https://github.com/Zamiell/hanabi-conventions/issues/167) we need in 3 suits 5-player.

- However, it is not guaranteed to win the perfect scores in each attempt, even the efficiency is exceeding 3.0 or higher. You would still lose the games because the playable cards might be out-of-order in last round.

### Three Suits 5-player Conventions

- First **3 clues** are _hat-guessing clues_. Get as many cards to play as possible with these 3 clues.

> Or 4 clues if there are more than 3 cards left in the deck after 3 clues.

- _Tips:_ While giving a hat-guessing clue, you should always touch cards with high rank (e.g. 4 or 5), since you would probably need those cards in last round.

- Starting from the fourth clue (there are always 3 or less cards left in the deck), every clue should be given as a _normal play clue_.

- Each player can decide to draw the last card triggering the end game, even the team still has some clues in the bank.

### Example

- 87443: Three Suits 5-player (https://hanabi.live/replay/87443)

**Comment by iamwhoiamhahaha** [comment]
### Clue Interpretation Tables (3 Suits 5-player)

- **Action**
```
0 - give clue
1 - play a card from slot 1
2 - play a card from slot 2
3 - play a card from slot 3
4 - play a card from slot 4
5 - play a 1-away card from slot 1
6 - play a 1-away card from slot 2
7 - play a 1-away card from slot 3
8 - play a 1-away card from slot 4
```

- **Type of clue**
```
 0 (12) - (1 player away) number clue on newest card
 1 (13) - (1 player away) color clue on newest card
 2 (14) - (1 player away) any clue not touching the newest card
 3 (15) - (2 player away) number clue on newest card
 4 (16) - (2 player away) color clue on newest card
 5 (17) - (2 player away) any clue not touching the newest card
 6 (18) - (3 player away) number clue on newest card
 7 (19) - (3 player away) color clue on newest card
 8 (20) - (3 player away) any clue not touching the newest card
 9 (21) - (4 player away) number clue on newest card
10 (22) - (4 player away) color clue on newest card
11 (23) - (4 player away) any clue not touching the newest card
```

**Comment by Zamiell** [comment]
typically we don't allow hat guessing since it is considered to be cheating. thus this can be an optional convention that i'll link to from the "hat guessing" doc

**Comment by Zamiell** [comment]
it is linked now so i'll close this
