### ISSUE TITLE
Ejection/discharge/charm should work differently in Duck

### ISSUE THREAD

**Issue by aliblong** [Zamiell/hanabi-conventions#174]
The normal definitions of ejection and discharge are not particularly well suited to Duck, where you can't generally single bluff or self-finesse. I would propose the following:
1. rank clue focusing a two-away 3 gets f + 1 (ejection);
2. colour clue to a 5 in the early game gets f + 1;
3. rank clue focusing a two-or-more-away 5 off-chop gets f + 2 (discharge);
4. rank clue focusing a two-or-more-away 4 gets f + 3 (charm).

Consequences:
1. can't perform a true double finesse with a rank clue;
2. can't trash discharge;
3. can't double bluff except with one-away cards.

IMO, Consequence 1 will generally not cause interpretation issues, since even if a colour clue would be wrong focus, a reclue to shift focus will be available; it would lose a small amount of aggregate efficiency from free choice of rank, which seems like a reasonable tradeoff. Consequence 2 is not important. Consequence 3 could be painful; this could be addressed by e.g. making Proposal 1 be a double bluff.

**Comment by iamwhoiamhahaha** [comment]
The current conventions in duck are fine to me. It's simple and works pretty well:

- any clue focusing a 2: a finesse / a double bluff

- any clue focusing a two-or-more-away 3: a double finesse / a double bluff

- any clue focusing a two-or-more-away 5 (except the rank clue touching a 5 on chop): an ejection

- any clue focusing a trash: a discharge

- any clue focusing a two-or-more-away 4: a charm

If you want to "protect" 3s in duck as we do in other variants with 3 bluffs, I believe we can just replace _5 Ejections_ with _3 Ejections_. As following:

- any clue focusing a 2: a finesse / a double bluff

- any clue focusing a two-or-more-away 3: an ejection

- any clue focusing a trash: a discharge

- any clue focusing a two-or-more-away 4: a charm

Unknown Trash Discharge is extremely powerful in duck. It not only gives a known trash to the clue receivers, but also provides them more information on their cards (touched by the same clue) after discarding the trash.

**Comment by aliblong** [comment]
> Unknown Trash Discharge is extremely powerful in duck. It not only gives a known trash to the clue receivers, but also provides them more information on their cards (touched by the same clue) after discarding the trash.

Telling someone where trash is doesn't sound that powerful to me. I can't recall it ever being something I actively looked to do in duck. Seems a lot better to tell someone where useful cards are than to tell them where trash cards are.

I think that in Duck, where you can't put actual positively identifying clues on a card, tradeoffs ought to fall more in favour of specificity than generality. Your first two bullet points are together favouring generality over specificity. I think you're also neglecting to account that generally, any bluff has to be a double bluff. So what note do you put on your card when two unrelated consecutive blind cards play? Any one-away card, any 3... that's a lot of possibilities.

> I believe we can just replace 5 Ejections with 3 Ejections.

This sounds like a bad thing. Protecting 3s is not, IME, a primary concern in Duck. Conversely, positively identifying 5s is *very* strong.

Do you see something that you dislike in my proposal? Is it just that cluing trash can no longer be used productively?

**Comment by iamwhoiamhahaha** [comment]
Your proposal seems fine and deleting UTD is okay to me, but I'd prefer to make it simpler. How about this:

- any clue focusing a 2: a finesse

- any clue focusing a two-or-more-away 3: an ejection

- any clue focusing a two-or-more-away 5 (except the rank clue touching a 5 on chop): a discharge

- any clue focusing a two-or-more-away 4: a charm

**Comment by iamwhoiamhahaha** [comment]
_**3 Discharge**_ looks awesome  :grinning:

**Comment by iamwhoiamhahaha** [comment]
UTD is turned off until all the 3s are no longer two-or-more-away.

**Comment by aliblong** [comment]
Sounds good, but I'd want to playtest your version vs an equivalent version where colour clues are always multi-finesse (i.e. my version).

**Comment by Zamiell** [comment]
i also opt for the simpler version (surprise, surprise)

**Comment by Zamiell** [comment]
```
* any clue focusing a one-away card: a finesse / a double bluff
* any clue focusing a two-or-more-away 5 (except the rank clue touching a 5 on chop): an ejection
(preserve the current convention 5CE)
* any clue focusing a two-or-more-away 3: a discharge (3 means slot 3)
* any clue focusing a two-or-more-away 4: a charm
```

this sounds fantastic, and easy to remember

**Comment by Zamiell** [comment]
ok, I've updated this page with this:
https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/Duck.md

feel free to continue playtesting, and lets open a new issue for any additional changes
