### ISSUE TITLE
Known rank choice bluff (with a single 1)

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-conventions#176]
In the early game, when cluing a single 1, you want to do it with a color clue. It's because it gives more information about player's hand. Usually, the only time you want to clue single 1 with a rank clue is because otherwise the focus of the clue would not be on 1, or to avoid bad touch.

What if a player does this anyway? Something extra must be communicated.

For an example:

- No variant, 3 player game.

- First turn of the game. Alice clues 1s to Cathy. It touches a single red 1 on Cathy's chop and nothing else.

- Bob sees that there was no reason for Alice to clue Cathy's red 1 with a number as Bob sees no duplicate red cards in Cathy's hand. As Bob has nothing clued on his hand that could cause a bad touch, it would be a rather lousy clue. Alice must be communicating something extra. 

- Bob blind-plays his finesse position. It is green 1.

- Without Bob's blind-play, Cathy would have assumed duplicates in her hand. Now she plays her red 1 without assuming anything else about her hand.

Should be fairly common occurrence with almost no downsides.

**Comment by Zamiell** [comment]
we commonly do this if bob has r1 on finesse position. so in your example he would bomb

**Comment by hanabirnoob** [comment]
So it conflicts with hesitation blind-play?

**Comment by Zamiell** [comment]
does what conflicts with a hesitation blind-play

**Comment by hanabirnoob** [comment]
The thing I proposed.

**Comment by Zamiell** [comment]
hesitation blind-play isn't really a "convention", it is just a specific read that people do from time to time, thus it isn't really sensible to talk in terms of things "conflicting" with it

**Comment by hanabirnoob** [comment]
But would that mean that if Alice gives that 1 clue that touches only Cathy's chop, does it always mean that Bob has matching card on finesse position? And if so, can he mark it as known trash?

**Comment by Zamiell** [comment]
not necessarily no, that's too strong of a read
