### ISSUE TITLE
Rename Occupied Focus Inversion as Selfish Color Focus Inversion

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#178]
I found a lot of people misunderstood this move. They thought they can do an OFI each time they were occupied. Wrong. If I'm holding a globally known red 1 and I give you a play clue touching two blue cards and you think I am doing an OFI? Omg. It only applies when I give a play clue touching two or more cards with the color I'm holding. In this situation, I'm not only occupied but also selfish. Yeah I'm a selfish person lol. Anyway, renaming _Occupied Focus Inversion_ as _**Selfish Focus Inversion**_ is clearer.

**Comment by iamwhoiamhahaha** [comment]
This happened after I created the issue.
![ofi](https://user-images.githubusercontent.com/50160641/78963141-21d98300-7b29-11ea-8890-21a2de97b0df.png)
MasN bombed the n3 thinking that was an OFI.

**Comment by Romain672** [comment]
(I don't care about the name anyway, I didn't tried a single one of those.)

**Comment by iamwhoiamhahaha** [comment]
Oops, it should be **_Selfish Color Focus Inversion_** as I mentioned [here](https://github.com/Zamiell/hanabi-conventions/issues/162), if _[Selfish Number Ejection](https://github.com/Zamiell/hanabi-conventions/issues/160)_ is going to be a new convention.

**Comment by Zamiell** [comment]
ok
