### ISSUE TITLE
The Bad Touch Layered Finesse (Bluffs that Blind-Play a Duplicated Card)

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#179]
* If a player performs a *Bluff* that causes a blind-play of a globally-known duplicated card, that is quite strange. Doing this is not very good, as it violates *Good Touch Principle* and does not accomplish very much in general.
* Players agree that this is not a *Bluff* at all, but instead a *Layered Finesse*. The player who blind-played the card should continue to blind-play cards until they find the promised card.
* This section also applies to *Priority Bluffs* that cause the blind-play of a duplicated card.
* For example, in a 3-player game:
  * All of the 2's are played on the stacks.
  * Alice has a globally-known red 3 in her hand. (It is "filled in" with both a red clue and a number 3 clue.)
  * Alice clues blue to Bob, touching a blue 4 as a *Play Clue*.
  * Bob knows that this must be a *Finesse*, so he attempts to blind-play blue 3 from his *Finesse Position*. Instead, he blind-plays red 3.
  * Cathy discards her chop.
  * Alice discards her known red 3 (since it is already played and is now trash).
  * Bob knows that *Bluffs* that duplicate a card like this are supposed to be treated as *Layered Finesses*. Bob blind-plays his *Second Finesse Position* as blue 3 and it successfully plays.

**Comment by iamwhoiamhahaha** [comment]
imo this is just a sort of "pseudo-save" on the target (saving the blue 4 in the case above)

**Comment by Zamiell** [comment]
historically the way we have played it that it was a pseudo save (invented by Duneaught), but since they we have played more high-efficiency variants and we don't play like that anymore. this github issue is more just documenting how we have been playing over the last 1-2 years or so instead of proposing a new convention.
