### ISSUE TITLE
Hat-Guessing for Duck 3 suits 5-player

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#181]
### Duck 3 Suits (5-player) Conventions

- Use `Action Clue Interpretation Tables` with first **3 clues**. (Or 4 clues if there are more than 3 cards left from the deck after giving 3 clues.)

- Starting from the 4th (or 5th) clue, use `Information Clue Interpretation Tables` to give **information clues** to the whole team. Any player can initiate the End Game (by drawing the last card).

- The conventions are similar to [Three Suits 5-player Conventions](https://github.com/Zamiell/hanabi-conventions/issues/168).

### Type of Clue Interpretation Tables (mod 9)
```
 0  (9) - (1 player away) any clue on newest card
 1 (10) - (1 player away) any clue not touching the newest card
 2 (11) - (2 player away) any clue on newest card
 3 (12) - (2 player away) any clue not touching the newest card
 4 (13) - (3 player away) any clue on newest card
 5 (14) - (3 player away) any clue not touching the newest card
 6 (15) - (4 player away) any clue on newest card
 7 (16) - (4 player away) any clue not touching the newest card
 8 (17) - (any player away) any clue touching only the oldest card
```

### Action Clue Interpretation Tables
```
0 - give clue
1 - play a card from slot 1
2 - play a card from slot 2
3 - play a card from slot 3
4 - play a card from slot 4
5 - play a 1-away card from slot 1
6 - play a 1-away card from slot 2
7 - play a 1-away card from slot 3
8 - play a 1-away card from slot 4
```

### Information Clue Interpretation Tables
```
0 - no useful card
1 - a useful card on slot 1
2 - a useful card on slot 2
3 - a useful card on slot 3
4 - a useful card on slot 4
5 - a unique card on slot 1
6 - a unique card on slot 2
7 - a unique card on slot 3
8 - a unique card on slot 4
```

**Comment by iamwhoiamhahaha** [comment]
### Information Priority

1. a unique card

2. a useful card with lowest rank

3. a useful card on the left-most

### Information Rules

- The player is not allowed to give information on the same unique card the second time.

- Each useful card should be reassigned each time a player gives a clue (if they see a better line).

**Comment by iamwhoiamhahaha** [comment]
### Example
https://hanabi.live/replay/117203

### Turn 2
- **Type of Clue**: 6 (15) - (4 player away) any clue on newest card
![duck1](https://user-images.githubusercontent.com/50160641/79041502-ffc42b80-7c22-11ea-8dbe-0fa6854b933e.png)

- **Action**: **+1** (squirtle's red 1) **+4** (bulbasaur's green 1) **+0** (eevee) **+1** (dratini's blue 1) = **6**

### Turn 4
- **Type of Clue**: 8 (17) - (any player away) any clue touching only the oldest card
![duck4](https://user-images.githubusercontent.com/50160641/79041652-f7b8bb80-7c23-11ea-9f75-89a337cc350d.png)
- **Action**: **+6** (dratini's blue 3) **+2** (charmander's blue 2) = **8**

### Turn 9
- **Type of Clue**: 4 (13) - (3 player away) any clue on newest card
![t9](https://user-images.githubusercontent.com/50160641/79041782-081d6600-7c25-11ea-8c0b-01ddfde61a42.png)

- **Action**: **+0** (dratini) **+3** (charmander's green 2) **+1** (squirtle's red 2) **+0** (bulbasaur) = **4**

### Turn 10
- **Type of Clue**: 0  (9) - (1 player away) any clue on newest card
![t10](https://user-images.githubusercontent.com/50160641/79041822-69ddd000-7c25-11ea-8501-3a13968bf322.png)

- **Action**: **+0** (eevee) **+0** (dratini) = **0**
> Notes: 
> - This is an **action clue** since there are 3 or more cards left from the deck.
> - This clue looks like a finesse on eevee (green 4 or red 4). However, this is ambiguous and dratini doesn't know which card eevee should play. So it can't be a finesse but just a stall clue.

### Turn 13
- **Type of Clue**: 8 (17) - (any player away) any clue touching only the oldest card
![t13](https://user-images.githubusercontent.com/50160641/79041900-ecff2600-7c25-11ea-8f4d-4b90c0b13a91.png)

- **Information**: **+1** (charmander's useful blue 4) **+8** (squirtle's unique blue 5) **+1** (bulbasaur's useful green 3) **+7** (eevee's unique red 5) = **17**

### Turn 14
- **Type of Clue**: 6 (15) - (4 player away) any clue on newest card
![t14](https://user-images.githubusercontent.com/50160641/79042078-4c116a80-7c27-11ea-8ffa-0dff82f58541.png)

- **Information**: **+1** (dratini's useful red 4) **+1** (charmander's useful blue 4) **+0** (squirtle) **+4** (bulbasaur's useful red 3) = **6**
> Note 1:
> - bulbasaur already knew he has a useful card (green) on slot 1 from last clue. (He can narrow down the possibility knowing it is a red 3 or a green 3.
> - Now, bulbasaur knows he has another useful card on slot 4 (again, could be a red 3 or green 3). If his red 3 is on slot 1, eevee would probably assign him `1` telling him to play slot 1 instead of slot 3. Then he plays a red 3 from slot 4.

> Note 2:
> - By conventions, eevee should probably assign `3` to squirtle telling him he has a useful card on slot 3. Since from charmander's perspective, he doesn't know that blue 4 is "useless".

> Note 3:
> - '5' assign to dratini and bulbasaur is quite ambiguous. From bulbasaur's perspective, it could be "+1 (dratini) +4 (bulbasaur)" or "+3 (dratini) +2 (bulbasaur)".

### Turn 16
- **Type of Clue**: 2 (11) - (2 player away) any clue on newest card
![t16](https://user-images.githubusercontent.com/50160641/79042350-88de6100-7c29-11ea-8cc2-c46f22ee913f.png)

- **Information**: **+6** (bulbasaur's unique green 3) **+1** (eevee's useful green 4) **+3** (dratini's useful green 4) **+1** (squirtle's useful blue 4) = **11**
> Note 1:
> - Why assign `6` to bulbasaur? By conventions, every useful card should be reassigned each time a player gives a clue. However, bulbasaur draws another copy of green 3 and his green 3 on slot 2 becomes "unique". That's the reason charmander assign `6` to bulbasaur.
> - However, this is quite ambiguous, since it could be the case: **+5** (bulbasaur's unique green 5) **+2** (eevee's useful red 4) **+3** (dratini's useful green 4) **+1** (squirtle's useful blue 4) = **11**.
> - It seems like charmander should probably assign `2` to bulbasaur since other players can understand that.

> Note 2:
> - This clue is ambiguous to assign `4` to eevee and dratini. Since it can be "+1 (eevee) +3 (dratini)" or "+2 (eevee) +2 (dratini)".

### Ending
![endgame](https://user-images.githubusercontent.com/50160641/79042733-9ea15580-7c2c-11ea-8e8f-e9aa26c7e786.png)

**Comment by iamwhoiamhahaha** [comment]
### Summary
- Like any 3 suits 5-player game, the problem is not on **high required efficiency** (+1.67) but **low starting pace** (+0). Hat-guessing is amazing, you don't need to worry about efficiency too much. Even you play so well by giving a lot of 3-for-1 or 4-for-1 clues at first, you might still lose the game (not getting perfect scores) since the cards are out-of-order.
- The problem I confront so far is the ambiguity of useful cards from the _Information Clues_. If we can find a way to define more details about useful cards (like priority), then I can say: "Beating 3 suits 5-player game in duck is not a dream."

**Comment by iamwhoiamhahaha** [comment]
### Type of Clue Interpretation Tables (mod 9)
```
 0  (9) - (1 player away) any clue on newest card
 1 (10) - (1 player away) any clue not touching the newest card
 2 (11) - (2 player away) any clue on newest card
 3 (12) - (2 player away) any clue not touching the newest card
 4 (13) - (3 player away) any clue on newest card
 5 (14) - (3 player away) any clue not touching the newest card
 6 (15) - (4 player away) any clue on newest card
 7 (16) - (4 player away) any clue not touching the newest card
 8 (17) - (any player away) any clue touching only the oldest card
```

### Action Clue Interpretation Tables
```
0 - give clue
1 - play a card from slot 1
2 - play a card from slot 2
3 - play a card from slot 3
4 - play a card from slot 4
5 - play a 1-away card from slot 1
6 - play a 1-away card from slot 2
7 - play a 1-away card from slot 3
8 - play a 1-away card from slot 4
```
### Information Clue Interpretation Tables (Changed)
```
0 - no useful card
1 - a useful card on slot 1
2 - a useful card on slot 2
3 - a useful card on slot 3
4 - a useful card on slot 4
5 - two or more useful cards and the card with lowest information rank is on slot 1
6 - two or more useful cards and the card with lowest information rank is on slot 2
7 - two or more useful cards and the card with lowest information rank is on slot 3
8 - two or more useful cards and the card with lowest information rank is on slot 4
```

### Information Rank
- Red 1 has lowest _information rank_ and blue 5 has highest _information rank_.
(i.e., r1<g1<b1<r2<g2<b2<r3<g3<b3<r4<g4<b4<r5<g5<b5)

### Information Clue Rules
- If the players who have two or more useful cards and one of them is a unique card (e.g. a 5), and if everyone knows they can only play one card for the rest of the game, **only count** that unique card while giving an information clue.
- If the players who have two or more useful cards already knew the position of their card with lowest information rank from previous clue, **do not** count that card while giving an information clue.

**Comment by iamwhoiamhahaha** [comment]
### Information Clue Example

### Turn 13
- **Type of Clue**: 4 (13) - (3 player away) any clue on newest card
![h13](https://user-images.githubusercontent.com/50160641/79046343-f77be880-7c42-11ea-8488-7979ba3d69bc.png)

- **Information**: **+1** (charmander's blue 4) **+7** (squirtle's blue 4) **+8** (bulbasaur's red 3) **+6** (eevee's red 4) = **22**

### Turn 14
- **Type of Clue**: 2 (11) - (2 player away) any clue on newest card
![h14](https://user-images.githubusercontent.com/50160641/79046423-7113d680-7c43-11ea-85cd-aa9548309fb0.png)

- **Information**: **+5** (dratini's red 4) **+1** (charmander's blue 4) **+4** (squirtle's blue 5) **+1** (bulbasaur's green 3) = **11**

### Turn 16
- **Type of Clue**: 4 (13) - (3 player away) any clue on newest card
![h16](https://user-images.githubusercontent.com/50160641/79046572-58f08700-7c44-11ea-8708-77b16295c3b5.png)

- **Information**: **+4** (bulbasaur's red 3) **+5** (eevee's green 4) **+3** (dratini's green 4) **+1** (charmander's blue 4) = **13**

### Turn 18
- **Type of Clue**: 3 (12) - (2 player away) any clue not touching the newest card
![h18](https://user-images.githubusercontent.com/50160641/79046780-770ab700-7c45-11ea-9d1f-6697abdd1e1e.png)

- **Information**: **+1** (charmander's red 3) **+4** (squirtle's blue 5) **+4** (bulbasaur's red 3) **+3** (eevee's red 5) = **12**

**Comment by iamwhoiamhahaha** [comment]
Okay so I completed the perfect scores with the strategies above. (First attempt)
### Perfect Scores in Duck 3 Suits 5-player
https://hanabi.live/replay/117203

**Comment by iamwhoiamhahaha** [comment]
Okay so I completed the perfect scores with the strategies above. (First attempt)
### Perfect Scores in Duck 3 Suits 5-player
https://hanabi.live/replay/117350

**Comment by iamwhoiamhahaha** [comment]
### Information Clue Rules (Changed)
1. **Do not** count the card which has assigned by action clues.
2. If the players have only one known useful card, **do not** count that card while giving another information clue, i.e., assign them with `0`.
3. If the players have only one known useful card (from previous information clues) and they play another playable card (from previous action clues):
(a) If they draw a trash, assign them with `0`.
(b) If they draw a useful card with higher rank, assign them with `1`.
(c) If they draw the other copy of the known useful card, **reassign** their known useful card, i.e. with `2`, `3`, or `4`. (It gives more information to their known useful card.)
(d) If they draw a useful card with lower rank, assign them with `5`.
4. If the players who have two or more useful cards, **do not** count the cards they have known from previous information clues while giving a new clue, i.e., assign the information to the other cards (including the new card they draw).
5. If the players who have two or more **unknown** useful cards and one of them is unique (e.g. a 5), and if everyone knows they can only play one card for the rest of the game, only count that unique card while giving an information clue.

**Comment by Zamiell** [comment]
did you update your guide with this information? can I close this issue?

**Comment by iamwhoiamhahaha** [comment]
yes
