### ISSUE TITLE
Out-of-Position Ejections/Discharges

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#182]
### Proposal
Change the current convention _Out-of-Position Unknown Trash Discharge_ to **_Out-of-Position Discharges_** and add **_Out-of-Position Ejections_**

- _Unknown Trash Discharge_ was a globally known move (for expert) when the first time I brought up [this idea](https://github.com/Zamiell/hanabi-conventions/issues/119). However, nowadays, there are more and more people learning and knowing _5 Number Discharge_, and we might have another kind of discharges in the future. I think it's time to extend an _Out-of-Position Unknown Trash Discharge_ to every kind of discharges, e.g., an _Out-of-Position 5 Number Discharge_, a move I did it once before, Zamiel knew that.
- Also, I believe we can extend this idea to ejections. And actually I brought up [this idea](https://github.com/Zamiell/hanabi-conventions/issues/119#issuecomment-557904794) in the same issue, but Zamiel didn't approve that (saying "it might not make sense to document it unless you are already doing this move in a semi-routine fashion"). However, I saw someone did this recently and I think it's time to make it official.

**Comment by Zamiell** [comment]
> I saw someone did this recently

link the game

**Comment by iamwhoiamhahaha** [comment]
you did it, zam
https://hanabi.live/replay/111246/3

**Comment by Zamiell** [comment]
propaganda

**Comment by iamwhoiamhahaha** [comment]
hehehe

**Comment by iamwhoiamhahaha** [comment]
can you split these into two parts? it's so strange to see *Out-of-Position Ejection* in *Discharges* section

**Comment by iamwhoiamhahaha** [comment]
and as i've pm'd you, fireheart is the first player did an out-of-position 5 color ejection
https://discordapp.com/channels/140016142600241152/225437979085242369/628071994767704074
i believe he should take the credit on *Out-of-Position Ejection*

**Comment by Zamiell** [comment]
> can you split these into two parts?

done

>  fireheart is the first player who did an out-of-position 5 color ejection

afaik there isn't a section for that since it isn't a new convention

**Comment by iamwhoiamhahaha** [comment]
> afaik there isn't a section for that since it isn't a new convention

you mean someone did an *out-of-position ejection* and *out-of-position discharge* before?

**Comment by Zamiell** [comment]
i dont know who first did it, but it doesn't matter, because i'm not adding it as a section
