### ISSUE TITLE
5 Ejection / 3 Discharge / 4 Charm

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#183]
### Proposal
Add _**3 Discharge**_ and extend **_5 Ejection_**, _3 Discharge_, and **_4 Charm_** to any variant where a move doesn't give positive information. For example, _Color Blind_ (color clue), _Number Blind_ (number clue), _Totally Blind_, _Cow & Pig_, and _Duck_, 

- _5 Ejection_ and _4 Charm_ are the current move in duck. And _3 Discharge_ came from the idea when I replied @aliblong in [this issue](https://github.com/Zamiell/hanabi-conventions/issues/174#issuecomment-608206583).
- The idea is simple, if it requires you to blind-play two or more cards to fulfill the finesse, then respond _Second Finessed Position_ to a 5 as a _**5 Ejection**_, _Third Finessed Position_ to a 3 as a _**3 Discharge**_, and _Fourth Finessed Position_ to a 4 as a _**4 Charm**_.

**Comment by iamwhoiamhahaha** [comment]
I believe we can also extend this to _Extremely Ambiguous_ when giving a color clue.

**Comment by iamwhoiamhahaha** [comment]
_Unknown Trash Discharge_ is turned off in these variants until all the 3s are no longer two-or-more-away, i.e., all of the 1's are played on the stacks.

**Comment by iamwhoiamhahaha** [comment]
Example of **_3 Discharge_** in _Extremely Ambiguous (4 Suits)_
![3 Discharge](https://user-images.githubusercontent.com/50160641/80061021-a03f1780-8562-11ea-9a6b-fcf6108087fd.png)

**Comment by Zamiell** [comment]
how is that a 3 discharge if it is focused on a 2

**Comment by iamwhoiamhahaha** [comment]
the focus is on sky 3 (two-away)

**Comment by Zamiell** [comment]
its just a 3 bluff then

**Comment by iamwhoiamhahaha** [comment]
how does schark know that is a 3 bluff?

**Comment by Zamiell** [comment]
wouldnt schark assume berry 1?

**Comment by iamwhoiamhahaha** [comment]
if schark has berry 1 on slot 2 and i clue blue to schark as an _Unnecessary Blue Bluff_, then alphabeta plays slot 1 and schark plays slot 2

if schark has a two-away 3 and i clue blue to schark as a _3 Discharge_, then alphabeta plays slot 1 and schark marks his slot 3 as a 3

**Comment by Zamiell** [comment]
if schark has berry 1 on slot 2 and i clue blue to schark, then it would be UTD and alphabeta plays slot 3, then schark discards slot 2

**Comment by iamwhoiamhahaha** [comment]
ohh sorry i forgot b1 is played

as my suggestion, utd is turned off until all the 1's played

**Comment by iamwhoiamhahaha** [comment]
or we can mix both

**Comment by iamwhoiamhahaha** [comment]
libster said "Telling someone where trash is doesn't sound that powerful to me."
https://github.com/Zamiell/hanabi-conventions/issues/174#issuecomment-608202402

**Comment by iamwhoiamhahaha** [comment]
so basically we do 3D until all the 1's played and then turn on UTD

**Comment by iamwhoiamhahaha** [comment]
we don't have that many trash at the start of the game, then 3 Discharge is more useful than UTD

when all the 1 has played, it is exactly the appropriate moment to turn UTD on, since there will be more trash available to initiate an UTD at the same time

**Comment by Zamiell** [comment]
lets leave this on hold until #179 is closed

**Comment by iamwhoiamhahaha** [comment]
we mean #174 ?

**Comment by Zamiell** [comment]
yes, i meant 174

**Comment by Zamiell** [comment]
please see: https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/No_Positive_Clues.md

**Comment by iamwhoiamhahaha** [comment]
it also apply to **Cow & Pig**, zam

**Comment by iamwhoiamhahaha** [comment]
and why not turn the *UTD* on after the *3 Discharge* is not available to perform

**Comment by Zamiell** [comment]
fine

**Comment by Zamiell** [comment]
should be fixed now

**Comment by iamwhoiamhahaha** [comment]
👍
