### ISSUE TITLE
Convention Proposal: Unnecessary UTD

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#184]
![2020-04-15_0919](https://user-images.githubusercontent.com/48993588/79361754-94b47680-7efa-11ea-87bb-f17fafa242cc.png)

Form 1:
Follows this convention:
[https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-unnecessary-trash-finessebluff-chop-move](url)

Kakashi clue's pink to Sucubis
Sin_faith plays G4 as UTD
Arnino can see that this was an unnecessary UTD as 4's or green could be given.  Because the card to the right of the trash is something valuable to cm, it should be interpreted as Form 1.  

Sucubis should chop move all the cards to the right of the trash card, as Sucubis can see that it was "unnecessary"

Form 2:
Let's say that Sucubis's slot 2 was some trash card like B1
Kakashi clue's pink to Sucubis
Sin_faith plays G4 as UTD
Arnino can see that this was an unnecessary UTD as 4's or green could be given.  Additionally, Arnino can see that, if this was Form 1, Sucubis would chop move a B1.  Arnino must do something to show that Sucubis should not CM.
Thus, Arnino will play slot 1 to show it is Form 2.  
Sucubis can see this was Unnecessary and can see that Arnino played slot 1 to show that this is Form 2 of the Unnecessary UTD and will not chop move.

Form 3:
Same thing as in the first two forms only the trash card is a card on chop. Thus, this should be taken as a trash push.

**Comment by hanabirnoob** [comment]
Could be made even more generalized by applying it to most ejections and discharges.

**Comment by efaust** [comment]
It's hard with more than one card touched, because the extra touch of a good card might make it work in and of itself. Imagine if the i4 was i5 and g5 was trash. might Dr_Kakashi not still choose to discharge?

With one card touched, I think it's clear. It should be a cm.

**Comment by efaust** [comment]
Another interesting question is: are fillins on existing cards worth enough? Like for example, what do people think about: https://hanabi.live/replay/123829/9

**Comment by Dr-Kakashi** [comment]
> Another interesting question is: are fillins on existing cards worth enough? Like for example, what do people think about: https://hanabi.live/replay/123829/9

I still feel it's worth it for Kyle to cm.  Yes, you are filling in valuable information on good cards, but that's just a "bonus."  Dr_Kakashi doesn't have to give Kyle trash to discard.  He can just clue the R2 directly.

**Comment by efaust** [comment]
Granted, but surely the filling is higher value if it also gets the card to play (if negative color isn't valuable, as in that case)

We can say that it's rare or specific enough as to not be worth worrying about, but I don't think "I could have just given a worse clue" (cluing it directly) holds up for me, in this scenario.

**Comment by iamwhoiamhahaha** [comment]
You are not the first player doing this. But I believe it's time to add them to the doc:
- Extend the _Unnecessary Trash Push_ to _**Unnecessary Unknown Trash Discharge Trash Push**_
![Unnecessary Unknown Trash Discharge Trash Push](https://user-images.githubusercontent.com/50160641/79643463-a5ecd400-81d5-11ea-8c9d-7b9cc472bbff.png)

- Extend the _Unnecessary Trash Finesse/Bluff Chop Move_ to _**Unnecessary Unknown Trash Discharge Chop Move**_

**Comment by hanabirnoob** [comment]
Can unnecessary misplay chop moves though bluff work in the same manner?

**Comment by Dr-Kakashi** [comment]
Additionally, can we apply this idea to the rest of the conventions?

Like Unnecessary Trash Push, Unnecessary Trash CMetc.?

**Comment by Zamiell** [comment]
form 1 is fine, form 2 doesn't seem very useful

**Comment by Zamiell** [comment]
in terms of asynchronicity, is is UUTDCM more or less or same than UTFCM.
if more, then i vote deny

**Comment by Dr-Kakashi** [comment]
> in terms of asynchronicity, is is UUTDCM more or less or same than UTFCM?
> if more, then i vote deny

UUTDCM - Unnecessary Unknown Trash Discharge Chop Move
UTFCM - Unnecessary Trash Finesse Chop move

I'm not really sure what you mean by more or less.  They both follow the same concepts.

**Comment by Zamiell** [comment]
i think its probably the same. in general i am wary of async conventions.

**Comment by Zamiell** [comment]
### The Unnecessary Unknown Trash Discharge Chop Move (UUTDCM)

* First, see the *[Unnecessary Trash Finesse/Bluff Chop Move](#the-unnecessary-trash-finessebluff-chop-move)*.
* This same concept applies to *Unknown Trash Discharge*. In other words, if an unnecessary *Unknown Trash Discharge* is performed, then the player who receives the clue should *Chop Move* in the same way as the *Unnecessary Trash Finesse/Bluff Chop Move*.
* Note that this convention **only** applies if it touches exactly **one** trash card. (This is because we want players to have the ability to perform 2-for-1 UTDs without promising a *Chop Move*.)
