### ISSUE TITLE
Convention Proposal: Inverted Finesse/Bluff

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#185]
- Generally, finesses/bluffs are given to a card that calls for a blind play of an in-between card.  This convention is a way to call for a blind play of a card that is NOT in-between.
- Normally, when a player receives a finesse/bluff they must immediately blind play to demonstrate that a finesse/bluff was given.  
- If the player defers and does something else, it generally means the finesse was ambiguous and the next player must immediately blind play the card that was called for.  
- Additionally, a player may defer a finesse/bluff to give a finesse/bluff of their own that only they can see.  
- Thus, if a player who is finessed/bluffed gives a standard play clue, it must be to initiate a finesse by context.
- After the card is played, the next player with the matching card must immediately blind play to show that an inverted finesse was performed.  

Example 1:
Cards played on the board: R1
Cathy's hand: x - R2 - B3 - x
1. Alice clue's Cathy blue touching a blue 3 initiating a finesse/bluff.  
2. Bob can see that Donald has a R3 on finesse position.  Bob can also uniquely clue Cathy's R2.
3. Bob clue Cathy's R2 with red.
4. Cathy has a card that could be B1, but she see's that Bob has a playable card on finesse position.  She also can see that Donald has a R3 on finesse position.  Thus, she must respect that an inverted finesse is being performed.  As an added benefit, it puts the ambiguous finesse on Donald so he will have to blind play his finesse position.
5. Cathy plays R2
6. Donald can see that Bob deferred the finesse/bluff.  Donald can reason two scenarios:
a. It's an ambiguous finesse on him.
b. Bob deferred the finesse/bluff to give a finesse/bluff of his own.  
7. In both cases, Donald must blind play. Donald blind plays R3. 

Example 2:
Cards played on the board: Y1
Cathy's hand: x - R2 - B3 - x
1. Alice is being finessed/bluffed.
2. Alice can see that Donald has a Y3 on finesse position.
3. Alice can also see that both Bob and Cathy are holding a Y2.  So she can safely assume that she is not being finessed/bluffed for a Y2.
4. Alice defers her finesse/bluff to clue Bob's Y2.
5. Bob finds this strange that Alice didn't respond to the finesse/bluff.  However, he can also reason that he was given Y2 so that it sets Cathy up to get Y3.  Thus, Bob should not blindly play an ambiguous card and play Y2.
6. Cathy can see that Alice deferred to set her up to get Y3 in Donald's hand.  However, because of this Inverted finesse convention the Y3 is already gotten.  Thus, Cathy will do something else.
7. Donald finds the series of events extremely odd.  Donald can reason two scenarios:
a. It's an ambiguous finesse on him.
b. Alice deferred the finesse/bluff to give a finesse/bluff of his own.  
8. In both cases, Donald must blind play. Donald blind plays Y3.

Discussion:
I believe this Convention would fall in line around the same level as a Hesitation Blind Play.  A player must be careful to not dupe cards.  

In Example 1, what if Bob deferred playing a R2 and clued Cathy's R2 causing a duplication?  Well, in this case, Cathy will get a safe discard and discard the R2 as a Gentleman's to pass it back to Bob.  This is similar to a Certain Discard, only, in this case, it's a card that is touched by a clue.  Additionally, it would be very bad for Bob to waste a clue, while also not playing his finesse position.  Bob must have a reason to do this.  In this case Donald would mark his slot 1 as R3 and will play it once R2 is down.  Thus, this still satisfies the minimum clue value principle even in the worst-case scenario where a card is duped.

In Example 2, everyone at the table can understand why Alice deferred her finesse/bluff.  It is just better teamwork for her to get Y2 to keep tempo going on Y3, so I would say this is the purest example of this convention working well.  

I believe an extension of this can be Inverted Bluff.  Where the examples are still the same, but the blind played card does not match the card that was clued.  However, great care must be taken to not dupe cards, as the person blind playing will be unable to certain discard.  

Players must also not confused this covention with intentionally saving a card on chop.  What I mean by this is, if a play clue is given to a card on chop as a play clue, players must understand whether or not that card would've been discarded.  However, if a finesse/bluff was given to a player, they must follow Guide Principle and understand that they can blind play safely without the next person discarding the critical card.  Thus, this point might not even be a point, just something to be aware of.

**Comment by iamwhoiamhahaha** [comment]
- It is not 100% sure that the line would work in the Example 2. If I were Cathy, and if I don't think it is urgent to "get" (I know in your proposal it is gotten) the yellow 3 from Donald's slot 1, I would probably blind-play slot 1 to solve the ambiguous finesse.
- And I believe it should only be a finesse not a bluff.
- But actually, I like this idea. **Inverted Finesse** for the Example 1.

**Comment by Zamiell** [comment]
* is confusing
* prevents bluffs from resolving immediately
* can duplicate cards
* seems unlikely to be useful
* seems likely to decrease winrate

**Comment by Dr-Kakashi** [comment]
> * is confusing
Not really sure how it's confusing?

> * prevents bluffs from resolving immediately
Bluffs don't need to be resolved if you're doing a finesse/bluff of your own, which is what this is doing

> * can duplicate cards
Yes, but I explained how that isn't much of an issue.

> * seems unlikely to be useful
> * seems likely to decrease winrate
I've actually done this a few times and it works out fine.  This is in an environment where this convention isn't even defined.

**Comment by aliblong** [comment]
This is basically deferring playing into a bluff to do a priority finesse? Given the rarity and risk, I don't think this pattern deserves a special name.
