### ISSUE TITLE
Convention Proposal: Relaxed Finesse Priority

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#187]
So, I've gotten into this position several times and I feel it's good enough to have some form of this in the doc.  

- Generally, when a player is finessed/bluffed, they must immediately blind play to demonstrate that a finesse/bluff was given and to synchronize the table.  
- If a player decides to not demonstrate the finesse, there must be a good reason why.
1. The finesse was Ambiguous
2. The player is initiating a Priority Finesse
- If it can be seen that priority was/is being initiated, the original clue receiver should "relax" the finesse and give the finessed player another chance to play their finessed card.  

![2020-04-17_1921](https://user-images.githubusercontent.com/48993588/79626039-ea974300-80e1-11ea-9442-b7f22ec65417.png)

Dr_Kakashi is finessed for G1 and is clued B1.  
Dr_Kakashi plays B1
It's clear to the whole table that Dr_Kakashi is playing into Livia's hand and "might" be initiating priority.  Thus, the whole table should not assume the G1 is ambiguous.  
When it gets to scharkbites turn he should "relax" and not play G2 as G1 and give Dr_Kakashi another turn to demonstrate the finesse, as he can see that he's playing into Livia's B2.     
When it gets to Livia's turn she has a clear view of the entire table and can deduce:
1. The ambiguous finesse is on her
2. A priority finesse is occurring

In both cases, Livia must blind play and plays B2

Discussion:
If you watch the replay, Floriman even clues the G3 as a continuation clue and scharkbite still plays the G2 as G1.  During the review scharkbite says that no matter what we absolutely have to demonstrate our finesse.  I know this is something we've been teaching new players that they absolutely must play their finesse/bluff, but once you get good enough there are situations/cases where it's better to defer.  I believe the best case for that is to initiate priority.  

If Livia can see that the finesse was indeed ambiguous on another player, then she should not blind play and let Dr_Kakashi play the G1 as he will see that an Ambiguous Finesse Pass-Back is occurring

Edit: 
As an added support, I believe something like this would even happen naturally.  However, there is a key difference.  

Example:
Alice is being finessed/bluffed and has B1 clued in their hand
Bob has a B2 in his finesse position
Alice plays B1 
Bob can reason that the finesse was ambiguous and will blind play immediately and plays B2
The whole table can immediately see a priority has occurred and the situation is resolved.  The table will give Alice time to demonstrate her finesse/bluff.  

The difference between this example and the one presented above is that there is a delay.  So I'm basically asking for us to define this delay.

**Comment by hanabirnoob** [comment]
So it takes a priority over pass bluffs?

**Comment by Dr-Kakashi** [comment]
> So it takes a priority over pass bluffs?

The immediate next player will have to look around the table to see if the matching card is anywhere.  Thus, in my example, sin_faith must look around the table to see if there is a B2 is someone's finesse position.  If he see's one, he must assume a priority is occurring and do something else.  If he doesn't see one, then he must assume the finesse was ambiguous and blind play.

**Comment by iamwhoiamhahaha** [comment]
Are you allowed to do this when you are double finessed? Says Alice is double finessed (b1 on slot 1 and b2 on slot 2). Instead of playing into the finesse, she plays her known r1. Bob sees Cathy has a r2 on slot 1 assuming Alice was doing a Priority Finesse and discards. Now, it's Cathy's turn, she doesn't know if she has a b1 on finessed position as an ambiguous finesse or a r2 on finessed position as a priority finesse, then she discards. Donald bombs his b3 as a b1. (Or you think Donald should defer in this situation?)

**Comment by Dr-Kakashi** [comment]
> Are you allowed to do this when you are double finessed? Says Alice is double finessed (b1 on slot 1 and b2 on slot 2). Instead of playing into the finesse, she plays her known r1. Bob sees Cathy has a r2 on slot 1 assuming Alice was doing a Priority Finesse and discards. Now, it's Cathy's turn, she doesn't know if she has a b1 on finessed position as an ambiguous finesse or a r2 on finessed position as a priority finesse, then she discards. Donald bombs his b3 as a b1. (Or you think Donald should defer in this situation?)

I think it would depend on if the next person will bomb.  If the next player could safely play, then they can defer.

**Comment by Dr-Kakashi** [comment]
> Are you allowed to do this when you are double finessed? Says Alice is double finessed (b1 on slot 1 and b2 on slot 2). Instead of playing into the finesse, she plays her known r1. Bob sees Cathy has a r2 on slot 1 assuming Alice was doing a Priority Finesse and discards. Now, it's Cathy's turn, she doesn't know if she has a b1 on finessed position as an ambiguous finesse or a r2 on finessed position as a priority finesse, then she discards. Donald bombs his b3 as a b1. (Or you think Donald should defer in this situation?)

Hmmm......that's unfortunate.  Probably should not allow to defer if it could be double.  So the first blind play must happen.  The 2nd blind play can be deferred as it would cause it to be ambiguous.

**Comment by Zamiell** [comment]
this proposal increases efficiency but lowers synchronization. we don't actually need any more efficiency in our conventions, so it doesn't make sense to turn the dial in that direction, especially if it is at the cost of anything important. in extremely hard variants, we already play the way in that the examples describe without any additional change to the conventions as stated

**Comment by Dr-Kakashi** [comment]
> this proposal increases efficiency but lowers synchronization. we don't actually need any more efficiency in our conventions, so it doesn't make sense to turn the dial in that direction, especially if it is at the cost of anything important. in extremely hard variants, we already play the way in that the examples describe without any additional change to the conventions as stated

I'm not sure I understand the reasoning.  You're saying on one hand it lowers synchronization and on the other hand this is already done in extremely hard variants.  So, what I'm understanding is that players need to learn this through experience as an unsaid definition that's agreed upon only in extremely hard variants.  If that's the case, then shouldn't it be listed in the doc some where under advanced cases.  

My issue is that what I did during this game by playing B1 was some what clear.  However, it was made even more clear when Floriman clued G3 as a continuation clue.  Schark still played G2 as G1.

**Comment by Zamiell** [comment]
> If that's the case, then shouldn't it be listed in the doc some where under advanced cases?

no, because things that are 1) obvious / common-sense and 2) really rare aren't listed in the doc

**Comment by Dr-Kakashi** [comment]
What's obvious/common sense to some may not be so for others.  I consider schark to be an excellent player and he's one of the purple players and he still misplayed. 

I've used this many many times.  Sometimes it works and other times it doesn't.  Because as you've stated, only players who play games where high efficiency is needed to understand why this is done.  and it isn't listed in the doc for others to reference.

**Comment by Zamiell** [comment]
the problem is that it is an *actively bad* convention to have in general, lowering winrate.
the only time that this convention increases winrate is when used in extremely difficult variants.
and in extremely difficult variants, players are playing drastically different from they normally would anyway. thus I don't believe having a section in the doc for this case is helpful.

if something is obviously a priority finesse from context, then it is. if its not, its not. read [this section in the doc](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#context)
