### ISSUE TITLE
Convention Proposal: Positional Layered Bluff Stop

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#188]
- Normally, when a positional clue is given for a null card, the card blind played must be null.  
- If the card is not Null, it initiates a Positional Layered Finesse where a player must find the Null card until they hit chop, where they will do a Positional Bounce Finesse to continue searching.
- If the immediate next player can see that the player will continue to search for a Null card, but do not have one to find AND no more playable cards to play.  They must do something to tell that player to stop searching.  
- Thus the player can do this by ejecting from when the positional clue was given.  This differentiates it from a patch.

Form 1: Positional Layered Bluff Stop (The card used to stop is not a null card)
Cards played on the board: None
Example:
1. Alice clues Cathy's 4 indicating a positional clue on 4 for Bob
2. Bob blind plays slot 4 and plays B1
3. Cathy can see that Bob blind play slot 4 and will blind play slot 5 on the next turn.
4. However, she can see that Bob has a 5 on that spot.  Even if Bob is clued 5, Bob will proceed to play slot 4 trying to find a null card.  Bob's slot 4 is a B1
5. Cathy blind plays slot 2 to tell Bob to stop and successfully plays R1.  This immediately resolves the situation and Cathy should not search for Null 1.
6. Bob can see that the only reason Cathy played was because of the 4's clue given initially.  Thus it must be a signal to him to stop searching.

Looks like Null finesse on Null 2 using patch component
~~Form 2: Positional Layered Finesse Stop (The card used to stop is a null card)~~
~~Cards played on the board: None~~
~~Example:~~
~~1. Alice clues Cathy's 4 indicating a positional clue on 4 for Bob~~
~~2. Even though Bob can see that Cathy has a Null 1 on slot 1.  Bob must show that the positional is on him.  Bob blind plays slot 4 and plays B1~~
~~3. Cathy can see that Bob blind play slot 4 and will blind play slot 5 on the next turn.~~
~~4. However, she can see that Bob has a 5 on that spot.  Even if Bob is clued 5, Bob will proceed to play slot 4 trying to find a null card.  Bob's slot 4 is a B1~~
~~5. Cathy blind plays slot 1 to tell Bob to stop and successfully plays Null 1.  This immediately resolves the situation.~~
~~6. Bob can see that the only reason Cathy played was because of the 4's clue given initially.  Thus it must be a signal to him to stop searching.~~

**Comment by iamwhoiamhahaha** [comment]
1. This conflicts to my [Positional Bluff Finesse (in Null)](https://github.com/Zamiell/hanabi-conventions/issues/155). In my proposal, the immediate next player needs to blind-play the same slot to tell that player to stop searching.
2. Your definition is fine (compares to mine), but it should be an ejection, since blind-playing (first) finessed position looks like a "patch".
3. Form 2 doesn't work, for it looks like a finesse on null cards.

**Comment by Dr-Kakashi** [comment]
> 1. This conflicts to my [Positional Double Bluff (in Null)](https://github.com/Zamiell/hanabi-conventions/issues/155#issuecomment-590899257). In my proposal, the immediate next player needs to blind-play the same slot to tell that player to stop searching.
> 2. Your definition is fine (compares to mine), but it should be an ejection, since blind-playing (first) finessed position looks like a "patch".
> 3. Form 2 doesn't work, for it looks like a finesse on null cards.

1. Oh sorry! I didn't realize you made proposal.  
2. That's awesome that there are several view points to tackle this.  I guess, since it could be interpreted as a patch we should make it an ejection!  That way we have have both moves. 
3. That's really interesting that we can have a reverse finesse on null cards using a patch mechanism.  I guess I'll put a strikethrough on it.

**Comment by Zamiell** [comment]
this is on hold until #155 is resolved

**Comment by Zamiell** [comment]
now that #155 is resolved, @iamwhoiamhahaha does this issue conflict? should this issue be rejected and/or closed?

**Comment by iamwhoiamhahaha** [comment]
The original proposal didn't conflict, but I suggested him to define it as an ejection lol. You can close it now, just the same idea.
