### ISSUE TITLE
Example: Positional Purge Bluff

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#189]
![2020-04-18_0741_(Positional_Purge_Bluff)](https://user-images.githubusercontent.com/48993588/79641642-a6da2300-814d-11ea-89e4-fded9a9bcae4.png)

This is a Null Variant where a positional clue was given to sin for him to respond.  After sin play's G2 the team can see he will search for null 1 and play G3 next.  This will immediately resolve the situation and nobody should search for Null 1.  

If you feel this is good enough to add this as a new Convention, then please do so.  I remember a time where we had Dump truck.  I can realistically see players using this often to get a player's entire hand and everyone is aware of what's occurring.  It should definitely occur more often than Dump truck as you can strategically choose where the player can start the search.

**Comment by Zamiell** [comment]
i dont see how this is a new convention

**Comment by Zamiell** [comment]
i think this flows naturally from the "Positional Bounce" convention and is intuitive enough such that adding an extra section in the doc seems not worth it
