### ISSUE TITLE
Character Traits have been ending the game incorrectly

### ISSUE THREAD

**Issue by Str8AWay** [Zamiell/hanabi-conventions#19]
The game ended with a loss with no strikes and no reason for it to end due to traits.

Traits:
str8away - Stubborn
klapbot - Insistent
ninjasquirrel21 - contrarian
squirreliche - compulsive

It ended after str8away played a card. The previous player (squirreliche) had clued so that shouldn't have been a problem. Klapbot the next player had only clued once and the card he clued was played immediately after that, so that shouldn't have been a problem either.

<img width="1637" alt="screen shot 2019-02-15 at 9 35 19 am" src="https://user-images.githubusercontent.com/3453432/52866836-27922f00-3105-11e9-884f-de36e4fc3eb5.png">

We also had this problem the previous time we played with traits where we thought it ended for no reason, but I don't remember the details of that game.

**Comment by Zamiell** [comment]
What was the game ID of both games?

**Comment by Zamiell** [comment]
also you opened an issue in the wrong repository

**Comment by Str8AWay** [comment]
oops i opened an [issue](https://github.com/Zamiell/hanabi-live/issues/341) in the correct repo now and added the game id (id: 20117, seed: p4v3s13)
