### ISSUE TITLE
Interesting Exception

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#190]
![2020-04-20_0542](https://user-images.githubusercontent.com/48993588/79753390-b3d05100-82ca-11ea-8875-b5f5dd622937.png)

So we have an interesting situation here.  Kakashi has 1's but he wants to initiate the red finesse with R3.  Kakashi could have a R1 in his hand and he needs to convey that he is performing a certain finesse. 

The interesting thing is that Asaelr could be bluffed for G2, so to actually prove it's impossible to be a bluff, 3 must be given to letical.  

After 3 is given asaelr knows it's a true finesse and impossible to be a bluff so he certain discards R1.  

So before the discard it looks like 3 bluff, but after it turns into a real certain finesse.  
https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-certain-finesse-clandestine-exception

Sin_faith should believe he has R2 as asaelr proves the certain finesse by doing a certain discard. 

Thoughts?  Should something be added to the doc to explain this? 

Note: 
- Red to R3 makes it possible to be a bluff for G2 
- Kakashi is not allowed to potentially dupe a 1

General Notes:
- Certain Finesses can be performed from Bluff Seat if it is strictly impossible to be a Bluff. In other words, this means that it is illegal for a player to perform a Clandestine Finesse on the very next player that targets a potentially duplicated card and the other player can rule out the possibility of a Bluff.

**Comment by Zamiell** [comment]
too edge case to add to the doc unless it happens 2-3 more times

**Comment by Dr-Kakashi** [comment]
![2020-08-19_09-58-03 (3 bluff exception)](https://user-images.githubusercontent.com/48993588/90667508-b94f9080-e203-11ea-9f3a-72eb083eb2e2.png)
