### ISSUE TITLE
Convention Proposal: Skip Unknown Trash Discharge

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#191]
![2020-04-21_0649](https://user-images.githubusercontent.com/48993588/79874070-c5822900-839c-11ea-85e5-2d7add2f852e.png)

I was looking at this review and I noticed something special could be done here.

The R1 is already "gotten" from a 5 pull. 

Assuming the P3 has not been previously touched.   Sheriff can clue Yellow to Awe as a UTD

Because the R1 has already been "gotten" the UTD is obviously not for the R1.  Thus, sin_faith needs to skip the 5 pulled card and played the next card, which is P3.

That's the end of this proposal.

So additionally, according to the proposal I've presented here:
https://github.com/Zamiell/hanabi-conventions/issues/184

This is a situation of Form 3 Unnecessary UTD as both purple and 3 can be given instead of doing such a complicated move.  

Because it turns chop into trash and gives no benefit to awe in terms of chop moving cards, it should be taken as a trash push.

**Comment by Zamiell** [comment]
i dont think that needs to be documented, its kind of self-evident
