### ISSUE TITLE
The Bubblegum Bluff (by Stephen)

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#193]
* Similar to a *Bubblegum Finesse*, it is also possible to perform a *Bubblegum Bluff*.
* For example, in a 3-player game:
  * It is the first turn and nothing is played on the stacks.
  * Alice clues number 3 to Cathy, touching a pink 2 on slot 5.
  * Bob knows that Alice is violating *Pink Promise*. This must mean that he is supposed to play his slot 3 card.
  * Bob blind-plays slot 3 and it is a red 1.
  * Cathy knows that if this was a *3 Bluff*, then Bob would have played his *Finesse Position*. So it cannot be a *3 Bluff*.
  * Thus, Cathy knows that this must be a *Bubblegum* clue. Since blue 3 is not a pink card and Alice was in *Bluff Seat* for Bob, this must be a *Bubblegum Bluff*.
  * Cathy marks her slot 5 card as the one-away-from-playable pink card, the pink 2.
* *Bubblegum Bluffs* can only be performed on non-pink cards; otherwise, it will look like a *Double Finesse* with one part *Bubblegum Finesse* and one part normal *Finesse*.
* Note that it is impossible to *3 Bluff* and *Bubblegum Bluff* at the same time.

**Comment by Dr-Kakashi** [comment]
Jeff and I did something similar to this during the first month the pink variant was released.

Our method was we could do this to any pink card.  This allows for more opportunities to do a positional clue.  The pink is promised nothing but not n, for n is the number of the rank clue.  

For example, in a 3-player game:
- It is the first turn and nothing is played on the stacks.
- Alice clues number 3 to Cathy, touching a pink 5 on slot 5.
- Bob knows that Alice is violating Pink Promise. This must mean that he is supposed to play his slot 3 card.
- Bob blind-plays slot 3 and it is a red 1.
- Cathy knows that if this was a 3 Bluff, then Bob would have played his Finesse Position. So it cannot be a 3 Bluff.
- Thus, Cathy knows that this must be a Bubblegum clue. Since blue 3 is not a pink card and Alice was in Bluff Seat for Bob, this must be a Bubblegum Bluff.
- Cathy marks her slot 5 card as a pink card that is not 3.

**Comment by Zamiell** [comment]
I prefer option 1 because it just flows directly from first principles. In general, we don't allow bluffs on just any card. Nor do I want to.

**Comment by iamwhoiamhahaha** [comment]
kakashi you just copy my comments from the private chat, except the example
i thought you would write something new lol

**Comment by iamwhoiamhahaha** [comment]
i like both btw, i don't think one is better than the other
i'm okay to any option

**Comment by iamwhoiamhahaha** [comment]
but i think it depends on variants you are playing
to any variant relied on positional clue (except null), like brown and muddy rainbow
option 2 is better than 1
but in general, 1 is better than 2 imho

**Comment by Dr-Kakashi** [comment]
Our proposal follows first principles as well?  I know in general we don't allow bluffs on any card, but our proposal allows the ability to have more opportunity to do the positional in addition to being able to pick up more pink cards.  Pink cards easily block one another in addition to having other cards as blockers.  

The first proposal actually has 2 restrictions:
1. You can only do it with a 1 away card.
2. It can easily be blocked with another card or another pink card.

**Comment by Dr-Kakashi** [comment]
For example:
Pink & Brown Variant
Bob's hand 
n3 n1 n2 - x - x

Proposal 1:
No possibilities

Porposal 2:
i1 in any slot - 5
i2 in any slot - 0
i3 in any slot - 5
i4 in any slot - 5
i5 in any slot - 5

So 20 possibilities assuming there's only 1 pink card in cathy's hand.

**Comment by Dr-Kakashi** [comment]
Maybe you can say my example was extreme.....but let's look at the example you proposed in the Original Comment

Proposal 1:
i2 in any slot - 5

Proposal 2:
i1 in any slot - 5
i2 in any slot - 5
i3 in any slot - 5
i4 in any slot - 5
i5 in any slot - 5

so 5 possibilities vs 25 possbilities

**Comment by Dr-Kakashi** [comment]
Basically, our proposal uses the power of negative information.  You only know what the pink card isn't.  Let's say you use 3 on the pink card and you know it is not pink 3.  From now on that player can only touch i3, as touching any other pink card may dupe.  This can be powerful as if a player does use a pink card, the card is immediately known.

**Comment by Zamiell** [comment]
i think that the goal here is to have *less* possibilities to do a positional clue, not more.
* positional clues are confusing and typically reduce winrate.
* pink variants are easy enough such that there is no overriding need to invent anything additional
* it seems to me that arbitrarily allowing positional clues on any pink card does not flow from first principles, because we don't have any other bluffs that are allowed to be on *any* card in the game. thus, this is more complexity for the group to manage

looks like we have consensus that 1 is better for general use
