### ISSUE TITLE
Culling Conventions for Summer 2020

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#196]
i looked through the entire doc looking for conventions to cull.
the following are moves that stand out, because they are moves that I have not seen in 1+ years.
vote to keep or they will die:

* The Redundant Save Chop Move
* The Unnecessary Trash Finesse/Bluff Chop Move (Alternate Form)
* Trash Push Ejection
* Order Ejection
* Junk Ejection

**Comment by Zamiell** [comment]
also maybe junk ejection? not sure about that

**Comment by sjdrodge** [comment]
I'd like to keep Trash Push Ejection. Fine with the rest disappearing.

**Comment by hanabirnoob** [comment]
I'd say generalize the conventions.

**Comment by Dr-Kakashi** [comment]
I've actually done each of those several times in the past year.  My vote is to keep all of them.

**Comment by Zamiell** [comment]
link the games

**Comment by Zamiell** [comment]
deleted The Unnecessary Trash Finesse/Bluff Chop Move (Alternate Form)

**Comment by Zamiell** [comment]
deleted Order Ejection

**Comment by Zamiell** [comment]
deleted The Redundant Save Chop Move

**Comment by Zamiell** [comment]
> I'd like to keep Trash Push Ejection and Junk Ejection. Fine with the rest disappearing.

remember to record the game IDs of the games that you do these in.
if we don't have demonstrated usage of these conventions, then they will be deleted during the next culling

**Comment by iamwhoiamhahaha** [comment]
sorry i just noticed that *Redundant Save Chop Move* was on the list
i believe you can move it to 2p doc

but it's fine if you refuse to add it to the 2p doc
i have a **[Chop Move Guide](https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Chop_Move_Guide.md)** and i have added it to my doc

**Comment by Zamiell** [comment]
yes, add it to your doc instead
