### ISSUE TITLE
Color Positional Clues in Null with OoE

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#198]
Copy and pasted from here: https://github.com/Zamiell/hanabi-conventions/issues/145

So Jeff tells me to post this here as it's my idea. We were playing Null + Black and there was some confusion as to what a black clue would mean if used as a positional clue. I suggested that logically we can't set Black to be dedicated to chop as there are only 5 unique cards in the deck.

Realistically, for black cards to even be interpreted as a positional clue they must be 3 away and 3's can be used for 3 bluffs. Thus, only black 4 and black 5 can be used initially. Additionally, the window for these cards disappears as the black suit is being built up.

For comparison, a normal suit has 3 cards that can be used for positional color clues. This number goes up as cards already clued can be reclued color/rank to indicate position. However, one thing to note is that there are more opportunities as there are double the amount of cards that can appear on the board compared to a OoE suit.

There's just not enough black cards for them to be useful to do play clues or cm as dedicated to chop. In fact, what we really want is more opportunities to clue chop. Thus, we should just add the black pool to the blue pool and say that Black + Blue color positional clues represent chop. While the rest of the color suit stays normal.

This will apply to all of the variants where there is One of Each (OoE)

In a situation where there are 2 OoE we can combine those two to represent chop. This is ideal actually as it allows for 4 cards to be initially clued for color position. While also having a total of 10 cards that can appear on the board.

In this situation, we can have blue represent 1 away from chop.

**Comment by iamwhoiamhahaha** [comment]
We don't have `2 OoE + Null` variants

**Comment by iamwhoiamhahaha** [comment]
By the current convention [Null Color Positional Clue Wraparound](https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/Null.md#9-what-happens-a-color-positional-clue-is-used-that-goes-past-slot-1), my suggestion is: OoE can be the last color that wraps around.

For example, in Black & Null (6 Suits), there are 5 possible colors: red, yellow, green, blue, and black. The wraparound order is blue, green, yellow, red, and then black.

**Comment by Zamiell** [comment]
> By the current convention Null Color Positional Clue Wraparound, my suggestion is: OoE can be the last color that wraps around.
For example, in Black & Null (6 Suits), there are 5 possible colors: red, yellow, green, blue, and black. The wraparound order is blue, green, yellow, red, and then black.

what do you mean wraparound order. as currently defined in the doc, the colors would have the following assignments:
black --> slot 4
blue --> slot 3
green --> slot 2
yellow --> slot 1
red --> slot 4

do you want to keep this or change it

**Comment by iamwhoiamhahaha** [comment]
I'd like to change it. OoE is always the last color to wraparound.

#### 4 slots
blue --> slot 4
green --> slot 3
yellow --> slot 2
red --> slot 1
black --> slot 4

#### 3 slots
blue --> slot 3
green --> slot 2
yellow --> slot 1
red --> slot 3
black --> slot 2

#### 2 slots
blue --> slot 2
green --> slot 1
yellow --> slot 2
red --> slot 1
black --> slot 2

**Comment by Zamiell** [comment]
seems fine

**Comment by Zamiell** [comment]
#### One-of-Each Colors Are Skipped

* One-of-each colors are skipped over when finding the "rightmost color". This is because the right-most color is the most important color, and one-of-each colors are less likely to be around.
* For example, in a 3-player game of the "Black & Null (6 Suits)" variant:
  * Everyone has 5 cards in their hand.
  * There are 5 possible colors: red, yellow, green, blue, and black.
  * Normally, the rightmost color would be black, meaning that black would be assigned to slot 5. But black is skipped over, so blue is assigned to slot 5.
  * Subsequently, green is assigned to slot 4, yellow is assigned to slot 3, and red is assigned to slot 2.
  * Black is then assigned to slot 1. (In a 4-player game with 4 cards in the hand, then black would wrap-around and be assigned to the oldest slot again.)

**Comment by Zamiell** [comment]
I've also revamped the null document, putting *Color Positional Clues* in their own separate section
