### ISSUE TITLE
'Guide' for end game

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-conventions#200]
Hi,
So I worked a little on that for bga (so multicolor variaint), and I improved myself a lot about that.

I created a small quizz about a specific point of end game situations: https://docs.google.com/spreadsheets/d/11YIcOh3N-z0gV9nBMoIGiIyp9QYylm9OMO1JowgNwTM/edit#gid=0

With a general guideline:
1) | Discard as earliest as possible on the general case (when you can affoard it).
2) | If another player has a lot of plays, he should not discard, and others players should help him to not discard.
3) | Put priority on chop management: if you could have a useful 4 on chop, and if others players didn't steal one of your clue, try to not discard.
4) | If there is some duplicate cards, keep the card which are on the player the closest to the 5/who got the least amount of plays.
5) | Holding a 5 doesn't mean you should never discard: you can still start the last turn if you draw the card the team wanted.
6) | When only a 2 (or less) is played on one color, pay attention to which player discard. You need to reduce the amount of players between the 4 and the 5 at the minimal possible when it's possible.

And here is a second one:
1) A player who must make many plays should try to avoid discarding, and other players should try to allow them not to discard.
2) Discard as early as possible when you can afford it. If there is only one player who can play some cards, and you know you will run out of clues before the end, someone else will be forced to discard. But if you discard immediately, there could be potentially two players with some plays.
3) If there are some duplicated cards, try to keep both of them around if the 5 of this color isn't drawn, or to save the 4 of the closest before the one with the 5. Exception: if the person who holds the 4 already has many cards to play already (or in some other complex circumstances where the order in which cards must be played is taken into account).
4) Count out the last 2-3 full rounds with potential cards being drawn, especially if the path to 30 is tricky or may not be visible or clear to other players.
5) If you have many clues, try to make the player just before the hardest 5 to play discard in hope of forcing them to draw the 4 (if the 3 of this color isn't played). If 4 is already visible, do the same trick with the player before the 4 card (if the 3 of this color isn't played).
6) If there are multiple ways to clue to achieve the best order: use the clearest way. e.g. don't positional discard when you have the clues available for a direct clue and e.g. and if for example the hand is 4g 3r 5r 1g and you want to get the 4, use 4 clue (highly situational dependent though).
7) When you prepare the last turn, check which cards are played, or will be played. These cards will generally be played before the last turn. So these cards don't count in their hand. Exceptions, sometimes they could hold these plays for being able to play something in the last turn. Especially if the order of these plays are pretty good (like 3 in player A, 4 in player B, 5 in player C, with order of play A>B>C>D>A).
8) When you prepare the last turn, if some cards aren't drawn, pay attention to the probability these cards will be drawn. If both 2s are in the deck, you can be pretty sure these cards will be drawn before a single 3 whose copy is already discarded. So, in general, the plays of the 3/4/5 of the color of both 2s will be played before the end game. Which makes tip 4) way more useful with the color of the single 3, compared to the color of both 2.
9) Same than 8), for probability reasons, if a 3 or 5 of the same color are missing, if there is still two 3s in the deck, and if the 2 isn't drawn or if we are enough close to end game, you can ignore the 3 draw because, since there are two of them left, they will be more easily put on the right person. So you should most of the time trying to apply tip 4) to the 5 of the player after the 4.

The main thing which happen is the fact a game goes really differently when a player saw all useful not critical card on the board, and when a player doesn't:
 - when he doesn't, his main goal is to keep alive his chop and other useful cards. This mean, except if he got informations about it (like anohter player who 'stole' his clue), he should not discard.
 - when he does, his goal is to line up well the different cards of others players. He wants the 4 the closest possible to the 5 if the 3 of the color is not drawn.
And this point I already said 3 times is what change lots of things on my bga reasonning.

**Comment by Romain672** [comment]
So this is not a guide finished. So it require ameliorations, but you have here all the stuff I already writed about it.

**Comment by Zamiell** [comment]
im not going to integrate the quiz into the doc.
so for now, we can always refer people to this issue if they ask about a guide to the end game.

**Comment by Romain672** [comment]
Hi, here is my second shot about it. I just made things more clear, and mix the quiz and the explanations with examples.
1) 2) 3) are the same. 7) 8) are the oldest 8) 9).

Basics:
1) A player who must make many plays should try to avoid discarding, and other players should try to make it possible for him to not have to discard.
 
2) Discard as early as possible when you can afford it. If there is only one player who can play some cards, and you know you will run out of clues before the end, someone else will
be forced to discard. But if you discard immediately, there could be potentially two players with some plays.
It’s related to Pace.
 
3) If there are some duplicated cards, try to keep both of them around especially when the 5 of this color isn't drawn yet, or in front of two options for the 4, try to save the 4 in the hand of the player playing just before the player holding the 5. Exception: if the person holding the 4 already has multiple cards to play (or in some other complex circumstances where the order in which cards must be played has to be taken into account).
 
Advanced:
4) Playing any card of 4 or below makes your team lose one clue. It’s counter-intuitive, but at your turn, you have the choice between playing your card, or discarding and gaining a clue.
This means that if you are in a situation where your team is low on clues, where you see that you do not have too many playable cards, you should consider to delay a play or even to discard.
Example :
3 players. 2 cards in the deck left. 0 clues left.
Played : r3, b3, y5, g5, w5, m5
Alice’s hand : x-x-x-(r4)-(r4)
Bob’s hand : x-x-x-x-(r5)
Cathy’s hand : x-x-(b4)-(b4)-(b5)
If Alice plays, Bob is forced to play or to discard, and b5 will never get played.
If Alice discards, Bob gets a clue back he can use to tempo, and 30 is done.
 
5) If you have many clues available and not all playables cards are visible, then:
a) if there are 2 cards left in the deck, the person who discards is really important. At this point, you can know who will start the last turn (it could be the person who discards).
Example :
Played : r3, b5, y5, g5, w5, m5. Discarded : r3. 2 cards in the deck left. 7 clues remaining.
Alice’s hand : x-x-x-x-x
Bob’s hand : x-x-x-x-(r5)
Cathy’s hand : x-x-x-(r4)-(r4)
If Alice discards, 29 is the max score.
If Bob discards and draws r3, 30 is done.
 
b) if there are 3+ cards left in the deck, you could be in the previous situation if someone must play before the end game. Else, you have more time, but that doesn’t mean you can’t optimise that.
Try to make the right person discard. Like try to reduce the gap of numbers of players between two ‘adjacent’ cards.
Example :
Played : r2, b5, y5, g5, w5, m5. Discarded : r3, r4. 3 cards in the deck left. 7 clues remaining.
Alice’s hand : x-x-x-x-(r5)
Bob’s hand : x-x-x-x-x
Cathy’s hand : x-x-x-x-x
Alice can’t discard. If three remaining cards of the deck are exactly r4, r3, x, it costs 1 point.
 If you don’t believe me, here is all the cases :
If Alice discards and draws r4, 28 or 29 is done depending on the order of the two last cards.  
If Alice discards and draws r3, 29 or 30 is done.
If Alice discards and draws an unrelated card, 28 or 29 is done.
Average : 28,89
If Alice delays, Bob discards and draws r4, 29 or 30 is done.
If Alice delays, Bob discards and draws r3, 29 or 30 is done.
If Alice delays, Bob discards and draws an unrelated card, 28 or 29 is done.
Average : 29,17
So Alice must delay. And Bob should discard (it’s him or Cathy so why not).
  
Very advanced:
6)
a) The forth tips can be true even when it’s deeper.
Example :
3 players. 3 cards in the deck left. 0 clues remaining.
Played : r3, b4, y4, g5, w5, m5
Alice’s hand : x-x-x-(r4)-(r4)
Bob’s hand : x-x-x-(r5)-(b5)
Cathy’s hand : x-x-x-x-x
Alice must discard.
 
b) Or when cards are aligned (playing r2+r3+r4 make the team loss 3 clues):
Example :
4 players. 3 cards in the deck left. 0 clue remaining.
Played : r1, b4, y4, g5, w5, m5
Alice’s hand : x-x-(r2)-(r2)
Bob’s hand : x-x-(r3)-(r3)
Cathy’s hand : b5-x-(r4)-(r4)
Donald’s hand : x-x-x-(r5)
Alice must discard.
 
7) When you prepare the last turn, if some cards aren't drawn, pay attention to the probability these cards will be drawn. If both 2s are in the deck, you can be pretty sure these cards will be drawn before a single 3 whose copy is already discarded. So, in general, the plays of the 3/4/5 of the color of both 2s will be played before the end game. Which makes tip 4) way more useful with the color of the single 3, compared to the color of both 2.

8) Same than 7), for probability reasons, if a 3 or 5 of the same color are missing, if there is
still two 3s in the deck, and if the 2 isn't drawn or if we are enough close to
end game, you can ignore the 3 draw because, since there are two of them left,
they will be more easily put on the right person. So you should most of the
time trying to apply tip 4) to the 5 of the player after the 4.

**Comment by Romain672** [comment]
Ok,
I believe this link will be the final thing I will do it about that subject for a while (I put in on general 2 days ago):
https://docs.google.com/document/d/1jKFqt9WbWAc1Dj3M2E_kwDwS3J0xeIp0UNkiqkLLApk/edit

Zamiel, if you can read it, change where it's herberged if you want, and add if you want to put it somewhere else, you can.

Just for you know, this link is done to be commun with any convention. It explain how to not 'lose', so each convention or logical thing in game should have in final goal to reduce the probability of these 4 factors.

**Comment by Zamiell** [comment]
### End-Game Strategy

* The previous three sections introduce the *End-Game* at a high-level. When the *End-Game* arrives, you should probably be changing the way you play.
* However, giving specific advice for the *End-Game* is very difficult - things vary widely based on the deal and there are a lot of different things to consider.
* The best advice is to play lots of games of Hanabi to get a feel for the most common situations. But there is no substitute for thinking through each *End-Game* yourself, one step at a time. Ask questions like:
  * Which cards are left in the deck that we need?
  * What is the probability of drawing those cards?
  * Who should be drawing those cards?
  * Does stalling produce a line that is better than playing?
* If you really want to get into the weeds of *End-Game* strategy, Romain has written a [short strategy guide](https://docs.google.com/document/d/1jKFqt9WbWAc1Dj3M2E_kwDwS3J0xeIp0UNkiqkLLApk/edit) that goes into more depth.
