### ISSUE TITLE
Example: Junk Ejection

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#201]
red to Fey

![junk ejection](https://user-images.githubusercontent.com/50160641/80858406-b5ffbb80-8c8b-11ea-9399-d12b501d5e9d.png)

but blue to alphabeta is better in this case

**Comment by Zamiell** [comment]
on hold until #217 is resolved

**Comment by Zamiell** [comment]
on hold until #239 is resolved

**Comment by Zamiell** [comment]
is blue to alphabeta is better, then find a different example
