### ISSUE TITLE
muddy rainbow + rainbow always reverse tempo clue

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#203]

**Comment by Zamiell** [comment]
### Muddy Rainbow Inversion

* Muddy rainbow cards are like brown cards. This means that *Brown Inversion* also applies to muddy rainbow cards.
* This means that when multiple muddy rainbow cards are re-clued with **any** color clue, it only means to play the right-most one and nothing else.

**Comment by Zamiell** [comment]
### Muddy Rainbow Assumption

* If players get a *Tempo Clue* on two or more cards that could be either rainbow cards or muddy rainbow cards, this puts them in a conundrum:
  * If they are rainbow cards, then they should play the left-most touched card as a normal *Tempo Clue*.
  * If they are muddy rainbow cards, then they should play the right-most touched card as an *Inverted Tempo Clue* (because *Brown Inversion* applies to muddy rainbow cards).
* In this situation, players always assume that they are muddy rainbow cards, and play the right-most card.

**Comment by iamwhoiamhahaha** [comment]
My [Muddy Rainbow Tempo Clue](https://github.com/Zamiell/hanabi-conventions/issues/208#issuecomment-627332771) proposal is clearer and better than these conventions imho. Muddy rainbow cards are like brown cards, but they are still different. We don't need *Brown Inversion* for muddy rainbow.

**Comment by iamwhoiamhahaha** [comment]
I've tested several games with some players and most of them like my proposal

**Comment by Zamiell** [comment]
closing in favor of #208
