### ISSUE TITLE
typo in trash flowchart - Unkown trash ejection

### ISSUE THREAD

**Issue by NicolleLouis** [Zamiell/hanabi-conventions#206]
In the clueing trash flowchart (cf screenshot), the box about Unknown Trash Ejection tells Bob should blind play 2nd finesse, but I don't see any reference to unknown trash ejection in the main doc but instead discharge on 3rd finesse. Is it referenced under another name in the doc or is it a typo? 

![Screenshot from 2020-05-09 20-48-47](https://user-images.githubusercontent.com/30229476/81482348-a73e7900-9236-11ea-9aab-aa1aabd7f8d0.png)

**Comment by Zamiell** [comment]
yeah thats old because it used to work different and then we changed it

**Comment by NicolleLouis** [comment]
Ok thanks :)

**Comment by Zamiell** [comment]
can leave it open until it is fixed

**Comment by Zamiell** [comment]
on hold until #217 is resolved

**Comment by Zamiell** [comment]
on hold until #237 is resolved

**Comment by Zamiell** [comment]
its updated now, thanks again @NicolleLouis
