### ISSUE TITLE
Self-Bluffs with Color Clues (Changed) (2-player)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#207]
### Self-Bluffs with Color Clues (Changed)

* Change the convention name to "Self Color Bluff" (SCB for short).
* Now, you can perform a *Self Color Bluff* by touching any card which is not on slot 1, including a *Chop Moved* card or any other brand-new card (if it has full context that it is not playable).

#### Reason & Consequence
* SCB is one of the most commonly used advanced moves in 2-player. Typing "Self-Bluffs with Color Clues" is way too long, I personally like to call it "Self Color Bluff".
* SCB is an extremely powerful move in 2-player as the 5CE in 3p+, where you can "save" a 5 with a color clue and also get a free blind-card. I tried a lot of SCBs by touching a brand-new card and it worked surprisingly well.

#### Example
* A *Brown & Light Pink (6 Suits)* game:
  * [154213, Turn 21](https://hanabi.live/replay/154213/21): Bluffing a pink 1 by touching a brand-new green 3 with a green clue.
  * [154213, Turn 33](https://hanabi.live/replay/154213/33): Bluffing a yellow 2 by touching a brand-new brown 4 with a brown clue. (*Telling my teammate they have a brown 4 so that we don't need to worry about brown blocking cards for the rest of the game.*)
* A *Light Pink (6 Suits)* game:
  * [160146, Turn 21](https://hanabi.live/replay/160146/21): Bluffing a purple 1 by touching a brand-new red 5 on chop with a red clue. (***Typically, it is a 5CE!***)
  * [160146, Turn 43](https://hanabi.live/replay/160146/43): Bluffing a green 1 by touching a brand-new (critical) blue 4 with a blue clue. (*Pre-saving a critical card.*)

**Comment by iamwhoiamhahaha** [comment]
By the way, I have a 2-player document (Score Hunting Guide) that enables SCB by touching a brand-new card.

**Comment by iamwhoiamhahaha** [comment]
we can close it now since my Score Hunting Guide is being official. it is not a good convention for conservative way to play 2p games

but i still want to change its name

**Comment by Zamiell** [comment]
change it to what. SCB is exactly what it is

**Comment by iamwhoiamhahaha** [comment]
i know *Self-Bluffs with Color Clues* is *Self Color Bluffs*
but it's just like we call *Unknown Trash Discharges* as *Discharges with an Unknown Trash*

**Comment by Zamiell** [comment]
huh

**Comment by Zamiell** [comment]
ok i changed the name

**Comment by Zamiell** [comment]
make a pull request if you want any additional changes
