### ISSUE TITLE
Muddy Rainbow Tempo Clues

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#208]
### ~Positional Clues (with Color Clues)~
* ~When one or more muddy rainbow cards are retouched with a color clue, and there are no "new" cards introduced (or, if the only "new" cards introduced are trash), then extra information can be conveyed by what color is chosen.~
* ~The color chosen should correspond to a slot number that is based on the order of the stacks. Stacks correspond to the slot numbers **from right to left**., but only count the cards that are touched by the positional clue.~
* ~*Color Positional Clues* always "wrap around" to the **oldest** card.~
* ~For example, in a *Muddy Rainbow (6 Suits)* 3-player game:~
  * ~Bob has two muddy rainbow cards clued in his hand on slot 3 and slot 4. He does not know the rank of either card.~
  * ~Alice clues red to Bob, which touches both muddy rainbow cards and nothing else.~
  * ~Since there are only two cards touched by the red clue, Bob knows that the red clue "wraps around" and it means to play his right-most card which is touched by this clue.~
  * ~Then Bob plays the muddy rainbow card from slot 4.~

**Comment by Dr-Kakashi** [comment]
I've talked with jeff about whether or not this was already a thing and I believe it is.  I assume the positional clues clarified in the Null section of the document pertains to any variants that require positional clues (both color and rank).  So, I've personally already been doing this already in muddy rainbow and other players have as well.

**Comment by Dr-Kakashi** [comment]
I don't expect Zam to list every convention required in each variant's subsection.....There would be duplicate entries and it would be tedious.....so for this situation I would use both null and brown conventions in addition to any muddy rainbow conventions.

**Comment by iamwhoiamhahaha** [comment]
no you are not. last time you clued green to me telling me to play slot 3 (green is the third color). however, by my definition, i was supposed to play slot 5 since it wraps around and i bomb m5 from slot 5

**Comment by Dr-Kakashi** [comment]
right....we did that before zam specified that colors needed to wrap around.

**Comment by Dr-Kakashi** [comment]
What I'm understanding is that this is basically bubblegum finesse but with muddy rainbow using colors instead of rank.  From what I understand, this is already being done because it just follows what we've already established using null and brown conventions.

**Comment by iamwhoiamhahaha** [comment]
no, you did it recently but i can't find the replay

**Comment by iamwhoiamhahaha** [comment]
basically this is not a "new" convention but a convention combined the current convention (pink choice and null color positional clues). but we still need this to be added to the doc just for clarification

**Comment by iamwhoiamhahaha** [comment]
and actually there are a little bit different between color positional clues in null and in muddy rainbow. in null, we skip the cards with positive information, while in muddy rainbow, we skip the cards which are not touched by the clue.

**Comment by iamwhoiamhahaha** [comment]
padi asked "do brown conventions apply to muddy rainbow?" zamiel answered "yes they do"
but we shouldn't apply *[Brown Inversion](https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/Brown.md#brown-inversion)* to muddy rainbow, it's stupid.
that's the reason we need a specific *Tempo Clue* for muddy

**Comment by Dr-Kakashi** [comment]
Then I misunderstood the wrap around and made a mistake.  If it was a recent game.

**Comment by Dr-Kakashi** [comment]
I'm not really sure I agree with what you're proposing about skipping the cards which are not touched by the clue.  You're basically saying the play can only be within the cards retouched.  

Cathy's Hand: P5, MR3, P1, MR4, P1
MR3 and MR4 have previously been touched with some color that isn't purple
Here Bob can clue green to Cathy to get P1 from slot 3 to play.  

I can see the benefits of getting cards to play outside of the color clue, which still keeps the standard of the null positional clues.

**Comment by iamwhoiamhahaha** [comment]
I believe it is a *Muddy Rainbow (6 Suits)* game in your example (since purple cards are available), where Alice has these options to give a *Color Positional Clue*: red, yellow, green, blue, and purple.
In this situation: 
* purple is a bad choice since it's bad touch
* blue and yellow mean play slot 2
* green and red mean play slot 4

**Comment by iamwhoiamhahaha** [comment]
ohh i see your point. hmm, this is way too confusing

**Comment by iamwhoiamhahaha** [comment]
the proposal is just for tempo on the muddy rainbow card. we don't need color positional clue to "bluff" a purple. not really usefull

**Comment by Dr-Kakashi** [comment]
Yea, it's probably best to just let Cathy discard to have elimination notes for P1. I was just trying to think of a situation where we would get a card to play that is not touched by the color clue.   Actually, since it is a bluff, it doesn't belong here.  I guess I'll write up another issue on this as well.

**Comment by iamwhoiamhahaha** [comment]
* If you want to extend my convention then you can propose this (actually i'm going to propose this if this proposal got approved):
  * All 2's have played on the stacks.
  * Bob's Hand: p5, m3, p1, g3, P1 (both m3 and g3 were touched by a green clue)
  * Alice gives a green clue retouching the m3 and g3 on Bob's hand.
  * Bob knows that it is a *Tempo Clue* on a muddy rainbow card. By *Positional Clues (with Color Clues)* rules, he is supposed to play a muddy rainbow card from slot 4. Bob plays slot 4 and it is a g3.
  * Bob is surprised, he knows that it is illegal to get a g3 from the positional clues, therefore, his another "green card" must be a m3.

something like that

**Comment by Dr-Kakashi** [comment]
Oh, I see, so you're also proposing that we should dig for muddy cards?

**Comment by iamwhoiamhahaha** [comment]
no, not now. since actually, we should probably define the convention that it only counts the cards which are known to be muddy rainbow cards. i'm not sure which is better

**Comment by iamwhoiamhahaha** [comment]
i tested few games with kakashi and it worked pretty well

**Comment by iamwhoiamhahaha** [comment]
### Muddy Rainbow Tempo Clues
* When one or more muddy rainbow cards are retouched with a color clue, and there are no "new" cards introduced (or, if the only "new" cards introduced are trash), then extra information can be conveyed by what color is chosen. The color chosen should correspond to the slot that they should play.
* The slot number is based on the order of the stacks. Stacks correspond to the slot numbers **from right to left**., but only count the cards that are touched by the positional clue. The exceeded colors always "wrap around" to the **oldest** card.
* Basically, the player are only allowed to get muddy rainbow cards and it is never a *Tempo Clue Chop Move*. However, in the following special circumstances, you are allowed to get a non-muddy-rainbow card and do not dig for muddy rainbow cards:
  * When the clued card is "out of order" (meaning that it is impossible for a Prompt to get the card played)
  * When the clued card was Chop Moved and it is now playable
  * When playing the clued card would "unlock" someone's hand (see the section on Locked Hands later on)
  * When the clue giver is in a situation that requires them to stall (e.g. the player is Locked, etc.)
* For example, in a *Muddy Rainbow (6 Suits)* 3-player game:
  * Bob has two muddy rainbow cards clued in his hand on slot 3 and slot 4. He does not know the rank of either card.
  * Alice clues red to Bob, which touches both muddy rainbow cards and nothing else.
  * Since there are only two cards touched by the red clue, Bob knows that the red clue "wraps around" and it means to play his right-most card which is touched by this clue.
  * Then Bob plays the muddy rainbow card from slot 4.

**Comment by Zamiell** [comment]
is the proposal in your last post different than the OP? then cross out all of the text in the OP if so

**Comment by Zamiell** [comment]
ok, seems fine

**Comment by Zamiell** [comment]
* For example, in a *Muddy Rainbow (6 Suits)* 3-player game:
  * All of the 2's are played on the stacks.
  * Bob has two muddy rainbow cards clued in his hand on slot 3 and slot 4. He does not know the rank of either card.
  * Alice clues red to Bob, which re-touches both muddy rainbow cards and nothing else.
  * Bob knows that the colors available to clue in this variant are red, yellow, green, blue, and purple.
  * Starting from the final color, a purple clue would mean to play slot 4, a blue clue would mean to play slot 3, a green clue would mean to play slot 4 (wraparound), a green clue would mean to play slot 3, and a red clue would mean to play slot 4 (another wraparound).
  * Bob plays his slot 4 card as a muddy rainbow 3. It successfully plays on the stacks.

**Comment by Zamiell** [comment]
is that right?

**Comment by iamwhoiamhahaha** [comment]
Starting from the final color, a purple clue would mean to play slot 4, a blue clue would mean to play slot 3, a green clue would mean to play slot 4 (wraparound), a **yellow*** clue would mean to play slot 3, and a red clue would mean to play slot 4 (another wraparound).

**Comment by iamwhoiamhahaha** [comment]
And also change this:
* The slot number is calculated in roughly the same way that Null Color Positional Clues are calculated. In short, the slot number corresponds to the ordering of the colors from right to left. But skip the cards that are not touched by the color clue **as well as the known unplayable cards that are touched by the color clue**. And the colors always "wrap around" to the oldest card.

This is the problem we currently face while testing this convention:
* In a 3-player game of the "Muddy Rainbow (6 Suits)" variant.
  * All of the 2's are played on the stacks.
  * Bob has two muddy rainbow cards clued in his hand on slot 2 and slot 4. He does not know the rank of either card. He also has a red 5 on slot 3 with a 5 clue on it.
  * Alice clues red to Bob, which re-touches both muddy rainbow cards and the red 5.
  * Bob knows that the colors available to clue in this variant are red, yellow, green, blue, and purple.
  * Starting from the final color, a purple clue would mean to play slot **`a`**, a blue clue would mean to play slot **`b`**, a green clue would mean to play slot **`c`**, a yellow clue would mean to play slot **`d`**, and a red clue would mean to play slot **`e`**.
* What are **`a`**, **`b`**, **`c`**, **`d`** and **`e`** in this situation?
* IMO, skip red 5 and it would be **`a=4`**, **`b=2`**, **`c=4`**, **`d=2`** and **`e=4`**.

**Comment by Zamiell** [comment]
i fixed both of those errors

**Comment by Zamiell** [comment]
yes, bob should skip red 5, as per `But skip the cards that are not touched by the color clue as well as the known unplayable cards that are touched by the color clue.`

**Comment by Zamiell** [comment]
added this section:

### Muddy Rainbow Choice Tempo Clues (Skipping Over Unplayable Cards)

* If known-unplayable cards are touched as part of a *Muddy Rainbow Choice Tempo Clue*, then they should be skipped over.
* For example, in a 3-player game of the "Muddy Rainbow (6 Suits)" variant:
  * All of the 2's are played on the stacks.
  * Bob has two muddy rainbow cards clued in his hand on slot 2 and slot 4. He does not know the rank of either card. He also has a red 5 on slot 3 with a 5 clue on it.
  * Alice clues red to Bob, which re-touches both muddy rainbow cards and the red 5.
  * Bob knows that this must be a *Tempo Clue* on the muddy rainbow cards, so now he must figure out which slot Alice wants him to play. To start with, Bob knows that the colors available to clue in this variant are red, yellow, green, blue, and purple.
  * Starting from the final color, a purple clue would mean to play slot 4.
  * A blue clue would normally mean to play slot 3, but the red 5 is a known unplayable card, so Bob skips over that. Thus, a blue clue would mean to play slot 2.
  * A green clue would mean to play slot 4 (wraparound).
  * A yellow clue would mean to play slot 2 (skipping over the red 5 again).
  * A red clue would mean to play slot 4 (another wraparound).
  * Bob plays slot 4 as the muddy rainbow 3.
