### ISSUE TITLE
Convention Proposal: Muddy Rainbow Positional Finesse

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#209]
Extension of https://github.com/Zamiell/hanabi-conventions/issues/208

Just like in Bubblegum finesse, you can tell a player what slot to blind play.

For example:

Nothing is played on the field.
Cathy's Hand: Muddy Rainbow 2 - r2 - g2 - x - x
Alice clue's green to Cathy
Bob can see that Alice had free choice using any color.  If red was chosen it would get Cathy's slot 1. Since green was chosen, Cathy knows it's a positional clue and should play slot 3.
Cathy play's slot 3 and plays Muddy Rainbow 1.
Bob can see that Cathy played slot 3 and understands it's a Muddy Rainbow Positional Finesse. He plays slot 1 as muddy rainbow 2.

Issues:
If we decide to go with this, it would conflict with trash, ejection, discharge conventions.  
Like in my example, there are no trash green cards as the game just started, but what about the middle of the game where there are green cards in trash?  
This would mean that those conventions might have to be turned off.  If that's the case, I'm unsure if the benefits outweigh the absence of those conventions.
If slot 4 or 5 plays, then there would be no conflicts.

If it isn't worthwhile to get blind cards from slot 1-3.  Then we can edit this convention to only get slot 4-5.  This might conflict with Jeff's proposal that color positional clues shall wrap around.  

Additionally, we should have a discussion on if players should dig or not for the muddle rainbow card that was called.  I'm thinking that if we do have conventions turned off, we should dig.  

Edit:
I just realized that there is no conflict if the immediate next player both received the color clue and is blind playing.  

Cathy's Hand: P5, MR3, P1, MR4, P1
MR3 and MR4 have previously been touched with some color that isn't purple
Here Bob can clue green to Cathy to get P1 from slot 3 to play.
After Cathy blind plays slot 3, it's a known bluff and resolves immediately.

**Comment by iamwhoiamhahaha** [comment]
alice doesn't have free choice between red and green in your example

**Comment by Dr-Kakashi** [comment]
You're right, I've changed it.  She can use any color, since no color clue is blocked in my example.

**Comment by iamwhoiamhahaha** [comment]
* Your proposal has a lot of problems.
* For example: In a *Muddy Rainbow (4 Suits)* game (where red, yellow, green clues are available). 
  * All 1's has played on the stacks.
  * Cathy has m3, g1, g1, g5 in hand (g5 has `positive 5` and `negative red` information).
  * Alice has free choice between red and yellow on the m3.
  * In your proposal she is supposed to give a red clue as a normal *Finesse*, or a yellow clue as a *Positional Finesse*.
  * However, she saw that Cathy's green 5 has `negative red` on it. If she gives a red clue to Cathy, then it tells nothing on her green 5; while if she gives a yellow clue to Cathy, it not only gets the m3 but also tells her 5 is a green card.
  * Is it suboptimal to clue yellow to Cathy? Should Bob responds slot 1 as a *Finesse* or a specific slot as a *Positional Finesse*, if Alice gives a yellow clue?

**Comment by Dr-Kakashi** [comment]
That's a good point, so beneficial negative information must be ignored.

**Comment by Zamiell** [comment]
i dont see what this has to do with muddy rainbow. the normal rainbow suit is also touched by all colors. is the logic then that the extra complexity is only worth the cost in the (harder) muddy rainbow variants?

in any case, it is going to be pretty rare that you dont want to give any specific negative information to someone's hand. post a replay of a game where a muddy rainbow positional finesse is clear, meaning that there is a free choice between two or more colors **and** there is no useful negative information to give.

my intuition is that this would be extremely rare, making the convention not worth the cost

**Comment by Dr-Kakashi** [comment]
I'm going to close this.
