### ISSUE TITLE
Bubblegum Finesse Wraparounds & Skips

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#214]
### Bubblegum Finesse Wraparounds (by kimbifille)
* This convention only apply to 4 or more player games.
* Note that you cannot do a *Reverse Bubblegum Finesse* with "wraparound" property.
* In a 4 or 5 player game, if a player gives a 5 clue touching a one-away pink card in order to avoid *Bad Touch* by giving a 1 clue. In this situation, they are trying to perform a ***Bubblegum Finesse Wraparound***. The player who doesn't see the matching pink card should blind-play their *Finessed Position* to fulfill the *Finesse*.
* Similarly, in a 6 player game, the players can perform this move by giving a 4 clue touching a one-away pink card in order to avoid *Bad Touch* on a 1; or giving a 5 clue, avoiding *Bad Touch* on a 2.
* For example:
![bubblegum finesse wraparound](https://user-images.githubusercontent.com/50160641/82112431-7ce14400-977f-11ea-875e-82fafff0abcb.png)

### Bubblegum Finesse Skips (by IAMJEFF)
* You can only perform this move if you're sitting in *Bluff Seat*.
* If the player sees their next player has cards with negative pink information, they are allowed to perform a *Bubblegum Finesse* by giving an unrelated number clue in order to avoid *Bad Touch*.
* In this situation, the next player should skip their cards with negative pink information and blind-play that slot as a ***Bubblegum Finesse Skips***.
* For example, in a 3-player game:
  * Red 4 and Pink 1 are played on the stacks.
  * Bob has a pink 2 on slot 4 and an unknown yellow card on slot 5.
  * Cathy has a pink 3 on slot 1 and a red 4 on slot 2.
  * Alice wants to perform a *Bubblegum Finesse*. Normally, she is supposed to give a 4 clue to Cathy. However, Cathy has a red 4 on slot 2, if Alice gives a 4 clue, then it is a bad touch on the red 4, which is quite bad.
  * Alice finds that Bob has a yellow card on slot 5; therefore, she gives a 5 clue to Cathy, touching the pink 3 on slot 1.
  * Bob is surprised, since this clue breaks the *Pink Promise* on the pink 3. If Bob does nothing then Cathy is going to misplay the pink 3 as a red 5.
  * Bob knows *Bubblegum Finesse* and he realizes Alice was trying to avoid bad touch on the red 4 by giving a 5 clue instead of a 4 clue .
  * Bob blind-plays slot 4, and a pink 2 is successfully played.

**Comment by iamwhoiamhahaha** [comment]
* Wraparounds property can be applied to a 3-player game with Skips property I guess. And 5 clue does not always wraparound to slot 1 in 4-player.
* For example, replace the pink 4 with a pink 1 on Othnia's slot 2 in the screenshot above:
  * Kimbifille can clue 4 to alphabeta as a *Bubblegum Finesse Wraparounds & Skips* on Othnia's pink 1 on slot 2. (Skipping green cards on slot 3 and 4, and it wraps around to slot 2)

**Comment by Zamiell** [comment]
Bubblegum Finesse Wraparounds - seems kind of edge-case to add to the doc

**Comment by Zamiell** [comment]
> Red 4 and Pink 1 are played on the stacks.
Bob has a pink 2 on slot 4 and an unknown yellow card on slot 5.

is bob's hand completely unclued?

**Comment by iamwhoiamhahaha** [comment]
bob has a yellow card on slot 5 with a yellow clue on it, the others completely unclued

**Comment by Zamiell** [comment]
> Bubblegum Finesse Skips

isn't this just the same thing as null slides?

**Comment by iamwhoiamhahaha** [comment]
ohh yea

**Comment by Zamiell** [comment]
what direction do Bubblegum Slides go in? left or right?

in null, they go right.
if they go right, then your example is wrong, because Bob would play slot 1 instead of slot 4.

**Comment by iamwhoiamhahaha** [comment]
Ohh yeah you're right. My example was wrong, if *Wraparound* property has been accepted.

**Comment by Zamiell** [comment]
does it matter and/or do you care whether it slides left or right?

if you do not care, then lets have it slide right so that it is the same as null

**Comment by iamwhoiamhahaha** [comment]
Yeah sure, slide right lol

**Comment by Zamiell** [comment]
ok, i added this
