### ISSUE TITLE
Junk Ejection --> Known Trash Ejection

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#217]
It occurs to me that *Known Trash Ejection* would be a better name for this.

* Currently, *Known Trash Ejection* is defined as a move which re-touches a trash card that is already known to be trash.
* The current *Known Trash Ejection* is a move that is (almost) never performed.
* Thus, we can merge *Junk Ejection* and *Known Trash Ejection*.
* In other words, the new *Known Trash Ejection* would be defined as a move that touches a known trash card, regardless of whether or not the trash card is "brand new" or whether the known trash card is being re-touched.

**Comment by iamwhoiamhahaha** [comment]
seems fine. but there are two forms of *Junk Ejections*: with Trash and with 5's. you mean only merge *Junk Ejection (with Trash)* to *Known Trash Ejection* right?

**Comment by Zamiell** [comment]
Correct

**Comment by Zamiell** [comment]
i changed my mind, will open a new issue
