### ISSUE TITLE
Empathy glitch 

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#221]
![2020-05-18_1754](https://user-images.githubusercontent.com/48993588/82272880-b86f4000-9930-11ea-8990-2034f8bab3fd.png)
![2020-05-18_1754_001](https://user-images.githubusercontent.com/48993588/82272884-bad19a00-9930-11ea-9844-393a2a38b735.png)

Muddy Rainbow Ones and Light pink glitch
Empathy shows pink icons on cards but gui is highlighting i1 with pink color

**Comment by padiwik** [comment]
wrong repo lol

**Comment by Dr-Kakashi** [comment]
omg.....how do I move this to hanabi.live? =\ or should I delete this

**Comment by Zamiell** [comment]
delete it
