### ISSUE TITLE
Somehow Reduce Complexity of "5" Moves

### ISSUE THREAD

**Issue by NoMercyO** [Zamiell/hanabi-conventions#226]
[original topic: Delete 5 Stalls]

They are bad in all cases except hand configurations with only 1 or 2 valid play/save clues. We have so many 5 techs now, and a more mature understanding of when to end the early game. Early game 5-stalls are a bastion of old conventions and do more harm than good.

**Comment by Zamiell** [comment]
@fpvandoorn

**Comment by fpvandoorn** [comment]
> They are bad in all cases except hand configurations with only 1 or 2 valid play/save clues.

* So you are saying they are useful when there are only 1 or 2 valid play/save clues? Then let's keep them.
* Sometimes you see an amazing 7-for-1 and you don't want the next player to discard immediately afterwards. More generally, if there is any finesse that you can do better than the next player, you might want the next player to not yet discard
* They only exist in easy variants anyway. After doing a bunch of 2+-for-1s, being required to do a *single* weak 1-for-1 (the 5 stall) is fine.
* The rule *one 5 stall is required before you are allowed to end the early game* is a bad rule (except that it makes things easy for beginners), and I'm happy to get rid of that. Discarding after some other weak(ish) clues have been given is fine. I've written my opinions about when it's fine to end the early game (without 5 stall) before: https://pastebin.com/8KneYWKa

**Comment by Zamiell** [comment]
@libster

**Comment by Zamiell** [comment]
> and I'm happy to get rid of that

florrat and I agree that it should stay as a rule for beginners and experts can violate it (which is what we already do)

**Comment by Zamiell** [comment]
https://hanabi.live/replay/177685

1) in the opener, libster does a layered finesse to get a nice 3-for-1 clue
2) libster does not want to lose the p2
3) libster can safely lock-in the 3-for-1 because he knows that zamiel is required to 5 stall

in mercy's proposed change, libster would probably **not** sacrifice p2, rather opting for a 2 save to zamiel, which would allow zamiel to finesse or bluff b1. we can probably agree that this line is not super-bad, but strictly less optimal than the line that was actually chosen in the review

thus, we can conclude that in this situation (and by proxy, many other similar situations), this is an example where 5 stalls are beneficial / positive expected value

**Comment by Dr-Kakashi** [comment]
I vote to keep 5 stalls, unless if it's a hard variant of course.

**Comment by NoMercyO** [comment]
Sigh. Fine. 

Number 5 clues are reaching a point where there are genuinely confusing, especially in the early game. Between 5stalls, FPE, 5cm, 5ND, 5 Play clued, 5 pulls, 5 double pulls, 5 pull finesse, even 5 number triple bluff (this is still a thing apparently). It is causing increasing errors. 

Perhaps we can put a bit of time together to try and reclarify it, perhaps changed some conventions, or at least explicitely disable some in early game, to make it more streamlined.

**Comment by Zamiell** [comment]
im fine with deleting esoteric, rarely-used conventions, if deleting them would reduce overall mistakes and reduce overall complexity.

propose something to delete.

specifically:

* 5 stalls - we use all the time

* FPE (finesse position exception) - this is interesting in that it is something that is used from time to time. but deleting it would simplify things a lot, so i might be in favor of deleting that.

* 5ND (5 number discharge) - in particular im pretty sure I have not seen used, maybe one time or something. might want to nuke it

* 5 play clues - would seem extremely weird to disable the ability to give play clues in the early game, but i guess that could be a thing

* 5 pulls - we use this all the time

* 5 double pulls - yup, should probably be deleted, i have not seen this

* 5 pull finesse - yeah, this is used uncommonly, but complexity of it is fairly low and it is used enough such that it should probably not be deleted

* 5 number triple bluff - i think this flows from first principles. with that said, i have not seen it used in the past 2 years, so probably should delete it

**Comment by NoMercyO** [comment]
I agree with your evaluation of all of these, with FPE being the only one im inclined to defend keeping (an alternative is keep only in hard variants).

Additionally a clarification for 5cm/5 stall/5 play clues is required:
- preamble: if a 5 clue is either a play clue, or a save when on chop we agree save take precedence (obviously).
- in the mid game we treat a 5cm in a way 'as if' it were on chop. That is to say 5cm takes priority over a 5 play clue. Note that this applies whether or not the the card actually chop moved is also critical, and we respect the 5cm on any non junk card. 
- if the situation is a valid 5 stall scenario (early game criteria met, DDA, lock hand) the 5 stall takes priority over everything else. 

So:
1) where does this leave play clues on 5s (using number)? 
- current(?): place it below 5 save, below 5 stall, below 5 cm (rare exception cm card is knowable as trash). 
- suggestion place it below 5pulls and other early game tech. -> result effectively disable it in early game entirely.

2) Are we ok with treating 5cm in the early game exactly the same as in the mid game?
 - Pro: its simple.
 - Con: there are many less reasons to want to 5cm in the early game, as there are no critical cards that are non 5s. (Value cm on 2s and 3s can still be desirable, but not necessary).
- Alternative: 5 pulls take priority over 5cm, effectively disabling 5cm in early game. 

For reference: Incomplete, but still very useful.
https://raw.githubusercontent.com/Zamiell/hanabi-conventions/master/img/flowcharts/early_game_5_flowchart.png

**Comment by Zamiell** [comment]
>  FPE being the only one im inclined to defend keeping (an alternative is keep only in hard variants).

FPE doesn't apply in hard variants anyway, right?  because 5 stalls are turned off in hard variants, except in the situation of a scream discard or something, so making extra rules around that edge case would be weird and/or unnecessary

**Comment by NoMercyO** [comment]
Good point yes. Due to the line 
"Players are not required to clue anything in the Early Game; they are allowed to initiate the Mid-Game whenever they see fit."
FPE in hard variants does not make any sense. It is how i would act personally, but nothing on a convention side is required for change or clarification.

**Comment by Zamiell** [comment]
> current(?): place it below 5 save, below 5 stall, below 5 cm (rare exception cm card is knowable as trash).

correct

**Comment by Zamiell** [comment]
> suggestion place it below 5pulls and other early game tech. -> result effectively disable it in early game entirely.

the solution here is to just say that:

"It is impossible to give a *Play Clue* to a 5 with a rank clue in the *Early Game*. Instead, all rank 5 clues are to be interpreted as a *5 Stall*. (Or, if a *5 Stall* is illegal, then some more advanced move.)"

**Comment by Zamiell** [comment]
even though doing this would be weird, i am probably fine with this

**Comment by Zamiell** [comment]
* it prevents the mistake from occurring where a player accidentally 5 stalls and it bombs as the playable red 5
* it adds the mistake where a player gives a play clue to a red 5 with rank, and then it gets interpreted as a 5 pull and some other card bombs

i think between these two, the second is less-likely to be catastrophic, so overall we should be in favor of this trade

**Comment by Zamiell** [comment]
> Are we ok with treating 5cm in the early game exactly the same as in the mid game?

don't we already? can you clarify

**Comment by NoMercyO** [comment]
> > current(?): place it below 5 save, below 5 stall, below 5 cm (rare exception cm card is knowable as trash).
> correct
Not according to some document notes which orders 5 play clues: 5 save -> 5 play clue -> 5 stall -> 5 cm. Which is quite confusing when we consider 5cm to have priority over a 5 play clue, so is some sort of weird cyclical priority for 5s one away from chop. 
"5 Stalls cannot be given if there are any playable 5's. In this situation, a number 5 clue would just look like a Play Clue on the 5." 

> > Are we ok with treating 5cm in the early game exactly the same as in the mid game?
> don't we already? can you clarify
Currently we do. I was noting that this is not necessarily the best use of early game conventions in non black suits. I think it is best to leave 5s as it is for simplicity. However explicitely disabling 5cm in the early game is also a simple rule that allows to simple expansion of 5pulls etc - and thus should be discussed.

**Comment by Zamiell** [comment]
> Not according to some document notes which orders 5 play clues: 5 save -> 5 play clue -> 5 stall -> 5 cm. Which is quite confusing when we consider 5cm to have priority over a 5 play clue, so is some sort of weird cyclical priority for 5s one away from chop.
"5 Stalls cannot be given if there are any playable 5's. In this situation, a number 5 clue would just look like a Play Clue on the 5."

ok.
so then it sounds like you agree with my new convention proposal of:
"It is impossible to give a Play Clue to a 5 with a rank clue in the Early Game. Instead, all rank 5 clues are to be interpreted as a 5 Stall. (Or, if a 5 Stall is illegal, then some more advanced move.)"

**Comment by Zamiell** [comment]
> Currently we do. I was noting that this is not the best use of early game conventions in non black suits. I think it is fine to leave 5cm as it is for simplicity. However explicitly disabling 5cm in the early game is also a different but simple rule that allows for clear expansion of 5pulls conventions etc - and thus should be discussed.

does that actually result in overall less complexity? it sounds like it definitely wouldn't
e.g. a number 5 clue in early game is a 5 pull, a number 5 clue in the mid game is a 5 chop move, so now there is another branch in the flowchart

**Comment by fpvandoorn** [comment]
I'm happy to remove 5ND, 5 double pull and the 5 triple bluff (I don't even know how the current priority of 5 triple bluff vs the other two).

The 5 play clue is the most common mistake I've seen (either by cluer or clue receiver), at least in speedrunning games. I'm not sure if that is a solvable problem, unless we eliminate number 5 play clues altogether in the early game.

* 5 play clue is and should be below 5 save and 5 chop move.
* I think the current rule about putting the 5 play clue above the 5 stall is good. It seems weirder to disallow play clues than to disallow stalls (and given that you have clued 4 cards of a single suit means that this is not the kind of game where you need 5 stalls)
* 5 play clue vs 5 pull (and other tech) I could go either way.

> Not according to some document notes which orders 5 play clues: 5 save -> 5 play clue -> 5 stall -> 5 cm. Which is quite confusing when we consider 5cm to have priority over a 5 play clue, so is some sort of weird cyclical priority for 5s one away from chop.

This is indeed a little weird. How I think about the current conventions:
* Cluing a 5 on chop: 5 save
* Cluing a 5 1-away from chop: 5 stall -> 5 cm [-> 5 play clue; it can only be a play clue if there are no valid chop move targets, which I guess might happen in 3-4 suit games]
* Cluing a 5 2+-away from chop: 5 play clue -> 5 stall -> 5 pull

**Comment by sjdrodge** [comment]
I think banning play clues with a number 5 in the early game is probably a good change on balance. When play clues on 5's are most urgent, they are already on chop, in which case a color clue is already needed in order to play clue them. If they are off-chop, it's usually not much penalty to pay to simply wait for the middle game, and in exchange you get all your 5's conventions back even when a 4 is on the stacks.

**Comment by iamwhoiamhahaha** [comment]
#### Possibility

In a 5 Suits 4-player game, the possibility of specific 5 techs are shown below:

* The possibility of a *5 Save* is roughly: 30%

```
1/10*3 (a 5 on Bob's, Cathy's or Donald's slot 4) = 30%
```

* The possibility of a *5 Pull* is roughly: 18%

```
1/10*3*2 (a 5 on Bob's, Cathy's or Donald's slot 1 or 2) * 3/10 (a 1 next to the 5) = 18%
```

* The possibility of a *5's Chop Move* is roughly: 12%

```
1/10*3 (a 5 on Bob's, Cathy's or Donald's slot 3) * 4/10 (a 2 or 3 next to the 5) = 12%
```

* The possibility of a *5 Pull Finesse* is roughly: 0.48%

```
3/10 (a playable 1 on Bob's slot 1) * 1/10*2*2 (a 5 on Cathy's or Donald's slot 1 or 2) * 2/10/5 (the connecting 2 next to the 5) = 0.48%
```

* The possibility of a *5 Double Pull* is roughly: 1.44%

```
3/10 (a playable 1 on Bob's slot 1) * 1/10*2 (a 5 on Cathy's or Donald's slot 3) * 3/10*4/5 (another playable 1 next to the 5) = 1.44%
```

* The possibility of a *5 Number Discharge* is roughly: 4.8% 

```
3/10 (a playable 1 on Bob's slot 3) * 1/10*2*2 (a 5 on Cathy's or Donald's slot 1 or 2) * 4/10 (a 3 or 4 next to the 5) = 4.8%
```

#### Discussion

* The possibility of a 5ND (4.8%) and a 5DP (1.44%) are not as low as you think, compared to 5P (18%) and 5CM (12%).
* Deleting 5ND (4.8%) and 5DP (1.44%) but leaving much impossible 5PF (0.48%) seems stupid.
* Some reasons why people don't do a 5ND or 5DP:
  * Few people know them.
  * They are advanced moves which are not beginner friendly.
  * In the situation where there are some other better clues to give when they are available.
  * People living in the old age refuse to try new things.

**Comment by iamwhoiamhahaha** [comment]
#### Possibility (general)

* Furthermore, you are not able to perform some 5 techs if you are not on the bluff seat. 5CE, for example, if Cathy has a playable card on slot 2 and Donald has a 5, Alice is not able to perform the 5CE in this situation. However, Alice can do something else and let Bob do the 5CE in his turn.
* On the other hand, *5 Pull* is a move that can easily be done by any player. Therefore, the increments of the possibility of a *5 Pull* is lower than the other 5 techs.

In a 5 Suits 4-player game, the roughly possibilities of specific 5 techs that can be done by **any player** in their first turn:

> Notes: I only count the chance that has only one 5, so the real possibility of 5 pull, for example, might be higher.

* The possibility of a *5 Save* is roughly: 40%

```
1/10*4 (a 5 on Alice's, Bob's, Cathy's or Donald's slot 4) = 40%
```

* The possibility of a *5 Pull* is roughly: 24%

```
1/10*4*2 (a 5 on Alice's, Bob's, Cathy's or Donald's slot 1 or 2) * 3/10 (a 1 next to the 5) = 24%
```

* The possibility of a *5's Chop Move* is roughly: 16%

```
1/10*4 (a 5 on Alice's, Bob's, Cathy's or Donald's slot 3) * 4/10 (a 2 or 3 next to the 5) = 16%
```

* The possibility of a *5 Pull Finesse* is roughly: 1.92%

```
3/10 (a playable 1 on Bob's slot 1) * 1/10*2*2 (a 5 on Cathy's or Donald's slot 1 or 2) * 2/10/5 (the connecting 2 next to the 5) * 4 (4 players) = 1.92%
```

* The possibility of a *5 Double Pull* is roughly: 5.76%

```
3/10 (a playable 1 on Bob's slot 1) * 1/10*2 (a 5 on Cathy's or Donald's slot 3) * 3/10*4/5 (another playable 1 next to the 5) * 4 (4 players) = 5.76%
```

* The possibility of a *5 Number Discharge* is roughly: 19.2%

```
3/10 (a playable 1 on Bob's slot 3) * 1/10*2*2 (a 5 on Cathy's or Donald's slot 1 or 2) * 4/10 (a 3 or 4 next to the 5) * 4 (4 players) = 19.2%
```

**Comment by NoMercyO** [comment]
I support the no 5 play clues in the early game rule. 

> This is indeed a little weird. How I think about the current conventions:
> 
> * Cluing a 5 on chop: 5 save
> * Cluing a 5 1-away from chop: 5 stall -> 5 cm [-> 5 play clue; it can only be a play clue if there are no valid chop move targets, which I guess might happen in 3-4 suit games]
> * Cluing a 5 2+-away from chop: 5 play clue -> 5 stall -> 5 pull

I dont hate this but i do prefer changing it to:
> * Cluing a 5 2+-away from chop: 5 stall > 5 play clue > (other 5 tech)
Reasoning: This is really only now relevant in the mid game with us disabling early game 5 play clues if lieu of other tech. And in the mid game 5-stalls in easy variants are one of the cleanest actions to perform in DDA which is clear and safe. I think it is better to have more valid 5 stalls in DDA situations than to lose all 5stalls once any mid game 4 is play clues or on the stack. In hard variants this is irrelevant. 

> * The possibility of a _5 Pull Finesse_ is roughly: 0.48%
> * The possibility of a _5 Double Pull_ is roughly: 1.44%
> * The possibility of a _5 Number Discharge_ is roughly: 4.8%

This is useful data for evaluating their merits. 
- 5 pull finesse is very rare, but intuitive. (vote to delete, see below)
-  5 double pull conflicts with 5cm lightly. If this convention exists we must that early game 5cm on playable cards is strictly* illegal (*unless there is no good touch alternative). I am not convinced this convention should exist either. (vote to delete)
- Ive never seen a 5ND but ill concede this is more of an old-age thing. I'm not entirely convinced that the convention's soft conflict with 5-pull finesse is simple enough to keep both. Based on your numbers listed we could delete 5 pull finesse entirely and expand 5ND opportunities? (vote to keep/expand)

**Comment by sjdrodge** [comment]
I thought 5ND only works if a 5 clue would already be a play clue. Perhaps I misunderstand, but if not, the probability as calculated is severely overstated.

**Comment by Zamiell** [comment]
that is correct, 5ND work works if it can't be several other more-ordinary things

**Comment by Zamiell** [comment]
to start with, it sounds like we have consensus to implement:

"It is impossible to give a Play Clue to a 5 with a rank clue in the Early Game. Instead, all rank 5 clues are to be interpreted as a 5 Stall. (Or, if a 5 Stall is illegal, then some more advanced move.)"

**Comment by Zamiell** [comment]
however, is adding another rule actually increasing complexity or reducing it? im unsure

**Comment by NoMercyO** [comment]
Proposals for early game 5 clues:

0: Recreate an early 5 clues flowchart (once conventions are decided)

1: Remove early game 5 play clues:
- I support, consensus support.

2: Remove 5 double pull
- I softly support. Florrat supports.
- Jeff is against.
- kakashi i think i for (see link)
https://github.com/Zamiell/hanabi-conventions/issues/234

3: remove 5 pull finesse
- i suggested (removing makes 5ND better and easier). No other feedback given

4: Remote 5ND
- lack of clear understand of mechanic.
- Jeff support keep. I soft support keep. 
- Florrat support removal. 

5: Remove 5 triple bluff (from early game / entirely) . 
- I am in favor of deletion from early game. (confusing interaction with 5ND and 5CE, would require an exception to those for cases of 'i see 2 other playable slot 1s')
- Keep in mid game? soft vote for  delete due to rarity.

**Comment by Zamiell** [comment]
> kakashi i think i for

he is strongly against

**Comment by Zamiell** [comment]
> remove 5 pull finesse

libster, florrat, and i did one in our weekly competition matches. they seem not-super-common, but common-enough to keep around. also they are super intuitive, which i like.

**Comment by Zamiell** [comment]
> Remote 5ND

i think ive done this move a grand total of once or twice. only seems marginally useful. i dont care much either way

**Comment by Zamiell** [comment]
> Remove 5 triple bluff (from early game / entirely) .

i opened a new issue regarding this

**Comment by fpvandoorn** [comment]
I think @aliblong has opinions about whether 5 clues are play clues early game. And it's true that this increases the number of rules for 5s in the early game, not decrease it...

I like to keep the 5 pull finesse. You might be able to give them less frequently than some other moves, but also much more efficient. (Jeff's calculations compute how often they are possible, not how often they are good).

I don't like the 5 triple bluff in the early game, I'm ambivalent about the midgame.

My other "supports to remove" (5ND, 5 double pull) I don't feel strongly about.

**Comment by aliblong** [comment]
1. Probably bake in an exception for white compromise
2. No opinion; don't think I've ever done one
3. Seems bad; 5 pull finesse follows logically from 5 pull, so it's intuitive, and I've used it a fair number of times. We even use it in speedruns.
4. Also no opinion, since I don't think I've done one. I think they should be clear in hard variants. There's some tension with 5 layered finesse.
5. My only exposure to this convention was around a year ago, when I tried a whole-suit finesse and it somehow turned into this. Haven't seen it once since. Kill it.

**Comment by Zamiell** [comment]
Thanks again to Mercy for putting together this summary.

1) Remove early game number 5 play clues

Let's continue discussion in #260 please. Will likely be accepted / enacted.

2) Remove *5 Double Pull*

Consensus is against, as represented in issue #234. So it will stay.

3) Remove *5 Pull Finesse*

Consensus is against. Didn't open a separate issue on it because it seems popular. As mentioned previously, the best thing going for *5 Pull Finesse* is that it is fairly intuitive. It will stay.

4) Remove *5 Number Discharge*

Consensus is divided. Thus, let's keep for now. If @fpvandoorn strongly wants to remove it, then please open a dedicated issue for it so that we can gather more detailed feedback from others. However, this move is indeed rarely used, so I have added it to [the newly-created Rarely Used Conventions document](https://github.com/Zamiell/hanabi-conventions/blob/master/misc/Rarely_Used_Conventions.md).

5) Remove *Triple Bluff* / *5's Triple Bluff*

Let's continue discussion in #254 please. Will likely be accepted / enacted.

**Comment by Zamiell** [comment]
In summary, it looks like we will (probably):

1) Delete Early Game Number 5 Play Clues
2) Delete Triple Bluff / 5 Triple Bluff

But remember that our goal was to "Somehow Reduce Complexity of 5 Moves" or to "Somehow Reduce Complexity of the Early Game". Doing merely these two things above do not really being to address the greater problem.

I would love to reduce complexity, but unfortunately, I am sad to say that even after our discussion, we still don't have a good path forward. For now I will close this issue, and let's continue to brainstorm into the future.



Then I don't think that this really meets either goal.
