### ISSUE TITLE
Example: Selfish Focus Inversion

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#227]
bulbasaur gives green to valetta
(my very first time doing this move lol)

![selfish focus inversion](https://user-images.githubusercontent.com/50160641/82732411-a251ed00-9d3f-11ea-863b-fd2f59389a27.png)

**Comment by Zamiell** [comment]
your numbers are disgusting

**Comment by Zamiell** [comment]
i don't think that this is a very good example because the green cards are on chop, so it illustrates the wrong concepts

**Comment by Zamiell** [comment]
take another screenshot where g3 is on slot 2 and g2 is on slot 3

**Comment by iamwhoiamhahaha** [comment]
> your numbers are disgusting

LOL. Have too many accounts. Maybe I was testing that feature and forgot to change it back...

**Comment by iamwhoiamhahaha** [comment]
Sucubus has a red 1, it's not urgent for me to give that green clue

**Comment by iamwhoiamhahaha** [comment]
But okay

**Comment by Zamiell** [comment]
> Sucubus has a red 1, it's not urgent for me to give that green clue

that's besides the point, the point of the example it to show the concept without introducing other exceptions on contexts

**Comment by iamwhoiamhahaha** [comment]
> that's besides the point, the point of the example it to show the concept without introducing other exceptions or contexts

Yeah I understand that

**Comment by iamwhoiamhahaha** [comment]
Is it a good example?

scharkbite has a known brown 1 from gentleman's discard, and he clues brown to IAMJEFF

https://hanabi.live/replay/99369/13

![SFI](https://user-images.githubusercontent.com/50160641/83709671-9c1e1380-a651-11ea-8ad9-81402cb00942.png)

**Comment by Zamiell** [comment]
i guess

**Comment by Zamiell** [comment]
actually, this isn't a good example, because it just looks like an OPC on slot 5.
find an example that doesn't involve OPC
