### ISSUE TITLE
Convention Proposal: Positional rank clues for Pink Ones Variant

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#228]
Since we can't use 1 as a rank and 1's are touched by all rank.

In a 3p game, since there are 5 slots
positional clues are the same
2 is slot 2
3 is slot 3
4 is slot 4
5 is slot 5

In a 4p-5p game, since there are only 4 slots, we subtract 1 from the rank clue given
cluing a 1 with a 2 means play slot 1
3 plays slot 2
4 plays slot 3
5 plays slot 4

In a 6 p game, since there are 3 slots
2 is slot 2
3 is slot 3
4 is slot 2
5 is slot 3

**Comment by iamwhoiamhahaha** [comment]
Nice idea! But I like 2 always means slot 2, for example. How about introducing my proposal [*Bubblegum Finesse Wraparounds & Skips*](https://github.com/Zamiell/hanabi-conventions/issues/214).

**Comment by Zamiell** [comment]
> In a 4p-5p game, since there are only 4 slots, we subtract 1 from the rank clue given
cluing a 1 with a 2 means play slot 1
3 plays slot 2
4 plays slot 3
5 plays slot 4

i agree with jeff, it should just copy the wraparound convention

**Comment by Zamiell** [comment]
going to leave this open until i play pink ones

**Comment by Zamiell** [comment]
so this is kind of self-explanatory, it follows directly from Bubblegum conventions, so i will close this

**Comment by padiwik** [comment]
they're proposed tables are different from pure bubblegum conventions, no?

**Comment by Zamiell** [comment]
jeff and i vetoed the proposed tables

**Comment by padiwik** [comment]
scharkbite told me that you said these only work when all the ones are played? I feel like that doesn't make much sense, since that is very low value and you basically need the positional clues at the beginning of the game, not the end. Consider https://hanabi.live/replay/238017/1 , I think if DMoney clues 4 to padi it works correctly to get p1 and r1 played
