### ISSUE TITLE
Convention Proposal: Self Color Bluff with White Ones Variants

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#229]
Since ones are not touched with color we can do self color bluff/finesse.

3p game nothing played on the stack
Bob's hand g1 - g2 - x - x - x
Alice clue's green to Bob only touching G2
Bob can look around the table and not see G1, thus he must have it
Bob plays g1

3p game nothing played on the stack
Bob's hand r1 - g2 - x - x - x
Alice clue's green to Bob only touching G2
Bob can look around the table and not see G1, thus he must have it
Bob plays R1 as G1. 
Should Bob continue to look for g1?  No, it should be treated as a self color bluff and he marks the green card as G2 or G3

**Comment by iamwhoiamhahaha** [comment]
I've already done this when this variant has implemented, but I was too lazy to propose this convention lol. You know, there are so many variants, I'm not sure if I should propose everything here lol. For example, I invented *2's Chop Moves* and *4's Chop Moves* in *Pink-Ones & Dark Null* and made the perfect scores with Fireheart in 2-player, and I was not sure if I should propose these conventions on github 😂.

**Comment by Zamiell** [comment]
this is pretty obvious (e.g. naturally flows from first principles) and doesn't belong in the doc

for example, i played with kyle yesterday and he was already doing this without any pre-coordination or knowing that this was a "thing"

**Comment by Dr-Kakashi** [comment]
Sounds good!
