### ISSUE TITLE
Edit to Loaded Play Clues in Hard Variants (Part 2)

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#230]
https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#loaded-play-clues-in-hard-variants-part-2

Bullet Point 3
Similarly, Loaded Play Clues also apply to the Trash Chop Move. This means that any clue that looks like a Trash Chop Move will instead become a Loaded Trash Ejection (if the clue receiver is currently "loaded" with a play).

Trash ejection has been deleted.  Should this be changed to known trash ejection?

**Comment by Zamiell** [comment]
trash ejection has not been deleted yet, see #217

**Comment by Zamiell** [comment]
actually, see #238

**Comment by Zamiell** [comment]
actually, im going to completely delete this bullet point and leave it undefined in order to remove some complexity
