### ISSUE TITLE
Convention Proposal: Known Trash Double Pull

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#231]
Just like for 5 Double Pull but with Trash.  This must strictly be done in end game and/or a board state where there is no cards left to chop move.  

3p game, all 1's are played
Cathy's Hand x - x - x - r1 - b2
Alice clue's 1 to Cathy
Bob can see that Alice could've just give a normal blue or 2 clue to Cathy.
If Bob does nothing, Cathy will chop move the b2
Bob plays slot 1 and plays r2
Cathy can see that had Bob done nothing, she would've just chop moved.
However, since Bob played slot 1, she can know it's a Trash Double Pull and play B2.
Cathy successfully plays B2.

**Comment by Dr-Kakashi** [comment]
![2020-05-24_1708](https://user-images.githubusercontent.com/48993588/82768052-32943e80-9de1-11ea-8b81-341bc0e57e72.png)

**Comment by iamwhoiamhahaha** [comment]
Seems fine. But your example is not good lol. Looks like the blue 3 is blocked and this is the only thing you can do which should not trigger a *Trash Double Pull*.

**Comment by Dr-Kakashi** [comment]
The 1's are not touched by color....sorry the variant was Light-Pink-Ones & Black

**Comment by Zamiell** [comment]
the group does not use the "normal" 5 double pull.
thus, you should not be proposing a convention even more edge-case and even more unlikely to be used. as it stands 5 double pull will be deleted soon unless i see some evidence of people using it on a regular basis

**Comment by iamwhoiamhahaha** [comment]
5 double pull is common. I've seen it more than 10 times.

**Comment by Zamiell** [comment]
link the games

**Comment by Zamiell** [comment]
but do it in #234

**Comment by iamwhoiamhahaha** [comment]
This is your short not using it. IIRC, asaerl, kakashi, fireheart, micerang... have done it before.

**Comment by Zamiell** [comment]
ok, link the games

**Comment by Zamiell** [comment]
the consensus from #234 is that 5 double pull should stay.

with regards to this issue, post more evidence beyond one screenshot that it will be useful

**Comment by Zamiell** [comment]
furthermore, doesn't this conflict with the *Trash Double Bluff*?

**Comment by Zamiell** [comment]
closing since kakashi isn't responding to me
