### ISSUE TITLE
Delete the 5 Double Pull

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#234]
https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-5-double-pull--the-double-5-pull

Zamiel pointed out that 5 double pulls are only done during early game.  Why is that so?  We can 5 chop move any time during the game.  

I've even done this in other games during mid game and it works.  Everyone is just aware it's weird to chop move a playable card.

**Comment by iamwhoiamhahaha** [comment]
It is because it could be a finesse on the 5

**Comment by Dr-Kakashi** [comment]
Wait, so we have 5CE where you must eject if it's 2+ away from playable.  So, let's say there's a 5 that's 3 away from playable.  I can just clue the 5 with rank and everyone will finesse out the cards?

**Comment by Zamiell** [comment]
yes

**Comment by Dr-Kakashi** [comment]
So, what about a situation where you can freely clue color or 5?  Both will cause the finesse on the suit?

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#junk-ejection-with-5s

**Comment by iamwhoiamhahaha** [comment]
By the current definition, if yellow 5 is two or more away from playable, color clue means 5ce, rank clue means finesse/triple bluff. Or you can define it as a 5 double pull if that 5 is two/three or more away from playable, and see if zamiel would approve it.

**Comment by Zamiell** [comment]
a finesse sounds like it would almost certainly be more useful than an edge-case esoteric convention of limited use

**Comment by Zamiell** [comment]
furthermore, i've not yet seen a 5 double pull, so it is a candidate for deletion currently

**Comment by Zamiell** [comment]
lets turn this into a "delete 5 double pull" thread since i haven't seen it used.
feel free to post a replay/screenshot of a game where you have used this move.

**Comment by iamwhoiamhahaha** [comment]
@Zamiell https://hanabi.live/replay/120357

**Comment by Dr-Kakashi** [comment]
![2020-05-27_0556](https://user-images.githubusercontent.com/48993588/83021466-e1ea3480-9fde-11ea-9b05-5152ba19d741.png)
Done and successfully played.

**Comment by Dr-Kakashi** [comment]
So I see that you've listed the Junk Ejection.  There are some slight differences.

The ejection locks the cm card as trash.

The players know a playable card was chop moved.  However, I can understand why a single blind play would cause it to be a full on finesse for that 5 and cause other players to search for the cards, including the clue receiver.

**Comment by pianoblook** [comment]
This worked yesterday: 
<img width="986" alt="Screen Shot 2020-05-27 at 11 38 56 AM" src="https://user-images.githubusercontent.com/32303453/83042108-43c29280-a00f-11ea-967a-d66732329d89.png">

**Comment by Dr-Kakashi** [comment]
![2020-05-28_2319](https://user-images.githubusercontent.com/48993588/83227743-c3e51700-a139-11ea-834e-2f2cd1d5a95a.png)

**Comment by Zamiell** [comment]
looks like there is enough evidence to not delete 5 double pull,
if you want to make a new convention to extend it to the mid-game, then open a separate issue for that.
