### ISSUE TITLE
Convention Proposal: Unnecessary UTD Trash Push

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#236]
![2020-05-25_2131](https://user-images.githubusercontent.com/48993588/82860670-3900e400-9ecf-11ea-8277-5db870097a4e.png)

UTD on B4
Kimbi can see it was unnecessary.  However, there is no purpose to give her trash on chop
She takes it as a trash push and plays k1

**Comment by iamwhoiamhahaha** [comment]
I don't know why zam rejected uutdtp last time tbh

**Comment by Zamiell** [comment]
this conflicts with trash double bluff

**Comment by Dr-Kakashi** [comment]
Trash double bluff needs to be redefined....it was created before we had all these unnecessary conventions.
