### ISSUE TITLE
Proposal to remove: Disease Bluff and Heal clue

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-conventions#240]
Reason: the disease bluff is just not very strong. 2 clues to touch 3 cards, and get tempo on two of them? (at least in the [two](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#1-a-disease-bluff) [examples](https://github.com/Zamiell/hanabi-conventions/blob/master/examples/Disease_Bluff.md) given). In both examples I prefer that the clue would instead be interpreted as a Clandestine Finesse + Fix clue. So the person who played the first blind card keeps playing blind cards until they play a card that can match the originally clued card (of course, that doesn't work in the given examples). If we want to give this move a new name, it could be the Diseased Clandestine Finesse or something.

I do want to keep the Pestilent Double Bluff.

**Comment by Dr-Kakashi** [comment]
3 for 2 is 1.50 efficiency.  That's quite high for sticky situations like the example.  Additionally, it leaves open the option to clue green later once the g1 shows up.  It isn't just about getting the cards, it's also about giving the team the most information.

**Comment by fpvandoorn** [comment]
I disagree that these situations are sticky, there are many options which have similar strength. Almost always, when doing a Disease bluff, you can do a regular finesse or bluff, which is stronger). And the existence of this convention removes the (occasional) more efficient clue clandestine finesse + fix.

In the first example, I don't even think the disease bluff is the best move. If Alice clues red to Bob and Bob plays, Cathy can bluff or finesse the red 2 however they want (for example by cluing the blue 2, in which case you have achieved the same result, but there is probably something better).

In the second example, I'm not convinced that the disease bluff is the best move. There are many fine 2-for-1s that can be given: red to Kyle, 1 to Kyle (or MasN). Sure, some of them have to be followed up by a 1-for-1, but that's not lower efficiency than the disease bluff (and the g2 is less interesting than the other 2s from Kakashi's perspective). With the disease bluff you also touch the newly drawn card in MasN's hand if it is yellow, but that could also be bad (y1 or y2).

And I think this does reduce complexity, since it removes a type of bluff.

**Comment by Zamiell** [comment]
>  In both examples I prefer that the clue would instead be interpreted as a Clandestine Finesse + Fix clue.

what would you prefer the example in the doc be

**Comment by Zamiell** [comment]
>  In both examples I prefer that the clue would instead be interpreted as a Clandestine Finesse + Fix clue. So the person who played the first blind card keeps playing blind cards until they play a card that can match the originally clued card (of course, that doesn't work in the given examples).

these sentences don't seem to make any sense.
what exactly do you propose happens in both of these examples that you linked

**Comment by fpvandoorn** [comment]
I propose that different clues are given.

**If** Alice clues 2 to Bob, Bob plays r1, Cathy clues r2, I propose that Bob writes `f` on slot 3.
**If** Dr_Kakashi clues 2 to RaKXeR, MasN plays y1, Kyle clues yellow to MasN, I propose that MasN writes `f, g1` on slot 2.

**Comment by Zamiell** [comment]
```
asaelrToday at 12:02 PM
Does The Clandestine Finesse contradict The Heal Clue?
Suppose that Bob has y1-g1-... and Alice clues (at first turn) Donald's g2 by 2.
Of course, Bob played y1. Suppose that Emily has a y2. Is Cathy allowed to clue it now?
```

**Comment by Zamiell** [comment]
i copied the above quote from discord, as it highlights one of the "cons" of having a *Heal Clue* convention

**Comment by NoMercyO** [comment]
I believe I support florrats change. In the disease bluff example, i agree a yellow clue shouldn't prevent the attempted cladestine finesse.

Mason should respond by playing slot 1 as a pestilent double bluff.

**Comment by hakha3** [comment]
I think diseased bluff lose a lot of efficiency because it requires heal clue, what makes that almost always there is something better available. Having it makes that often something more efficient like double bluff isnt possible. So you should probably remove it or I kinda like idea of keeping diseased bluff which doesnt need heal clue. So like in this <a href="https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#1-a-disease-bluff">example</a>. Cathy doesnt need to do anything and Donald will just play his finesse slot. I think it could even work in reverse order. Fact that its not known immiedietely if intial clue was bluff or not doesnt seem that much of a problem as its pretty much the same as in case of Ambiguous Finesse. I guess problem with that way of resolving is that it would look like patch finesse or some other stuff, but I think you could make an distiction between them or kill other stuff

**Comment by fpvandoorn** [comment]
That is an interesting point hakha. I think your suggestion about Cathy not needing to fix is a interesting suggestion new convention (it's not how we currently play). Since it's a different point than this issue, let's have discussion about that in a separate issue (#262)

**Comment by Zamiell** [comment]
im fairly neutral, so i guess this is accept

**Comment by Zamiell** [comment]
florrat can you submit a PR to "fix" the disease bluff section

**Comment by Zamiell** [comment]
@fpvandoorn

**Comment by Zamiell** [comment]
**The Disease Bluff & The Heal Clue** (deleted) (by Florrat)

```
* Previously, when a *Bluff* occurred that was "mismatched", the *Disease Bluff* was the highest priority interpretation (requiring Cathy to perform a *Heal Clue*).
* Now, both the *Disease Bluff* and the *Heal Clue* conventions are deleted. Now, Cathy is always supposed to assume a *Pestilent Double Bluff*.
* See the section on the Pestilent Double Bluff in the doc for more specific details.
* In very rare circumstances, if Cathy sees that she can transform the *Pestilent Double Bluff* into a *Clandestine Finesse*, then she should always do so. For more information, see the section in the doc called the *Diseased Clandestine Finesse*.
```
