### ISSUE TITLE
Convention Clarification: Early Fix Chop Move

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#242]
![2020-05-27_0519](https://user-images.githubusercontent.com/48993588/83018792-b5341e00-9fda-11ea-927d-c2a8823c8a32.png)

Sometimes during the game we accidentally dupe cards in a player's hand.  
Generally, we leave the card alone, so it's very strange for one of the teammates to suddenly tell you it's trash. 
When this happens they are mainly protecting your chop as they are giving you trash to discard.  
The clue receiver should now chop move.  
This is similar to the chop transfer convention.  Only the chop moved cards are clued as trash

**Comment by iamwhoiamhahaha** [comment]
I have that in my **[Chop Move Guide](https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Chop_Move_Guide.md)**.

**Comment by Zamiell** [comment]
isnt this the same as the early fix clue chop move, which we already deleted?

**Comment by Zamiell** [comment]
see: https://github.com/Zamiell/hanabi-conventions/blob/master/misc/Deleted_Conventions.md#the-early-fix-clue-chop-move

**Comment by Dr-Kakashi** [comment]
Yep looks like the early fix clue chop move.  I was looking through the guide and didn't find this convention anywhere.  I had no idea it was deleted 😅.

Ok so it was deleted because it was ambiguous whether or not a fix clue was early or not.  

So, the picture doesn't show the trash but B3 is also critical.  Kakashi can see that Zakisan can get G1.  
Zakisan's options:
1. Can defer (Kakashi has some playable card on finesse position or even G1 himself)
2. Can give the B5 save (it's a hard variant and he doesn't have to, since Fey has a known play.)
3. Zakisan is not going to misplay the m1 as he has no knowledge of his cards prior to the clue.

Thus, if Kakashi gives a 5 save to Zakisan he might still discard B3.
Additionally, since it's a hard variant, it's just so bad for Kakashi to give a 0 for 1 giving no additional information to his hand.  

Thoughts?

**Comment by Zamiell** [comment]
in some situations it is an obvious chop move, in some situations it isn't. thats why it was deleted
