### ISSUE TITLE
Trash Double Bluff (Form 2) is defined the wrong way around

### ISSUE THREAD

**Issue by florian-5f3759df** [Zamiell/hanabi-conventions#243]
A [Trash Double Bluff (Form 2)](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-trash-double-bluff-form-2) occurs when a (necessary) trash bluff is done, but using two trash cards when one was possible.

Touching two cards lets a player perform a [Trash Order Chop Move](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#trash-order-chop-move) if necessary, perhaps saving a free card, so in general it's more optimal, and touching only a single trash card is suboptimal.

The suboptimal action should get the extra blind play, with the optimal action being the default, so Form 2 should be defined in the opposite way.

**Comment by Zamiell** [comment]
@jeff

**Comment by iamwhoiamhahaha** [comment]
Make sense. But actually, TDB is mainly used near the end game where we typically don't need a tocm.
So how should it be defined you think?

**Comment by Dr-Kakashi** [comment]
From my understanding, only the focus is trash. The 2nd blind play must be done to show that both are trash.  

So, if we say cluing 2 trash cards gets 1 blind play, how does Donald know that both are trash?

**Comment by florian-5f3759df** [comment]
That shouldn't be the case, the other green card is also trash.

Current conventions say: "In the case where multiple cards are clued as part of a Trash Bluff, all of the touched cards are considered to be trash. However, the focus of the clue should be the first thing discarded, which allows for the possibility of your teammates to give a follow-up Fix Clue."

So the blind play is not something that differentiates that, it's already both trash. The double bluff question only comes up if a single touched trash would have also been possible. (Contrary to UTD, where good touch is maintained by default on other cards. If you disagree with this difference, that's a separate issue.) 

It's more like the situation where you give a save on a card that only touches that card, vs. a save that also touches more known good cards. The first gets a play if it's clearly suboptimal. My point in making this issue was only that the situation is symmetric for trash bluffs: knowing about more trash cards is usually better than not knowing about them, for discard strategy and TOCM purposes. 

The conventions do say you have to allow for a fix clue, so my original point is weakened by TOCM often not being allowed.

**Comment by Zamiell** [comment]
> From my understanding, only the focus is trash. The 2nd blind play must be done to show that both are trash.

thats wrong

read the final bullet point: https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-trash-bluff

**Comment by Zamiell** [comment]
as jeff points out, TDB is only used in the end game, so TOCM is irrelevant at this point

**Comment by Zamiell** [comment]
i think the current configuration of:
- touch 1 trash, play 1 blind card
- touch 2 trash play 2 blind cards
is pretty intuitive

**Comment by florian-5f3759df** [comment]
Fair enough. I guess '1 means 1 play and 2 means 2 plays' could in this case be easier to remember than the general 'suboptimal = extra meaning' principle, and it's pretty rare anyway. I'm fine with closing this.
