### ISSUE TITLE
Examples of the Purge Bluff

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-conventions#244]
Zamiel is going to misplay null 5, and there is no way to fix it
https://github.com/Zamiell/hanabi-conventions/blob/master/examples/Purge_Bluff.md

**Comment by Zamiell** [comment]
should be fixed now, reopen if not fixed

**Comment by Aigul9** [comment]
description doesn't match

**Comment by Zamiell** [comment]
i dont know what that means, can you just submit a pull request?

**Comment by Aigul9** [comment]
idk how. i see mention of y2 in the example description, but there is no yellow suit

**Comment by Zamiell** [comment]
ok, should i close this issue now?

**Comment by Aigul9** [comment]
sure

**Comment by Zamiell** [comment]
kk
