### ISSUE TITLE
The Bad Touch Finesse (For 2's)

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-conventions#245]
In this situation, **the left-most** card can be played and the other card discarded as known trash.
In the same section:
Cathy plays **the chop** 2 (the original focus of the clue) and then discards the other one later.

**Comment by Zamiell** [comment]
fixed, thank you!

**Comment by Aigul9** [comment]
in bad touch bluff Cathy did the same

**Comment by Zamiell** [comment]
can you open a PR for this too?

**Comment by Zamiell** [comment]
ok, should i close this issue now?

**Comment by Zamiell** [comment]
should we close this now?

**Comment by Aigul9** [comment]
+

**Comment by Aigul9** [comment]
yes

**Comment by Aigul9** [comment]
i clicked wrong button. is it okay?

**Comment by Zamiell** [comment]
yeah, its good, you can close issues too or i can
