### ISSUE TITLE
Play Style Proposal: No Saves in Clue Starved

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#248]
Instead of using clues to directly save cards, players should use the chop move discards to tell players to chop move.  

- Scream Discard Chop Move
- The Whisper Discard Chop Move
- Double Scream Discard Chop Move

2p chop move conventions shall be used
- Skip discard chop move
- Double Chop Move by bombing chop

Any clue that touches chop is a play clue.

Exceptions:
When team has 2 strikes, clues on chop are saves if they can be a save.

**Comment by iamwhoiamhahaha** [comment]
Zamiel won't approve it since hyphenated conventions are not designed for score hunting. And clue starved is not that difficult imo. It is self-evident that you can do whatever you want in order to complete perfect scores in clue starved. Anything can happen since the required efficiency is high.

**Comment by Zamiell** [comment]
what he said
