### ISSUE TITLE
Convention Proposal: 1 & 5 Save Bluff In Up & Down

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#249]
https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/Black.md#the-black-save-bluff

For Up & Down Variants

Once a 1 is played, 5's on chop is a save clue.
Following this, once a 5 is played, 1's on chop is a save clue. 
If a player has a free choice to clue color or rank but decides to choose rank instead, causing the player who received the clue to instead save.  This would be very strange.
Similarly to the Black Save Bluff, the next player is expected to blind play, as a known bluff.
To the person who received the clue, it would be very strange to see a blind play occur on a 5 or 1 save.  Thus, it is not a save but in fact a play clue.
If the person needs to blind play 2+ cards, then it shouldn't be treated as a finesse but instead just a play clue on the 1 or 5.

**Comment by iamwhoiamhahaha** [comment]
1. Is it a proposal for *Up or Down*?
2. It is currently defined as *Rank Choice Ejection* I guess.

**Comment by Dr-Kakashi** [comment]
Thanks Jeff.  I forgot to write the variant lol.

Eh, I guess it could be rank choice ejection as well since it's the same concept.  Let's have Zam weigh in on this and then we can close this post.

**Comment by Zamiell** [comment]
need evidence, same as all your other proposals

**Comment by Zamiell** [comment]
closing since no evidence was given
