### ISSUE TITLE
Example/Proposal: Tempo Clue Ejection (or Junk Ejection w/ Tempo Clue)

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#250]
I tried something apparently undefined today, and it's basically another specific form of a _Bad Chop Move Ejection_. 

_Tempo Clue Ejection_
-If a playable card is retouched as only a _Tempo Play Clue_, normally this should trigger a _Tempo Clue Chop Move_ on the clued player.
-However, if the immediate next player sees that this would _Chop Move_ trash, they should blind play their Second Finesse Position
-By doing so, the clue receiver will undo the cm and still know their card is playable. 

<img width="1262" alt="Screen Shot 2020-05-29 at 2 23 03 PM" src="https://user-images.githubusercontent.com/32303453/83292396-02211b80-a1b8-11ea-8190-eccc32af054f.png">

**Comment by pianoblook** [comment]
I'll be on the lookout for more of these, since it seems like a potentially more powerful form of a _Double Play Ejection_, since that is purely a 1-for-1 while this also helps cards get played.

**Comment by Zamiell** [comment]
its not a very good convention because it has overlap with common mistakes, e.g. a player thinks that they are locked, and gives a tempo clue

**Comment by pianoblook** [comment]
Yeah it's definitely on the weaker side, since it's just a 1-for-1 plus tempo. _Double Play Ejections_, _Junk Ejections (w/ trash), and _Known Trash Ejections_ are all pure 1-for-1's, though.

**Comment by pianoblook** [comment]
<img width="1015" alt="Screen Shot 2020-05-29 at 9 50 36 PM" src="https://user-images.githubusercontent.com/32303453/83316869-8b574300-a1f6-11ea-819f-c6c4e7fae62b.png">

Just happened now

**Comment by Zamiell** [comment]
tempo clues on omni cards are not generally tempo clue chop moves, so this is a bad example

**Comment by Zamiell** [comment]
convention seems weak, and not enough evidence, so ill close this
