### ISSUE TITLE
Make generation discard optionnal by making the next player discard his second chop

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-conventions#255]
Hi,
Alice has a play and 0 clue.
Bob has no play.
Cathy got a critical card in chop.

Actually, on general, Alice should generation discard, and Bob save Cathy's chop.
On some specific cases, Alice can play her card if she saw a clue for Cathy to do, which would conventionnally force Bob to discard normally, both expecting Cathy to clue what was planned by Alice (or clueing something else).

Instead on bga, if Alice decide to play her playable, Bob should conventionnally discard his second chop, which make Cathy save her chop.

Example:
This example use an extention of that move, where Romain discard his third chop for saving two cards in Kimbi's hand.
https://hanabi.live/replay/190766/20

.

So here is my proposal:
On that situation, Alice has the choice between:
 - either generation discard as usual ;
 - or to play if second chop of Bob isn't critical, and force Bob to discard his second chop.

I really want to make that optionnal.
[If you force Alice to play on that situation, it create a lot of problems (having a player chop move his second chop per example) and would totally mess up something which work well (echo scream discard chop move, rebellious discard...).]

**Comment by Zamiell** [comment]
> I really want to make that optionnal.

yes (obviously) i think that the new convention would be optional, building on the tools that we already have

**Comment by Romain672** [comment]
NoMercy: "You are suggest a convention involving players discarding away from chop? Sounds extremely mentally draining as now you need to constantly account for the possibility of any slot of cards being at risk of discard given any board state.

In endgame that is already done."
Again, that's optionnal, that mean if some slots is at risk, it's Alice's responsability to not do that move.

**Comment by iamwhoiamhahaha** [comment]
* Kimbi did it twice before and made me laugh lol. She told me you did it on her yesterday and it worked surprisingly.
* However, how can Bob distinguish from the case that Alice sees something for Cathy to do. For example, if Bob discards normally, there will be a 5 on *Chop* for Cathy to save. In the proposal that kimbi and you have done, Bob might discard a critical 5 from slot 4. (Imagine Alice has a safe discard and Cathy would definitely save the 5.)

**Comment by Romain672** [comment]
If both Alice and Bob saw something Cathy must do (=saving Donald's chop), then Bob can just discard normally.
If only Bob saw something Cathy must do (=3players, saving Alice's chop), then Bob is promessed to have a safe discard in his second chop, while his chop is any card. So Bob for safety should discard his second chop.
If Alice saw something Cathy will do most of the time, she can't assume that anymore if Bob's second chop is critical.
If Alice is locked, she can't generation discard normally anyway, so it doesn't matter.

**Comment by Zamiell** [comment]
> However, how can Bob distinguish from the case that Alice sees something for Cathy to do. For example, if Bob discards normally, there will be a 5 on Chop for Cathy to save.

This is important. In this hypothetical, if Bob discards normally, he may now be putting a 5 in his own hand on chop, and then Cathy will clue it, and that was Alice's plan.

So if this convention was adopted, it would make that play illegal.

**Comment by NoMercyO** [comment]
What cards can Bob off chop generation discard for?

3 player game:
example G4 on Cathys chop. 
G2 on the stack

Alice sees nothing untoward and plays her b2. She draws a g3. 
Bob sees that the g4 is unique and now board playable. He does not want to risk losing it. He knows he could discard and expect Cathy to buy a turn. So he does. 
Cathy bluffs the g3 using a card in bob's hand.
Alice plays slot 1.
Bob now has no plays, no good clues for Cathy, and a playable on chop. 

Under out current conventions Bob has two choices. misplay his chop, or let the g4 die and deal with illegal elimination notes.
Under your extension you want Bob to be also allowed to discard 1 away from chop. This is a game losing risk.

**Comment by Zamiell** [comment]
this convention would only apply to globally-known critical cards, not playable cards.
playable cards would just force elim notes on bob.

**Comment by Zamiell** [comment]
* In our group, sometimes players accidentally *Chop Move*.
* Normally, when that happens, it can result in a critical card being discarded when the erroneous *Chop Move* is first demonstrated. But if that does not happen, it is generally harmless - everyone on the team is aware of the *Chop Move*, and no further cascading mistakes happen.
* One problem with this convention is that, if Bob accidentally *Chop Moves*, Cathy will interpret it as a *Skipped Scream Discard*, which turns a single mistake into a double mistake, and causing potentially further cascading mistakes if e.g. Cathy then gives a "stall" clue.

**Comment by Zamiell** [comment]
learning towards "no" myself, jeff/mercy feel free to vote

**Comment by iamwhoiamhahaha** [comment]
I'm against this but feel free to do it in difficult variants

**Comment by Zamiell** [comment]
ok, will close it for now
