### ISSUE TITLE
Reversed Conventions

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#256]
* No *4 Saves*. Let 4's die.

**Comment by iamwhoiamhahaha** [comment]
### 2's Double Bluff

* If a two or more away reversed 2 is touched by a clue, it is a signal as a *Double Bluff*.

**Comment by NoMercyO** [comment]
How many suits are reversed in this game mode? i failed to find the summary doc :/

**Comment by Zamiell** [comment]
1

**Comment by NoMercyO** [comment]
Ok thanks, this is that new game official game mode with one backwards suit that is only number clued (black in the box, white by our color definitions)


1s:
- 1s order chop moves are disabled. Exception. if the reverse 1 is visible you may order chop move with your 1s as per normal (and are encourage to do so on most non trash to produce rev1 elimination notes.
- 1s clues on chop always respects rev1, and can assume rest of 1s are playable. (note in cases where chop 1 is actually playable, and rev1 in a different one, use color on chop 1. 
- any 1s clue retouching already clued 1s, promises the next expected 1 to be played is rev1. rest of retouched 1s remain playable. Fresh one touched are not fresh, and are undefined if playable.
          -  could make all incidental 1s KT (reasoning color clues exist to tell player to prioritize these 1s first)
          -  could stick with fresh touched 1s from the fix clue are assumed good, and embrace a bomb many times. Better than undefined and they discard.

5s:
- one option: 5 clues unchanged. Makes rev5 very hard to play clue, requires bluff/eject, or prompting it out (and using the inverted 5s tempo clue when 5 is inevitably in wron slot). 5 saved 5s in a row will be REALLY obnoxious.
- let 5 play clues exist. Nuke most of our early game tech *unless black5 is visible. 

4s and 2s
- rev4 cannot be value saved with 4 clue.
- rev2 cannot be value saved with 2 clue (as clue focus). rev2 double bluff therefore works. 

3s. Everything is the same.

**Comment by Zamiell** [comment]
> let 5 play clues exist. Nuke most of our early game tech *unless black5 is visible.

this is what we are currently doing

**Comment by NoMercyO** [comment]
Regarding options for 'fresh 1s' Note this will also apply to a common hand setup of 
X X b1 rev1 b4. 
Hand is deemed largely unclueable until b3 is discarded. Team waits until early game ends and Alice discards.

New hand:
b4 X X b1 rev1
1s is now a save clue on rev 1. b1 is undefined whether it is KT or immediately played. What is correct to do is largely not a factor. wrong = bomb or discarding a playable. I think the bomb is the better choice.

**Comment by Zamiell** [comment]
You are not allowed to clue the reverse suit 5 with a number clue in the *Early Game*. If you want it to play, you need to clue it with color. (This preserves the ability to *5 Stall*, *5's Chop Move*, and *5 Pull*.)

**Comment by hakha3** [comment]
> * 1s clues on chop always respects rev1, and can assume rest of 1s are playable. (note in cases where chop 1 is actually playable, and rev1 in a different one, use color on chop 1.

What is reasoning for that convention? I think it would be better if we saved rev1 with color and treat every 1 clue as play from chop (unless there is context that 1 clued on chop is infact rev1)

**Comment by Zamiell** [comment]
there's pros and cons to that approach, notably we would lose the ability to chop focus play clue the rev suit

**Comment by Zamiell** [comment]
also note that doing this would be unintuitive because we don't play up & down that way

**Comment by Zamiell** [comment]
> 1s order chop moves are disabled. Exception. if the reverse 1 is visible you may order chop move with your 1s as per normal (and are encourage to do so on most non trash to produce rev1 elimination notes.

yup, this is how we are playing it today and yesterday

> 1s clues on chop always respects rev1, and can assume rest of 1s are playable. (note in cases where chop 1 is actually playable, and rev1 in a different one, use color on chop 1.

yup, this is how we are playing it today and yesterday

> any 1s clue retouching already clued 1s, promises the next expected 1 to be played is rev1 as a fix clue. Rest of retouched 1s remain assumed playable.

yup, same shit as pink, we already know how this works

> rev2 cannot be value saved with 2 clue (as clue focus). rev2 double bluff therefore works.

yes, thats how we are already playing, and also its what jeff already proposed

**Comment by Dr-Kakashi** [comment]
What about in black variants? is 4 the save or black?

**Comment by Zamiell** [comment]
save with black

**Comment by Zamiell** [comment]
someone please read through this page and see if i made any mistakes:
https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/Reversed.md

**Comment by padiwik** [comment]
> The 1 save

I thought we decided that the non-chop 1s are promised as playable. Add this? (i.e. you can safely play non-chop 1s by good touch, and know you aren't misplaying a rev1 from what was could otherwise be a chop-focused play clue OR a rev 1 save)

I think it might be good to clarify whether loaded play clues apply to rev 1 in a non-hard variant. The "usual stipulations" is a bit confusing as written.

**Comment by Zamiell** [comment]
### The 1 Save

* Similar to the *5 Save*, you can also do a *1 Save* in order to save the reversed 1. (There is only one copy of a reversed 1.)
* Any number 1 clue to a chop card is first and foremost respected as a *1 Save* (as opposed to a *Play Clue* on a playable 1).
* If a *1 Save* touches more than one 1, the non-chop 1s can be played as per normal.
