### ISSUE TITLE
Trash Push Ejection Example

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#257]
1 to charmander as a *Trash Push Ejection*

![trash push ejection example](https://user-images.githubusercontent.com/50160641/83522339-1dbb5780-a513-11ea-90e7-78fc91d2ff06.png)

**Comment by pianoblook** [comment]
What are your thoughts on restricting the _pushed_ card to be any >1-away-from-playable Critical card (and therefore letting it be 'cm'd for free)?

Here I see two other ejections possible anyway: 5ce for sure, but also even a double play clue ejection. Or just cluing the 4 directly, lol

**Comment by NoMercyO** [comment]
Black to charmander as 5CE also valid, and much better?

**Comment by Zamiell** [comment]
5ce seems like the optimal move.
find a better example where TPE is actually the optimal move.

**Comment by iamwhoiamhahaha** [comment]
what if charmander doesn't have a k5 lol. okay but i agree this is not a good example
