### ISSUE TITLE
You are No Longer Allowed to Give a Play Clue with a Number 5 Clue in the Early Game

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#260]
This convention only applies in both *Easy Variants* and *Hard Variants*. [edit]

Cons:

* You can't give a play clue to a 5 with a number clue in the *Early Game* anymore. (e.g. a color clue might be blocked, now you're fucked)
* There is one more extra rule to memorize regarding *Early Game* bullshit.

Pros:

* Removes a mistake - Players don't accidentally *5's Chop Move* or *5 Pull* when a normal *Play Clue* is given.
* Removes a mistake - Players don't accidentally bomb a 5 when a *5's Chop Move* or *5 Pull* is intended.
* More potential for 2-for-1s - You can do *5's Chop Moves* and *5 Pulls* in situations where before it would be a 1-for-1 *Play Clue* on a 5.
  * (Note: To be clear, a *5's Chop Move* counts as a 1-for-1, but a *5 Pull* counts as a 2-for-1.)

Does this new convention increase complexity or reduce complexity? It is unclear to me.

**Comment by padiwik** [comment]
This feels like one less rule to memorize. When you receive a number clue to a 5 in early game, you know it can't be a play clue on the 5, and defer to the next interpretation. (Basically, early game 5 pulls/stalls become non-early game direct play clues/stalls)

Side note, I don't think I've seen a directly play-clued 5 in an early game, so this situation is already pretty rare.

**Comment by NoMercyO** [comment]
As per other discussion I support this.
