### ISSUE TITLE
Pestilent Bluff Finesse

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-conventions#262]
@hakha3 (in #240):
> I think diseased bluff lose a lot of efficiency because it requires heal clue, what makes that almost always there is something better available. Having it makes that often something more efficient like double bluff isnt possible. So you should probably remove it or I kinda like idea of keeping diseased bluff which doesnt need heal clue. So like in this [example](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#1-a-disease-bluff). Cathy doesnt need to do anything and Donald will just play his finesse slot. I think it could even work in reverse order. Fact that its not known immiedietely if intial clue was bluff or not doesnt seem that much of a problem as its pretty much the same as in case of Ambiguous Finesse. I guess problem with that way of resolving is that it would look like patch finesse or some other stuff, but I think you could make an distiction between them or kill other stuff

hakha makes [an interesting suggestion](https://github.com/Zamiell/hanabi-conventions/issues/240#issuecomment-639072468): if someone does a clue like in [the disease bluff example](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#1-a-disease-bluff), someone has to play r2. If Cathy sees no r2 in a finessable position, then Cathy blind-plays slot 1 (that can be any playable card, as a Pestilent Double Bluff). If Cathy sees r2 in a finessable position, then she does not play, and let the other player play r2. Then it's like a Pestilent Bluff Finesse or something (we need a better name for that).

I can see some problems with this (does this violate Good Lie Principle? Can information get desynced from Bob's perspective?), and I'm not sure if I actually want to propose it as a new convention, but let's move discussion about this to a new (this) issue.

**Comment by Zamiell** [comment]
this is similar to https://github.com/Zamiell/hanabi-conventions/issues/220

**Comment by fpvandoorn** [comment]
Oh, that is a weird convention, but yes, #220 is a different way to indicate the same kind of response.

I'm worried about desync issues for either of the conventions.

* Suppose Alice performs a `Unnecessary `Trash Push (Finesse Form)` (or a `Pestilent Bluff Finesse` if it gets accepted) by cluing Bob
* Bob plays `r2` into Alice's clue
* Cathy sees that Donald has `r3` in slot 1, so doesn't respond. Instead, Cathy gives a play or save clue to Bob
* Donald plays `r3` from slot 1.

Now Bob *cannot* know whether Donald blind-played into Alice's clue or into Cathy's clue, and this will not be automatically clarified to Bob later. This is unlike most conventions we have currently, which is a problem with either convention.

**Comment by Zamiell** [comment]
agreed

**Comment by hakha3** [comment]
I see the problem with unnecessary trash push (finesse form), but with Pestilent Bluff Finesse I understand it would mean that Bob needs to decide if Pestilent Bluff Finesse happened or if he really has 3r and someone bluffed another copy of 3r. And I think Bob shouldnt assume second interpretation

**Comment by fpvandoorn** [comment]
Good point hakha, the case is different with the Pestilent Bluff Finesse: If Bob has r3, then it is illegal to bluff the r3. So that interpretation doesn't work. There are still some other conflicts (the bluff could be a [Bad Touch Layered Finesse](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-bad-touch-layered-finesse-bluffs-that-blind-play-a-duplicated-card)), but Bob can distinguish those interpretations by waiting another round (except in very contrived situations where it can also be a [Bad Touch Double Finesse](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-bad-touch-double-finesse-for-3s)).

**Comment by Zamiell** [comment]
on hold until #240 is resolved

**Comment by fpvandoorn** [comment]
While writing something for the *Diseased Clandestine Finesse*, I realized I do like this convention as well: in the situation below it makes sense for Cathy to wait if she sees red 2 in Finesse Position. I wrote up the changes if we accept this convention.
```
### The Disease Finesse & The Pestilent Double Bluff & The Diseased Clandestine Finesse

* In the *Good Touch Bluff*, a *Bluff* is given that looks like a *Finesse*. However, what if something that looks like a *Good Touch Bluff* is done, but the "matching" card is not yet clued?
* For example, in a 4-player game:
  * It is the first turn and nothing is played on the stacks.
  * Alice goes first.
  * Bob has a red 1 on slot 1 and a blue 2 on slot 2.
  * Alice clues Bob number 2, which touches the blue 2 on slot 2.
  * Bob doesn't see any other 1's on *Finesse Position*. Thus, the number 2 clue must be a *Self-Finesse*, so he blind-plays red 1.
  * Cathy comes next. From her perspective, Bob should currently think that his slot 2 card is red 2 (instead of blue 2). 
  * If nothing else happens, Bob will go on to misplay that card. However, giving a clue to Bob to fix the situation is inefficient.
* From Cathy's perspective, there are multiple possible interpretations, depending on the specifics:

#### 1) A *Disease Finesse*

* Say that Cathy sees the red 2 in Donald's *Finesse Position*.
* In this case, Cathy has to do nothing. Donald will blind play his *Finesse Position* as red 2. This will heal the problem, since Bob can see that the blind-play was related to the clue he received. 
* Bob will stop playing any more cards into Alice's clue, and keeps his 2 as any useful 2.

#### 2) A *Pestilent Double Bluff*

* If Cathy sees no other copies of red 2 in *Finesse Position*, then Cathy should blind-play her *Finesse Position* card as red 2. 
* Cathy could be blind-playing red 2, but could also be blind-playing **any** playable card. 
* Whatever card it is, it will still heal the problem, since Bob can see that the blind-play was related to the clue he received. Since Alice's clue got 2 blind-plays, Bob will stop playing any more cards into Alice's clue, and keeps his 2 as any useful 2.
* This is similar to a standard *Double Bluff*, but is different because the move was not initiated by a card that was 2-away from being playable.
* If Cathy sees one or more copies of red 2, and they are not in *Finesse Position*, Cathy should still blind-play her *Finesse Position*. In many cases (though not all), Alice could have clued the red 2 directly. We decide that it is not strong enough for Cathy to give a clue to a red 2 to fix the situation. 
* Even if Cathy sees both copies of the red 2, if neither of them are in *Finesse Position*, Cathy should still blind-play her *Finesse Position*. In that case it is a *Known Bluff* on Cathy.
* More examples of a *Pestilent Double Bluff* can be found [here](examples/Pestilent_Double_Bluff.md).

### 3) A *Diseased Clandestine Finesse*
* There is one exception to the *Pestilent Double Bluff*. What if Bob has the blue 1 in slot 3, and Cathy sees a copy of red 2 that is not in Finesse Position?
* In this case, the original intention of Alice was to do a *Clandestine Finesse* on Bob. However, this doesn't work, because Bob thinks his 2 is red 2.
* If Cathy gives a *Play Clue* to the red 2, then Bob knows that his 2 is not red 2.
* Since Cathy had to spend a clue to fix the situation, we decide that Alice's clue is not strong enough without any further plays.
* In this case, Bob interpret's Alice's original clue as a *Clandestine Finesse*, and will continue to play slot 3 as blue 1, and then play blue 2.
```

**Comment by Zamiell** [comment]
to clarify, this is the only new section:

#### 1) A *Disease Finesse*

* Say that Cathy sees the red 2 in Donald's *Finesse Position*.
* In this case, Cathy has to do nothing. Donald will blind play his *Finesse Position* as red 2. This will heal the problem, since Bob can see that the blind-play was related to the clue he received. 
* Bob will stop playing any more cards into Alice's clue, and keeps his 2 as any useful 2.

**Comment by fpvandoorn** [comment]
> to clarify, this is the only new section:

Yes, but some of the other sections are also modified a bit, to refer back to the new section.

**Comment by Zamiell** [comment]
i rewrote the section such that it follows from most probable to least probable, and that each move is in a separate section
