### ISSUE TITLE
level 14 out of order

### ISSUE THREAD

**Issue by tyrcho** [Zamiell/hanabi-conventions#269]
Hey,

Good job with splitting the reference guide !

A small confusion : 

https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#level-14---ejection--discharge-extensions goes after level 15 

Here is how the TOC looks to me:

![image](https://user-images.githubusercontent.com/700260/83940227-49746100-a7e3-11ea-9da3-c0424f4d031c.png)

**Comment by Zamiell** [comment]
should be fixed now thanks
