### ISSUE TITLE
Proposing a new convention kind of like UTD

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#271]
![2020-06-06_0942_(UTD_with_1's)](https://user-images.githubusercontent.com/48993588/83949741-4cb71f00-a7da-11ea-879a-cecdf97101bf.png)

**Comment by Zamiell** [comment]
what is the point of this screenshot

**Comment by Dr-Kakashi** [comment]
I'm not sure it is?  My thoughts are that it can be applied to situations where someone is holding two r2's, two r3's, or two r4's.  

Like if R1 is played and I touched r1 with color but it also touches r5, then it's a normal UTD where the player who received the clue understands that only the focus is trash.  

I've just looked at the trash finesse both strong and weak.
I've also checked the bad touch conventions.  

I don't think this would conflict with any of those.  It looks like this just works as a UTD, even in situations with two suits of the same color.  

If you wanted those players to play slot 1, then you would just use rank to initiate one of the bad touch conventions.  

So....Yes, it looks like this is a new convention that works even without a definition.  Shall we define this?

**Comment by Dr-Kakashi** [comment]
Oh, another situation:

R2 has been played
Alice clue's cathy red to two r4's
Bob plays slot 1 and it is r3
cathy can see that donald is holding r5

So, if we define this, we need to include these situations.

**Comment by pianoblook** [comment]
Very similar situation came up tonight: this time matched with an attempted Unnecessary component.

Right-most g1 was already known 1, leftmost was unclued

<img width="1219" alt="Screen Shot 2020-06-15 at 8 52 08 PM" src="https://user-images.githubusercontent.com/32303453/84722169-772e7800-af50-11ea-8da1-b4ee80a9de64.png">

**Comment by Zamiell** [comment]
we commonly clue two e.g. red 1s like this in order to get the red 1 out quickly so that we can e.g. give a color clue to a red 2 or so that we can e.g. give a color clue to a red 3 that is on chop

**Comment by Zamiell** [comment]
thus, this has some overlap with existing strategy, and could lead to unforeseen bombs when the above situations are happening

**Comment by Zamiell** [comment]
sounds like consensus is against

**Comment by Dr-Kakashi** [comment]
![2020-08-06_05-25-57](https://user-images.githubusercontent.com/48993588/89531600-55f64500-d7a5-11ea-9f2c-723626b6f771.png)

**Comment by ZakisanGithub** [comment]
This was also successfully used in https://hanab.live/replay/251739

![grafik](https://user-images.githubusercontent.com/68073156/89534338-07709700-d7f5-11ea-9308-eb12f822b772.png)

I see Zamiel's point of wanting to be able to give clues like this without being a discharge if there is urgency to get b1, which might depend on asymmetric information in Bobs hand, but I like applying this convention if there is no efficient fix for the bad touch. (Such as in the example that Kakashi just posted.)

**Comment by pianoblook** [comment]
^ I don't agree that the blue clue in Zak's screenshot should count. If the team is low on clues to give by turn 2, it's important to get the blue 1 out. 

Like, what else is Zak supposed to do here? Discarding would just exacerbate the crummy situation. Like you said, this clue + fix is not terrible inefficient (in fact it could just correct itself as soon as derek draws another 1)

**Comment by pianoblook** [comment]
<img width="1236" alt="Screen Shot 2020-08-06 at 9 23 53 AM" src="https://user-images.githubusercontent.com/32303453/89536915-8c908780-d7c6-11ea-90d7-d3ee4a54f8fe.png">

**Comment by Dr-Kakashi** [comment]
![2020-09-03_01-58-28](https://user-images.githubusercontent.com/48993588/92097937-7c4fd600-ed8d-11ea-903a-be109922edae.png)

**Comment by Zamiell** [comment]
i posted this in #convention-questions, but it should be recorded here:

consider a 3-player game:
- on the first turn of the game, alice clues red to cathy with the following hand - b4, b4, g4, r1, r1
- bob thinks that it is kakashis convention and bombs slot 3, losing the game
