### ISSUE TITLE
Pink Convention Help

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#273]
![2020-06-07_0531](https://user-images.githubusercontent.com/48993588/83968787-762a8600-a880-11ea-901b-c07c3a9cfb18.png)

So......I'm initiating a bubblegum finesse on jake.  It is not a bluff, since he's 2 seats away from me.  Is Jake supposed to play slot 4 then play slot 1?  Or is it like null where jake bounces, so he plays slot 4 then plays slot 3?

I personally thought jake would treat it like the null bounce, since I'm telling him where to look. 

Edit:
I'm also fine with playing slot 1 after, that way it's consistent with bubblegum finesse/bluff.  Just let us know, so we can adjust accordingly.

**Comment by Zamiell** [comment]
slot 1 after i think so that it is consistent with wraparound

**Comment by Dr-Kakashi** [comment]
Thanks for getting back to me on this.  I'll close the issue now.
