### ISSUE TITLE
Possible focus inversion

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#281]
![2020-06-11_0749](https://user-images.githubusercontent.com/48993588/84401510-33d2b300-abb8-11ea-918a-35891b46c876.png)

Here time can give green to Kakashi to finesse out g3, instead, he gives a direct play clue to melwen.  Should melwen focus invert?

**Comment by padiwik** [comment]
i thought 4 was the finesse because rank choice

**Comment by Zamiell** [comment]
> Should melwen focus invert?

no

**Comment by Zamiell** [comment]
furthermore, do not open issues for convention-related questions, ask those in the #convention-questions channel instead
