### ISSUE TITLE
Clarifying OOP rule option c

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#286]
https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-out-of-position-bluff-oop--the-reverse-bluff

However, players can rarely break the Bluff Seat rule if one of the following is true:

a. The next player is at 0 clues (and won't blind-play anything / will blind-play an unrelated card).
b.  The next player will think that they have the Bluffed card in their own hand and will not try to Finesse or Bluff the next player. (In this case, the Bluffed card means the card that will blind-play, not the "in-between" card.)
c. The next player has enough positive or negative clues on their entire hand to know that they cannot have the matching card.

Missing rule:
d. The next player doesn't have enough slots to respond to clue. For example, they don't have a slot 2 to respond to an ejection, slot 3 for discharge, or may even be locked and be unable to respond to a bluff/finesse.

**Comment by Zamiell** [comment]
thats covered by c

**Comment by Dr-Kakashi** [comment]
Shouldn't c be broken up into two parts for clarity?

1. They have an open hand
2. They have a limited hand

For example:
You clue the next player touching a single purple card that has negative 1.  P1 has not been played.  They have no other clued cards in their hand except for the purple card.

**Comment by Dr-Kakashi** [comment]
Additionally, if this is the case......If someone has a y5 that has already been clued/touched with rank as a save.  You clue the y5 with color that only touches the y5.  Does this count as OOP 5CE?

**Comment by Zamiell** [comment]
i dont see why the oop bluff section should have rules that only apply to oop ejection

**Comment by Dr-Kakashi** [comment]
Well it isn't just for OOP ejection....a player can have a locked hand, so you can do a bluff over that player.

**Comment by Zamiell** [comment]
thats covered by section c

**Comment by Dr-Kakashi** [comment]
Right, it specifies positive or negative clues, with no indication of slot limitation.

**Comment by Zamiell** [comment]
if you have a locked hand, then you by definition have positive clues on every card, so "slot limitation" is irrelevant

**Comment by Dr-Kakashi** [comment]
Hmm......alright I'll just close this then.
