### ISSUE TITLE
Convention proposal: The Gentleman's Finesse

### ISSUE THREAD

**Issue by cmangin** [Zamiell/hanabi-conventions#290]
Following a discussion on Discord, here is a proposal to allow apparently illegal Baton Discards to actually trigger a finesse (or a prompt or whatever).

- When a player discards a known card that is currently unplayable, it is usually a _Baton Discard_, which promises to another player that the discarded card is exactly on their finesse position.
- If the promised card is not on their finesse position, but layered behind other playable cards, then this communicates that the discarded card is, in fact, playable, and this should trigger a finesse.
- For example, in a 3-player game:
  - Red 1 is played on the stacks.
  - Alice discards a red 3.
  - Bob sees that Cathy's finesse position is blue 1, and her second finesse position is red 3.
  - Bob knows that this cannot be a _Baton Discard_, as red 3 is not exactly on Cathy's finesse position.
  - Bob blind-plays his finesse position as red 2.
  - Cathy is surprised, since a _Baton Discard_ should not trigger any blind-play. Thus she knows that a _Gentleman's Finesse_ is occurring, and her red 3 is layered behind other playable cards.
  - Cathy blind-plays her finesse position as some playable card. She will blind-play her slot 2 as red 3 on the next turn.

This occurred in https://hanabi.live/replay/194753/18 (and worked, despite it being illegal at the moment).
Is there any issue with this, or any risk of misinterpretation? Or is it simply too niche/specific to be worth an addition?

**Comment by Zamiell** [comment]
probably the latter.
you have to demonstrate that it is a generally-applicable convention, e.g. post screenshots of 2-3 game states where it works and it is the optimal move

**Comment by florian-5f3759df** [comment]
I think it would be much more powerful and applicable as a full replacement of the baton discard, which is now quite rare, where a discard of an unplayable card counts as a play clue on that card. 

(Of course, that convention does worsen a mistaken attempted sarcastic discard with not just a lost card, but also a bonus card bombing, so it would be a bit of a double-edged sword.)

**Comment by Zamiell** [comment]
define "rare". i would estimate that baton discord happens 1/8 to 1/10 games or so.

**Comment by florian-5f3759df** [comment]
Okay, if it's so often then you probably disagree. For me it feels like an order of magnitude less.

**Comment by Zamiell** [comment]
who is cmangin btw?

**Comment by cmangin** [comment]
Someone who should create another Github account for this purpose :)
In any case, I think I'm going to drop this, for two reasons:

- You're right, it's probably too rare, and fully replacing the baton discard is not something I would go for, it is a useful tool for various purposes.
- I think despite the current conventions, if people do their best to apply the stipulations of gentleman's and baton discards, and assume noone is making a mistake, it should actually just work in the rare cases where it could be used.

So I'm closing this issue. Thanks for your opinions!
