### ISSUE TITLE
8 Clue Save - Change

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#299]
Previously, the text for the *8 Clue Save* read that you are not allowed to use the move on a "freshly-drawn" card.
Now, the text for the *8 Clue Save* says that you are not allowed to use the move on any card that is on slot 1.

**Comment by NoMercyO** [comment]
Seems good, both for clarity and some flexibility for discarding at 7 clues without killing all possible play clues, possible even some bluffs, when discard modulation (or some being also locked) is a consideration.
