### ISSUE TITLE
request: distribute variants across levels

### ISSUE THREAD

**Issue by tyrcho** [Zamiell/hanabi-conventions#300]
As a rather new player, I start to get comfortable with conventions level 5-6. I also enjoy playing different variants of hanabi instead of sticking to "no variant".

It would be helpful to get a broad order on the difficulties of the variant, something like (just as a suggested layout, I'm not sure at all about the relevance) :
- keep playing no variant until comfortable with level 1
- you can mix in 3/4/6 suits at level 2
- wait until level 4 for rainbow; 5 suits is easier, then 6 suits. 3 suits is harder than 4 suits.
- you can try black at level 5 but should wait level 6. 3 suits black is harder because of required efficiency
- don't touch pink before level 7 !

From my personal experience, I feel that rainbow is the easiest variant (maybe because I played a lot of it in BGA. It might be black instead). Then black. And pink already feels like another level in itself, especially because of the sheer amount of new conventions.

**Comment by Zamiell** [comment]
where should i put it, on learning_path.md?

**Comment by tyrcho** [comment]
Yeah, learning_path is a very good place.

Also I suggest you move learning_path to the root folder and reference it
from README and/or Reference.md.
I find the learning_path super useful as a newcomer, and it should also
help more advanced players when we mix different levels.

Hi Sephiroth ;-)

**Comment by Zamiell** [comment]
all of this should be done now
