### ISSUE TITLE
Convention Proposal: Avoidance Ejection

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#303]
If a player could ‘get’ a card for free through a straightforward finesse, it would be very strange for them to decline to do so and instead just clue the card directly. In some cases this line might be chosen in order to touch other useful cards, or to avoid bad-touching something. But what if it’s done in a situation where there is *no* perceptible benefit - as an otherwise ‘known mistake’?

If this occurs, the following player should play their _Second Finesse Position_ as an _Avoidance Ejection_. Additionally, all other players (including the clue-receiver themselves, after the ejection & play resolve!) can now look for the matching card of that suit and make _Play Elimination Notes_ for it in their hand, if it’s nowhere else to be seen. (Or, in rare cases, even if it _is_ seen elsewhere, but in a location that would not have been able to trigger the Ejection.)

**EXAMPLE 1 (Simple Form):**
Turn 1
- Alice clues 1s to Cathy, touching a single Purple 1 on slot 1.
- Bob finds this to be an extremely odd clue; while it’s strange enough to clue a 1 on finesse position, Bob also sees that Donald has a purple 2 that could have been cleanly clued as a _Finesse_.
- Bob blindplays his _Second Finesse Position_, successfully.
- Cathy plays her 1.
- Donald does not see a Purple 2 in Cathy’s hand (or at least one that could have easily triggered a finesse). He therefore writes _Play Elimination Notes_ for p2 in his hand.

**EXAMPLE 2 (Layered Form):**
Turn 1
- Alice clues 1s to Cathy, touching two 1’s on slots 1 & 2.
- Bob sees Donald has the matching 2 that could have been easily used to cleanly get both of Cathy’s 1s as a _Layered Finesse_.
- Bob _Ejects_.
- Donald writes _Elimination Notes_ for the matching 2.

**EXAMPLE 3 (Reverse Form):**
Turn 1
- Alice clues 1s to Bob, touching a single 1 on his finesse position.
- Bob is very skeptical of why this might have been chosen. He sees multiple 2s and 3s that could have been used as straightforward _Finesse_ or Bluff_ targets.
- Then again, he can make an educated guess: he sees a playable 1 on Cathy’s slot 2. Bob plays his red 1.
- Sure enough, Cathy sees that Donald has a lone red 2. Cathy _Ejects_.
- Donald marks _Elimination Notes_ for red 2.

NOTES & THOUGHTS: 
 

- This works just as well in 3-player, including even the reverse form.

- Using color clues for this would usually be _Illegal_ because of its conflict with 5CE. It might still work in the Reverse Form, though, or later in the game.

- There seems to be opportunity to expand this concept to other clearly _Avoided_ lines. Here are a few reasonable examples I can think of:

1. _Avoiding_ a Double Finesse by only giving a single finesse (or by simply color-cluing the 1 & 2, if they’re in one hand)

2. _Avoiding_ a _5 Color Ejection_ (this would only work in reverse, of course)

3. _Avoiding_ a _5-Pull Finesse_ (although this seems inadvisable in most cases, imo)

- That said, there does need to be a clear distinction drawn of what should be perceived as “strictly inferior”. I can imagine plenty of edge-cases where there could be enough reason to ‘avoid’ a finesse (mostly in terms of driving discards/play modulation).

**Comment by pianoblook** [comment]
Obviously this hasn't been pulled off yet because it hasn't existed, but I was able to find two Turn One situations in my last 20 games that could have made use of this if a different player had just gone first.

Really curious to hear thoughts, and I'll be sure to look for more examples in games going forward.

Example 1: Pablo hints 1 to pianoblook. piper ejects brown 1.
<img width="1167" alt="Screen Shot 2020-07-02 at 9 29 41 AM" src="https://user-images.githubusercontent.com/32303453/86366135-68caa680-bc48-11ea-916e-85d0e81b7939.png">

Example 2 (Reverse): robense hints 1 to Markus. He should heavily suspect he has green or blue 1 if he knows about this convention, and plays. Sure enough, pianoblook ejects.
<img width="1168" alt="Screen Shot 2020-07-02 at 9 31 06 AM" src="https://user-images.githubusercontent.com/32303453/86366129-68321000-bc48-11ea-9da9-7f87600f3239.png">

**Comment by pianoblook** [comment]
Okay first self-criticism: the 'Layered Finesse' version should probably be illegal, since perhaps Alice is just choosing to set up Bob to be able to  _Order Chop Move_ a teammate. I guess it could still be functional if Bob chooses to just play the expected 1 anyway, but that seems super sketchy and I'd suggest it be banned

**Comment by pianoblook** [comment]
<img width="1168" alt="More complicated situation" src="https://user-images.githubusercontent.com/32303453/86400516-bf4ed980-bc76-11ea-8819-2f48101b6b9e.png">

Just popped in to watch a game in progress (finished now) and right away saw an opportunity for this, albeit a bit more complex than the Examples.

- In the game, Floriman gives the obvious '4' clue to Kyle to Finesse+Prompt m2&3.
- But what if he chooses to just hint '3' to Kyle instead? This is (A) clearly worse by getting one less play and less clarity; and, importantly, (B) very hard to miss and would basically never happen unintentionally in Level 15+/Expert play.
- If he _does_ hint 3 instead of 4, scharkbite plays his Second Finesse as an _Avoidance Ejection_
- Since _Avoidance_ can only result from situations that would (A) make a stronger line (≥+1 play) and (B) have to be strictly inferior, Kyle can mark his hand for the matching Multi 4 (since touching padi's 4 would not be sufficient to correctly prompt the 3.)

**Comment by padiwik** [comment]
we actually decided that cluing 4 is a fix clue in that game, which is annoying. but this illustrates the ickiness of the *Avoidance Ejection* - there can be information asymmetric reasons to give the "worse" clue

**Comment by pianoblook** [comment]
^ fair enough, I only peeked my head in for a second during the game and was unaware of any previous context. At the time, though, it looked like a pretty clear finesse. (watching the replay it still looks like a finesse, but /shrug)

For sure this would need to be incredibly sensitive to context. Perhaps as a first foray into considering this convention it should only be Turned On in immediate early game. Maybe the above example isn't a good one, but I am going to try and share a few examples to encourage discussion.

**Comment by pianoblook** [comment]
I'm pivoting on this one: see #305.

I'd love to discuss options on this

**Comment by pianoblook** [comment]
Can someone Close this?

this absolutely should not be an Ejection - this would be equivalent to changing _Blaze Discard_ to always just be an _Ejection. 

Now that the _Shadow Finesse_ idea has formulated, this proposal is outdated and awful.
