### ISSUE TITLE
The Penumbral Finesse (a Shadow Patch Finesse)

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#309]
**The Penumbral Finesse**

- If a strictly suboptimal play clue is given _Out of Bluff Seat_ that touches a single card on _Finesse Position_, this can often only reasonably be interpreted as a _Backlit Shadow Finesse_.
- The very next player should therefore assume they have the “Target” somewhere in hand (i.e. the card that could have been simply _Finessed_)
- But what if they notice that the very next player (who would be promised to have the _Shadow_) doesn’t have any immediately playable cards, and instead has only one (or more) one-away-from-playables?
- In this case, they must immediately blindplay their _First Finesse Position_ as a _Penumbral Finesse_ (aka. a _Shadow Patch_)
- The following player, although surprised, trusts what has happened thus far and plays their originally marked _Shadow_ card as expected.

Hypothetical:
￼
<img width="1266" alt="Patch Finesse Hypothetical" src="https://user-images.githubusercontent.com/32303453/86555849-9ac95a80-bf1f-11ea-9c82-817cb5e9105d.png">

- pianoblook initiates a _Backlit Shadow Finesse_ through this strictly suboptimal clue
- ADrone can trust that a _SF_ is likely occurring, but realizes he must play a _Penumbral Finesse_ to Patch the Shadow
- Huxley marked his _Shadow_ on Slot 3. He recognizes what’s going on and confidently plays it.
- after y1 blindplays, fishcat will initially assume that this was a _bluff_ on his own g23. When Huxley suddenly blind plays from _Slot 3_, everything is completely understood.

NOTES:

- This is **Illegal** in the _Reverse SF_ form. Bob should instead assume that he himself must have the _Shadow_ (through _Occam's Razor_)

- It is (sadly) **Illegal** to attempt a _Penumbra Bluff_ (in which the Target doesn't actually exist at all!) Unfortunately, this would cause the subsequent player to simply believe that this was a _Shadow Finesse_ on their own Slot One.

**Comment by Zamiell** [comment]
wait until shadow finesse is accepted before posting more issues about shadow finesse

**Comment by Zamiell** [comment]
too complicated
