### ISSUE TITLE
new convention proposal: the unusual 1/premonition finesse

### ISSUE THREAD

**Issue by joelwool2** [Zamiell/hanabi-conventions#317]
This isn't a hypen-ated convention, just something of my own creation.
Original convention name: the unusual 1. If applied to more (such as suit fillers) could be called: premonition finesse

The convention states that if a player (Bob) receives a color play clue on a single card at the start of the game when another player (Cathy) has the same color 1 and at least 1 other playable 1 (not in finesse position, clandestine position or flawed by duplication), and that no other player has the suit in finesse position, that it's illogical to receive the clue as a play clue for a single 1 (since a 1's clue to Cathy would be more efficient). Instead, it's a color clue for the 2 of the suit, and they have a finesse position card that plays and is useful to the team (if it's the first clue of the game, it's a 1 in the finesse position). After receiving the clue, it's expected that someone on the team clue the primary 1's holder (Cathy) about their ones, or that the receiver of the clue play their slot 1 to confirm the nature of the clue (or else Cathy will be surprised when her finesse fails by playing slot 1). This is more efficient than a bluff on Bob's hand to get the 1 played for a couple reasons: 1) Bob's 2 will become playable soon after Cathy is clued 1's, and it's often better to have a card clued which can be played immediately than another bluffed card clued but unplayable; 2) It allows Bob to act as he sees fit rather than forced to play his first position slot as a bluff or finesse normally would; 3) Sometimes there's no suitable card to bluff. Subsequently, after receiving the clue Bob will typically clue Cathy about her 1's and save slot 1 as a play for later. This clue is a 2 for 1 clue, and it allows for flexibility on the receiver of the clue. 

In it's simplest form, Alice clues Bob green touching 1 card. Bob looks at Cathy's hand, it contains a red 1 and a green 1 not in finesse position. Since it makes little sense to receive a green clue for a single playable 1 when there's a superior 1's clue to Cathy, Bob looks around the table and sees no evidence of this being a finesse on his green 2 in any other player's hand. Bob now knows that this must be the unusual 1, and knows his card is actually green 2, and his first position card is a useful 1. Bob clues Cathy 1's to let Cathy know she wasn't being finessed. Later on, Bob can either play slot 1 or make another clue if it suits him more. If Bob thinks the team might benefit more by playing his finessed card, he can do that instead (revealing the unusual 1) to allow Cathy to give a clue to Alice's hand. However, this sequence can have an alternative meaning, which I will reveal as the advanced caveat later on.

I imagine this convention could also be applied to games including up to 6 players, and not always be necessary for the player being clued to be the next player to act. The only requisite is that the player who has the multiple 1's not be forced to act next (or else they will react by playing their slot 1 as a finesse). Presumably, if Alice clues Frank green, touching a single green 2 when he has a slot position 1 that's useful to the team, and another player (Donald) has a green 1, and another 1 in their hand where the 1's aren't in finesse or clandestine position, it will be apparent what the nature of the clue really is, and Bob will not be fooled into playing his slot 1 thinking he was finessed. It will be the responsibility of either Bob or Cathy, however, to clue 1's to Donald before it's too late (or Donald, not in on the gag, will play slot 1). 

I also imagine there could be more applications of this type of clue as well, such as cluing color to a player, when another as of yet unclued player has many playing cards in that suit which aren't in finesse position (but are easily cluable). The intention of which would then suggest they have a useful card in the suit and a card in finesse position which is beneficial to the team. It will be the responsibility of the team to clue that as of yet unclued other player that they actually have the suit which was color clued not in finesse position (unless the clued player first reveals the situation by playing his finesse position card). This type of play could be called a premonition finesse, since there is a player completely in the dark, but has a hand in which a clue of the color suit would be very tempting.

An example of how premonition finesse could be applied: stacks are at 2. Bob has y3xxp4x Cathy has xxp3p5x. Alice clues Bob purple, touching just the 4. Since Cathy has a very good purple clue to her hand, Bob recognizes this as a premonition finesse, telling him he has purple 4 and a card in finesse position useful to the team. Option #1 Bob next clues Cathy purple to reveal the premonition to Cathy. Option #2, Bob next plays his finesse position card revealing to Cathy a premonition finesse. Bob might choose this play because Cathy must use their team's clue on an important clue to Alice's hand. However, option #2 can have an alternative meaning (explained in advanced caveat). 

A final caveat for the truly advanced premonition finesse. If a player is clued a premonition finesse, and plays their slot 1 card (revealing the premonition), and then nobody clues the dark player, assuming there isn't any apparent reason for this (clue starved and said player must give a clue that only they can give), it is a sign that the dark player should start their cards beginning from the chop position (the most likely natural clue spot in their hand that wasn't already in finesse position), and continue in natural order as if given a finesse that began at the chop. Example: the stacks are at 2, Alice clues Bob purple, touching just 1 card. Bob's hand is y3xxp4x, he plays his finesse position card revealing the premonition finesse. Cathy's hand is xxxp5p3. Cathy knows that she is the holder of the purple suit. Since she wasn't given a clarification clue, she assumes her suit starts with her chop (the most likely natural clue destination) and plays her chop position card. Assuming no more clarifying clues, she will continue playing the suit from her chop once Bob plays the purple 4. You might ask yourself, why the chop position? why not make it position 2 or position 3? The reason is more apparent in multiple player games. In such games, players will often start with fewer than 5 cards (or have their last card already chop moved). In order for the premonition finesse to operate, the dark player not being clued must hold either 1's or a suit of superior quality not in finesse position, and also have the suit or 1's playable from their natural order if clued. If that player begins the game with only 3 cards, then surely their suit must start from the 3rd slot since xp5p3 or p5xp3 are the only possiblities. Same thing for an unusual 1's clue, since they aren't in the finesse position, it must start from the 3rd slot as either 1x1 or x11. If they have 4 cards, the suit would only start from the 2nd slot if it were xp3p5x (given the previous example with a premonition finesse). It's twice as likely to start from the 4th slot as either xxp5p3 or xp5xp3. 

Some examples where premonition finesse are best play when using the caveat: https://hanabi.live/replay/239028/3 yellow to Sephiroth, touching just the y3. Sephiroth notices yellow 1 and 2 in easy clue position and assumes premonition finesse. Sephiroth plays b1 revealing the premonition finesse since Asaeler needs no correction. Joelwool also doesn't correct, and Asaeler will now begin playing from the chop due to advanced caveat and will continue playing from chop unless told otherwise. https://hanabi.live/replay/241739/9 correction to Blueberry plays p2, now Joelwool clues purple to Dmoney, touching just the p5. Dmoney plays b1 revealing premonition, MarcusKahlsen knows that his purples start from the chop (only possibility), and begins them there and will continue playing from chop unless told otherwise. https://hanabi.live/replay/240775 change starting player to Dmoney. Dmoney clues Sheamol green, touching just the g2. Sheamol sees Bonja's hand and no other g1, so he assumes unusual 1 and plays w1 from slot 1. Nobody corrects, so Bonja will play his 1's beginning from the chop until told otherwise (should play twice and stop since unusual 1's only promise two 1's, and having three 1's would mean they were in finesse position).

**Comment by Zamiell** [comment]
unfortunately, this convention doesn't work very well in a general sense.

1) we often distribute 1s between different hands for tempo reasons, and we wouldn't want to cause a (fake) premonition finesse when we do so.

2) these types of situations like this are common when we perform finesses with a lie component. the "premonition" component is a key attribute that allows the clue receiver to determine that a lie is occurring. this is powerful/flexible, since it allows the clue receiver to give the fix clue (as opposed to the clue giver; it is the clue givers responsibility to fix in the conventional sense)

these two situations come to mind, but they are possibly other situations that conflict

**Comment by NoMercyO** [comment]
Instructing Bob his slot 1 is an unknown playable but that he cannot play immediate and must give a play clue risks a non trivial chance of him duplicating his slot 1. This is a known problem we encounter with 5pulls, so it is not a deal breaker, but certainly an issue.

We would have to disable finesses with a lie component to account for this, as it is effectively a finesse with a lie, plus a self bluff, except you must lose tempo to immediately heal the lie. Not a big fan. 

Suboptimality is a very cool game space to explore so i applaud the effort. However it is also a space that accounts for high chance of human error. Whether or not something is actually suboptimal is very influenced by hidden information and deceptively complex. Our history with priority finesses is a testament to that.

One simple example: 
Bob has g1
Cathy has g1 and r1
Donald has r1 and p1.

Alice should clue Bob green. This should not be a premonition finesse as Cathy's better 1s clue is of no interest to the team from Alice's perspective.

**Comment by Zamiell** [comment]
will close for now
