### ISSUE TITLE
OOP Bluff is still confusing

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-conventions#320]
https://hanabi.live/replay/246054/3 This is illegal, right? (it doesn't satisfy any of a,b,c). However, Kakashi read this part and thought, therefore, the move is legal:
> Valid Out-of-Position Bluffs take precedence over Layered Finesses. In other words, if Alice does a valid Out-of-Position Bluff on Cathy, it would be natural for Cathy to think that this is a Layered Finesse, since Alice is not in Bluff Seat for Cathy. However, Cathy must pay close attention and see that because of the very specific situation, an Out-of-Position Bluff was legal, which means that Cathy should not continue to blind-play cards from her hand. (This is a common mistake.)

How to improve this? Maybe we need a section on *Illegal OOP Bluffs* to *really* make sure people  understand it all? The section would go through the process of a,b,c with common examples where noobs want to do an illegal oop bluff

**Comment by padiwik** [comment]
yes, exactly.. *even though* someone else might think he isn't allowed to because kakashi has "two blind plays" and defering is bad here

**Comment by Zamiell** [comment]
```
* Since valid *Out-of-Position Bluffs* are so rare, it is important to remember that:
  * Valid *Out-of-Position Bluffs* take precedence over *Known Bluffs*. In other words, if Bob can see that an *OOP Bluff* could be valid (meaning it meets one of the 3 criteria above), then Bob should not blind-play anything as a *Known Bluff*.
  * Valid *Out-of-Position Bluffs* take precedence over *Layered Finesses*. In other words, if Cathy can see that an *OOP Bluff* could be valid (meaning it meets one of the 3 criteria above), then Cathy should not continue to blind-play cards as a *Layered Finesse*. (This is a common mistake.)
```
