### ISSUE TITLE
Delete / Revamp Trash Double Bluff

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#323]
The following are moves that stand out to me in that they are not used very often (or at all). Please speak up if you actively use this move, or you have seen this move used by other players.

* Trash Double Bluff

Previous thread: https://github.com/Zamiell/hanabi-conventions/issues/196

**Comment by padiwik** [comment]
> Trash Double Bluff

uh then why was it so contentious whether or not to keep it for the Unnecessary Principles PR?

**Comment by Zamiell** [comment]
is it contentious?

**Comment by NoMercyO** [comment]
Ive never seen trash double bluff, as currently written. It's a classic Jeff convention, not sure if i would ever think of it unless i was in a game with him :P.  

I would replace it with the 1's trash double bluff, (ie Libster clue). It is totally artificial but easier and useful.

**Comment by florian-5f3759df** [comment]
> is it contentious?

It was a little bit contentious.

We had multiple versions of the proposal of the situation where: Alice clues trash to Donald, Bob plays into Trash Bluff (with a card that could have been clued directly), and now if Cathy doesn't do anything Donald will A) CM a trash card or B) trash push a trash card / one-away from playable card.

The final PR just always lets Cathy play slot 1 as a cancellation blind play. The first alternate version we considered was: eject in case A, follow the trash push conventions for case B (so discharge for trash, slot 1 for one-away). So Cathy just responds as if known trash was clued to Donald. And alternate 2 considered version was like that, but blind play in case A, instead of eject.

We decided on the PR also for backwards compatibility with the trash double bluff, since it basically expands it. And also it was decently simple to explain the cancellation blind play, and slot 1 is the most common slot you want to get. But alternate 2 was a very close alternative, since it's more powerful in situations where it can get three cards (the Trash Bluff Trash Push Finesse is now basically impossible in <5 players).

**Comment by Dr-Kakashi** [comment]
Bear with me in talking about Unnecessary Advanced Convention situations.  It may sound off-topic, but it directly relates to keeping Trash Double Bluffs or not.

**Unknown Trash Situation**
Alice Clues an Unknown Trash on Donald
Bob must Discharge
Donald will either push or chop move depending on the location of trash
If Cathy sees that the push or cm is "good," she should do nothing.
If Cathy can see that there is nothing to push nor cm, how should Cathy blind play to tell Donald to not cm nor push?

1. Cathy plays slot 1, this preserves Trash Double Bluff

2. Cathy plays slot 2 as an ejection, this will allow for situations to do 3 for 1.  
- For example, Bob plays slot 1 that's g1.  
- Cathy can see g2 is being pushed and G2 could've easily been directly play clued.  
- Cathy blind plays slot 1
- Donald can see two unrelated cards have played, but he also understands that it's just a continuation.
- If his push was bad, then Cathy would've just ejected.
- Donald pushes to play g2.  

3. Cathy reverts to the known trash convention.  This would lead to some interesting situations, such as 2 discharges in a row.  However, Florian and I agree that the majority of playable cards are in either slot 1 or slot 2.  

Option #2 and #3 will delete trash double bluffs.

**Comment by pianoblook** [comment]
@Dr-Kakashi If y'all like to keep consistency in what Ejections/Discharges signal, then it feels really weird to have an Ejection be called for when the target card is actually trash. That's currently very clearly defined as Discharge territory.

(and if anyone's interested, I've made a [guide](https://docs.google.com/document/d/1n3IjeFZo-VFEf5KSsk9mu_hDjPFvooZjXEuiYk0FSu4/edit) in an attempt to simplify + demystify all the various Es&Ds. Just take a glance at the basic logic model to see what I'm pushing for - it's even got a picture :P )

**Comment by aliblong** [comment]
> I would replace it with the 1's trash double bluff, (ie Libster clue). It is totally artificial but easier and useful.

The 1s part isn't actually important, it's just touching any known trash off-chop to get a double bluff. I would even call it "trash double bluff", and frame this as a simplification and improvement to the existing trash double bluff.

**Comment by florian-5f3759df** [comment]
> The 1s part isn't actually important, it's just touching any known trash off-chop to get a double bluff.

In what situations does the double bluff interpretation override the Bad Chop Move Ejection?

**Comment by aliblong** [comment]
Bad Chop Move Ejection would become obsolete, which is probably for the best, since double bluff is a way more relevant and useful thing IME.

**Comment by Zamiell** [comment]
> I would even call it "trash double bluff", and frame this as a simplification and improvement to the existing trash double bluff.

agreed, which is also the main reason why i started this thread in the first place

**Comment by Zamiell** [comment]
> Bad Chop Move Ejection would become obsolete, which is probably for the best, since double bluff is a way more relevant and useful thing IME.

agreed. but of course note that BCME with 5s stays the same

**Comment by iamwhoiamhahaha** [comment]
> In what situations does the double bluff interpretation override the Bad Chop Move Ejection?

If the next player has a playable card on slot 1 you play slot 1 as a *Trash Double Bluff* and if they don't you play slot 2 as a *Bad Chop Move Ejection*.

see https://github.com/Zamiell/hanabi-conventions/issues/334

**Comment by pianoblook** [comment]
^ that seems super clear. And if the clued (known) Trash was on chop, then it'd be a _Trash Push Discharge_.

@Zamiell you've mentioned something called a "Double Ignition" which basically sounds like a Trash Double Bluff: A 'burn' clue when a _play_ clue was obvious. I dug up the Discord convo:
(and here's the game link: https://hanab.live/replay/223768/40)
<img width="618" alt="Screen Shot 2020-08-04 at 9 30 32 PM" src="https://user-images.githubusercontent.com/32303453/89361624-bd26d300-d699-11ea-8205-cf96b21cfd14.png">

What if Trash Double Bluff just functioned like that, as an "Ignition"? 

- IF Bob sees that Alice could/should have just clued a playable on slot 1 in the late game, but chooses to clue random trash, then it's a _Double Bluff_.

- IF Bob doesn't see any playables on slot 1 to clue, then he can either:
(A) _Eject_ as a BCME (see #334 )
(B) Discharge as a TPD

**Comment by Zamiell** [comment]
double ignition is a better name because cluing unplayable trash does not induce any misplays and/or wrong notes to be written, which are the core tenants of what a bluff is

**Comment by robertos** [comment]
It's the remix to Ignition
(I can't not make that joke)

**Comment by pianoblook** [comment]
Interesting case from tonight: what clue would be clearest for piano to give to get both 5s to play?

https://hanab.live/replay/262412/37

-conventionally it would be cluing 1 to piper as a TDB right?

-piano went with the _Double Ignition_ (touching color to the trash 3) mostly for science. 

This felt relevant to the discussion so figured I'd share!

How neat would it be if when '3s' to piper (one off chop) **isn't** met with an _Ejection_ (and instead just a _Finesse_, piper can know that it therefore can't be a bad chop move? Would it still be justifiable to assume a _Double Bluff_ and play slot 1 as well? Or would it revert to just, like, an _Unnecessary Trash Pull Finesse_?

**Comment by florian-5f3759df** [comment]
> If the next player has a playable card on slot 1 you play slot 1 as a _Trash Double Bluff_ and if they don't you play slot 2 as a _Bad Chop Move Ejection_.
>
 
This would conflict with the current (implied) definition of an Unnecessary Bad Chop Move Ejection, since that calls for slots 2 and 1. Which might be a decent trade-off, since double bluffs are much more common, but just noting that in the current interpretation Cathy's slot 1 might already be gotten if Bob ejects.

**Comment by aliblong** [comment]
Another day, another term for blind-playing finesse position.

>cluing unplayable trash does not induce any misplays and/or wrong notes to be written, which are the core tenants [sic] of what a bluff is

1. Not playing _would_ cause a wrong note to be written - namely, chop move notes.
2. By that logic, we ought to rename known priority bluff using a 5.

**Comment by Zamiell** [comment]
> By that logic, we ought to rename known priority bluff using a 5.

i dont think so. a priority bluff is not known in 90% of situations. thus, in the same number of cases when it is known, it doesn't make sense to call it something different - you just call it a known priority bluff.

this is dissimilar to double ignitions, because it is usually (or maybe even "almost always") known to be an ignition, with no consequence of not playing.

> Not playing would cause a wrong note to be written - namely, chop move notes.

sometimes yes, but most of the time, no.
double ignition is generally performed at the end of the game where there are no more chop movable cards.
e.g. look at pianos screenshot
e.g. https://hanab.live/replay/259372

**Comment by aliblong** [comment]
I don't disagree with any of that, but if anything, this all seems like a reason to do one of the following:
1. Use a more general term than "bluff" or "ignition"; in the document I was writing with Raz before he disappeared, I introduced the terminology of "blind call" to represent the general concept of asking someone to play an unclued card, which constitutes a superset of "finesse" and "bluff" (and now this).
2. Redefine bluff to mean "blind play a card not matching the clue that was given".

I don't think introducing a totally new term for what essentially amounts to "play consecutive finesse positions" (or as I term it, "blind call position") will help players to understand that that is the prescription for this particular instance of "artificial clue calling for a blind play".

**Comment by pianoblook** [comment]
^ that's interesting; a 'blindcall' (or just blindplay? I hear that term often already) being something technically different than a "bluff". e.g. 5ces, UTDS, 5-Double-Pulls, Double Ignitions, Unnecessary Trash Stuff...all these things *call* for a blindplay but aren't really being " bluffed " in the same sense as in a traditional Bluff.

----

In regards to distinguishing between a _BCME_ and _Trash Double Bluff_ in the late game, I'll float one more idea: 
| in LATE GAME, if a player gives a random _Trash_ clue it's almost certainly calling for some blindplay(s).
| If the player chooses to touch trash in such a way that it is exactly one-off-chop (and they had free choice in this decision), they are calling for a _Bad Chop Move Ejection_
| If the Trash is elsewhere (>1 away from chop), **or** just retouches a known trash card, this is calling for a _Double Ignition_

**Comment by Zamiell** [comment]
@lib

to expand on what i wrote in my last post, i think the benefit of having a dedicated term is that it makes a clear distinction between:

1) a consequential blind-play (e.g. one that if you don't do, your teammate will go on to bomb the clued card on his next turn, or more generally, a *blind-play necessary for information synchronization*)

2) an inconsequential blind-play (e.g. one that doesn't prove anything and is globally known, information is already synchronized)

so it sounds like you don't agree that there is an important / relevant distinction between these two things.
however, to me, these do feel like fundamentally different things. calling them a word that is a superset of a bluff doesn't seem quite right. i'll try to think of more arguments why.

as a group, we can explicitly acknowledge this distinction by adding the word "Known" to the name, and naming the move a "Trash Known Double Bluff".
however, that is quite verbose. as everybody knows by now, i prefer short & distinct names for conventions (the shorter the better), which is why i prefer "Double Ignition" over 'Trash Known Double Bluff".

**Comment by pianoblook** [comment]
To my above point re: distinction between Double Bluff and Other-Stuff (BCME / U. Trash Pull), check out #336

**Comment by iamwhoiamhahaha** [comment]
#### Terminology: Trash Double Bluff vs. Double Ignition
* I'm fine with changing the name to *(Trash) Double Ignition*.

#### Interpretation: Trash Double Bluff vs. Unnecessary Bad Chop Move Ejection
* TDB takes priority over UBCME if Cathy has a playable card on *Finessed Position* in my opinion, unless Bob can see other good *Double Bluff/Ignition* targets.

#### Double Ignition vs. Color Double Bluff
* CDB is the convention I proposed three months ago. https://github.com/Zamiell/hanabi-conventions/issues/205
* The proposal has been stale since I haven't played hanabi for the past 50 days. I hope it can be reopened if I find other good examples recently.
* *Double Ignition* and *Color Double Bluff* (or *Color Double Ignition*) are basically the same things. The former targets an unplayable trash while the latter targets an unplayable card.

**Comment by aliblong** [comment]
> so it sounds like you don't agree that there is an important / relevant distinction between these two things.
however, to me, these do feel like fundamentally different things. naming an ignition to be a word that is a superset of a bluff doesn't seem quite right. i'll try to think of more arguments why.

> as a group, we can explicitly acknowledge this distinction by adding the word "Known" to the name, and naming the move a "Trash Known Double Bluff".

I'm on board with distinguishing these concepts, and I'd greatly prefer to use descriptive nomenclature like "trash known double bluff", rather than a random term like "ignition".

**Comment by Zamiell** [comment]
its too long though

**Comment by pianoblook** [comment]
Ignition seems especially succinct because it actually describes what the move is intending:

By declining to give an obvious play clue and instead (re)cluing random trash, Alice is essentially forcing Bob into a _Positional Blindplay_ to 'get' Cathy/Donald's matching fresh card.

TBH calling it a Bluff feels much less intuitive

**Comment by aliblong** [comment]
> thats too long though

The name "trash known double bluff" is too long? I reject that on two bases: a) it's five syllables, come on; and b) many existing convention names have similar word and syllable counts.

> Ignition seems especially succinct because it actually describes what the move is intending

That would be a fair argument if there were a strong existing story around usage of the term "ignition" for what has otherwise been termed "known bluff". But that word only appears in the context of a recently added convention. If you're really going to call this "double ignition", you'd better create that story. I personally prefer using existing terminology, especially as it applies to really obvious and intuitive concepts of "blind play cards".

**Comment by pianoblook** [comment]
TBF the 'story' is similar to that of _Blaze Discards_: playing a card as a way to elucidate something else. The same metaphor was intentionally used for Shadows too, fwiw (as the Target 'casting light and creating a Shadow'). 

Speaking from my experience as a teacher and as someone who is still relatively new in learning all these conventions, I think having a memorable + conceptually-relevant name can be really great for retention

**Comment by aliblong** [comment]
> TBF the 'story' is similar to that of Blaze Discards: playing a card as a way to elucidate something else. The same metaphor was intentionally used for Shadows too, fwiw (as the Target 'casting light and creating a Shadow').

*To be fair*, literally none of that is in the reference document. The only relevant occurrence of `ignite` is this one:

> This is called a Blaze Discard because it "ignites" the next player's hand to fix the problem.

I think introducing the term "ignite" in the middle of a subsection at the tail end of the doc does not a strong story make. If the changeset derived from this issue involves the term "ignite", it had better include a reorganization of the relevant conventions in such a way that clearly puts forth a compelling story around what ignition is, and why this term deserves extra space in your brain.

**Comment by padiwik** [comment]
I thought *Ignition* can be any slot (based on what Bob sees, e.g. with the Blaze Discard and Shadow Finesse) and is a way for Bob to demonstrate to Cathy what to do. Isn't this different from the convention described here, a slot 1 play known to all but the clue receiver?

**Comment by pianoblook** [comment]
it's essentially the same @padiwik : Bob is blindplaying first-finesse-position in order to get someone else to also blindplay first-finesse-position.

but I'm gunna duck out of this discussion and let the pros talk haha. I'm just a sucker for good metaphors :P

**Comment by Zamiell** [comment]
the blind-play from a blaze discard is not formally given a name, but i suppose we could call that an ignition if we wanted.
in any case, the ignition from a blaze discard seems to be a separate mechanic from the ignition proposed in the "#2" section in my previous post, because it has to communicate slot number to prevent a misplay.

it sounds like we agree to not change the name of the known priority bluff.
correct me if i am wrong, but besides known priority bluff, the only other "inconsequential blind-plays" in our convention framework seem to be the ones from unnecessary moves (e.g. unnecessary trash push).
in the "unnecessary" section, they are simple described as "blind-plays", so if we adopt ignition as a name, we would also update that section, e.g.:

> Depending on the situation, the "extra" thing will be an additional blind-play or a *Chop Move*.

-->

> Depending on the situation, the "extra" thing will be an *Ignition* (blind-play) or a *Chop Move*.

**Comment by Zamiell** [comment]
> if there were a strong existing story around usage of the term "ignition" for what has otherwise been termed "known bluff"

i don't think you are framing this properly.
a *Known Bluff* is a move that is almost exactly like a *Bluff*, and would otherwise be a *Bluff*, if only a tiny thing was changed.

e.g.

* Alice plays blue 2, which did not have priority.
* Bob tries to play blue 3, but it was instead a red 1. Bob now knows that he was *Priority Bluffed*.

vs

* Alice plays blue 2, which did not have priority.
* Bob has negative 3 on his entire hand. There is no other explanation for why Alice would do that, so Bob knows that Alice is doing a *Known Priority Bluff*.

we probably agree that it does not make sense to rename this *Known Bluff* to a separate name. It's clearly still a type of *Bluff*. it directly flows from the *Bluff*.

but that doesn't map on to double ignition. you could change a ton of stuff about the situation, and it wouldn't be a *Bluff* no matter what you changed. rather, it is a brand new move that is arbitrarily calling for two blind-plays and, unlike all other forms of *Bluffs*, has nothing to do with the playability of the card that is clued.

perhaps a simpler way to phrase this concept:
- the two blind-plays are unrelated to the clue that was given (like a *Double Bluff*) **and**
- the two blind-plays are unrelated to the playability of the clued card (unlike a *Double Bluff*).

**Comment by Zamiell** [comment]
re: kakashi i dont think that is relevant for my purposes here because double ignition is about cluing known trash

sounds like the consensus so far is that we delete jeff's trash double bluff and implement double ignition

**Ignition**

* An *Ignition* is a type of move that makes someone blind-play a card from their *Finesse Position*.
* An *Ignition* is different from a *Finesse* and a *Bluff* because the blind-play from an *Ignition* is:
  * unrelated to the clue that was given
    * e.g. It doesn't "match", which is unlike a *Finesse*, but like a *Bluff*.
  * and unrelated to the *playability* of the clued card
    * e.g. Nothing needs to be "proved" to the player who got clued, which is unlike a *Finesse*, and unlike a *Bluff*.
* Currently, there is only one type of clue that can cause an *Ignition*; see below.

### **Double Ignition**

* Near the end of the game, there are two common situations where a player will clue one or more known trash cards.

#### Late-Game Burn Clues

* Sometimes, players give meaningless *Burn Clues* to known trash cards in order to avoid drawing more cards. (This is rare, because they would normally re-clue a playable card, but sometimes it is done.)
* However, players can know that a *Burn Clue* is impossible if they see that a normal *Play Clue* could have been given instead.

#### Late-Game Trash Chop Moves

* Sometimes, players perform a *Trash Chop Move* by cluing known trash in another player's hand.
* However, players can know that *Trash Chop Move* is impossible if they can determine that they are no cards left to *Chop Move* (meaning that all of the cards are accounted for, or all of the remaining cards could be given a direct *Play Clue* or a direct *Save Clue*).

#### Meaning

* In these situations, a clue that touches known trash communicates a *Double Ignition*, meaning that the next two players should blind-play their *Finesse Position* card.
* For the players playing into a *Double Ignition*, it is pretty easy to see what is going on, because they can see the playable *Finesse Position* card of the other person.

**Comment by fpvandoorn** [comment]
Please add that a trash push / trash push finesse takes priority over double ignition.

**Comment by Zamiell** [comment]
ok, updated

**Comment by pianoblook** [comment]
It feels like a bummer that this seems to 'turn off' a few opportunities for getting off-finesse cards in tricky lategame situations.

1. It seems like there'd still be room for late game _BTCMEs_ if there is free choice in what trash to clue but they choose to 'seemingly chop-move' a *single* card. This would also keep the possibility of it being an _Unnecessary_ Ejection (if Cathy can see that the Ejected card could have been clued directly), thus still netting two cards.

> In other words, what's the prescribed way of getting a slot 2 from Bob + a slot 1 from Cathy?

2. Similarly, what if Alice once again has plenty of trash to choose from but specifically clues a card on Chop? It seems like this should also indicate something extra: a _Trash Push Discharge_.

**Comment by Zamiell** [comment]
> It seems like there'd still be room for late game BTCMEs if there is free choice in what trash to clue but they choose to 'seemingly chop-move' a single card.

agree.

> Similarly, what if Alice once again has plenty of trash to choose from but specifically clues a card on Chop? It seems like this should also indicate something extra: a Trash Push Discharge.

agree.

both of these things are niche though, so probably doesn't need to / shouldn't be documented

**Comment by satoshinakamotoVoltage** [comment]
mehdimehrabi1372@yahoo.com
BTCME.COM 
For Me
