### ISSUE TITLE
Pink Trash Clues

### ISSUE THREAD

**Issue by NoMercyO** [Zamiell/hanabi-conventions#324]
From the Doc: 

https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/Pink.md#trash-pushes-in-pink

Why?
Why not for trash finesse and trash bluffs?

Propose either: a) streamline trash clues with pink (removing this clause imo is better than not). or
b) Be more verbose: Add a sentance stating this trash push exception does not apply to trash finesse and trash bluff.

**Comment by NoMercyO** [comment]
To clarify i am mainly suggesting B: add documentation without change. However the point stands that this exception seems less easy to intuit.

**Comment by Zamiell** [comment]
it hasn't really been an issue before now because:
- trash pushes are generally performed with a number 1 clue or a number 2 clue
- trash finesses & trash bluffs are generally performed with a color clue

**Comment by NoMercyO** [comment]
Trash finesses are often performed with a number clue. Color clues run the risk of being UTD. the simple examples of 1's occurred right here: 

Example that prompted this:
https://hanab.live/replay/250646/18

**Comment by Zamiell** [comment]
```
### Trash Finesses & Trash Bluffs in Pink

* When a *Trash Finesse* or a *Trash Bluff* happens in a normal variant, if more than one card is touched, then all of the touched cards are known to be trash.
* When a Trash Finesse* or a *Trash Bluff* happens in a variant with a pink suit, if more than one card is touched, it is possible that only the focused card was trash, and that the other cards touched are useful / critical pink cards.
* In this situation, after discarding the focus of the *Trash Finesse* or *Trash Bluff*, the player should then hold on to the other touched cards.
```
