### ISSUE TITLE
Clarification for elimination finesse

### ISSUE THREAD

**Issue by ZakisanGithub** [Zamiell/hanabi-conventions#326]
The second sentence of the first bullet point of https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-elimination-finesse seems to state that it is impossible to have elimination notes on your finesse position, which isn't true. (Or am I misunderstanding?) 

Also can a clarification on the following be added? (padi 02.06.2020 "if someone is finessed for a card and has elim notes for that card in their entire hand, which slot should they play?" Zamiel 02.06.2020 "oldest", https://discordapp.com/channels/140016142600241152/456214043351580674/717407657086025740 ) Part of the "some experience" group thinks that it is newest, since I recall a previous review and another today in which I was the only one thinking it should be oldest rather than newest. 

I think both of these can be clarified at once by stating that we apply this convention even when the finesse position has elimination notes, since it acknowledges that this case  is actually possible at the same time.

**Comment by Zamiell** [comment]
i rewrote the section and edited some of the surrounding sections as well.

let me know if further clarification needs to happen.
