### ISSUE TITLE
Some new mobile UI issues

### ISSUE THREAD

**Issue by MicahSE** [Zamiell/hanabi-conventions#328]
After the last patch, some things don't work on mobile:
--Pressing and holding to view someone's hand as they see it
--Double Tapping to add notes to cards.

I think that's it from what I've seen, but there may be others

**Comment by padiwik** [comment]
Please open issues about the website at https://github.com/Zamiel/hanabi-live , as this repository is for the conventions.

Anyways, it's already known (https://github.com/Zamiell/hanabi-live/issues/1553) and will be fixed soon!
