### ISSUE TITLE
Introducing levels for Pink specific conventions

### ISSUE THREAD

**Issue by PabloJ-1** [Zamiell/hanabi-conventions#329]
So, most variant specific conventions are quite short. However, this is not the case for Pink.
I think it would be easier to separate the Pink specific conventions in at least two levels. It would mainly be just a reorganisation, and possible renaming, of the current subsections:

1.Basic Pink Principles
2.Finesses and Other Special Moves
3.Edge Cases

The main goal of a level subdivision is to make every level playable, meaning it is consistent with itself.

I really don't know how to organize them in the best way, however, I think the first level should be the basics, enough to beat Pink (5 Suits). In my opinion this can be done even at _master_ level 7, just before bluffs. The rest should introduce the remaining conventions, which are more useful on harder variants (I'm thinking of you Special Mix).

Let me try at least:

**1. Basic Pink Principles**. The idea is to keep it simple. For example:

_Good Touch Principle_

_Pink Tempo Clues_

_The Pink Prompt Rank Exception_

_Pink Promise_

(Maybe put one way to fix Pink? I think The Pink Fix Promise (PFP) is the easiest one)

**2. Pink Fixes**. I would give all the remaining fixes here, meaning

__The Pink Fix Clue (on 1's)_

_The Pink Fix Promise (PFP)_

_Remaining 1's After All the 1's Have Been Played_

_Pink Fix Clues (in general)_

along with the beloved:

_The Pink Play Clue Lie (with multiple 1's)_

_The Pink Play Clue Lie (with a mismatched Play Clue that touches other cards)_

_No Order Chop Moves_

**3. Bubblegums and edge cases**

This would containt the remaining convetions.

Of course, there can be a rethinking on how to spread the levels/conventions, for example to introduce three or four things at a time (this way, we can  get a more linear growth on fixes and plays.

Looking to see if people have opinions about how to split it into levels.

**Comment by Zamiell** [comment]
i updated the pink.md file, you can tell me if you have any further suggestions
