### ISSUE TITLE
Convention Proposal: Bad TCCM Ejection

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#330]
I believe we've designated bad cm's as ejections in the ejection part of the doc.  This is one that hasn't been defined yet

Basically you do a tempo clue that causes a cm to a trash card.  Once this happens the immediate next player to react should eject.  This will cover both forward and reverse situations.  Though the reverse situation should be with the matching card

Forward:
Board: R1 is down
Cathy has a previously clued R5 and R2 from a 5CE earlier in the game
Alice clue's Cathy 2 as a tempo clue.
Bob can see that it is a tempo clue and additionally Cathy will cm a Y1 on chop as a TCCM.
Bob ejects and plays B1
Cathy can see that Bob ejects and undo's the cm.

Reverse:
![2020-08-01_17-31-16](https://user-images.githubusercontent.com/48993588/89112789-06b6ba00-d41d-11ea-8a24-ddac7bb8d980.png)

Flo clue's Kim 2 cm the Y1
Kim plays R2
Kakashi can see the Y1 will cm so he ejects and plays R3
Kim will have to retroactively undo the cm.

**Comment by pianoblook** [comment]
This is currently open in #311

**Comment by iamwhoiamhahaha** [comment]
it was proposed a year ago lol

**Comment by Dr-Kakashi** [comment]
geez too much going on, alright I'll close this.
