### ISSUE TITLE
Order Chop Move Change

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#332]
* Previously, for the purposes of the *Order Chop Move*, "identical" ones are defined as 1's that have an equal amount of positive and negative clues.
* Now, for the purposes of the *Order Chop Move*, "identical" ones are defined as 1's that have an equal amount of positive clues. Negative clues are ignored.
* This is the way that we already play AFAIK.

**Comment by aliblong** [comment]
Pair this with a proposal that in dual-colour variants, only 1s whose true identity is globally known are excluded from being used for order chop move.

**Comment by Zamiell** [comment]
i put them in separate threads because they are separate conventions

**Comment by aliblong** [comment]
The proposal in this issue in isolation is incompatible with dual-colour variants, so the appropriate fix, #331, is part of an atomic transition to another working state. Therefore, they should be part of the same issue and discussion and commit.

**Comment by Zamiell** [comment]
sure
