### ISSUE TITLE
Bad Chop Move Ejection Example

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#334]
piano gives 1 to piper

https://hanabi.live/replay/261318/38

![Bad Chop Move Ejection](https://user-images.githubusercontent.com/50160641/89360325-abc1e300-d6fa-11ea-9bb4-e369f17b7859.png)

IAMJEFF sees that Kakashi doesn't have a playable card on slot 1 so it is a signal as an *Ejection* instead of a *Double Bluff*

**Comment by Zamiell** [comment]
do a PR

**Comment by Zamiell** [comment]
> i think i need to remove the Bad Chop Move Ejection example
as it isn't very good
> - Now, it's IAMJEFF's turn. If he does nothing, piper would *Chop Move* the blue 2 as a *Trash Chop Move*.
>
> this is not true. there are no cards left to chop move
> furthermore, the clue looks like a double ignition, so you would need to start talking about Double Ignition in the example
> maybe you can take a modified screenshot of a hypothetical where g3 is the highest stack and all the 1's are played, or something along those lines?
> or i could just delete it

**Comment by iamwhoiamhahaha** [comment]
Guess we can redefine BCME and add a new rule:
If it looks like a double ignition and your next player doesn't have a playable or one-away card on their finessed position, you should eject.

**Comment by Zamiell** [comment]
> Guess we can redefine BCME and add a new rule:
If it looks like a double ignition and your next player doesn't have a playable or one-away card on their finesse position, you should eject.

that sounds like it would conflict with a trash push discharge, or a trash pull discharge.
anyways, this is not the place for such discussion. can you open a new issue then?

**Comment by Zamiell** [comment]
i will close this for now until we can find a better example

**Comment by hanabirnoob** [comment]
blob:https://imgur.com/0a858629-c456-4020-bc24-735507a6049c

**Comment by iamwhoiamhahaha** [comment]
looks like a double ignition

**Comment by hanabirnoob** [comment]
If it was double ignition, Fey would clue 2s to Ksortson.

**Comment by hanabirnoob** [comment]
This one seems to be a better example.

https://i.imgur.com/F4OyreH.png

**Comment by pianoblook** [comment]
In your previous example blue should technically work as a BCME if you go by stricter one-off-chop definition (since there plenty of cleaner double ignitions, most notably being **recluing known trash**. 

But it's still a strange example because a trash push on Bob would be simpler.

In the newer example that might be misinterpreted as a somehow-necessary trash finesse on Bob. 3s would be much cleaner since all 3s are kt and mountainrog will have their whole hand available as kt as well.

**Comment by iamwhoiamhahaha** [comment]
this might be a good example

https://hanabi.live/replay/385838#22
