### ISSUE TITLE
5 Pull Double Finesse Example

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#335]
Kakashi gives 5 to piano as a *5 Pull Double Finesse*

https://hanabi.live/replay/261283/3

![5 pull double finesse](https://user-images.githubusercontent.com/50160641/89360708-df513d00-d6fb-11ea-8bb1-7a45af54445f.png)

piper sees that the pulled card is two-away, it is a signal as a *5 Number Discharge*. However, he also sees IAMJEFF has a connecting card on *Finessed Position*; therefore, the pulled card should be treated as a one-away card, and it is exactly a rarely seen *5 Pull Double Finesse*

**Comment by Zamiell** [comment]
do you wanna do a pull request?

**Comment by iamwhoiamhahaha** [comment]
don't know how to do it

**Comment by Zamiell** [comment]
click "fork" in the top right hand corner to fork the repository
then edit your repository to include the screenshot in the images folder and the new MD page in the example folder
etc.
then click "create pull request"

**Comment by Zamiell** [comment]
done
