### ISSUE TITLE
Unnecessary Trash Pull: 2 Examples

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#336]
There's currently lots of discussion around Trash Double Bluffs, and these are neat examples of Something-Else. 

https://hanab.live/replay/262412/37

-piano can give blue to piper as a _TCM_

First, piper's perspective:
1. If Jeff _Ejects_, piper would know this was a BCM
2. If Jeff doesn't do anything, piper knows this was indeed a TCM - and, furthermore, a _Trash Pull_

- Jeff sees piano could have just directly clued y4, so this is Unnecessary
- Jeff blindplays
- piper plays slot 5
-------
That reminds me, here's another example of an in-game attempt at a UTPull:
https://hanab.live/replay/255711/43

**Comment by Zamiell** [comment]
the https://github.com/Zamiell/hanabi-conventions/blob/master/examples/Unnecessary_Principles.md page is already quite long. 

how much value do we get by adding a UTPull example to the bottom of this page

**Comment by pianoblook** [comment]
There's currently no reference to Unnecessary Trash Pulls in the doc so maybe?

Currently, I believe something like this would always be assumed to be a Double Ignition, which is a shame

**Comment by Zamiell** [comment]
> piano can give blue to piper as a TCM

the example you typed out does not make sense - it is not a trash chop move because there are no cards left to chop move

thus, this is a double ignition

**Comment by pianoblook** [comment]
Bleh, that's just such a shame..

like in this example, piano would be declining to reclue trash (y3) *and* purposefully chose to clue 1-off chop. You're right that there's "no cards left to chop move" but that's the same logic for Trash Pulls in the first place

**Comment by Zamiell** [comment]
> like in this example, piano would be declining to reclue trash (y3) 

jeff does not know that, he could have just drawn a y4

**Comment by pianoblook** [comment]
> > like in this example, piano would be declining to reclue trash (y3)
> 
> jeff does not know that, he could have just drawn a y4

If Jeff plays slot 1, piper needs to discern what that means: he sees piano could have Double Ignited w/ Known Trash
From Jeff's seat, he sees that piano could have clued 1s to piper

This is a good example of when both players can cleanly determine that a clearer Double Ignition was not chosen

**Comment by Zamiell** [comment]
ok, but that seems like it is playing with fire.

just imagine going into a review where Alice does a double ignition, and then Bob explains that because the clue was slightly suboptimal in the tiniest way, he interpreted it as an unnecessary trash pull instead, and thats why they lost the game

**Comment by Zamiell** [comment]
i want to add examples to the doc that are super clear

>  he sees piano could have Double Ignited w/ Known Trash
From Jeff's perspective, he sees that piano could have clued 1s to piper but instead chose to clue one off chop

adding an example that is predicated on this is going to make the eyes of whoever is reading it glaze over
