### ISSUE TITLE
Delete Patch Finesse (Weak Form) section

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#337]
In the 0.1% of games that *Patch Finesses* successfully occur, they are *Hidden Form*. Even more rarely, they can also be *Strong Form*. But they are never *Hidden Form*.

Thus, its time to delete this section from the doc. I do not expect that this will be controversial in any way.

Additionally, I should probably rename "Strong Form" to "Known Form", so that we just have a "Hidden Form" and a "Known Form".

**Comment by pianoblook** [comment]
As per the current Discord discussion, I think the "Strong Form" needs to be more clearly defined. Could there be a couple specific Requirements, similar to _Out of Position Bluff_?

here's a stab:
> A _Patch Finesse_ should only be assumed if it is "Known" that a Fix is not intended or possible. Therefore, one of the following conditions must be true:
1. All remaining copies of the card that could be used to _Patch_ are visible
2. No clues remain to Fix, or only one clue remains and a Fix will result in losing something critical
3. _Blindplaying_ is currently being called for anyway this turn, from an apparently Finesse or Bluff

**Comment by Zamiell** [comment]
im in favor of deleting it instead of bloating the doc with more specific requirement.
see the other thread

**Comment by NoMercyO** [comment]
The distinction between strong as weak is tenuous at best. Yes it is a little easier so resolve if there is only one possible card being targeted, so no-one assumes they have the second copy, but the is not a lot of practical distinction between a player playing finesse position for patching, or for  assuming second copy. 

So certainly remove this version and compress to two forms.
