### ISSUE TITLE
unnecessary trash push or chop move

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#344]
![image](https://user-images.githubusercontent.com/5511220/90466111-ebb39d80-e0de-11ea-867f-e753d273d5d4.png)

who knows

**Comment by NoMercyO** [comment]
I dont think this is a trash push. A trash push requires that the focus of the clue is known trash at the point the clue is given. So while it might be suspected as trash from context, this clue looks like a trash finesse/bluff and micerang must play slot 1 to expose the 'lie'. So if the hypothetical is that micerang plays the r1: the response should be for Zamiel to treat his blue cards as trash, and chopmove the y4 if he sees the trash bluff was unneccessary (which it wouldve been).
He should not play his new chop as r2 as a trash push finesse. 

This would apply even if the blue clue ONLY touches the chop. it still chop moves y4 as an unnecessary trash bluff. relegating trash push finesse to be lower priority and only valid if the trash bluff interpretation is impossible.

**Comment by Zamiell** [comment]
```
* If **unknown trash** is used as a clue target that is on-chop, but the clue **also** touched other trash cards in the hand that were not on the chop, then the "extra" thing is a *Chop Move* (e.g. a *Trash Chop Move*), similar to the previous section.
* If **unknown trash** is used as a clue target that is on-chop and it only touches one card (or all the cards touched were also on chop), then the "extra" thing is a blind-play (e.g. a *Trash Push*).
```

**Comment by sjdrodge** [comment]
I've been playing this as an unnecessary trash push. The logic is that Bob blind plays because the trash is unknown, and Cathy blind plays because once it's known trash, and the move was unnecessary, everything matches for a typical trash push (the focused now-known trash was on chop when the clue was given). However, I refuse to believe this edge case warrants inclusion in the docs given how many others have been excluded on the basis of rarity and complexity.

**Comment by pianoblook** [comment]
Whatever the answer, this ambiguity should be generalized. Here's my take:

> - If an _Unnecessary Trash Move_ is used, usually the clued player must either _Chop Move, Trash Push_, or _Trash Pull_.
> - Rarely, if two or more Trash cards are newly touched and one was on chop, it would then be _Ambiguous_ whether this was a _Trash Push_ or _Trash Chop Move_.
> - We agree that in this situation, Bob should assume [???????]
