### ISSUE TITLE
Known priority bluff: conflicting information + self-finesses

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-conventions#35]
According to new conventions, known priority bluffs are allowed. However, in "expert strategies" section, known priority bluffs are stated as illegal.

Also, I noticed that there is no section describing self-finesses (they're not in beginner and intermediate strategies either) and nuances that go with it. Perhaps "reverse finesse" section could be renamed "reverse finesse and self-finesse"?

**Comment by Zamiell** [comment]
>According to new conventions, known priority bluffs are allowed. However, in "expert strategies" section, known priority bluffs are stated as illegal.

fixed, thanks

**Comment by Zamiell** [comment]
```
Also, I noticed that there is no section describing self-finesses (they're not in beginner and intermediate strategies either)
```
ok, i added a new section
