### ISSUE TITLE
Convention Proposal(s): the Mirage Bluff & Lucidity

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#350]
Now that Shadows are in, I'm excited to introduce this super flexible _Bluff_ form (The Mirage) and it's most powerful extension (Lucidities, which are usually 4-for-1s). As a quick TL;DR, these are 'false' Shadows, as a _Lie with a Fix_. The Mirage = requires a Fix Clue, while Lucidity = 'fixes' the lie with a specific kind of blindplay from Cathy. Anyway, enjoy!

## The Mirage Bluff ##

* If a clue is given to the immediate next player that looks like a _Self Shadow Finesse_, it’s Illegal them to do anything except immediately play their Shadow. 
* This ‘forced’ play means that the clued card can actually be a _Lie with a Fix_. 
* Therefore, as long as everything else about the (apparent) Shadow Finesse is valid, any single card of the matching suit can be clued to initiate the blindplay. 
* This is called a Mirage Bluff (because the clued player is currently ‘hallucinating’ that their touched card is playable) .
> Although the clued card itself is a Lie, all other elements of the ‘hallucinated’ Shadow are True: so the Target card is now globally known. 
* The team must obviously remedy the Lie before the player’s next turn. 

At face value, this would end up just being a very confusing 3-for-2. The Fix Clue MUST be able to give sufficient extra value or else this is Illegal to perform. Therefore, we [will need to] agree that one of the following conditions MUST be true about the Fix Clue:

> 1. It touches 1+ new card of the rank they thought it was (a Fix via negative info) 
> 2. It cleanly touches 1+ additional critical cards (usually 5s) in their hand 
> 3. (rarely) It cleanly touches 2+ additional useful cards in their hand 
> 4. (rarely) It unambiguously gets a real copy of the Miraged card elsewhere (a Heal Clue) 

----------

**In-Game Mirage Examples:**
Example 1: Fix with 1s 

<img width="1127" alt="fixed with 1" src="https://user-images.githubusercontent.com/32303453/91661350-72865400-eaa9-11ea-9ef9-6a9ae758a71e.png">

- Yellow to Smith gets r1 to play as a SSF
- st1ngr3y (or anyone else) clues 1 to Smith, Fixing the y4.
- Overall, this is a 4 for 2.

Example 2: A better Fix with 1s

![fixedwith1](https://user-images.githubusercontent.com/32303453/91661359-7f0aac80-eaa9-11ea-8555-67491aaef72c.png)

- Green to hanabilawyer01 gets r1 to play as a SSF
- Although a Fix is called for, paulcd can delay: they can 3-bluff sjdrodge, since g2 is now known.
- efaust can now clue 1s to hanabilawyer01, fixing everything.
- Overall, this is a 4-for-2 that also greatly helps get other cards

Example 3: Fix with a Heal Clue

<img width="1241" alt="another 1 fix" src="https://user-images.githubusercontent.com/32303453/91661381-a2cdf280-eaa9-11ea-9072-8db508c11483.png">

- Blue to TheDaniMan gets p1 to play
- Although a 1s Fix is called for eventually, Mishka is free to delay, e.g. to do a finesse on y4
- joelwool now can fix in two ways: 1 to TheDaniMan or 1/blue to Mishka!
- if joel clues Mishka’s 1, Dani will know a Mirage occurred (once Markus doesn’t Discharge)
- a 5CE might be a cleaner line, but from Fey’s perspective it is pretty valuable to get the b4 touched - and it even leaves the 5 unclued for future 5CEs (e.g.  to get the y2 if need be)!

-----------------

…But what if there doesn’t even need to be a Fix clue at all? 

## The Lucidity (Bluff, 5CE, UTD, and Sarcastic) ## 

* If a _Mirage Bluff_ is initiated but does not meet any of the above conditions (at the time it was given), this must mean that, somehow, **no Fix Clue is intended**  
* Instead, a _Lucidity_ is being called for (to “elucidate” the original Mirage). 
* A Lucidity is carried out in one of several ways, depending on the true identity of the originally touched card: 

> If the Miraged (clued) card is…
> 	•	One-away: the original Target card is immediately discarded, as a Sarcastic Lucidity. 
> 	•	Two-away: the next player plays their First Finesse Position as a Lucidity Bluff.  
> 	•	5 (not one-away): the next player plays their Second Finesse Position as a Lucidity 5CE. 
> 	•	Trash: the next player plays their Third Finesse Position as a Lucidity UTD.

**In Game Lucidity Examples**

Example 1: Lucidity Bluff (4 for 1)

<img width="1263" alt="Perfect" src="https://user-images.githubusercontent.com/32303453/91661528-a4e48100-eaaa-11ea-8104-57435b2dcee6.png">

- Blue to Lamguin gets g1 to play as a SSF
- crossproduct now sees that a Fix would not be sufficiently valuable (only touching an extra 3)
- He therefore plays y1 as a Lucidity Bluff
- Lamguin is surprised, but marks their blue card as b34.

Example 2: Lucidity Bluff in Up & Down (4 for 1)

<img width="1228" alt="Lucidity Bluff" src="https://user-images.githubusercontent.com/32303453/91661554-cfced500-eaaa-11ea-9540-9d482f128835.png">

- Teal to Aharon gets p1 to play, assuming they must have tS/5
- spjtheater sees that a Fix must not have been intended, and that this cannot be a Sarcastic Lucidity (since Seven has the 4, not the matching 2).
- therefore, spjtheater blindplays First Finesse Position.
-SevenSpirits now knows they must have exactly t4 (not t2).

Example 3: Lucidity Ejection (4-for-1)

<img width="1138" alt="Rainbow LCE" src="https://user-images.githubusercontent.com/32303453/91661576-e83eef80-eaaa-11ea-8033-4d2cde33f121.png">

- Pink to pour1out4bga gets r1 to play as pink 2’s Shadow 
- shocksteel sees that a Fix must not have been intended: there were no other 5s in the hand
- Therefore, shocksteel blindplays Second Finesse Position as a Lucidity Color Ejection
- pour1out4bga now knows they must have pink or multi 5.
- Overall, this was a 4-for-1, although like any rainbow-pink bluff the 2 and 5 are known as only pink or rainbow.

Example 4: Sarcastic Lucidity (2-for-1 + free discard)

<img width="1247" alt="fixed with GD" src="https://user-images.githubusercontent.com/32303453/91665654-2f39de80-eac5-11ea-925d-c373023547cb.png">

- Green to hanabihavefun gets r1 to play as a SSF
- NathanPain plays normally, e.g. cluing 2 to zumpywumpy
- Jadon sees that a Fix is not intended. They discard their known g2 as a Sarcastic Lucidity.
- Overall, this is a clean 2-for-1 (to be fair, a UTD w/ purple to NathanPain is also good)

Example 5: Self-Lucidity (ignore the dupe risk)

<img width="1248" alt="simple dupe risk" src="https://user-images.githubusercontent.com/32303453/91661641-5b486600-eaab-11ea-9f70-689ebec8a6f5.png">

- Blue to cagdas gets p1 to play as a SSF
- egerdm now knows b2 is in their slot 1. But they also know they must perform a _Lucidity 5CE_
- egerdm plays their **new** _Second Finesse Position_, which is r1.

**Comment by pianoblook** [comment]
<img width="1255" alt="Screen Shot 2020-09-07 at 12 59 18 AM" src="https://user-images.githubusercontent.com/32303453/92419450-a57cb780-f13b-11ea-9716-b8127f17ab52.png">

A perfect example of Condition 4 from last night:
- kimbi plays _Third Finesse Position_, since it must be a Self Shadow
- piano can immediately clue 1s to piper. This satisfies condition 4:
> (rarely) It unambiguously gets a real copy of the Miraged card elsewhere (a Heal Clue)

**Comment by timotree3** [comment]
> Example 2: A better Fix with 1s
>
>    Green to hanabilawyer01 gets r1 to play as a SSF
>    Although a Fix is called for, paulcd can delay: they can 3-bluff sjdrodge, since g2 is now known.
>    efaust can now clue 1s to hanabilawyer01, fixing everything.
>    Overall, this is a 4-for-2 that also greatly helps get other cards

That's cool. At first I thought that paulcd can't 3-bluff because it would just look like a fix but it sounds like because only four kinds of fixes are allowed for mirage bluffs, it actually works.

**Comment by timotree3** [comment]
How can the player who is supposed to play into a Lucidity know that there isn't a plan to fix the Mirage Bluff by cluing a copy of the Miraged card in their hand?

**Comment by pianoblook** [comment]
If the next player doesn't see a "legal Fix", they must assume a Lucidity. 

That means they must blindplay something if they don't see any of the following: (A) a fix via negative info to Bob; (B) a Heal Clue to any player (like the screenshot from today); (C) a sufficiently valuable _Fix_ clue (e.g. if there was another unclued 5 in kimbi's hand in that screenshot); or, rarely, (D) that the fake-Shadow's target will be _Gentleman's Discarded_ (which btw they themselves could be holding!)

**Comment by timotree3** [comment]
So it's impossible to give a Mirage Bluff where the only valid fix is a heal clue to Cathy?

**Comment by pianoblook** [comment]
Yep, because Cathy needs to assume she's being called to do a _Lucidity_ blindplay. Otherwise none of this really makes much sense - it's basically just a type of Double Bluff.

**Comment by pianoblook** [comment]
I'm leaning towards Floriman's suggestion of just *always* assuming that no fix is needed. This would have the double-benefit of (A) being a LOT simpler to understand and remember (no more list of weird 'acceptable fix' stipulations), and (B) allow for a broader range of uses

**Comment by pianoblook** [comment]
Just posted a video explaining the updated (simplified!) version of this proposal: check it out! https://youtu.be/3TgW1JdOLVI

**Comment by Zamiell** [comment]
since shadow finesses were implemented, i've not seen anyone do them (yet)

thus, i think adding something that builds on top of shadow finesses would be premature

**Comment by Zamiell** [comment]
been playing some more hanabi recently, and *still* haven't seen any shadow finesses

let's reopen this if/when shadow finesses become more widespread
