### ISSUE TITLE
Self Color Bluffs

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#353]
![2020-09-03_06-48-00](https://user-images.githubusercontent.com/48993588/92123671-c054d200-edb1-11ea-898d-0c6dac69e789.png)

We've made this proposal in the past, but it was declined due to conflicts with patch finesses. 
We can use rank to self bluff someone, since color is a "stronger" clue than rank, I believe we should allow for self color bluffs.  
In the example I've posted here, both yellow and 3 add no information to Kakashi's hand.  
Red is clearly the superior clue.  Only 1 blind play is called for and it tells Kakashi which 2 he has.  

![2020-07-30_15-54-42](https://user-images.githubusercontent.com/48993588/92130545-b8992b80-edb9-11ea-8c66-0548a248cc0c.png)
Here's another example involving double bluffs.
So blue to kimbi is a double bluff but black to kyle isn't due to how it's defined in the doc.  
We should have both be equal double bluffs.

**Comment by Zamiell** [comment]
> We've made this proposal in the past, but it was declined due to conflicts with patch finesses.

no.
see https://github.com/Zamiell/hanabi-conventions/issues/205#issuecomment-634149813

**Comment by Dr-Kakashi** [comment]
The two example screenshots I've provided satisfy your comment.  They are not fill-ins, in hard variants, and in situations where it's more valuable to do the move over doing other clues.

**Comment by Dr-Kakashi** [comment]
> 3. in a situation where a player thinks they are screamed discarded for (but they are not actually scream discarded for), SCB as a convention has the potential to lose the game.
> 4. in a situation where a player thinks they are locked (but they are not actually locked), SCB as a convention has the potential to lose the game.

Are these two points even a valid argument against SCB's?  If a player thinks they were being screamed at, locked, or in a stall situation and did a Fill-in clue.....someone would just bomb anyways.  If the clue receiver doesn't respond, someone else on the team will respond.  

> 1. fill-in stalls are less likely in hard variants, because DDA is turned off. 

If this is the case and players are good enough to understand scream/lock/stall situation.  SCB's should just be on or at least not even be listed as explicitly illegal.

**Comment by Dr-Kakashi** [comment]
> if a player thinks they were being screamed at, and did a fill in clue, someone would bomb anyway
> like in your game, if joel for some reason thought he was in a stall situation, and filled you in
> if you dont respond, asa would bomb
> well, if you trust the clue giver, you should always blind play
> why would they waste a clue to fill in if they are clearly not in a stall situation?
> also, if they did make a mistake, and you dont respond, the next player will bomb 100%
> so you need to blind play anyway to resynch the team
> tell everyone they dont have a playable on fin and tell kimbi she was not in a stall and delete her cm or w/e

Quoted from Kimbi

**Comment by pianoblook** [comment]
Just based on the 4 arguments against it, I don't understand why this would ever be accepted as legal in 2-player. It clearly works in 2-player, which seems like pretty good evidence that it should work here as well.

For sure the payoff in 2-player is higher since there are far fewer tools to bluff/finesse stuff, but the logic (at least for cards that are being *re*-touched) seems exactly the same.

**Comment by pianoblook** [comment]
Just realized we've been using this all the time now and it's yet to ever cause any confusion.

If there's still any objection to this I'd be happy to dredge up a whole ton of in-game examples...This is probably our most-used Double Bluff strat in 3p, and it's a free way to gain tempo in the Single form too

**Comment by Zamiell** [comment]
either kakashi or piano can do a PR

**Comment by pianoblook** [comment]
@Dr-Kakashi all you! 

Is there any discussion left to be had about the details? Here are a couple last thoughts:

- I assume conventionally this should strictly be only for (a) reclued cards +(b) newly touched when 100% known (from negative info) to not be playable
- I guess SCB Ejection should be a separate convention to propose? (say a known Double SCB is initiated but Bob sees Cathy's Finesse Position would bomb if he finesses)

**Comment by Zamiell** [comment]
> I assume conventionally this should strictly be only for (a) reclued cards +(b) newly touched when 100% known (from negative info) to not be playable

yes

> I guess SCB Ejection should be a separate convention to propose?

obviously

**Comment by Dr-Kakashi** [comment]
Pull request made.  I didn't add piano's first point as it's self-evident.  Do you feel we should add those Zam?

**Comment by Zamiell** [comment]
> I didn't add piano's first point as it's self-evident.

agreed that it seems self evident

**Comment by Zamiell** [comment]
i fixed up kakashi's PR, so we can close this now
