### ISSUE TITLE
The 5 Triple Pull (and Layered Triple Pull)

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#357]
- Normally, a 5 Double Pull will only be recognizable when the card being _Chop Moved_ is currently playable.
- But what if a player opts to _5 Chop-Move_ a one-away playable, when they could have cleanly _Finessed_ it instead?
- Just like in a normal Double Pull, this calls for the next player to blind-play.
- After the initial blind-play, someone on the team is now promised to have the connecting card to the now-_Pulled_ card. - Note that this resulting _Finesse_ could even be _Layered_.

Examples: I'll work on it

**Comment by Dr-Kakashi** [comment]
https://github.com/Zamiell/hanabi-conventions/issues/121

**Comment by pianoblook** [comment]
👏
