### ISSUE TITLE
Volume button request

### ISSUE THREAD

**Issue by invarse** [Zamiell/hanabi-conventions#36]
Any chance we could get a volume button in the settings? I typically keep my volume up pretty high, both on my computer and my browser, and would love to be able to just place the hanabi volume where I want it instead of adjusting my own settings every time.

Thank you!

**Comment by Zamiell** [comment]
this repository is for our conventions. the website repository is at hanabi-live

**Comment by rogers-j** [comment]
@Zamiell there is a button to transfer an issue to another repository
