### ISSUE TITLE
update paths in links

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-conventions#360]
Some links don't contain '#' (i guess, that causes the problem or might be something else, idk), and I get error 404 trying to open it. (e.g. link in a section "bad cm ej with 5s")

**Comment by Zamiell** [comment]
which other ones

**Comment by Aigul9** [comment]
a lot of. i would do it myself if it was so easy. 
e.g. https://github.com/Zamiell/hanabi-conventions/blob/master/the-trash-finesse-strong-form

**Comment by Aigul9** [comment]
in reverse trash finesse section

**Comment by Zamiell** [comment]
it is easy https://github.com/Zamiell/hanabi-conventions/commit/7e8157f04b820202a2fce9020538b20bd8b81ef1

**Comment by Aigul9** [comment]
find all the links?

**Comment by Aigul9** [comment]
i tried to find another incorrect link after this one, and i did. => you have to check all the doc

**Comment by Zamiell** [comment]
tell me if you find any more

**Comment by padiwik** [comment]
i did a regex search and i agree there are no other mistakes like this which are missing the # character
