### ISSUE TITLE
Interesting Finesse

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#361]
I have an interesting finesse that we can maybe add to the document.

Stack: R1 played
Alice clue's Cathy Yellow focusing on Y3
Bob's hand: Y1 - X - X - X - G1
Green 1 was touched previously with 1's
Cathy's hand: X - Y3 - Y2 - X - X

Bob can see that, if he plays the 1 clued in his hand as a prompt as Y1, Cathy will immediately bomb Y3 as Y2.
Bob can also see that Y2 is touched, so it's impossible for him to have Y2 on Finesse position.  
Thus, Bob is in a known bluff situation and immediately blind plays.  Y1 is played.

Cathy finds this surprising because if the focus was Y2, then Bob would've played G1 as a prompt and therefore would have to play Y1 on his next turn.  
The only reason Bob blind played was that the focused card is not Y2, but Y3.  Additionally, if the other card was Y45, Bob would've blind played G1 as Y1 thinking he has to play Y2 on his next turn.  Thus, she knows it must be Y2.  She plays slot 3 as Y2 even though the focus of the clue was Y3.  

![2020-09-22_04-17-51](https://user-images.githubusercontent.com/48993588/93875850-a01a8380-fc8a-11ea-99ab-01a7f284a1ff.png)

The example above is the finesse component.  The bluff component would be if B1 was some other card that doesn't match.

**Comment by Aigul9** [comment]
https://hanab.live/replay/179121
isn't it just a known bluff, and that's it?

**Comment by Dr-Kakashi** [comment]
Yes, but that's the bluff example.

**Comment by Zamiell** [comment]
1) probably too rare to bother putting in the doc
2) its not a great convention because information on cards is asymmetrical. thus, even if Cathy finds this surprising, Cathy could still go on to play the cards in the right order if Bob is using asymmetrical information.
