### ISSUE TITLE
Late Game Trash Double-Play Tech

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#363]
FYI I covered all this and more in video form here: https://youtu.be/knAUJT7xT_0

Some of the stuff in the video conflicts with the current form of Double Ignitions, so I'm only posting the ideas here that don't get in the way.

**NOTE** most of these *do* build off of the assumption that Unnecessary Trash Ejections/Discharges should revert to _Pushes_, as laid out in #311 . None of these would be possible otherwise, since players would simply always need to play slot 1 in response to these moves (which I think is preposterous and super limiting).

**Reverse Bad Chop Move Ejection Double Play**
_Late Game Only_ 
- Usually if Trash is clued off chop as a _Trash Chop Move_ in the Late Game, this is very strange and signals something extra.
- If the clued player sees that the following teammate has a playable card in their _First Finesse Position_, they should assume that this is some sort of  _Double Ignition_ or Unnecessary _Trash Pull/Chop Move_
> (^ ^ ^ although currently it's ALWAYS assumed to be a Double Ignition; we don't have room for distinction.)
- But what if they see that the next player's cluable+playable card is on their *_Second Finesse Position_?
- This must mean something very special: the initial clue must be trying to _Eject_ that card somehow.
- In order for the _Ejection_ to make sense, the seemingly-_Chop Moved_ card(s) must actually be trash...and this must actually be an _Unnecessary BCME_ directed at the following player.
- Therefore, the clued player should _Trash Push_ the next card to the left of the (right-most) clued Trash

In-game example: https://hanab.live/replay/296087/38

**Reverse Trash Push Discharge Double Play**
_Late Game Only_ 
- Usually if Trash is clued on chop, this is simply a _Trash Push_ - and probably Unnecessary, too, if they see that the following player has a card on their _First Finesse Position_.
- But what if they see that the next player's cluable+playable card is actually on their *_Third Finesse Position_?
- This must mean something very special: the initial clue must be trying to _Discharge_ that card somehow.
- In order for the _Discharge_ to make sense, the seemingly _Trash Pushed_ card must actually also be trash...and this must actually be an _Unnecessary Trash Push UTD_ directed at the following player.
- Therefore, the clued player should _Trash Push_ the card TWO slots to the left of the clued trash

In-game example: https://hanab.live/replay/296125/36

**Trash Pull Discharge** (w/ Unnecessary + Reverse forms)
_Late Game Only_ 
- Usually if Trash is clued to someone's slot one or two during the Late Game, this looks like a _Trash Pull_ on the clued player.
- But what if the immediate next player sees that the _Pulled_ card is also actually Trash?
- They must immediately _Discharge_ in order to signal what is happening.
- Further, if the clued player sees that this was actually an _Unnecessary_ way to get the _Discharged_ card, they should now _Trash Pull_ the card TWO slots to the right of the clued trash.
- This _Unnecessary_ form can also work in Reverse, just like the _TBCME_ and _RTPD_ Double Plays: if the clued player sees that the following hand should be getting _Discharged_, they can deduce that this is a Reverse _Unnecessary Pull Discharge_

**Comment by Zamiell** [comment]
blocked by #363 then

**Comment by pianoblook** [comment]
Wait did you mean to reference a different #number? Or is this blocking itself 🤔

**Comment by Zamiell** [comment]
oops, meant 311

**Comment by Zamiell** [comment]
no longer blocked by 311

**Comment by Zamiell** [comment]
nothing strikes me as particularly compelling here, although I will leave the issue open for now.

these look like the kind of proposals that are added to the doc, and then not used at all, and then deleted from the doc 1 year later when we find out that not 1 person in the group has ever done the move over the course of a year

**Comment by pianoblook** [comment]
2 to piper as an Unnecessary Trash Pull Discharge

<img width="1260" alt="Screen Shot 2020-12-30 at 1 01 07 AM" src="https://user-images.githubusercontent.com/32303453/103333082-9bf4c380-4a3a-11eb-8fd6-662b292cd673.png">

**Comment by Zamiell** [comment]
looks like nobody else thinks that this stuff is particularly useful, so im going to close this for spring cleaning

**Comment by iamwhoiamhahaha** [comment]
they are good tools but probably only good in the competition
