### ISSUE TITLE
Black/Dark Charm

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#364]
https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/Black.md#the-black-save-bluff

In the black save bluff, k1 is touched along with another black card.  **2+ cards**

However, what about situations where k1 is on chop and is only touched by black?  **A single card**

Alice clues cathy's chop black touching a single k1 card
What should Bob do?

Slot 1 - Cathy will mark k1 as k2 or some rainbow card (in a rainbow game)
Slot 2 - Cathy will mark k1 as k5
Slot 3 - Discharge Cathy will mark k1 as trash (in a rainbow game).  This is undefined in a game with only black.
Slot 4 - Charm slot.  

I believe Charm will work the best universally across all variants and all player counts.  

Additionally, this might work with all playable black cards.  So if for example k234 was on chop and it was clued with black as a black save.  3 or 4 would be the expected clue when they are playable on k34.

We might be able to apply this convention to dark pink and cocoa rainbow (using red saves)

**Comment by Dr-Kakashi** [comment]
Kimbi brings up a good point:

Donald has k2 or Cathy has neg 2 
Alice clue's Cathy's chop touching k1 with black
Bob can see that Cathy knows she has no k2.  Thus in this situation Bob can play slot 1, which would tell Cathy she has k1 as k34 would just be a save and k5 would be an ejection.

We can add this as an exception that only applies in situations where Cathy has enough information to know it isn't k2.

**Comment by pianoblook** [comment]
I always figured this would work as an Ejection as long as it has negative 5 or k5 is visible. When I've asked about it before people just said that Bob should play slot 1.

Feels like ejection would be good enough if (a) it's known not k5 OR (b) it touches another black card and therefore wouldn't trigger 5ce in the first place

**Comment by Dr-Kakashi** [comment]
Personally, I would like to have it be slot 1 as it's the slot with the most playable cards.  It will however add more head space. 

Situation: K1 is not down
Alice clue's Cathy's K1 on chop with black
If Bob can see Cathy has Negative 2 or can see K2 on the board, he should play slot 1. 
If not, he should Charm and play slot 4.

Situation: K1 is down
I believe in this situation everyone is expecting 2 as a 2 save, since black is a save on K34.  
Alice clue's Cathy's K2 on chop with black (There are no blocking 2's)
Bob can play slot 1. 

Situation: K2 is down
Black on chop would be a save on K4.  Everybody is expecting 3's as a play clue, assuming there are no blocking trash 3's.
Bob can play slot 1 

Situation: K3 is down
Nobody does anything as black is just a play clue on black 4.

**Comment by pianoblook** [comment]
On further reflection, I think having it be a _Charm_ is pretty clean based on #311 Signal theory.

A black clue is usually *never* trash (outside of Rainbow), so the signal can only shift between Play <--> Save. 5ce shifts it once, but Discharge would be nonsensical (Save --> Save). Therefore 3 shifts (P-S-P) makes sense.

And as for Rainbow variants, this just means you could extend this to several black-to-chop situations (e.g. 1s are down, black touching a m2 on chop = _Charm_)

**Comment by Zamiell** [comment]
> However, what about situations where k1 is on chop and is only touched by black? A single card

it simply means that k3 + k4 are visible.
no blind plays are needed to respond to the clue

**Comment by Zamiell** [comment]
closing this since kakashi isn't responding
