### ISSUE TITLE
Eureka Finesse + Priority Exception

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#366]
We agree as a community that Priority should never be done and is turned off in a situation where the player has a blind play.  
The blind play must be shown to indicate that it isn't ambiguous. 

However, I believe I've found an exception to this rule.

Board state: Y3 is down
Alice has a card clued as yellow in her hand.  Thus, it can be Y4 or Y5.  Additionally, a finesse/bluff was initiated on her, so she has a blind play.
Prior to this, one of the players discarded and drew Y5.  
Alice playing Y4 here would globally shock the team, as she could've bombed Y5.  This must mean, someone drew the Y5, which also means they can play it from slot 1.
There is also a sense of priority because Alice has a blind play to do, but deferred.  

I believe at this point, the entire team knows what's going on and should give Alice another chance to demonstrate the blind play.  

Priority Exception Aside.  This move also works when there isn't a blind play.  The only way Alice plays her yellow card is because someone drew the Y5.  So the Y5 is technically already "gotten."

Shall we also define this convention, give it a name, and put it in the doc?

**Comment by Dr-Kakashi** [comment]
**Eureka Finesse**

Normally, cards touched ancillary generally have an Unknown Identity.  
However, there are times in the game where other players can draw a card that immediately identifies the card clued in their hand.  
We can call this a Eureka moment and they can immediately play their clued card.  
The rest of the game would be globally shocked that the card plays.  The only reason why they were able to play is that they see the rest of the suit.  Thus, all those cards are called for.   

Board state: R3 is down
Alice has a card clued as red in her hand that could be R4 or R5. 
The game plays out and one of the players draws R5.
Alice will immediately play the R4 when it gets to her turn, as she now knows her red card must be R4.  

The team should not clue the R5 nor bluff out the R5 as it is now "gotten."

**Comment by Dr-Kakashi** [comment]
**Declined Eureka Finesse**

As stated in the Eureka Finesse, Alice has an urgency to immediately play her clued card to get the matching card(s).  
If she declines to do so, the table should treat her actions as if she has a play.  
Situations:
* Alice has a blind play, but blind plays instead.  The rest of the table does nothing.  
* Alice discards, the table should treat this as a scream.
* Alice plays a globally known card over the Eureka card.  This triggers priority, even if the card is a lower rank.

**Comment by florian-5f3759df** [comment]
Sometimes you can figure out the identity of a card by context. For instance, you have a green card, 1-3 is played, and a teammate went out of the way to get Bob's r4 by color instead of rank (which would have touched g4). Or your team lets Bob's g4 ride on chop. So if you now play g4 from context, without seeing g5 anywhere, how does Bob know it's from context instead of drawing g5?

**Comment by padiwik** [comment]
A humorous example of deferring a blind-play to execute a priority, from a while back: https://hanab.live/replay/200266/51

**Comment by Dr-Kakashi** [comment]
> Sometimes you can figure out the identity of a card by context. For instance, you have a green card, 1-3 is played, and a teammate went out of the way to get Bob's r4 by color instead of rank (which would have touched g4). 

In this situation, I believe the team globally knows what's going on.  The players can see that G4 was avoided.  The clue receiver understands that G4 only plays after the color clue.  Generally, in this situation, no fresh cards are drawn.  

> Or your team lets Bob's g4 ride on chop. So if you now play g4 from context, without seeing g5 anywhere, how does Bob know it's from context instead of drawing g5?

This is a bit harder for me to defend.  My main example is with cards being freshly drawn.  Though, I can see this happening

Board State: G3 is down
Alice has a clued Green card in her hand.  
The team has been busy and have been unable to clue Bob's G4.
Bob discards putting G4 on chop.  
Cathy and Donald both avoid G4.

I think in this situation, Alice should not play and just defer until Bob discards G4.

**Comment by Zamiell** [comment]
> Alice playing Y4 here would globally shock the team, as she could've bombed Y5. This must mean, someone drew the Y5, which also means they can play it from slot 1.

no, it doesn't. it means that you can write elimination notes for y5

**Comment by Zamiell** [comment]
currently, if Alice played y4, then Bob would bomb for the finesse card (even if he sees y5).
if this convention existed, then Bob would have to explicitly remember that this convention exists, or he would bomb the card.

dont you think that this is too rare to add to the document? post 3+ examples if it being used in a real game

**Comment by iamwhoiamhahaha** [comment]
I believe this is only for 2p as [*Explosive Redistribution*](https://github.com/iamwhoiamhahaha/hanabi/issues/8). I can change the name to *Eureka Finesse* if you think it's better.

**Comment by Zamiell** [comment]
closing this since kakashi isn't responding
