### ISSUE TITLE
Extend 5-Pulls [Proposal/Discussion]

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#367]
5-Pulls (and all its related tech) are ridiculously powerful, though their utility wanes as 5s themselves become closer to being playable. Instead of arbitrarily turning them off as soon as someone discards, I propose that we change the threshold so that it actually reflects the changing likelihood of 5-playability.

A few of us have had success - _especially_ in Hard Variants - keeping 5-pulls on until the team has reached a score of [2xSuits]: so 10 points in 5-suit, and 12 in 6. This averages to all 2s being played, which seems to be a reasonable 'tipping point' for when 5 play clues (and therefore 5DBs) become more likely.

Curious to hear others' thoughts on this. 10 points (in 5 Suits) might not be the optimal threshold, but it sure-as-heck feels better than tying it to 'early game'. Especially in Hard Variants, it just feels so bad to need to turn Pulls and 5NDs off on like turn 3 if someone decides to discard early

**Comment by Zamiell** [comment]
are you proposing this for hard variants or for all variants

**Comment by pianoblook** [comment]
I was assuming any variant with 5 pulls

**Comment by Zamiell** [comment]
all variants have 5 pulls. so then you want it for all variants

**Comment by pianoblook** [comment]
That said, I could see this not being as useful as true finesses until 5NDs are 'on', since 5-pulls are lvl 14 and 5ND aren't until 17. But with everything on the table, I believe extending the benefits of 5pulls/5p finesses/5NDs/etc would outweigh double bluffs

The simple way to phrase this proposal is just to say, "the team should continue prioritizing  _5 Pull_ over _Finesse_ until [the point threshold] has been reached"

----

^ and not quite all variants, right? e.g. Null, 3 Suit, No Positive Info

**Comment by Zamiell** [comment]
when i said "all variants" i meant "the set/composition of easy variants and hard variants"

**Comment by Zamiell** [comment]
this sounds like a fine proposal to me, looks like noone else cares

**Comment by Zamiell** [comment]
do a PR

**Comment by pianoblook** [comment]
@Zamiell what level would you like this at? 

This could just be an edit to 5-pulls from their introduction (level 11), or this could be a higher level alteration

**Comment by Zamiell** [comment]
the former
