### ISSUE TITLE
Play instructions while 5 Pulled

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-conventions#370]
Objective: Define how *Bluffs*, *Ejections*, *Discharges*, and *Charms* work on *5 Pulled* players.

Some have suggested that a *5 Pulled* player blind-playing *First Finesse Position* (ignoring the *5 Pulled* card) should signal an *Ejection*, *Second Finesse Position* a *Discharge*, and so on.

However, such a convention would make it impossible to give a *Bluff*/non-hidden *Finesse* to a *5 Pulled* player.

Instead, I propose the following:

- We allow *Bluffs*/non-hidden *Finesses* on *5 Pulled* players as long as both the clue giver and the blind-player (but not necessarily the clue receiver) understand that the *5 Pulled* card cannot be the promised card.
  - In other words, after Alice gives a play clue that promises Bob a blind-card, Bob should play his *5 Pulled* card if Bob knows that Alice thinks that Bob thinks it can be the promised card, otherwise *Bob* should immediately play his *First Finesse Position* as a possible *Bluff*.
- Therefore, since *First Finesse Position* would signal a *Bluff* to the clue receiver, *Second Finesse Position* is necessary to signal an *Ejection*, *Third Finesse Position* would signal a *Discharge*, and so on.

This leaves *5 Pulled* cards and *5 Pull Promise* behaving the same as clued cards and *Prompts*; a clued card does not occupy a *Finesse Position* and is prompted by a play clue only when either its holder or the clue giver thinks that it can actually be the promised card.

**Comment by Zamiell** [comment]
the value of specifying what to do in this edge case does not warrant the cost of additional text in the document

**Comment by timotree3** [comment]
Hmm. The text is pretty short and could go in Rarely Used Strategies. It seems like this is something that will come up in #convention-questions again and be met by a lack of consensus there unless we come to a consensus and document it.

**Comment by Zamiell** [comment]
it came up in #convention-questions as a purely hypothetical that had nothing to do with an actual game of hanabi

**Comment by timotree3** [comment]
It was concrete https://discordapp.com/channels/140016142600241152/456214043351580674/764267626553016361

**Comment by Zamiell** [comment]
if you look at the replay you can see that it has nothing to do with the OP

**Comment by pianoblook** [comment]
I imagine this would basically only come up in a "[Call-Out Bluff](https://github.com/Zamiell/hanabi-conventions/blob/master/misc/Bluff_Types.md)". Otherwise it almost would just be assumed as a separate finesse (e.g. via negative info on the 5-pulled card), and it's pretty clear that in this case the bluff would therefore be illegal.

So if Bob was 5-pulled for a slot 3 card, and slot 1 is unknown, there certainly are situations where he would need to blind-play other slots.

Slot 1 would be for Call-Out Bluffs, e.g.:
> Alice clues 1s to Bob, touching slot 4 and 5
> Bob plays a blue 1
> Cathy clues 5 on slot 2 as a 5-Pull
> Alice clues 1 to Cathy, touching a single blue 1

Slot 4 would be for _Ejections_

Slot 5 would be for _Discharges_

**Comment by Zamiell** [comment]
indeed, that is the explanation for why i answered slot 4 to the question in #convention-questions

**Comment by pianoblook** [comment]
Yeah it feels pretty clear cut as it stands. Changing the wording would just add more confusion

**Comment by timotree3** [comment]
> if you look at the replay you can see that it covers a situation already specified by the document

Really? Where is it specified in the document?

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-stacked-ejection

**Comment by timotree3** [comment]
That section is talking about an already finessed player which seems different from 5 Pulled

**Comment by Zamiell** [comment]
in the context of the replay, being 5 pulled or being finessed is identical, right?

**Comment by pianoblook** [comment]
fwiw I can even imagine scenarios where a Call-Out Bluff could preemptively get a Pulled card played, so just considering it as "touched" and not technically occupying a Finesse Position would be very confusing.

e.g.:
> Turn 1, Alice clues 3 1s to Cathy
> Bob clues a 5 on Alice's slot 1, _5-Pulling_ slot 2. Alice marks it as either one of three 2s or a 1
> Cathy plays a y1
> Donald clues a single 1 to Bob's - it's a dupe of one of Cathy's
> Alice must blind-play her First Finesse Position card (which was 5-pulled) *immediately* to demonstrate the bluff
> y2 successfully plays
> Bob knows this must have been a **Call Out Bluff** for Alice to play, and his 1 must be trash. He discards
> Alice has now been promised an additional _Finessed_ card from the trash bluff

**Comment by timotree3** [comment]
> in the context of the replay, being 5 pulled or being finessed is identical, right?

That's a good point. 

We can probably close this issue then. It sounds like consensus among the more experienced players here is that we should think of 5 pulled cards like cards that are finessed are far as stacked bluffs and ejections are concerned. (as opposed to a card that is already play clued)

I have some follow-up questions about stacked bluffs and ejections though that would therefore apply equally to the 5 pulled case.

Is it possible to do a stacked bluff when Bob's First Finesse Position is older than the already finessed card? The way I was thinking of it would suggest yes. It would look like a stacked ejection so I suppose not. But we do do stacked bluffs when the bluffed card is newer than the finessed card. I guess that's because newer cards have less negative information.

Which card is called for when a player who is still playing into a layered finesse and is finessed for their slot 2 is ejected? slot 1 or slot 3? I suppose slot 3 because otherwise it looks like a stacked bluff?

**Comment by pianoblook** [comment]
In my experience that signals an OOP Ejection. I've never seen such a case where Cathy is the one being clued and Bob is the one who needs to respond. Seems inadvisable

**Comment by Zamiell** [comment]
> We can probably close this issue then. It sounds like consensus among the more experienced players here is that we should think of 5 pulled cards like cards that are finessed are far as stacked bluffs and ejections are concerned. (as opposed to a card that is already play clued)

that sounds probably right

> Is it possible to do a stacked bluff when Bob's First Finesse Position is older than the already finessed card?

can you type out an alice and bob story

> I suppose slot 3 because otherwise it looks like a stacked bluff?

probably slot 3, but note that giving that clue isn't legal anyway, so discussing it in kind of pointless

**Comment by Zamiell** [comment]
closing because tim isn't responding

**Comment by timotree3** [comment]
> > Is it possible to do a stacked bluff when Bob's First Finesse Position is older than the already finessed card?
> can you type out an alice and bob story
- Alice clues 1 to Bob as a play clue on the blue 1
- Bob plays blue 1
- Cathy clues red to Donald as a play clue on the red 2, finessing Bob's newly drawn red 1.
- Donald discards.
- Alice clues purple to Cathy as a play clue on the purple 2.
- Bob knows that the purple 2 is not in fact playable, since Bob has a red 1 on exactly slot 1 and no other 1's in hand. Does Bob blind-play slot 2 as a stacked bluff?

In this example, Bob's First Finesse Position is slot 2 and Bob is finessed for a card on slot 1, which is not a typical stacked bluff scenario.

**Comment by pianoblook** [comment]
That just sounds like an [OOP Bluff](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-out-of-position-bluff-oop--the-reverse-bluff) (condition iii)

**Comment by Zamiell** [comment]
the doc says that valid stacked bluffs are when bob has "relevant negative information on their entire hand".
this does match your hypothetical (negative 1 on the entire hand).
thus, it stands to reason that Bob should play slot 2 if he thinks that Alice is not making a mistake.
however, Alice's purple clue does not work because Cathy will likely assume that her purple card is a purple 5 as a *Stacked Ejection*.

Cathy will almost certainly assume a *Stacked Ejection* because of *Frequency Bias*:
- *Stacked Ejections* are uncommon but not rare
- *Stacked Bluffs* in general are extremely rare
- and more to the point, I've *never* seen this specific hypothetical
