### ISSUE TITLE
Changing blaze discards to make the n finesse position call for the n+1 finesse position for the next player

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-conventions#371]
Hi,
Alice has a known r1
Bob's hand: y1-x-x-x
Alice discards her r1.
Bob plays his first slot: y1.

It's now Cathy's turn. Cathy is on a weird spot, Alice promessed Bob he got a r1 in second slot and he is going to bomb AND Alice discarded a playable card which isn't in someone else hand.
What could it mean?

The reason I find is that Cathy got a copy of r1 that Alice wants to be played immediately. That mean, it should be in slot 2 because Cathy got neg r1 in slot 1 from the play of Bob.

So here is the full example:
Alice has a known r1
Bob's hand: y1-x-x-x
Cathy's hand: x-r1-x-x
Alice discards her r1.
Bob sees there is another r1 to clue, but clueing it will be pretty inneficient. 
He could assumes a 'blaze discard' and plays his slot 2, but conventionnally, since there is three copies of r1, he must assume it was a normal gentleman's discard.
So he must have the third copy of r1. He plays his slot 1.
Cathy now know nothing make sense. Furthermore, Cathy got negative r1 in her slot 1 because Bob tried to play r1, and Cathy has r1 because Alice discarded it, so it's a 'xxxx discard', and she plays her slot 2.

(There is lots of others cases like if Cathy has a bluff too, if Bob got r1 in slot 3, if Cathy saw both r1 which are both inneficient to clue... But let's talk about that 'basic' first)

**Comment by Zamiell** [comment]
read https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-blaze-discard-a-gentlemans-discard-or-baton-discard-that-promises-the-wrong-slot

**Comment by Romain672** [comment]
I did, that's different (from what was said in general chat).
r1 is in 3 copies, and Bob was forced to choose between a Gentleman's discard or a Blaze discard. And apparently Gentleman's discard has priority.
Yeah I will add it.

**Comment by Zamiell** [comment]
this move is too edge case to warrant adding

**Comment by Romain672** [comment]
Is it?
It's only any 1 in Alice's hand globally known.
Any playable in Bob's hand.
And one card in Cathy's hand which is the same of Alice, and Alice waited to play her card on purpose to try to gentleman's discard it next turn and get a 2for1.
And no other copy of that card visible (but only to be simple).

**Comment by Zamiell** [comment]
link 3 or more replays where this would be the optimal move (no hypotheticals)

**Comment by Romain672** [comment]
But then from that reasonning, blaze discards doesn't seems logical.
The n finesse's position of B should promesse the n+1 finesse's position of C.
I know that's confusing. But that seems the most logical.

**Comment by Zamiell** [comment]
from what reasoning?

**Comment by Romain672** [comment]
You usually wants player to assume that more a card is leftmost, more it has chance to be playable. So moves should in priority try to get the left cards.
And for blaze discard:
 - if B plays slot 1, C has neg blaze discard in slot 1, so it's slot 2
 - from that reasonning, if B plays slot 2, C has neg blaze discard in slot 1 because one line higher. So C can assume slot 3.

I suppose you will maybe tell me that atm, getting slot 3 or 4 with blaze discards is good. And I would have no argument against that.

**Comment by Zamiell** [comment]
our conventions are not designed to be logical

**Comment by Romain672** [comment]
I know that suggestion came too late, so there is more cost of changing it.
And there is complexity cost which change that value too.
But it's one thing I would consider at your place.

And it would be aligned with what these proposition said.

**Comment by IQubic** [comment]
Hey all.
I go by Rubix in the discord. I just wanted to say, we don't need to have conventions for every single thing that could happen in a game of Hanabi. There's just too many possible plays that could be made. Also, leaving some things up to context is good too. So, unless you can provide some replays where this is the optimal move, I'm inclined to agree with @Zamiell and say that this is too much of an edge case to merit inclusion in the official docs.

**Comment by pianoblook** [comment]
I'll just take this opportunity to re-advocate for allowing normal Blaze Discards for 1s 😆 

Via normal conventions, I think this scenario is pretty funny but very edge-case. Bob "must assume" he has r1 and plays it, which tells Cathy that her actual r1 must NOT be _Finesseable_. That would be rare enough that I would probably just laugh and add "r1 en" in my hand. Don't think it should guarantee a slot 2 blind-play though, dunno

**Comment by padiwik** [comment]
> our conventions are not designed to be logical

huh? I thought a large amount of the conventions, especially kinds of finesses, *are* exactly logical. And in fact "logical" conventions ease cognitive overhead.

However, Romain's "logical" shift for the edge case of 1s makes the blaze discard convention more complicated so it is undesirable from that perspective.

**Comment by Zamiell** [comment]
the fact that some conventions are logical is an artifact of other design goals (or simply a coincidence)
read convention_goals.md

**Comment by Romain672** [comment]
But yeah we talk me and pianoblook understand both each other the other pov about blaze discard (n for n or n for n+1). And both seems similar. While mine seems slightly better, it's more complicated because the logic only apply for discards (GD) and not plays (Shadow Finesses).
Pianoblook tell me which interpretation he give for playing the slot 1 under blaze discards. And if you take that meaning as an 'extra' (=not prompted card, or the extra slot), the two differents ways became pretty similar.

> Don't think it should guarantee a slot 2 blind-play though, dunno

Bob assumes y1-r1-x-x. That's the problem with not answering.

**Comment by Romain672** [comment]
Ok, I think I got the answers I wanted.
For me:
You can either keep that issue alive while blaze discards with 1s are still ambigious.
Or close it (and reopen it/link to it when you would like to remove that ambiguity).

**Comment by Zamiell** [comment]
> (the consequences of assuming a GD for) blaze discards with 1s are still ambigious.

its not ambiguous. its defined as always assuming a GD.

> Or close it

ok, i will close it then

**Comment by Romain672** [comment]
The consequences of assuming a GD is my proposition in the first post.
It's just coherent.

What happen on the case I wrote conventionnally is that Bob is going to bomb his slot 2.
Which is fine, you just don't do that discard.
But that's why I said the consequences were undefined.
