### ISSUE TITLE
Bubblegum Wraparound Example

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#372]
5 to Carunty (touching the pink 2) as a ***Bubblegum Finesse Wraparound*** on wump's pink 1

![Bubblegum Wraparound](https://user-images.githubusercontent.com/50160641/96347734-3e590800-10d6-11eb-80bd-954dfd0bc099.png)

https://hanab.live/replay/322231

**Comment by ZakisanGithub** [comment]
5 to will.i.am (touching the pink 2) as a Bubblegum Finesse Wraparound on TheDaniMan's pink 1
![grafik](https://user-images.githubusercontent.com/68073156/96347915-5fedcb80-10a5-11eb-9cee-b703c81587f4.png)

https://hanab.live/replay/320864

**Comment by Zamiell** [comment]
do a PR

**Comment by Zamiell** [comment]
the PR doesn't have any words in the example?

**Comment by iamwhoiamhahaha** [comment]
updated

**Comment by Zamiell** [comment]
the 3rd example doesn't make sense.
why doesn't jack clue number 3 to match pink promise?

**Comment by iamwhoiamhahaha** [comment]
O yeah true. Jack sent me the example and I didn't notice that lol

**Comment by Zamiell** [comment]
ok i will delete the 3rd one
