### ISSUE TITLE
Self-Color Ejection

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#375]
* A self double bluff should always be the first interpretation when a 2+ away card (4 or 5) is used in a Self Color Bluff.  
* 3's are excluded because they can be used as 3 Bluff's.
* However, what if the next player does not have a playable on slot 1?
* In this case, the immediate next player must not have a playable on slot 1 as well, since it would cause the next player to bomb
* Due to this, the immediate next player must eject to tell the team that no other cards are promised.

Board State: G1 B1 Y1
* Bob has a G4 that was previously clued in his hand with rank
* Alice clue's Bob's 4 with Green initiating a Self Color Bluff
* Bob can look at Cathy's hand and can see that Cathy's slot 1 is not playable
* Bob can also tell that the 4 that was clued is 2+ away from being playable, so if he plays slot 1, Cathy will also play slot 1 as a Self Color Double Bluff.
* Thus, in order to prevent Cathy from bombing slot 1, it must be an ejection on Bob as a Self Color Ejection.
* Bob plays his 2nd finesse position and plays R1
* Cathy finds that this is odd as normally a 2+ away card being clued promise's at least 2 cards to play.  
* However, because Bob did not play slot 1, that means her slot 1 is not playable and this is just a Self Color Ejection.
* Cathy does nothing as no other cards are promised.

**Comment by Zamiell** [comment]
seems fine

**Comment by pianoblook** [comment]
In the spirit of "waiting-on-more-discussion", what are your thoughts on the case in which Cathy's slot 1 a one-away from playable? 

Should Bob trust that this is a Double Bluff and he has exactly the connecting card, or should the Self Ejection take precedence?

**Comment by Zamiell** [comment]
the former

**Comment by Zamiell** [comment]
and its the former because of History Bias btw

**Comment by Zamiell** [comment]
kakashi can you do a pr?

**Comment by Zamiell** [comment]
jeff did it
