### ISSUE TITLE
Proposal/Discussion: 5 Kick for Duck

### ISSUE THREAD

**Issue by vEnhance** [Zamiell/hanabi-conventions#379]
In the Duck variant, even with loaded play clues it can still be tricky to get someone to play a card from their chop, because play clues can't be easily distinguished from save clues unless they are loaded.

Because of this, our team ended up rewriting the [existing table](https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/No_Positive_Clues.md) for the Duck variant in order to allow a special move which causes the next player to blind-play their *chop card*. Zamiell suggests calling this *5 Kick* (our team called it a blast before that). This was really nice because it gave us chances to do a 2-for-1 to get a card that is hard to get to play with a 1-for-1, and is also in danger of discarding soon. It replaced 5 ejections and we rewired some other special moves to perform ejections instead.

The [table our team actually used](https://paper.dropbox.com/doc/3p-Duck-Conventions--A~SmWcCBkeq9wCUrd_9bJrOxAg-P4XXPrIXXpswWRWwS8Xk7) for the competition was rather messy and complicated, but a simple version that still works reasonably well is presented below:

| Type of Clue                              | Interpretation
| ----------------------------------------- | --------------
| Any clue focusing a one-away card         | A *Finesse*, a *Transparent Bluff*, or a *Transparent Double Bluff*
| Any clue focusing a two-or-more-away 5    | A *5 Kick* (next player blind-plays chop)
| Any clue focusing a two-or-more-away 3/4  | An *Ejection*
| A trash card                              | An *Unknown Trash Discharge*

The order of the last two rows could be interchanged or edited in various other ways. (Probably, it should really depend on the number of players if we wanted to make it really optimized, but I'm again trying to keep things simple.) Like before, the special moves may be triggered either by number or color.

We disabled charms because they are easily confused with the 5 Kick and because we rarely used them even in situations where there wouldn't have been confusion. In general, if a Kick overlapped with one of the other moves (e.g. because Bob has some touched cards), we played with the agreement that the Kick interpretation is preferred (so the clue-receiver should mark 5). We found that this did not occur very often (at least with three players).

A few examples of 5 Kick usage from the recent competition:
https://hanab.live/replay/327692/26
https://hanab.live/replay/328415/17 (although ironically in this case 5ce works equally well)
https://hanab.live/replay/327726/5 (although ironically in this case 5ce works equally well)
(I didn't attempt to search for examples of the proposed 3/4 ejection or UTD because the real table we played with used something different.)

Curious to hear other's thoughts!

**Comment by vEnhance** [comment]
Forgot to add one funny example of *non-usage* from the competition:

On https://hanab.live/replay/328415/19: since anser is giving a play clue to the chop card, vEnhance has context to believe he has no 5's in his hand (or else a 5 blast would be used).
Therefore on https://hanab.live/replay/328415/35 when vEnhance knows his clued card is either y4 or y5, he can safely rule out y5 and therefore discard the duplicated card.

All this is a long-winded way of saying that *not* using a 5 blast can often provide !5 context.

**Comment by Zamiell** [comment]
keep in mind that a blast is already defined as 4th finesse position, not chop

**Comment by Zamiell** [comment]
if you want 5th finesse position, then you would need an a-word
if you want chop, you would need to come up with a different word

**Comment by vEnhance** [comment]
> blast is already defined as 4th finesse position

Isn't it Charm for 4th finesse position? :stuck_out_tongue: 

Anyways, I think I specifically want chop rather than 5th finesse position. I'm happy to take any suggestions for words.

**Comment by Zamiell** [comment]
you're right, i am confusing charm and blast, i edited my post above.

you could call it a punch or a kick

relevant https://www.youtube.com/watch?v=tX0wCyvn3pI

**Comment by Zamiell** [comment]
as a general note, as a group we don't spend a lot of time optimizing for the duck variant.
thus, the current table is a compromise of a few different configurations with the aim of keeping things simple and easy to remember.
not that i am not opposed to further edits to the table, i am just stating this so that we can be on the same page

**Comment by Zamiell** [comment]
going to close this since it hasn't gotten much discussion and the current table is probably "good enough"
