### ISSUE TITLE
add safety charm example

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#384]
for piano

**Comment by pianoblook** [comment]
I'm just a giant derp and can't figure out how to merge forks.

I've got my own copy of it here:
https://github.com/pianoblook/hanabi-conventions/blob/master/examples/Safety_Charm

**Comment by Zamiell** [comment]
you dont merge a fork. you fork this repo (which makes your own repo), then you edit that repo, then you click on the "make pull request" button.

i think the problem is that your fork is old, e.g. on your repo homepage:
```
This branch is 13 commits ahead, 134 commits behind Zamiell:master.
```
so just do this:
delete the fork, refork it, then you will be equal to my latest commit, and then you can submit your changes as per normal

**Comment by pianoblook** [comment]
awesome, thanks

**Comment by Zamiell** [comment]
done now
