### ISSUE TITLE
Duck Tourny Dump: Convention Proposals for Multiple No Positive Information Variants

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#385]
I noticed several teams all came up with different cool strats for the Duck tournament, and we wanted to share our take on tech. We put a lot of effort into crafting a good balance of different blind-plays, with top priorities being (a) efficiently dealing with Chop cards and (b) creating Known Trash.

Identifying Trash ended up serving two powerful purposes: they can be used to easily _Shout_, and also allow for any Chop-Focused clues to be trusted as "Loaded" (since they are now early saves). Overall, this meant a mix of Discharges, Charms, Blasts, and what we called PYDCs ("Play Your Damn Chop").

#### (Low Score) Unknown Trash Blast (UTB)
- Before 10 points have been scored (in 5 suit) OR before all the 1s are down, cluing unknown trash usually can't be appropriately resolved by a *Discharge*
- Therefore if unknown trash is clued, and a _Discharge_ would just look like a 3 Discharge, the next player must *Blast*
- Note that only the focus of the clue would be promised as trash, just like in normal UTD

#### (Normal Score) Unknown Trash Discharge + Charm
- Once the_ Normal Score Phase begins, we agree to universally turn off _3 Discharges_ **and** _4 Charms_.
- Instead, cluing Unknown Trash can now trigger either a _Discharge_ or _Charm_, as follows:
- **Discharge** Form: If only one Trash is clued, **OR** if multiple cards are newly touched and only the focus is Trash
- **Charm** Form: If multiple cards are clued and they are ALL Trash, **OR** if good-touching additional cards was intentionally avoided by clue choice
Example:
> All 2s are down in a 3-player Duck game
> Alice 'quacks' at Cathy, freshly touching two 1s
> Bob _Charms_, promising to Cathy that both of the cards are trash

#### Reclue Double Bluff
- If a previously clued card is 100% known to be 2-or-more away (from a previous 5E/4C, e.g.), recluing it can often safely trigger a double bluff

#### Reclue Ejection
If a card that requires two or more blind-plays is reclued, this triggers one of two things:
- If it was already 100% known to be 2+-away, this is a Double Bluff if the following player’s Finesse is also currently playable
- If a blind-play would just make the clued player assume it’s a Single Bluff, OR if the following player’s finesse isn’t playable, this must be a _Reclue Ejection_. 
> Note this can work as a _Self Ejection_ too, similar to #375 

#### Reclue Pestilent Double-Bluff
- If a previously-known 3/4/5 is retouched in Bob’s hand and it could now be 1-away from playable, he should assume it’s a Self-Finesse/Bluff
- This might actually be a Pestilent Double-Bluff in two cases:
1. If the blind-played card matches the clued card
2. If it doesn’t match BUT the clued card is actually a 2+-away card

#### Bad Touch Bluff
- If a playable card is clued in such a way that intentionally picks up ancillary trash, this is calling for something extra.
The next player should immediately play their _First Finesse_.
- The clued player will not assume this was a _Finesse_. Once the focused card is played and seen to be something unrelated, though, they will now know that the other touched card(s) were actually Trash.
> NOTE this means you must be wary of doing Gentlemans Discards on cards that were clued in this way!

#### Layered 5 Bluff
- Bluffs using newly touched cards are usually impossible, since Cathy will simply assume it was a _True Finesse_.
- Therefore, Bob must typically continue to blind-play until he plays the true connecting card(s).
- If at any point in this _Layer_, though a FIVE is blind-played, Bob can safely stop playing; he can trust that Cathy will know this was a _Known Layered Bluff_, and that her clued card can be any one-away card. 

#### The Play Your Damn Chop (PYDC)
If a clue only retouches card(s) already 100% KNOWN as either playable OR trash, this is sending a special & unambiguous message: “Play Your Damn Chop!”
> Note that this replaces DPE or Junk Ejection (recluing Known Trash), because an extra way to unambiguously get someone's Chop card played is inherently more valuable.

**Comment by pianoblook** [comment]
This game showcases a lot of this tech, which we won in 48 turns with more than half the cards being blind-played: https://hanab.live/replay/327544

Some highlights:

https://hanab.live/replay/327544/7   Reverse PYDC on b1 (since g2 was known playable)
https://hanab.live/replay/327544/23    On-Chop 5 Ejection made possible by known trash
https://hanab.live/replay/327544/25    Double Bluff retouching the known y5
https://hanab.live/replay/327544/43    Reverse Positional Bomb UTD (lolol)

**Comment by Zamiell** [comment]
conflicts with #379

**Comment by Zamiell** [comment]
going to close this since it hasn't gotten much discussion and the current table is probably "good enough"

also see https://github.com/Zamiell/hanabi-conventions/issues/379#issuecomment-717508586
