### ISSUE TITLE
Convention Proposal: Double Positional Misplay UTD

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#386]
This is probably the spiciest late game tech I cooked up for competitions last month, and we finally got a chance to pull it off in this past tourny!

### The Double Positional Misplay UTD
(Late Game)
- If a player performs a _Double Positional Misplay_, but the next player sees that no one else has a playable card on that slot, they must be making a huge mistake or are promising something extra.
- If the next player trusts this was intentional, and they see a playable in someone's hand in a *different* slot, this is calling for a _Discharge_. 
- When this occurs, the following player (Cathy) should realize that they must have a playable card somewhere in their hand... But it can't be in the same Position that Alice played (because of the UTD) **OR** that Bob played (because Alice would otherwise have just performed a regular _Double Positional Misplay_)
- If it's still potentially ambiguous which slot Cathy should play from, she should defer to **the rightmost (remaining) position** 

Example:
> 3 Player, No Variant. 
> Zero cards remain in deck, two 5s remain.
> Bob's 5 is on slot 3, and Cathy's is on slot 5. There is no magical single clue that could reliably get both cards.
> Alice bombs her fourth slot
> Bob sees that he can't play his fourth slot, or else Cathy will bomb hers too.
> Bob _Discharges_.
> Cathy is befuddled but now knows her 5 cannot be on slots 3 or 4. 
> Cathy knows that Alice must have chosen to bomb slot 4 for a good reason. She also knows she declined to do a _Trash Pull_ to Bob, or a _Reverse Trash Ejection_ (see #363 ).
> All in all, she can comfortably trust that her 5 must be on slot 5.

In tourny example:

https://hanab.live/replay/327544/43
<img width="1018" alt="Screen Shot 2020-10-27 at 9 24 26 PM" src="https://user-images.githubusercontent.com/32303453/97379271-cd1a1180-189a-11eb-9d07-b2d74002f9c1.png">

**Comment by Zamiell** [comment]
i like this slightly better than anything in #363, but not by much
