### ISSUE TITLE
Self Color Bluff (with an Unknown Trash)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#393]
* Alice gives a color clue to Bob touching an unknown (unplayable) trash.
* Bob blind-plays slot 1 as a *Self Color Bluff*.
* Cathy blind-plays slot 3 demonstrating the clued card is trash.

**Comment by Zamiell** [comment]
show 3 examples of it being used in a real game

**Comment by pianoblook** [comment]
What if it's done on a 5? Should Cathy just blind-play as a double, or Eject?

If eject, these both could be categorized as a type of Mirage (#350 )

**Comment by iamwhoiamhahaha** [comment]
depending on if bob knows it's a two-away 5
if he does, eject; otherwise, double

**Comment by Zamiell** [comment]
this feels like a convention that won't be useful very often, e.g. one in a thousand games

closing due to lack of evidence
