### ISSUE TITLE
Interesting Safety Charm

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#397]
Typically, it is not a safety charm since it's a 2-for-1 clue. But I don't see the point Tiramisu1th refused to do the 5 pull and touched the i4 like that (a fix clue must be given next turn).

![interesting safety charm](https://user-images.githubusercontent.com/50160641/97703974-80c61000-1aec-11eb-916a-97836f375ff1.png)

https://hanab.live/replay/331095

In this situation, after playing my b1 from slot 4, sin_faith should mark his slot 2 as a 5 and slot 1 as an unplayable pink card (probably not i2 since I can blind-play i1 from slot 1 as a patch finesse if Tiramisu1th refuses to fix it next turn).

(Btw, I know Tira probably doesn't know safety charms but just wanna play my slot 4 anyway lol)

**Comment by Tiramisu1th** [comment]
read the notes I wrote on your b1 and the declined r5 again before you think I don't know safety charms

**Comment by iamwhoiamhahaha** [comment]
hahaha that clue surprised me. couldn't believe you know it lol. that's awesome

**Comment by Tiramisu1th** [comment]
Actually I didn't know that it has become an official convention, but I still use that there becoz there's no immediate risk if you missed it(we can fix with a 5 save later on when we need to)

**Comment by Zamiell** [comment]
too edge case to bother adding to the doc
