### ISSUE TITLE
Example of Unambiguous 1s Blaze Discard

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#398]
I noticed in-game that if piper immediately discarded his green card, it must be a known g1... And for it to be a known g1, I must *not* have it in a Finesseable position. Therefore, it must be unambiguously a Blaze for kimbi's copy

<img width="1237" alt="Clear example of 1s Blaze Discard" src="https://user-images.githubusercontent.com/32303453/97713298-09659180-1a96-11eb-86b2-110d31f43729.png">

**Comment by Zamiell** [comment]
what is your intent with this issue
do you want to add a new section to the doc? do you want to add a new example to the doc?

**Comment by Zamiell** [comment]
i would say no to either one.
this ss is just an example of being able to use context to override normal protocol in an edge-case, which does not need to be documented https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#context
