### ISSUE TITLE
Double Bluff Ejection & Double Bluff Ejection Finesse

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#401]
* First, look at the screenshot below. It's jack's turn.
* Here's the question: How to get level's red 2 from slot 2 and Animex's red 3 from slot 1 with only one clue?

![unnecessary ejection finesse](https://user-images.githubusercontent.com/50160641/97895589-f17c5f00-1d6e-11eb-893f-5cce7bc9caf1.png)

* I believe we all face this problem during a game where the connecting card is not on the *Finessed Position* and the players are not able to do the *Finesse*.
* So, I'm gonna come up with a new convention to deal with this situation. I'll call them ***Ejection Finesses*** and ***Unnecessary Ejections***.

### Unnecessary Double Play Ejection
* This is not a new convention. We can easily understand it from the [*Definition of Unnecessary*](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-definition-of-unnecessary).
* If Alice gives a clue touching Cathy's known playable card without touching new card, it causes Bob to blind-play his slot 2 as an *Double Play Ejection*.
* However, from Cathy's perspective, she can see that the *Double Play Ejection* was unnecessary. Therefore, she has to blind-play her slot 1 from the unnecessary.

### Double Bluff Ejection & Double Bluff Ejection Finesse
* If Cathy has a one-away card on *Finessed Position*. And if Alice does any type of *(Known) Double Bluffs* without touching brand-new cards or giving more positive information. It is quite strange.
* From Bob's perspective, if it is a *Double Bluff*, he must have the connecting card on his *Finessed Position*, leading to Cathy's one-away card.
* However, It doesn't make any sense that Alice refuses to give a direct *Play Clue* on the one-away card as a normal *Finesse*. It somehow tells Bob that his connecting card is not on *Finessed Position*. Instead, it is on *Second Finesse Position*. Therefore, Bob has to blind-play his *Second Finesse Position* as a ***Double Bluff Ejection***.
* After Bob blind-plays his *Second Finesse Position*, Cathy realized that this must be an *Ejection*. The only type of *Ejection* that matches this kind of clue is a *Double Bluff Ejection*. Therefore, she can blind-play her *Finessed Position* as a ***Double Bluff Ejection Finesse***.
* For example (screenshot):
  * Instead of giving a red clue to Animex touching the red 3 on slot 1, jack gives a 5 clue retouching the 5s (without giving new positive information and getting new cards).
  * From level's perspective, it must be a *Double Bluff* and he has a red 2 on *Finessed Position* leading to Animex's red 3.
  * But wait! That clue doesn't make sense. Why jack not just giving the red clue to Animex to do a *Finesse*? It must be trying to communicate something extra.
  * level also knows ***Double Bluff Ejection***. Therefore, he blind-plays his *Second Finessed Position*. It is a red 2 and it successfully plays.
  * Animex realizes that something weird happened that causes level to blind-play his *Second Finessed Position*. It must be a ***Double Bluff Ejection Finesse***. Therefore, he blind-plays his *Finessed Position*. It is a red 3 and it successfully plays.

**Comment by pianoblook** [comment]
This seems to sort of contradict the discussion from here: https://github.com/Zamiell/hanabi-conventions/issues/375#issuecomment-717456112

**Comment by iamwhoiamhahaha** [comment]
it doesn't conflict. sce provides positive color information

**Comment by pianoblook** [comment]
oh sorry, gotcha: just recluing with rank. neat!

**Comment by iamwhoiamhahaha** [comment]
I thought about calling it *Rank Ejection (Finesse)* but it sounds stupid lol

**Comment by Zamiell** [comment]
Unnecessary Double Play Ejection seems fine

**Comment by iamwhoiamhahaha** [comment]
I'm proposing *Double Bluff Ejection* and *Double Bluff Ejection Finesse* as new conventions. *Unnecessary Double Play Ejection* doesn't need to be added to the doc.

**Comment by Zamiell** [comment]
> I'm proposing Double Bluff Ejection and Double Bluff Ejection Finesse as new conventions. Unnecessary Double Play Ejection doesn't need to be added to the doc.

ok.

i read the example of Double Bluff Ejection above and it seems fine, but very edge-case.
post 3+ examples where this is the optimal move in a real game

**Comment by iamwhoiamhahaha** [comment]
Not sure if it's a good example: piano clues 5 to piper causing kimbi to blind-play red 4 and piper to play black 2

![dbe](https://user-images.githubusercontent.com/50160641/100570265-580f8100-330b-11eb-9a52-efe30f86dc12.png)

Btw, 5 to kimbi might also work as an *Unnecessary Double Play Ejection*

**Comment by Zamiell** [comment]
it works because kim expects green to piper?

**Comment by iamwhoiamhahaha** [comment]
yeah. but the problem is it is a variant with null suit where green clue should be treated as a color positional clue. that's why i said that it might not be a good example. but we can just imagine they were playing dark brown.

**Comment by Zamiell** [comment]
just like the other issue i closed today, this doesn't jump out as being very useful in the general sense

piano, in your competition group, how do you get slot 1 + slot 2 in the general sense

**Comment by pianoblook** [comment]
> piano, in your competition group, how do you get slot 1 + slot 2 in the general sense

Outside of late game? It's not always possible but one of the following:
- Unnecessary Bad Trash Chop Move Ejection (as a push)
- Unnecessary Chop Move, if slot 2 is chop (again, any form of CM works)
- Unnecessary Trash Pull, but obv needs context that it's not just a giant cm
- Unnecessary UTC Push

This seems like another clever (though kinda niche) tool! I bet it's not all that rare but it also might have a high chance of being mistaken as a normal double bluff

**Comment by iamwhoiamhahaha** [comment]
Honestly, I don't like this convention since it's way too confusing. The reason why I proposed was just because I wanna find a way to call 2+1 with only one clue. Guess we can close for now.
