### ISSUE TITLE
Extend 4 Charm to All Variants

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#402]
I don't remember when was the first time I proposed this convention. (One year ago maybe)
I finally saw it in a random game that someone used it.

![4 charm](https://user-images.githubusercontent.com/50160641/97946285-ec49ff00-1dc4-11eb-9385-c1a127d4fda0.png)

https://hanab.live/replay/334165/7

### My definition of 4 Charms
* If a player gives a *Play Clue* touching a 4 with either a color clue or a rank clue, and the next player can see it is not a *4 Double Bluff* and requires them to blind-play **three** (or two or more) cards to fulfill the *Finesse*, it is a signal as a *4 Charm*.
* Charms are useful in the early game and most of the 4s are three-away-from-playable at the moment. That's why we can have this convention even it kills *Triple Finesses* on the next player, since the likelihood of the latter situation is rare.

**Comment by iamwhoiamhahaha** [comment]
Just found another example 5 mins ago:

![4charm2](https://user-images.githubusercontent.com/50160641/97948133-92e4ce80-1dca-11eb-9a52-219dad1fcf43.png)

https://hanab.live/replay/334199/8

piper gives 4 to pianoblook
(but probably not a very good strategy here riding critical p2 on chop)

**Comment by pianoblook** [comment]
This just worked in-game: OOP 4 Charm

<img width="1242" alt="Screen Shot 2020-11-08 at 9 53 51 PM" src="https://user-images.githubusercontent.com/32303453/98495431-1c523180-220d-11eb-9dd3-1f39fdf11b93.png">

**Comment by iamwhoiamhahaha** [comment]
https://hanab.live/replay/339793/13

**Comment by pianoblook** [comment]
also https://hanab.live/replay/338844/1

**Comment by iamwhoiamhahaha** [comment]
Note that if Cathy has a playable card or a one-away card on their *Finessed Position*, *4 Double Bluff* takes precedence over *4 Charm*.

**Comment by Aigul9** [comment]
2 or more implies we never can do a double finesse on one player if there is a 1 on stack, and finesse is more common situation than a charm

**Comment by iamwhoiamhahaha** [comment]
that's why i prefer 3 cards

**Comment by Zamiell** [comment]
seems reasonable

**Comment by vEnhance** [comment]
How to tell apart from Safety Charm? (Sorry if I'm missing something obvious.)

**Comment by pianoblook** [comment]
@vEnhance yeah there is some overlap, but not if any of the following are true:

- rank clue on 4
- 4 is on chop
- 4 is on slot 1 / there is no possibility of a 5 in front of it
- low score phase is over

**Comment by pianoblook** [comment]
or if the clue touches multiple cards

**Comment by pianoblook** [comment]
oh, also nice that this can basically never conflict with Junk Charm either, since that also: (1) always involves touching multiple cards and (2) only works once there's trash in that suit anyway

**Comment by iamwhoiamhahaha** [comment]
*Reversed 4 Charm* if eevee clue yellow to fey

![reversed 4 charm](https://user-images.githubusercontent.com/50160641/99047914-d9f37080-25cf-11eb-88ad-d5e7191b982f.png)

i didn't do it during the game because we're playing level 11 conventions

**Comment by Zamiell** [comment]
submit PR

**Comment by timotree3** [comment]
> Reversed 4 Charm if eevee clue yellow to fey
How does that work? Fey just thinks it's yellow 1 or rainbow 1 and it violates good lie principle, right?
A 4 clue to fey looks like it would work though

**Comment by iamwhoiamhahaha** [comment]
> How does that work?

her blue 1 could be a prism 1 and the yellow card could be a prism 2, so she is supposed to play b1 first

**Comment by hakha3** [comment]
Blue 1 could be prism 1? Isnt that prism 1 is red?

**Comment by padiwik** [comment]
it was clued with 1 so it could still be prism

**Comment by padiwik** [comment]
In terms of signal shifts is it that the signal is neither a Save nor a Trash so it must be a "Play" charm? Or do we just take this as an exception to signal shifting?

**Comment by Zamiell** [comment]
its an exception

**Comment by Zamiell** [comment]
jeff did a pr
