### ISSUE TITLE
Tempo Clue Update

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#406]
> 2. When the clued card is "out of order" (meaning that it is impossible for a Prompt to get the card played)

-->

> 2. When the clued card is not a 5 and it is "out of order" (meaning that it is impossible for a Prompt to get the card played)

**Comment by padiwik** [comment]
Suppose r4 is on the stacks and Alice has two clued red cards, x x r3 r5 x. Cluing 5 to her will now be TCCM?

**Comment by Zamiell** [comment]
no it wouldn't.
but that is probably an edge case that doesn't have to be explicitly clarified

**Comment by padiwik** [comment]
So why did it change for 5's? This is the same idea of being "out of order"

**Comment by padiwik** [comment]
I guess for the situation where you single out a 5 to play (which can't be prompted)? e.g. in the Inverted 5's Tempo Clue section. Makes sense then.

**Comment by Zamiell** [comment]
> So why did it change for 5's? This is the same idea of being "out of order"

because the reason that you clue an out of order 3 is so that you can clue a 4 in someone elses hand on the next 1-2 goarounds of the table (without wrong prompting)

and that logic doesn't apply to 5s

**Comment by timotree3** [comment]
what about
> 2. When the clued card is "out of order" (meaning that it is impossible for a Prompt to get the card played) and the connecting card is visible in some player's hand

**Comment by Zamiell** [comment]
that is async, so no
