### ISSUE TITLE
1's Chop Move (Reversed)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#410]
### 1's Chop Move
* If a 1 clue is given touching a 1 which is not on *Chop*, and if all the 1's are played on the stacks or it is known to be stale, it is a signal as a *1's Chop Move*.
* The player who receives the clue should *Chop Move* their cards to the right of the 1, also keep the 1 as a reversed 1 until they realize it is a trash.
* If a 1 clue is given touching two or more 1s as a *1's Chop Move*, the reversed 1 is promised on the right-most.

This convention sort of conflicts with *Trash Chop Moves*, but it is easily to "fix" if the 1 is not a reversed 1.

**Comment by Zamiell** [comment]
fine

**Comment by Zamiell** [comment]
submit pr

**Comment by Zamiell** [comment]
jeff submitted a pr
