### ISSUE TITLE
Free choice extension on rainbow variants

### ISSUE THREAD

**Issue by mmelwen** [Zamiell/hanabi-conventions#411]
Many times you dont have the free choice to use the color a multi card was touched with, when this is the case with our current conventions everything is a prompt, I believe we can do better if we have at least 2 colors available.

I am proposing the left color to be the finesse position and the right one to be the prompt

![Clipboard-1](https://user-images.githubusercontent.com/66402571/99471611-942c0480-294f-11eb-86a1-4fbee0818289.jpg)
in this game wump's cards have been clued blue or multi  so because we cannot clue blue to Time everything wrong prompts, 
with my proposal 
red is a finesse so wump plays slot 1 and everything else promps slot 3

![Clipboard-2](https://user-images.githubusercontent.com/66402571/99472391-2a145f00-2951-11eb-97ac-4933da7e2b14.jpg)
Here rkass was clued green and my proposal is that again 
red is a finesse where yellow or blue on Time prompts

**Comment by sephirothx** [comment]
100% agree with this

I would like to add some generalization to it

Rainbow 1 is on the stack, A is the one giving the clue, B has 2 promptable rainbow cards and C has the Rainbow 3. A has a free choice among 3 colors to clue the Rainbow 3. Cluing with the leftmost color should prompt the first promptable card, the second color should prompt the second promptable card and the third color should make B play his finesse position.

In general:
- if B has **N** promptable cards and A can give the clue with free choice among **N** colors, A can prompt any of those cards
- if B has **N** promptable cards and A can give the clue with free choice among **N + 1** colors, A can prompt any of those cards or make B play finesse

**Comment by Zamiell** [comment]
use their names, letters are difficult to parse

**Comment by Zamiell** [comment]
mel, i think you did the proposal backwards.
sep has the right idea such that the left-most thing should be the default thing.
other than that, good idea.

**Comment by mmelwen** [comment]
seph wants it more general I believe, I was thinking only the leftmost prompt and the finesse but I like seph's idea.  
I believe that we should have the leftmost available for the finesse and then the prompts, to match the order of the cards on the hand I find this easier in practice, but what you are saying is making sense since if we have only 1 available clue then is prompting the leftmost clued. In practice I believe that two most important slots are the left one and then the finesse and then the other prompts.

**Comment by mmelwen** [comment]
![Clipboard-1](https://user-images.githubusercontent.com/66402571/101197603-00567a00-366b-11eb-820d-862e8e270b31.jpg)

**Comment by mmelwen** [comment]
so in the image above o2 and m4 have a red clue on them and we cannot clue red but we have the color choices
Blue, Green and the rank choice 2
the rank choice could follow the rank choice bluff convention so is for clot 1
the default blue should be slot 3 
and the bad green clue could be slot 4

**Comment by iamwhoiamhahaha** [comment]
I don't think it's a very good conventions.
* For example:
  * All the 2's are played on the stacks except red 2.
  * Bob has a rainbow 3 which is either on *Finesse Position* or has been clued.
  * Cathy has a yellow 3 and a rainbow 4 which were touched by rank clues.
  * Now Alice wants to *Prompt*/*Finesse* the rainbow card and she has *Free Choice* between red and blue.
  * In your proposal, red means a *Finesse* while blue means a *Prompt*. However, in this situation, red is slightly better since it also put negative red information on the yellow 3.

**Comment by mmelwen** [comment]
Jeff I dont follow your logic, currently you can only prompt or finesse with both clues now you have the extra choice to give a slitly worse clue and get a card you couldn't get with a 2 for 1 instead for a 1-1 on finesse, how this can be worst?

**Comment by Zamiell** [comment]
jeff is basically outlining the reason that we didn't already have this convention of years and years of playing rainbow variants, e.g. sometimes it is nice to let players just choose the color they want without anything special happening

does anyone else besides mel/sep/jeff care one way or the other?

**Comment by Jayhui-q** [comment]
I tend to agree with Jeff here about the value of negative information. I love being able to pick what color to give so as to give the most useful negative info. 

However, I see the value of negative info dropping substantially if the clued player has no clued cards. I really like this convention in this case so perhaps that could be an addendum to it?

**Comment by Zamiell** [comment]
while i see the benefit in sep's proposal, i also don't want to make things more complicated.
it is an anti-goal to squeeze every last bit of efficiency from the conventions, especially if it will cause misunderstandings and bombs.
