### ISSUE TITLE
positional null clues are illegal if they can be both a reverse positional and a reverse finesse

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#412]

**Comment by iamwhoiamhahaha** [comment]
can you type an alice&bob's story where it causes the problem?

**Comment by Zamiell** [comment]
- All 1's are played on the stacks.
- Alice clues 3 to Bob.
- Bob sees red 2 on Cathy's *Finesse Position*.
- Bob sees null 2 on Donald's slot 3.

**Comment by iamwhoiamhahaha** [comment]
i see

**Comment by iamwhoiamhahaha** [comment]
Wait if all 1s are played then it is never a null position clue for a 3 clue no?

**Comment by Zamiell** [comment]
it is unclear

**Comment by Zamiell** [comment]
this thread is irrelevant now that you can only give a positional clue to bob
