### ISSUE TITLE
Typo in reference doc

### ISSUE THREAD

**Issue by hakha3** [Zamiell/hanabi-conventions#417]
In section about UTD [here](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-unknown-trash-discharge-2-for-1-form-utd) in example it says
_Bob knows that this must be an Unknown Trash Ejection, so he blind-plays his Third Finesse Position. It is a blue 2 and it successfully plays._

Instead of _Ejection_ should be _Discharge_

**Comment by Zamiell** [comment]
can you do a pull request

**Comment by hakha3** [comment]
I dont know how

**Comment by Zamiell** [comment]
fixed, thanks
