### ISSUE TITLE
Change Trash Order Chop Move such that the focus of a Trash Finesse/Bluff is discarded first

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-conventions#419]
That is the card that is 100% sure to be trash. Also similar to [the example in the FAQ](https://github.com/Zamiell/hanabi-conventions/blob/master/misc/FAQ.md#what-is-the-reason-behind-discarding-trash-from-left-to-right), in the case of a chop focus Reverse Trash Finesse, the clue receiver would be in a crappy situation if discarding the focus of the clue could trigger a trash chop move.

**Comment by Zamiell** [comment]
the example you quote is an atypical in that it is a reverse trash finesse instead of a forward one.
i've never seen a reverse trash finesse that is simultaneously chop-focused.
post 2+ examples of this happening in a real game in order to justify adding it to the doc

**Comment by timotree3** [comment]
I wouldn't be able to. I have never seen a chop-focus reverse trash finesse, but I have experienced confusion when players have logically discarded the focus of chop-focus forward trash bluff first, only to cause unintended trash order chop moves. 

The proposed convention feels very obvious to me. Like, if we're designing the convention for what order to discard promised trash in, the only things that matter are
- Discarding the focus of a reverse trash finesse first
- Discarding the cards that are 100% trash first (as opposed to ancillary cards that are promised to be trash but haven't been demonstrated to be by a blind-play)

Both of those things will be the case for the focus of the clue

**Comment by Zamiell** [comment]
> I have experienced confusion when players have logically discarded the focus of chop-focus forward trash bluff first, only to cause unintended trash order chop moves.

by convention, a chop-focus forward forward trash bluff promises that all of the cards touched are trash.
thus, by discarding the leftmost card, you are discarding a card that is 100% trash.

so when you say
> Discarding the cards that are 100% trash first
this is confusing to me

**Comment by timotree3** [comment]
The focus of the clue is 100% trash because Bob blind-played in response to it being focused by a clue. The rest of the cards are conventionally promised to be trash, and the chance that they are not trash is equal to the chance that your teammate took a line involving a fix clue on those cards. I have been in reviews where a line like that was agreed to be the best move. Usually in order to prevent a critical discard or in order to achieve an urgent trash push.

**Comment by Zamiell** [comment]
if I understand correctly, you are proposing to make the overall complexity of the conventions higher, in return for the ability for players to be more easily lie to each other.

this doesn't sound like a good trade to me. i dont want to increase the complexity of the conventions, and i dont want to make it easier for players to lie to each other

**Comment by timotree3** [comment]
> if I understand correctly, you are proposing to make the overall complexity of the conventions higher, in return for the ability for players to be more easily lie to each other.

I mean, we do that with 1's play order, right? Bad touching 1's would be considered a lie in the same way. Anyway, no, making it easier to lie is not the only benefit, I already mentioned the main one.

**Comment by Zamiell** [comment]
> I mean, we do that with 1's play order, right? Bad touching 1's would be considered a lie in the same way.

cluing 1's with a lie is common. therefore, adding complexity in the form of a specific play order is warranted.
performing a trash bluff with a lie is not common. therefore, adding complexity in the form of a specific discard order is not warranted.

conventions like this could decrease the win rate instead of increase it, because it causes more mental overload and more chances for mistakes

**Comment by pianoblook** [comment]
> I have never seen a chop-focus reverse trash finesse

This happens from time to time as an *Unnecessary Trash Push* where the team respects finesse (on a new 1) over bluff.

I think this convention only makes sense in Pink suits, and I just double-checked to see that it's already [in the doc](https://github.com/Zamiell/hanabi-conventions/blob/master/variant-specific/Pink.md#trash-finesses--trash-bluffs-in-pink)

**Comment by timotree3** [comment]
> conventions like this could decrease the win rate instead of increase it, because it causes more mental overload and more chances for mistakes

Maybe it would decrease win-rate. Personally, my thought process in Hanabi tends to involve deciding what I think the best convention is and hoping that my teammates decided the same thing on their turns, so when someone discards a card that is promised trash I think "Was that the best card for them to discard? If not, maybe they're trying to communicate something extra", but when I see someone discard the chop-focus of the clue first, I think "That was the best card for them to discard if they're not trying to communicate something extra, but I'm still conventionally supposed to read into their action"

Therefore, it's actually *more difficult* for me the way the convention is currently.

**Comment by Zamiell** [comment]
in the abstract sense, focus in a trash finesse is currently destroyed as soon as a turn advances.
no notes need to be written, no information is carried forward.
the algorithm is as follows:

1) trash finesse happens
2) write notes of kt on all cards touched
3) card is discarded, no special rules apply

conversely, you are proposing that players should be burdened with remembering extra information - players must explicitly record focus as soon as every trash finesse occurs, so that they can reference this note when a subsequent discard occurs.
the algorithm is as follows:

1) trash finesse happens
2) write notes of kt on all cards touched
3) write note of "trash finesse focus" on one specific card
4) card is discarded
5) players must explicitly hover over all cards, looking for a "trash finesse focus"
6) players use the input from step 5 to calculate the correct slot

this is arguably more difficult. there are more steps in the algorithm, and more chances for players to make mistakes along the way

**Comment by pianoblook** [comment]
timo it's definitely not necessarily the best card to discard though, since conventionally they should trust that the leftmost trash card is actually the most likely to truly be trash in the first place :P I suppose that's a little bit of chicken-egg logic though lol

Is it possible that the intuitive discomfort you're having might stem from a more general concern about trash order? Like, "this trash at the very end of my hand (and the focus, in this case) is the oldest and thus is *surely* the most likely to be actual trash, so I feel most comfortable discarding that first" right? 

tbh reversing normal trash order (older = 'higher priority', always) has always felt more intuitive to me, but I doubt we could ever change that due to w/e Zamiel calls it - history bias?

**Comment by Zamiell** [comment]
we won't change that for the reason listed in the faq

**Comment by pianoblook** [comment]
Are you referring to [this](https://github.com/Zamiell/hanabi-conventions/blob/master/misc/FAQ.md#what-is-the-reason-behind-discarding-trash-from-left-to-right)?

I don't get it. how is it not already know as p1? And why would reversing trash order change anything? Either way if they were to discard their slot 1 card it would communicate that they must see p1 elsewhere

**Comment by Zamiell** [comment]
> how is it not already know as p1? 

on t34 the note on the card is `p1, trash 1 if p1 is f`

**Comment by pianoblook** [comment]
but it wasn't a tf because Libster didn't blind-play, no? unless you're saying they should entertain that he delayed a potential bluff with a another bluff? seems already suspect. but in either case x dragun can safely discard and they would know 100% that Libster would play his slot 1

**Comment by Zamiell** [comment]
> unless you're saying they should entertain that he delayed a potential bluff with a another bluff?

it is possible that libster deferred playing into a finesse to perform a bluff.
that isn't relevant to this example, because you could imagine a hypothetical with 5 player games with the exact same scenario in which libster knows that it is a finesse

> but in either case x dragun can safely discard

if dragun discards slot 3 then it would cause a trash order chop move, so no, you are wrong

**Comment by timotree3** [comment]
What's important about the situation linked in the FAQ is that xdragun is allowed to discard *the focus of the clue* without causing chop moves. That's the only reason we discard trash left-to-right.

**Comment by timotree3** [comment]
> timo it's definitely not necessarily the best card to discard though, since conventionally they should trust that the leftmost trash card is actually the most likely to truly be trash in the first place :P I suppose that's a little bit of chicken-egg logic though lol

Maybe in the case of a trash push that's true, but in the case of a trash bluff it's definitely not. 
1. Alice chop-focus two 1's in Cathy's hand
2. Bob blind-plays slot 1 from Alice's clue
3. If Cathy's chop 1 was a useful card, then Bob wouldn't have blind-played. Bob did blind-play, so Cathy's chop 1 cannot be a useful card, regardless of the order that the team expects Cathy to discard the 1's in.

**Comment by pianoblook** [comment]
lol that example still just doesn't make sense to me. Obviously if xdragun would discard their left-most 1, it would signal that they trust that it must be discardable. x wouldn't be allowed to discard it (since it was, presumably, a play clue focused on slot 1) unless they see the other copy

**Comment by Zamiell** [comment]
in the example, the card is in a superposition of r1, p1

| card identity | convention decision | outcome
| --- | --- | ---
| p1 | discard leftmost | gentleman's discard ✔
| p1 | discard rightmost | gentleman's discard ✔
| trash 1 | discard leftmost | nothing special happens ✔
| trash 1 | discard rightmost | trash order chop move on libster ❌

**Comment by timotree3** [comment]
| card identity assumed | convention decision | xdragun will | outcome
| -- | -- | -- | --
| p1 | discard focus of the clue followed by rightmost | discard slot 1 | gentleman's discard :heavy_check_mark: |
| trash 1 | discard focus of the clue followed by rightmost | discard slot 1 | nothing special happens :heavy_check_mark: |

**Comment by Zamiell** [comment]
that's not what piano is asking

**Comment by pianoblook** [comment]
why would xdragun discard slot 3 if the convention decision was rightmost? xdragun should still discard slot 1 in all cases, in order to be sure that Libster will play p1

**Comment by Zamiell** [comment]
no, because if the identity of the card is trash 1, then zamiel performed a trash chop move, and discarding slot 1 would cause a trash order chop move on libster

**Comment by timotree3** [comment]
I think the table should say that xdragun discards slot 1 and it's an ocm on libster

**Comment by Zamiell** [comment]
the table indicates what xdragun is supposed to do, not a secondary hypothetical

**Comment by timotree3** [comment]
in the hypothetical that of all xdragun's 1's are trash and the convention in discard rightmost and xdragun discards slot 3, then libster certainly wouldn't chop move, slot 3 is the rightmost trash and therefore the expected discard

**Comment by Zamiell** [comment]
im aware of that. the real game is a p1 though so that is what is relevant

**Comment by timotree3** [comment]
the fourth row of your table doesn't make sense

**Comment by Zamiell** [comment]
what doesn't make sense about it

**Comment by timotree3** [comment]
> > in the hypothetical that of all xdragun's 1's are trash and the convention is discard rightmost and xdragun discards slot 3, then libster certainly wouldn't chop move, slot 3 is the rightmost trash and therefore the expected discard
>
> im aware of that


> trash 1 | discard rightmost | discard slot 3 | trash order chop move on libster
> -- | -- | -- | --

In the table row, the exact three conditions that I just spelled out are true, and the outcome is stated to be a chop move.

In the quote, the three conditions are true, and you agree the outcome is not a chop move.

**Comment by Zamiell** [comment]
in the 4th table row, the card is assumed to be a trash 1, but is in actuality a p1

the name of the table row is "card identity assumed", not "card identity". the "card identity" for all 4 rows is a p1, because that is the reality that matches the replay in question

**Comment by timotree3** [comment]
Well if we're assuming the card is truly purple 1 then the outcomes should be changed to say "gentleman's discard" in every discard slot 1 case

**Comment by Zamiell** [comment]
i updated the table

**Comment by Zamiell** [comment]
and i added it here: https://github.com/Zamiell/hanabi-conventions/blob/master/misc/Convention_Reasons.md#discarding-trash-from-left-to-right

**Comment by timotree3** [comment]
> i updated the table

Cool.

I think my comment earlier got missed though. 
> What's important about the situation linked in the FAQ is that xdragun is allowed to discard the focus of the clue without causing chop moves. That's the only reason we discard trash left-to-right.

The *only reason* for the current convention is that a situation came up where it was important to be able to discard the focus of the clue without ever causing chop moves. But there is one edge-case where "discard leftmost" fails at *the one purpose for which it was invented*. I want to fix that

**Comment by Zamiell** [comment]
it fails in an edge-case.
to correct for this, it would add additional complexity to the overall convention framework, so everything i said [in this comment](https://github.com/Zamiell/hanabi-conventions/issues/419#issuecomment-747698400) applies

**Comment by timotree3** [comment]
real in-game example from today where this convention would've been excellent https://hanab.live/replay/482822#11

**Comment by timotree3** [comment]
(and without it the team was desynced on a trash order chop move)

**Comment by timotree3** [comment]
Here's another real in-game example: https://hanab.live/replay/488914#14

qqqq's slot 4 was the focus of a UTD/UDD and timotree's note on it is "dupe or y4". qqqq sees the second copy of y4 in timotree's hand, so knows that they're both trash. If q discards slot 2, it communicates that they see a y4 in timo's hand, but it would not chop move y5. If q discards slot 4, it is the discard that timo expects, and it does not chop move y5. If my proposal was accepted, then discarding slot 2 would be a trash order chop move as q desires.

**Comment by timotree3** [comment]
By the way, turns out this is already in the doc. Last bullet point of the trash bluff https://hanabi.github.io/docs/level-13/#the-trash-bluff

**Comment by Lel0uch-H** [comment]
That bullet point is probably outdated and needs removal. Since in non pink variants, there is no concept of a "focus" of trash bluff. All cards are promised trash.

**Comment by timotree3** [comment]
I think what you mean is that many players play as though that bullet point does not exist, and discard left to right unconditionally. I agree, but I think that bullet point is a good convention and I don't think it needs removal, instead I would remind people of it so we can play more optimally. By the way, I think part of the pushback on this issue may have been because I said trash finesse or bluff. I would be happy to amend it to just cases where the cards are not obvious trash by empathy, such as trash bluffs, UDDs, reverse trash finesses, and trash moves that only work because the missing cards are clued + unknown.
