### ISSUE TITLE
8-clue save stall clue inconsistency

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-conventions#42]
In table it says "save any card off-chop"

In 8-clue save section, it says "Players at 8 clues gain the special ability to save any card that they want, on or off chop, as long as the card is not freshly drawn. "

So either any card or any card that's not freshly drawn.

So, any card or any slot2+ card?

Also, should "trash stall" be added below "hard burn" in case there are no clued cards in anyonyboy's hands? Rare but can happen.

**Comment by Zamiell** [comment]
i fixed the table to say "(saving any non-fresh card)"

>Also, should "trash stall" be added below "hard burn" in case there are no clued cards in anyonyboy's hands? Rare but can happen.
ive never seen this happen so no
