### ISSUE TITLE
Occupied/Loaded Tempo Clue Chop Move

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#423]
### Occupied Tempo Clue Chop Move
* If a player who is *Occupied* gives a *Tempo Clue* then it is always a *Tempo Clue Chop Move*.

### Loaded Tempo Clue Chop Move
* In a variant which loaded play clues are turned on and a player who receives a *Tempo Clue* while he's *Loaded* then it should always be treated as a  *Tempo Clue Chop Move*.

**Comment by iamwhoiamhahaha** [comment]
just figured out that they are probably not good conventions

**Comment by Zamiell** [comment]
ya cuz its async lol
