### ISSUE TITLE
positional clues can only be done on the next player

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#424]
as proposed by mel.

this fixes the problem where you clue 5 and the next player discards a critical card because positional clues are async

**Comment by Zamiell** [comment]
would make #412 irrelevant

**Comment by Zamiell** [comment]
would make #425 irrelevant

**Comment by iamwhoiamhahaha** [comment]
looks clearer but i think the current convention is clear enough to me

**Comment by jack67889** [comment]
Isn't the main reason null games are lost because people feel the need to give a positional clue, while there isn't a good one available (and something complicated is attempted)? I'm in favour of gtp in null, but I'm wondering if there are enough positional clues left that follow gtp if you can only perform them from bluff seat.

**Comment by Zamiell** [comment]
> Isn't the main reason null games are lost because people feel the need to give a positional clue, while there isn't a good one available

neg, positional clues are rarely blocked

**Comment by hakha3** [comment]
This change is nice for more players, but Im not sure if its good change for smaller counts of players, specifically 3p. There is less possible confusion on who it is (bc less players) and sometimes really one player finds nothing to positional and needs second player to help

**Comment by Zamiell** [comment]
if 2 players need to work together, then they can break the convention, and it is pretty obvious to everyone what is going on

**Comment by iamwhoiamhahaha** [comment]
same thought as i mentioned [here](https://github.com/Zamiell/hanabi-conventions/issues/425#issuecomment-759173399)
