### ISSUE TITLE
Unnecessary Trash Pull Discharge

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#429]
Is it a thing?

### Unnecessary Trash Pull Discharge
* johno00 gives purple to OddballGreg
* ikelos blind-plays slot 3 to tell OddballGreg the pulled card is trash
* OddballGreg blind-plays slot 3 as unnecessary

https://hanab.live/replay/358925#51

![Unnecessary Trash Pull Discharge](https://user-images.githubusercontent.com/50160641/100880362-95306a80-34e7-11eb-83b8-f4de19fb6421.png)

**Comment by iamwhoiamhahaha** [comment]
I'm proposing *Trash Pull Discharge* btw

**Comment by pianoblook** [comment]
This is covered back in #363

**Comment by iamwhoiamhahaha** [comment]
okay cool
then it is an example for your proposal

**Comment by hanabirnoob** [comment]
Oh...maybe one should elaborate that if unnecessary trash push discharge could be made instead, then unnecessary trash pull discharge should be interpreted as double ignition.
