### ISSUE TITLE
gray pink changes

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#432]
current convention:

> In situations where there are critical cards behind dark omni or gray pink cards, you are also allowed to *Fake Save* with any number (either 2, 3, or 4). (Again, *Pink Promise* does not apply to this variant.)

tim proposes replacing this with:

[edit - don't read this, see [this post](https://github.com/Zamiell/hanabi-conventions/issues/432#issuecomment-742792802))

- Players are allowed to *Fake Save* dark omni or gray pink 2's, 3's, 4's, and 5's with any rank they want if they have a somewhat obvious reason to do so.
  - For example, players might want to "get" a free card as part of the *Save Clue* (e.g. as a 2-for-1 instead of a 1-for-1).
  - For example, players might want to avoid violating *Good Touch Principle* (e.g. cluing number 5 in the situation where an unplayable dark omni 2 is behind a duplicated 2).
- Thus, *Pink Promise* does not apply in this variant, regardless of whether the card is a 2, 3, 4, or 5.

**Comment by florian-5f3759df** [comment]
I'm not against this change because it's kind of nice to pick up free 5s, and gray pink disambiguates itself well. But I prefer if it stays default to save 2 with 2, and the others with 5, if there is no reason to deviate from this. That does mean that you can at least sometimes figure out, after learning more about the rest of your hand, which pink card you had on chop.

**Comment by pianoblook** [comment]
Few questions for discussion:

1. Would this mean cluing a 2 as a 2 *instead* of picking up an extra 5 should be treated as a finesse?

2. Would this mean cluing a 2 as a 5 should no longer trigger a bubblegum, even if it's *not* perceivably avoiding bad touch/picking up extra 5s?

**Comment by timotree3** [comment]
Also does this mean that you can save a pink 4 with a 3 clue as long as there is a 3 discarded?

**Comment by Zamiell** [comment]
I'll update the text to say:

> - Players are allowed to *Fake Save* dark omni or gray pink 2's, 3's, 4's, and 5's with any rank they want if they have a somewhat obvious reason to do so.

thus:

> Would this mean cluing a 2 as a 2 instead of picking up an extra 5 should be treated as a finesse?

i would say no.
as written, the proposed text above says they can fake save "if they want".
it does not say that "they have to".
maybe the clue giver values pink promise. pink promise is a good thing and it is certainly valuable.

> Would this mean cluing a 2 as a 5 should no longer trigger a bubblegum, even if it's not perceivably avoiding bad touch/picking up extra 5s?

if you can see no visible reason to choose a "wrong" rank, then you should treat it as bubblegum

**Comment by Zamiell** [comment]
> does this mean that you can save a gray pink 4 with a 3 clue as long as there is a 3 discarded?

Yes. But that's not a new convention, thats the existing way we already play AFAIK

**Comment by timotree3** [comment]
> > does this mean that you can save a gray pink 4 with a 3 clue as long as there is a 3 discarded?
> 
> Yes. But that's not a new convention, thats the way we already play AFAIK

So we're deleting pink promise for any save clue with rank? That seems a lot more expensive than just deleting it for 5 saves.

**Comment by Zamiell** [comment]
pink promise is already deleted for:
- rank 3 clues when there is a non-pink critical 3
- rank 4 clues when there is a non-pink critical 4
that is the definition of the existing psuedo saves section in the document

> So we're deleting pink promise for any save clue with rank?

no?
if I clue you number 2, and it touches 1 card on your chop, and then later on in the game you find out it is an omni card, then you know that that hard is exactly dark omni 2

**Comment by timotree3** [comment]
oh okay. So are all these points true in your proposal?

- If you receive a 5 clue on chop, then it can be any gray pink card.
- If you receive a 2, 3, or 4 clue on chop and it would normally look like a save clue and it touches two or more cards, then it can be any gray pink card.
  - If it only touches one card, then the focus of the clue must be a non-gray pink card.
- Players should prefer to save a gray pink 2 with a 2 clue unless a different rank would pickup extra cards or avoid bad touch.
- Players should prefer to save a gray pink 3, 4, or 5 with a 5 clue unless a different rank would pickup extra cards or avoid bad touch.

> Thus, Pink Promise does not apply in this variant, regardless of whether the card is a 2, 3, 4, or 5.

This is misleading, because *Pink Promise* still applies to play clues and non-5 save clues that only touch one card.

**Comment by Zamiell** [comment]
is this my proposal or your proposal LOL

**Comment by Zamiell** [comment]
you are asking me questions about your own proposal, i dont know the answers, ask yourself

**Comment by timotree3** [comment]
Okay well then I guess I propose that it works as outlined in those 5 bullet points

**Comment by Zamiell** [comment]
im going to try to rewrite this to make it more clear, how about this

### Normal Saves

- Dark omni or gray pink 2's on chop should be saved with a number 2 clue, as per normal.
- Dark omni or gray pink 5's on chop should be saved with a number 5 clue, as per normal.
- However, there are some exceptions, which are listed below.

### Pseudo 3 Saves and Pseudo 4 Saves

- Dark omni or gray pink 3's and 4's on chop should be saved with number 5 clue.
  - This is because we want to preserve the ability to give Play Clues to 3's and 4's that are on chop.
- However, there are some exceptions, which are listed below.

### Fake Saves

- When saving a dark omni or gray pink card with a rank clue, players can break the rules listed above in order to:
  - avoid violating *Good Touch Principle*
  - pick up an extra card (as a 2-for-1 instead of a 1-for-1)
- *Pink Promise* does not apply if one of these things could be the case.
- Thus:
  - A 2 clue on chop (touching 1 card) --> `i2, any normal 2`
  - A 2 clue on chop (touching 2+ card) --> `i2, i3, i4, i5, any normal 2`
  - A 3 clue on chop (touching X cards with no 3's in the trash) --> `any playable 3` (e.g. this is a *Play Clue*)
  - A 3 clue on chop (touching 1 card with 3's in the trash) --> `any 3 that is in the trash`
  - A 3 clue on chop (touching 2+ card with 3's in the trash) --> `i2, i3, i4, i5, any 3 that is in the trash`
  - A 4 clue on chop (touching X cards with no 4's in the trash) --> `any playable 4` (e.g. this is a *Play Clue*)
  - A 4 clue on chop (touching 1 card with 4's in the trash) --> `any 4 that is in the trash`
  - A 4 clue on chop (touching 2+ card with 4's in the trash) --> `i2, i3, i4, i5, any 4 that is in the trash`
  - A 5 clue on chop (touching X cards) - `i2, i3, i4, i5, any other 5`

**Comment by timotree3** [comment]
Looks good. A notable downside of this convention is that if you give a chop-focus play clue to a 3 that touches more than one 3 while there is a 3 in the discard pile, then when someone else draws the critical 3, the card still can't play on it's own, unlike in No Variant.

An alternative convention that would resolve that would be: You can only use a non-standard rank to save gray pink cards if the extra cards that it picks up can themselves be saved with rank.
- Legal: 3 clue with `x x y3 x i4` while one y3 is discard
- Illegal: 3 clue with `x x k3 x i4` where black 3 cannot normally be saved with a 3 clue.

This convention would mean that when you do a fake save, they will never find out that the focus of the clue wasn't in fact a critical 3, or when they do find out, they will know it was a fake save

**Comment by Zamiell** [comment]
I don't think it is valuable to define illegality. In this framework, give the player the option to do either clue depending on what is better in their own particular game state. It feels like they will always go for the 2-for-1 anyway.

**Comment by iamwhoiamhahaha** [comment]
In fact, gray pink conventions were first originally invented from my 2p experience while score hunting with fireheart. In 2-player games, there are no bubblegum moves and we do fake saves. For example, it is legal to save o4 and k3 with a 3 clue while a y3 is in the discard pile; and we save o2 with a 5 clue if it picks up more cards, which sort of conflicts with bubblegum moves in 3p+ games. So I'm fine with the new changes.

**Comment by iamwhoiamhahaha** [comment]
Oh btw the reason why I said that *pink promise* doesn't apply to this variant was because it leaves us the opportunity to do a 3 bluff with an o5 for example, which is good for 2p score hunting. But I agree that it is quite illegal in 3p+ games, which means pp should appl y to bubblegum moves.
