### ISSUE TITLE
3-bluff exception

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-conventions#433]
Normally, when a player play into a '3-bluff' but is out of position, he should continue to blind play the card missing until the initial target of the clue become playable.

But it's not the case when the color of the '1' match the color of the '3'.

Example 1:
Bob: x-x-x-x
Cathy: r1-x-x-x
Donald: r3-x-x-x
Alice clues 3 to Donald.
Bob delay because he can't play anything anyway.
Cathy plays r1 because she would assume r1+r2 anyway.
Now what happen next?
Normally any other player would assume r2, Donald included. But with that exception, it's not the case anymore. Donald wrote his 3 as exactly r3, and is allowed to discard (nobody assume r2).

Example 2:
https://hanab.live/replay/367094#2
Bob: x-x-x-x-x
Cathy: r3-r1-x-x-x
Alice clues 3 to Cathy.
Bob delay.
Cathy plays her finesse position as a '3-bluff', and it's r1. Cathy check if there was any r2 in finesse position when the 3 clue was given and there was none. She wrote her 3 as r3.

Counter-example 3:
Bob: y2-x-x-x-x
Cathy: y3-r1-y1-x-x
Alice clues 3 to Cathy, but that clue became illegal (imo, that can be the other way around though). Cathy will play r1 and and assumes her 3 is r1.
Alice should clue 1 to Cathy instead, and hope to get the finesse next turn.

Counter-Example 4:
Bob: x-x-x-x
Cathy: r1-y1-y2-b1
Donald: y3-x-x-x
If Alice clues 3 to Donald, it gets r1+y1.

Example 5:
Bob: x-x-x-x
Cathy: r1-y1-y2-b1
Donald: b3-x-x-x
If Alice clues 3 to Donald, it gets r1+y1+y2+b1.
Donald must wait for b1 to play as a '3-bluff exception', else Donald will assume y3 and play.

(Counter-example 6:
Bob: b2-x-x-x
Cathy: b3-r1-b1-x
Donald: r2-x-x-x
Alice clues 3 to Cathy.
Bob delay.
Cathy plays her finesse position as a '3-bluff', and it's r1. Cathy check if there was any r2 in finesse position when the 3 clue was given and there was one, she except it to play as a finesse.
Donald discard. Cathy is surprised by that, since Donald was not in an emergency situation, Cathy will continue to play to search for the identity of her 3 because of that discard.)

**Comment by iamwhoiamhahaha** [comment]
It kills a true finesse if donald has r3r2xx in your example 1.

**Comment by Romain672** [comment]
Ok mb, I just saw the problem.
You want to be able to tell if it's a 3-bluffs or a finesse. And hyphen-ated do that well by changing the meaning depending of the position of players.

On the replay, 1 and blue are impossible, that's why there is that weird 3-bluff :(
