### ISSUE TITLE
good touch principle applies to positional clues by default

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#436]

**Comment by iamwhoiamhahaha** [comment]
that's what i play. i don't understand why it was defined that gtp doesn't apply to positional clues

**Comment by Zamiell** [comment]
so that you can give more positional clues

**Comment by Zamiell** [comment]
piano says:

> I imagine a lot of the time it can be seen that other clues might have been possible to get the same effect, which would only make sense if it's good touch
so the only time you should be a little wary is if it may have been the only way to get the null card played

im proposing that we must give a fix clue in this situation
