### ISSUE TITLE
Cursed Finesses

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#438]
Got this idea from https://github.com/Zamiell/hanabi-conventions/issues/437.

### Cursed Clandestine Finesse / Cursed Finesse / Pestilent Rank Choice Finesse
* If a player performs a *Finesse* by giving a rank clue when they have *Free Choice* between a color clue or a rank clue, then they must be trying to communicate something extra.
* They are instead performing a *Cursed Clandestine Finesse*. The following player is also being called to blind-play.
* And if the blind-card matches the rank of the clued card, someone has to heal the problem.
* In this situation, the one who doesn't see the matching card should realize that it is a *"Finesse"* on them. They have to blind-play immediately in their turn to demonstrate the *Cursed Clandestine Finesse* occured.

#### Example 1
* If TimeHoodie wants to do the red *Finesse* on red 1 and red 2, he is supposed to clue red to kevincasetdk1. However, instead of giving a red clue, he chooses a 2 clue.
* Now, it's avanderwalde's turn. He sees that TimeHoodie has *Free Choice* between a color clue or a rank clue, he must be trying to communicate something extra. Therefore, they blind-plays their *Finesse Position*. It is a yellow 1 and it successfully plays.
* After the bliind-play, kevincasetdk1 marks his 2 as a yellow 2 (or potential blue 2).
* Now, it's pianoblook's turn. He figures out something weird has happened. If he does nothing, kevincasetdk1 is going to bomb his red 2 as a yellow 2. He realizes it must be a *Cursed Clandestine Finesse* and he is the one who has to "heal" the problem since he doesn't see a red 1 in someone else's hand. Therefore, he blind-plays his *Finesse Position*. It is a red 1 and it successfully plays.
* kevincasetdk1 is surprised. He doesn't understand why piano blind-played the red 1 and he realizes it was a *Cursed Clandestine Finesse*. He erases the notes on his red 2 and marks it as a red 2.

![curved clandestine finesse](https://user-images.githubusercontent.com/50160641/102426206-dbd6a680-4049-11eb-92a5-d5c95e430c39.png)

**Comment by pianoblook** [comment]
nice, that's clever. wonder if it would work as color, too:

> Bob's hand is y1 g1 x x
> Alice clues 'green' to a g2 in Donald's hand
> Bob blind-plays, but now just assumes this was a normal bluff
> Cathy sees that Alice could have cleanly given rank to Donald's 2, as a *Clandestine Finesse*
> Cathy blind-plays

It's nice that I don't think this could be misinterpreted as a normal double bluff from Donald either, since normally Cathy would have to wait for g1 to play

**Comment by iamwhoiamhahaha** [comment]
### Double Cursed Finesse
* Based on *Cursed Clandestine Finesse*, what if the blind-card doesn't match the clued card? In this situation, they are instead performing a *Double Cursed Finesse*.
* The next two players have to blind-play their *Finesse Position* to tell the whole team it was a real *Finesse*.

#### Example 1
* Yellow 1 has played on the stacks.
* TimeHoodie clues red to kevincasetdk1 as a *Finesse*.
* avanderwalde can see that it is weird for TimeHoodie not giving a color clue. Therefore, he blind-plays his *Finesse Position* as a *Cursed Clandestine Finesse*. It is a yellow 2 and it successfully plays.
* Now, it's kimbifille's turn. If she does nothing then the whole team would stop from the 2 clue as a normal *Bluff*. Therefore, she blind-plays her *Finesse Position* to tell pianoblook it was a real *Finesse*. It is a blue 1 and it successfully plays.
* pianoblook is surprised. If it was just a *Bluff* then kimbifille would blind-play nothing. Then he realizes it must be a *Double Cursed Finesse*. Therefore, he blind-plays his *Finesse Position*. It is a red 1 and it successfully plays.
* kevincasetdk1 is astonished. He knows that it is illegal to perform a *Triple Bluff*. Therefore, he realizes it must be a *Double Cursed Finesse* and marks his 2 as a red 2.

![double cursed finesse](https://user-images.githubusercontent.com/50160641/102434250-581fb880-404f-11eb-846c-51776d75511f.png)

**Comment by iamwhoiamhahaha** [comment]
> nice, that's clever. wonder if it would work as color, too:
> 
> > Bob's hand is y1 g1 x x
> > Alice clues 'green' to a g2 in Donald's hand
> > Bob blind-plays, but now just assumes this was a normal bluff
> > Cathy sees that Alice could have cleanly given rank to Donald's 2, as a _Clandestine Finesse_
> > Cathy blind-plays
> 
> It's nice that I don't think this could be misinterpreted as a normal double bluff from Donald either, since normally Cathy would have to wait for g1 to play

It doesn't work since it looks like a *4 Double Bluff*.

**Comment by pianoblook** [comment]
> It's nice that I don't think this could be misinterpreted as a normal double bluff from Donald either, since normally Cathy would have to wait for g1 to play

**Comment by padiwik** [comment]
Isn't this more aptly a Pestilent Rank Choice Finesse? I don't very much like calling it Clandestine when the promised clandestine card is elsewhere.

**Comment by iamwhoiamhahaha** [comment]
> Is that not true?

Oh I see your point.

**Comment by iamwhoiamhahaha** [comment]
> Isn't this more aptly a Pestilent Rank Choice Finesse? I don't very much like calling it Clandestine when the promised clandestine card is elsewhere.

We can just call them *Cursed Finesses*.

**Comment by padiwik** [comment]
This move almost exists already: Bob blind plays from Rank Choice and Cathy defers a blindplay to Donald as a Pestilent Finesse

**Comment by iamwhoiamhahaha** [comment]
> This move almost exists already: Bob blind plays from Rank Choice and Cathy defers a blindplay to Donald as a Pestilent Finesse

Ah I see. Okay we can call it *Pestilent Rank Choice Finesse* then.

**Comment by pianoblook** [comment]
I imagined 'Cursed' as sort of the inverse of Pestilent: 

> A Pestilent blind-play is required in order to *prevent a bomb*
> A Cursed blind-play is required in order to *re-initiate a true finesse*

**Comment by iamwhoiamhahaha** [comment]
> I imagined 'Cursed' as sort of the inverse of Pestilent:
> 
> > A Pestilent blind-play is required in order to _prevent a bomb_
> > A Cursed blind-play is required in order to _re-initiate a true finesse_

I like the definition

**Comment by pianoblook** [comment]
So to padi's point I agree Example 1 is more Pestilent, because Cathy just trusts that the real r1 will still play (finesse > bluff). The second one (double finesse) does seem to fit more as *Cursed*, because if no other blind-plays occur nothing would bomb, so Cathy needs to blind-play to get the ball rolling again

**Comment by pianoblook** [comment]
Just attempted this in game as a suboptimal bluff but piper didn't bite :p

<img width="1066" alt="Screen Shot 2021-01-03 at 9 04 03 PM" src="https://user-images.githubusercontent.com/32303453/103496237-7f2a0880-4e0b-11eb-8b9e-0e70a45fae9c.png">

**Comment by jack67889** [comment]
We had a similar game state yesterday, but where g1 is was r2 instead. How would you tell the difference?

https://hanab.live/replay/391879#3

**Comment by pianoblook** [comment]
> We had a similar game state yesterday, but where g1 is was r2 instead. How would you tell the difference?
> 
> https://hanab.live/replay/391879#3

This looks unrelated - first notice that there is no _Free Choice_ in choosing rank vs color.
I suspect that clue was trying to be a Patch Finesse or something, which is dangerous and not allowed. anti should probably bomb g3

**Comment by jack67889** [comment]
I am aware there was no free choice in our game, but I am just asking why it couldn't be a patch finesse (like in our game) in your example, if g1 was r2 (for example) and piper starts playing; why would that be illegal?

(In our game we discussed in the review that everyone, except for maybe nitawa, should know what's going on as soon as anti doesn't get y1.)

**Comment by pianoblook** [comment]
It's illegal because it's not an official convention; Patches got deleted because they lead to a lot of confusion and people assuming patch finesses over simple Fix clues.

The difference with these are that (1) no Fix clue is needed but (2) everything gets perfectly clarified almost immediately, since multiple players will blind-play. So the important reason why these Cursed clues are not any sort of Patch is that the clue receiver - *and* the player who actually has the matching card - will both immediately know what's happening.

Curious what Jeff has to say on this though, since this sort of "matching lie" Curse was his idea

**Comment by jack67889** [comment]
The doc states that known patch finesses, double patch finesses and patch gentleman's discards are illegal. But none of those apply here, right (there is nothing specific about clandestine patch finesses)? To me it seems that (unknown) clandestine patch finesses should work (at least for these examples), because the person receiving the clue has to wait.

**Comment by pianoblook** [comment]
How is this a "Clandestine Patch Finesse"? There's no such thing - basically no one should *ever* assume there's a Patch happening, which means no one should ever delay blind-playing just "in case it's actually a delayed Patch Finesse".

**Comment by jack67889** [comment]
After your clue piper plays p1. It's clearly not a bluff, but piper doesn't have y1 either, nor is it a pestilent double bluff. So from the perspective of avanderwalde it looks like a patch finesse where avanderwalde's y1 is behind either p2 or r2.

**Comment by pianoblook** [comment]
I'll leave this to Jeff to describe as he sees best. This convention is an interesting mix of Pestilence, Patchiness, and Cursedness

**Comment by iamwhoiamhahaha** [comment]
Honestly, if I were rkass, I would probably assume it is a *Purge Bluff* on piper lol. Okay, if you think it is illegal to perform a *Purge Bluff* in 4p+, and if I were avander I would probably assume a *Clandestine Patch Finesse* instead of a *Cursed Finesse*. And I would blind-play my slot 2 as a yellow 1 in my turn and mark my slot 1 as `p2/r2/n2`. But if a *Clandestine Patch Finesse* is not a thing, then it should be interpreted as a *Cursed Finesse*.

**Comment by pianoblook** [comment]
I think jack's comment about the similarity between this _Cursed Finesse_ and a "normal" _Hidden Patch Finesse_ are actually pretty interesting.

They both basically lead to the same outcome right? 
Step 1. Player A assumes they need to play a card)
Step 2. some other player still *clearly* needs to continue blind-playing to fulfill the original clue

So I think jack is right that this is basically a "fake hidden patch finesse"
- In your first screenshot, it would make sense for pianoblook to assume that maybe he's actually layered for y2 + r1
- the same is true for second screenshot: maybe pianoblook should 'assume' he might be layered for y3 + r1

**Comment by Zamiell** [comment]
rank choice finesse is not a very good convention. it doesn't apply in very many situations, and when it does, it is a common source of mistakes / losing the game.
building any convention on top of this principle is folly. not only do you further increase the propensity of mistakes but you also restrict the freedom of a player to do what they want and find the best clue.

**Comment by Jayhui-q** [comment]
In the first example, 

What if avanderwalde had red 2? Rank choice is chosen to not be ambiguous. Free choice needs to expanded even more regarding potential ambiguity for this to make sense (and, unfortunately, that is asymmetric)

Either way, I agree with Zamiel on this:
> but you also restrict the freedom of a player to do what they want and find the best clue.

An example, might simply be for negative information, perhaps for a future clue that allows for a known bluff.

**Comment by pianoblook** [comment]
Looking back on this now, I think I agree with Zam that it's quite an ask to require people to assume that they should play into a _Rank Choice_ clue on a 2, when you can literally see the matching 1 on someone else's finesse. 

I've tried to pull this off twice, with very good players, and neither one bit

**Comment by florian-5f3759df** [comment]
There is some similarity between this proposal and a 5 double pull, namely something looks like a save and a blind play is necessary to make it a play (in this case to tell Cathy it's a play, instead of telling the clue receiver). But there slot 1 is unambiguous in a way that can't be the case for a 2. So:

What about having it just be a Rank Choice Ejection on Bob? Bob sees that the card is actually 'playable', so I don't quite see why we need a separate convention for this at all. For me it actually seems conceptually covered by the Rank Choice Ejection already. Then it doesn't matter whether the card Bob plays is a 1 or a 3, it's always enough signal for the rest of the team to know what's up, and that someone has to play their finesse position.

(I do agree that rank choice is a pain sometimes, and we shouldn't have too many conventions with it. So just not allowing this at all is fine too, it can just turn a 2-for-1 into a 3-for-1, which is way less important than turning 1-for-1 into 2-for-1.)

**Comment by Zamiell** [comment]
sounds like we should close for now then
