### ISSUE TITLE
Self Color Double Ejection

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#440]
### Self Color Double Ejection
* When someone performs a *Self Color Ejection* without giving new information, and the ejected card can be clued directly; it is a signal as a *Double Ejection*, then the next two players have to blind-play their *Second Finesse Position* as a *Self Color Double Ejection*.

#### Example 1
* All 1's played on the stacks.
* Bob has a globally known yellow 5 which was used as a *5 Color Ejection*.
* Alice gives a yellow clue to Bob touching only the yellow 5.
* Bob knows that the yellow 5 is not playable and he doesn't see the other matching yellow cards in somebody else's hands, and since yellow 5 is two-or-more-away-from-playablw; it is a signal as a *Self Color Double Bluff*.
* However, Cathy doesn't have a playable card (or a one-away-from-playable card) on her *Finesse Position*. It must be a *Self Color Ejection* instead. 
* Therefore, Bob blind-plays his *Second Finesse Position*. It is a red 2 and it successfully plays.
* Now, it's Cathy's turn. She sees that Alice can cleanly give a red clue on the red 2. It doesn't make sense that Alice performs a *Self Color Ejection* without giving new positive information. It must be communicating something extra.
* Then she realizes Alice is instead performing a *Self Color Double Ejection* and blind-plays her *Second Finesse Position*. It is a red 3 and it successfully plays.

**Comment by pianoblook** [comment]
It seems confusing for Cathy if both this and #401 exist.

From her perspective, what if Cathy's slot 1 is a one-away card that could have been cleanly clued (as a finesse or bluff), which is what causes Bob to *Eject* here in the first place? In #401 she's supposed to blind-play slot 1, but this is calling for slot 2.

My gut says to keep these consistent; either both should call for a double ejection, or it should be a slot 1 + 2

**Comment by iamwhoiamhahaha** [comment]
SCDE is invented from SCDB and SCE so it never call for 2+1. The rules is simple, if you see Cathy has a playable card or a one-away card then it is always a SCDB; otherwise, it's a SCE or a SCDE.

**Comment by iamwhoiamhahaha** [comment]
For https://github.com/Zamiell/hanabi-conventions/issues/401, we can just close that issue for now since it's way too confusing. But actually, my original thought was: *Double Bluff Ejection* can only be done by rank clues. So it sort of not conflicts with SCDE.

**Comment by Zamiell** [comment]
i think it hard to believe that this could be common enough to warrant inclusion

closing since you have provided no examples
