### ISSUE TITLE
Cursed Trash Finesse/Bluff

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#443]
(Last one for the day I promise lol - all these Cursed things are pretty similar but there's a lot to dissect and discuss)

This is pretty similar to an *Unnecessary Trash Push Finesse*, except the trash is clued *off* chop.

**Cursed Trash Finesse/Bluff**

- If a player gives an *Unnecessary Trash Bluff (Off Chop)*, this would be quite strange if the blind-played card could have been cleanly *Finessed* by simply cluing the now-CM'd card itself.
- The next player must blind-play in order to signal to the clued player that this was a *Cursed Trash Bluff*; their CM'd card is actually playable!

I suppose this runs the risk of being mistaken as a Double Ignition in some cases, but you know how I feel about that haha. My main rebuttal would be this:
> If the *CM'd* card is actually now trash, Cathy should *Eject* and not blind-play normally
> If the *CM'd* card is just a normal useful card, no second blind-play would ever occur, because Cathy would assume it's just a normal UTCM.
> Therefore, the second blind-play would only occur if the CM'd card is exactly playable

Also, to that last point, I believe this should work even if the CM'd card is *any* playable, but this is the much Stronger Form of that concept.

Example:
> r1 and g1 are played
> Donald's hand is [b5 r3 r1 y2]
- Alice clues 1 to Donald
- Bob blind-plays y1
- Cathy sees this is very odd, because Alice could have simply clued yellow to Donald as a Finesse. She also sees Donald now will have chop moved y2, which is awful for tempo.
- Cathy blind-plays as well (successfully, lol)
- Cathy's second blind-play tells Donald that this was a *Cursed Trash Finesse*, and that it was actually declining to Finesse his own copy of y2 - Donald blind-plays his chop-moved card

**Comment by Jayhui-q** [comment]
This is super neat! I agree with this one. I'm not sure I follow the implied "weak" form of this where the CM'd card is any playable and not the connecting card (why not cm the playable if there is only 1 clue, for example?), but I'm pretty sold on the version presented above.

**Comment by Zamiell** [comment]
seems pretty edge case, and so rare that it would not warrant inclusion.
closing this since no in-game examples are posted
