### ISSUE TITLE
Convention Proposal: The Prism 5 Cue

### ISSUE THREAD

**Issue by Jayhui-q** [Zamiell/hanabi-conventions#445]
While practicing for the prism competition, rkass, avanderwalde, and I ran into an issue wherein prism 5 and the matching color 5 both lie in the same player's hand and the rightmost one is playable and the leftmost one is not.

How do we signal to play the rightmost 5 when both color and rank are indistinguishable?

My proposal is the **Prism 5 Cue**:

If Bob knows he has both Prism 5 and the matching color 5, and only one of them is playable, then a trash chop move given from Alice to Bob that chop moves only one card cues to Bob that, of the two ambiguous 5s, the rightmost one is playable. Bob then undoes the chop move (open for discussion on this! I usually find that there are no worthy chop moves if we've gotten to this point).

Put differently, if a single trash chop move is given rather than a tempo clue, it is because the tempo clue would have been in the wrong order.

This is because Bob knows that if the playable 5 were on the left, then a simple save (on chop) or a tempo clue (potentially tempo clue chop move) would have been sufficient. 

Below is a hypothetical example, where a 1 clue from Jerry to rkass cues that prism 5 is the right-most.

![image](https://user-images.githubusercontent.com/55895573/102747808-9276a780-4326-11eb-8aa3-a6c3ab966328.png)

The Prism 5 Cue could potentially be extended to trash chop moves that chop moves 2 cards if all 3s are on the stacks. Otherwise, a trash chop move of two cards may be the only way to save a 5 followed by a critical card.

The 5 cue idea could potentially be extended to other ambiguous variants as well.

As a side-note, I considered this for other indistinguishable card pairs such as prism 3, green 3, but it seems far less urgent and we could just wait for the needed cards to play on the stacks for both. The above case was a particularly troublesome situation when the playable 5 was the oldest card, especially since waiting for the 4 may be game-losing and a positional discard is insufficient (and we had two strikes!).

**Comment by iamwhoiamhahaha** [comment]
I think the easiest (and cleanest) way to get the rightmost playable 5 is "delay few turns and give the tempo clue on the 5s" (with either color or rank) as a *Focus Inversion* / *Focus Slide*. It's really useful in *Ambiguous* btw.

**Comment by iamwhoiamhahaha** [comment]
But I'm also keen to see and find a new convention without contextual read for tempoing rightmost ambiguous card.

**Comment by Jayhui-q** [comment]
Yeah, definitely. The concern arises when the Focus Inversion / Focus Slide you mention is not possible. For example, if one of the 4s was only recently played and we are approaching the end game (we can't afford to delay). Or, rkass holds y5 p1 on slots 1 and 2, and it potentially is never resolved.

The trash chop move of a single card was selected for the above because now Bob can prove with near-certainty that the contents of his hand did not prevent a tempo clue.

Namely, Bob's hand (using 6 suit prism and 5 cards in hand for this argument) contains:
unknown, known trash, unknown, i5 + p5. 

If slot 1 were the blocking 5, slot 3 can always be saved with rank (if the known trash was clued with rank) or color (if the known trash was clued with color).
If slot 3 were the blocking 5, a 5 save is sufficient (now putting the trash card on chop)

Essentially, Bob thinks "why didn't you just tell me about this card and save to give me positive information, or tempo clue me?" and has an "aha!" moment, that something is weird in his hand. 

If we are thinking in reverse, then Bob might look at Cathy's finesse and see if the unnecessary chop move calls for a blind-play, and if not, reads it as the prism 5 cue.

**Comment by alyvan** [comment]
The other piece with that is to read focus inversion, there have to be a few rounds that pass where there is truly nothing being clued/done which is unlikely, and in competition, tempo is important.

**Comment by Zamiell** [comment]
its fairly rare that someone will have both 5s. when this happens, it is usually solved in the way jeff describes. furthermore, one could also solve this via a positional bomb. we probably don't need a specific convention to handle this case.

> in competition, tempo is important.

to be fair, competition use isn't really a criteria here
