### ISSUE TITLE
Triple Ignition (with unknown trash)

### ISSUE THREAD

**Issue by Jayhui-q** [Zamiell/hanabi-conventions#446]
I've attempted this maneuver twice now, and while they didn't work quite how I hoped in-game, we had mostly agreed in review afterward that it was the best interpretation of the clue.

The proposal is the following:

If:
- Bob can see that a triple blind-play is feasible (Cathy and Donald have a playable and a playable/one-away), and
- Alice could have given a save or play clue that does not interfere with Cathy and Donald's finesse, and
- There is more than 1 clue available, or there are no good cards that could come from an unnecessary chop move, 

Then a clue from Alice to unknown trash that calls for a discharge is extremely weird. Bob needs to react to clarify that it is trash, but why occupy Bob when Bob can be getting a double-play out of Cathy and Donald with a finesse, double ignition, or a double bluff? Or, if only one were playable from Bob's perspective, direct-cluing Bob and then letting him or someone else give the bluff?

Instead, Bob should play his finesse position rather than his discharge. 
Cathy and Donald both understand what is going on when the wrong position is played, and to clarify the unknown trash, blind-play accordingly.

Below is an in-game example of this, where yellow is given from Jerry to Avanderwalde.

Piano can not play finesse to show that the yellow card is trash (Jerry doesn't know about y5 in hand)
But, Piano can see that Kevin and Time both have playables, and joyfully plays his finesse position.
Kevin and Time follow and both play their finesse position.

![image](https://user-images.githubusercontent.com/55895573/102798459-c1b50500-4376-11eb-8ec2-723ad38bd9b1.png)

Here's another example:
![image](https://user-images.githubusercontent.com/55895573/102799633-67b53f00-4378-11eb-8687-6b72cd3c39e0.png)

(Although, I think this one is miraculously consistent with our current conventions. When I gave this clue I intended a double ignition that turns into a pestilent triple bluff for Emily so that we could redistribute and win. With the proposed convention, Emily would not need to hold both b3s). Squidgetx called it an "unnecessary double ignition." 

To elaborate on the third condition:
In case 1, of having more than 1 clue available, Bob wonders why Alice didn't let him give the clue. (With 1 clue, Bob might have something on chop worth protecting, or foresees that a double bluff from Bob will leave Alice/Emily clue-less)
In case 2, of 1 clue and no good cards from an unnecessary chop move, Bob similarly scratches his head, wondering why not discard and let Bob give the clue, or simply cluing Bob.

While the third condition adds more complexity, it helps protect against instances where a UTD is valuable or when a save on Bob is required. I'm also curious if we think the second condition is even needed! Both of these two cover edge cases, but maybe the convention as "denied discharge -> triple ignition" is both simple and valuable enough to not have extra stipulations.

When there is no discharge position on Bob, I think the triple ignition should take precedence over an OOP UTD. Giving Cathy a discharge when Bob could be getting Cathy and Donald's finesse seems much weaker when the discharge could totally be given at a later time but not the finesse. If both are given, neither would resolve appropriately within the round.

Bear in mind that, if no sensible discharge exists, Alice shouldn't be giving a clue that could be read as a pestilent double bluff! The yellow clue in example 1 only works as a triple ignition because Bob intentionally denies the discharge (or OOO) read, thereby signaling two playable finesses. (Alice might consider green to Kimbi instead if either Piano had his own discharge or Kevin didn't have a playable discharge)

**Comment by pianoblook** [comment]
These two examples nicely highlight an important difference to me: I think it needs to be not able to be interpreted as something else.

In the first pic, I remember that clue looked to me like a 'normal' OOP UTD on Cathy (kevin), which seemed legal (though definitely odd). 

The second pic seems pretty unambiguous, though, that Bob is supposed to respond in some way (and obv can't discharge). An alternative interpretation would be an triple-OOP UTD on emily's b3 with a double-patch component (lolol) but a Triple Ignition probably is simpler 😆

**Comment by Jayhui-q** [comment]
Interesting! So I guess what you would advise is:
If Alice asks for a discharge and Bob has no discharge and Cathy has no playable discharge, then it should call for a triple ignition. 

The inspiration of the above is simply that robbing the ability to let Bob give a double bluff / finesse / ignition is just so awful that Bob doesn't entertain that. Instead Bob is in on the trick, and blind-plays as well.

**Comment by pianoblook** [comment]
> The inspiration of the above is simply that robbing the ability to let Bob give a double bluff / finesse / ignition is just so awful and rude that Bob doesn't entertain that.

I'm not opposed to that actually, as long as (a) Bob is not otherwise Occupied or (b) something else obviously strange is happening like Alice being locked. Reminds me of a similar conversation recently about whether an OOP 5CE should actually be entertained as a true finesse if it could have been just as easily done by Bob instead

**Comment by Zamiell** [comment]
1) the 5p screenshot example isn't very generalizable because Bob can't discharge.
in a closely related hypothetical, bob would just discharge and cathy would play slot 1 because of the unnecessaryness, and then the clue would be done.
2) having both double ignitions and triple ignitions increases the potential for mistakes
3) getting 3 blind plays in a row is not necessary to win the game in nearly all cases.
2 blind-plays is enough for the general case.
4) if there is an exceptional circumstance where something looks like a double ignition but it was given with a suboptimal clue, then players can feel free to interpret that as a triple ignition. however, there's no need to make an official convention for that - just use the context of the game and play appropriately. official moves are meant to be for common things that happen in a lot of games.

**Comment by Jayhui-q** [comment]
> but it was given with a suboptimal clue, then players can feel free to interpret that as a triple ignition. however, there's no need to make an official convention for that - just use the context of the game and play appropriately. 

Very much agree with this, almost like a suboptimal double ignition. 

Going to close this, because after some more time/thought, I don't think it's actually very great to codify this. The conditions and context need to be too specific, in my opinion, and is not worth adding.
