### ISSUE TITLE
Finesse position exception and allowable stall clues priorities and fix clues

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-conventions#45]
Since allowable stall clues was changed recently, there are few things unclear:

Finesse position exception means that often 5 stall is performed when a player is forced to give a clue and there's a single playable unclued card in someone's finesse position.

However, when player is forced to give a clue and cannot give normal play or save clue AND cannot 5-stall, then in the documents, it's not clear what has higher priority:
Cluing card on a finesse position, disregarding finesse position exception 
Or giving a tempo clue?

Also, according to changes, when player is forced to give a clue, are players allowed to give a fix clue (even if there are no cards being in immediate danger of misplaying)  in order to prevent resorting to 5-stall?

**Comment by Zamiell** [comment]
finesse position exception only applies to 5 stalls. this is clear in the doc afaik

a player can give a fix clue whenever they want
