### ISSUE TITLE
Move some level 19 strategies down

### ISSUE THREAD

**Issue by vEnhance** [Zamiell/hanabi-conventions#453]
Proposals:

* I suggest to move double ignition to level 15. (I think I talked about this with Zam at some point, but never submitted the PR.)
* I think the [table about deferring bluffs](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#deferring-a-bluff) could be moved to level 16 at the same time double bluffs are introduced. I think of this table as a clarification on what is allowed rather than an opportunity to mess up something fancy, so I think this is better to say earlier.
* Now that SCE is in, I am curious how people feel about moving all the self-color moves (SCB, SCDB, SCE) into level 17, at the same time pestilent bluffs are being introduced, since I see the former much more often.

**Comment by Zamiell** [comment]
1) in my experience, double ignition is rare, with the exception of competition games and/or extremely hard variants
2) good idea
3) i havn't seen any SCB or SCE yet in any of my games

**Comment by Zamiell** [comment]
2 is done now
