### ISSUE TITLE
Selfish Focus Inversion (Changed)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#455]
SFI is forbidden in rainbow/prism/daul-color, etc.
It's obvious but I saw someone perform this move in rainbow and it killed the game eventually.

**Comment by Zamiell** [comment]
I added the following to the doc:

> - Note that *Selfish Focus Inversion* is not allowed in variants with a rainbow or prism suit. In that case, the player is simply giving a play clue to a rainbow/prism card.
