### ISSUE TITLE
The Pickup Truck (and Distributed version)

### ISSUE THREAD

**Issue by pianoblook** [Zamiell/hanabi-conventions#457]
So Dump Trucks are frowned upon because they can just instantly lose the game by bombing a good card...But I think we'd all agree they'd be a lot more powerful if we could guarantee that the bombed card was actually just trash!

### The Pickup Truck ###

- If Alice gives a clue that causes an intentional misplay, usually the only explanation (other than a known mistake) is that this was a _Misplay Chop Move_.
- ...But what Alice's clue was actually a _Trash Push_, causing Bob to misplay trash? This cannot be a Chop Move because there are no cards right of it to CM.
- This must actually be a special signal: Alice has just forcibly initiated a _Dump Truck_ or _Distributed Dump Truck_.

*Note that if this was indeed a _Distributed Pickup Truck_, Bob should end up playing his slot 2 card (since it was on slot 1 at the time of the _Truck_)
*Also note that this shouldn't be confined to just 5 player (like Dump Trucks) because there is zero risk involved

**Comment by Zamiell** [comment]
who is the dump truck on

**Comment by pianoblook** [comment]
well I've never seen a non-distributed Dump Truck before, but I assume they can be OOP right? 

So if it's Cathy's turn and she sees that Donald's hand is fully playable from left to right, she wouldn't respond. But if not, she should blind-play immediately

**Comment by Zamiell** [comment]
there is practically 0 chance of this being useful to initiate a dump truck. when you reach the point of the game where a trash push works, no player will have 4 or 5 sequential playable cards.

a distributed dump truck in a 4-player game would be a 3-for-2, at the cost of a strike, which is fairly bad.

a distributed dump truck in a 5-player game would be a 4-for-2, at the cost of a strike, which is okay i guess if you have a strike to spare.

**Comment by pianoblook** [comment]
why is it 3-for-2/4-for-2? It's just a single clue. Seems like a 3-for-1 / 4-for-1

**Comment by Zamiell** [comment]
a bomb costs 1 clue
