### ISSUE TITLE
Bubblegum Bluffs vs. 4 Charms

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#462]
https://hanab.live/shared-replay/387681

Imagine it is a valid *4 Charm* if willwin4sure opens the game with a 4 clue on nukelauncher. Which notes should nukelauncher mark right after anser blind-plays their slot 4? A pink 2 as a *Bubblegum Bluff*? Or a random 4 as a *4 Charm*? Or both?

**Comment by Zamiell** [comment]
4 charm should take precedence since it is a convention that applies to all variants

**Comment by pianoblook** [comment]
This reminds me of a recent discussion about whether someone should assume a _Bubblegum Wraparound_ versus a _5 Pull Finesse_ when the clue given was a 5.

I think it should just depend on the card that gets played:
> If a 4 Rank Clue leads to a slot 4 blind-play that is *not* a _Pink_ card, this is promised to be a _4 Charm_ and NOT a _Bubblegum Bluff_ on a 1-away pink card.
> Similarly, if a 5 Rank Clue leads to a slot 1 blind-play that is *not* a _Pink_ card, this is promised to be a _5 Pull Finesse_ and NOT a _Bubblegum Bluff Wraparound_ on a 1-away pink card.

The natural other half of those assumptions, of course, is that if the played card *IS* pink, then it *IS* promised to be a true _Bubblegum Finesse_

**Comment by Zamiell** [comment]
I added the following to the doc:

> - Note that *4 Charms* have precedence over *Bubblegum* moves.

**Comment by pianoblook** [comment]
So if a 4 clue gets a pink 1 to play from Charm position, it shouldn't be marked as i2?

**Comment by Zamiell** [comment]
it should be marked as i4.

do you want to make a new convention that makes an exception for i1, or something along those lines?

**Comment by hakha3** [comment]
I think its fine to have bubblegum finesse > 4 charm > bubblegum bluff
