### ISSUE TITLE
4 charm on critical 4s

### ISSUE THREAD

**Issue by hakha3** [Zamiell/hanabi-conventions#464]
In this game I attempted 4 charm, forgetting about it looking like critical 4 bluff, but I feel its better to have in early game more charm options than bluff targets on slot 1. Later you can easily switch to critical 4 bluff
![image](https://user-images.githubusercontent.com/43155373/103786142-618fb580-503c-11eb-9ee1-aa03f1e4c11d.png)

**Comment by pianoblook** [comment]
It seems confusing to add an exception to an exception: "It's a Double Bluff that's actually a single bluff that's *actually* a Charm

**Comment by Zamiell** [comment]
agree, no more exceptions
