### ISSUE TITLE
Doc change: warn players of invalid Inverted Priority Finesse

### ISSUE THREAD

**Issue by florian-5f3759df** [Zamiell/hanabi-conventions#465]
[Inverted Priority Finesses ](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#inverted-priority-finesse) only work if the players are ordered correctly. I've seen it happen before that they were attempted, but stomped (without blame) by the player holding the declined priority card, since from their perspective nothing weird has happened.

I propose adding a bullet point like: 

* Note that the order of players is very important here: the Inverted Priority Finesse normally is only safe if the blind play can be exhibited before the turn of the player holding the declined priority card. Otherwise the player holding the declined priority card is likely to clue or bluff the relevant card, with no way of ever knowing about the Inverted Priority Finesse. For instance, if we swap the cards of Cathy and Bob in the example, Bob sees nothing special about the play of red 1. Therefore, Bob could clue red 2, wasting a clue, or even try to bluff it, causing desynchronization and a possible misplay in the future. 
* Consequently, if the players are in the wrong order, it is safer to play the lower priority card, as an ordinary Priority Finesse

**Comment by Zamiell** [comment]
ok, i added something to that section
