### ISSUE TITLE
Doc change: Change early game permission to discard text from "not cluing the previous player" to "not cluing the previous player who didn't blind-play"

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-conventions#467]

**Comment by timotree3** [comment]
e.g. if Alice gives a bluff, Bob blind-plays, now it's Cathy's turn and by the doc she should not 5 stall in Bob's hand, but that doesn't make any sense. Instead she may not 5 stall in *Alice*'s hand

**Comment by Zamiell** [comment]
meh

**Comment by timotree3** [comment]
This just came up in convention-questions

**Comment by Zamiell** [comment]
i dont want to overspecify what to do, the early game is already so complicated

**Comment by Zamiell** [comment]
i will close this now unless anyone else wants to chime in
