### ISSUE TITLE
Positional Bluffs

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#468]
- This convention only applies to variants with a null suit.
- Currently, you can only give a *Positional Clue* to Bob.
- If you do this, and it gets a non-null card, then it would transform in a *Positional Layered Finesse*.
- I propose that this convention is turned off.
- If Alice performs a *Positional Clue* to Bob and Bob plays a non-null card, then it is treated as a *Positional Bluff* and no more cards are promised.

This configuration makes sense because the person blind-playing from a *Positional Clue* will always be in *Bluff Seat*.

**Comment by Zamiell** [comment]
I have played many practice games over the past few days and this convention seems to work well in practice.

**Comment by Jayhui-q** [comment]
I like this! I have historically found null positional clues to be awkward when we have such a powerful suite of ejection/discharges. I think allowing bluffs with positional clues buffs them substantially and makes it so every player is actively thinking about positionals throughout the game.

**Comment by iamwhoiamhahaha** [comment]
now it's getting harder to get a null card (or do some trick moves). but it follows the occam's razor

**Comment by florian-5f3759df** [comment]
I think it makes sense to improve the success rate, so I'm in favour. (I'll miss the rare layered bounce-back finesses though.)

Maybe one day we'll have enough ejections, charms, and discharges to be able to play null with only a few extra chop moves (say when recluing 5) and no positionals, but I guess that's not today yet?

**Comment by Zamiell** [comment]
**Positional Bluffs** (by Zamiel)

```
- This convention only applies to variants with a null suit.
- *Positional Layered Finesses* are deleted and *Positional Bluffs* are added.
- This means that a *Positional Clue* can be used to get a non-null card.
- Similar to a normal *Bluff*, a *Positional Bluff* only "gets" 1 card. No actual null cards are promised.
```
