### ISSUE TITLE
Unnecessary Gentleman's Discard Chop Move

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-conventions#47]
![gentleman discard chop move](https://user-images.githubusercontent.com/12693191/67507082-89406b00-f68e-11e9-8814-e865c04a152d.jpg)
Alice have a known r3 in her hand.
All cards in Bob's hand are saved except exactly 2.
Alice discard r3.
Bob play his finesse position : it's r3.

From that, Bob know his chop is usefull (from Alice pov).
So why not chop move that?
I think all the others conventions who make a player deducing a card is usefull make that player cm this card. So why not on this case?

.

 - By extension, if Alice discard r3, and if Bob's hand is : r3-x-b1-b1 with b1 already played/clued at the moment of the discard (from Alice pov), Bob should chop move the x card.
 - Bob should keep in mind his chop move card could be a card already saved in Alice's hand.
 - If Alice have discarded r3 for another reason than saving Bob's hand (per example, if she got no clue left, and Cathy's chop was critical OR if the card was layered OR if the card was already clued on Bob's hand OR if the clue gained let Bob did a finesse (or bluff?) OR?), Bob should not chop move.

**Comment by Romain672** [comment]
- By extension, if Alice discard r3, and if Bob's hand is : r3-x-b1-b1 with b1 already played/clued at the moment of the discard (from Alice pov), Bob should chop move the x card.
 - Bob should keep in mind his chop move card could be a card already saved in Alice's hand.
 - If Alice have discarded r3 for another reason than saving Bob's hand (per example, if she got no clue left, and Cathy's chop was critical OR if the card was layered OR if the card was already clued on Bob's hand OR if the clue gained let Bob did a finesse (or bluff?) OR?), Bob should not chop move.

**Comment by Dr-Kakashi** [comment]
Unnecessary Gentleman's Discard

**Comment by NoMercyO** [comment]
Pros: Theoretically sound. 
Cons: Niche (breaks-down as soon as you have multiple unclued cards. High human sensitivity required to use correctly (as with all chop move conventions).

**Comment by Dr-Kakashi** [comment]
There are times and/or variants where players will have a blocking card

Example:
Played on the stacks: G1 M1
Alice's Hand: x - x - (M2) - x - x
Cathy's Hand: M2 - x - x - x - G2

Alice knows she has M2 and she can see that the team needs to get G2; however, Cathy has a blocking M2 that guarantee's a dupe, if Alice plays her M2.
Alice gentleman's M2 so that Bob can choose the next best clue.

**Comment by Romain672** [comment]
It's not a cm on g2 on your example.
It would be cm only if Cathy's got 3 saved card : m2 - g5 - y5 - r5 - g2. And here you cm g2 which is good.
(Or, with the extension on this situation : m2 - g2 - trash - trash - trash, where g2 would be cm after the 3 discard)

**Comment by aliblong** [comment]
>There are times and/or variants where players will have a blocking card

Then the previously blocked card will be immediately clued, and the gentleman's discard revealed as _not_ useless. This is analogous to how load clue focus works.

**Comment by Zamiell** [comment]
1) People do Gentleman's Discards for all kinds of reasons:
    a) Sometimes it is to chop move Bob.
    b) Sometimes it is to provide a clue for Cathy in order to stall out Cathy's chop.
    c) Sometimes, it is to get a Layered Gentleman's Discard.
    d) Sometimes it is just to generate a clue so that someone can do a Finesse.

    Any maybe more that I am not thinking about right now.

2. Recently, we turned off / deleted the *Early Fix Clue Chop Move* convention, because it was **causing more problems than it was helping** - it was **unclear** to players whether any particular *Fix Clue* was "early" or not.

    Subsequently, the *Unnecessary Gentleman's Discard* seems similar to that. Given the possibilities I've outlined in above, I think it is much more clear to not *Chop Move* **anything** by convention - this has a greater likliehood of keeping the entire team in-sync with what is *Chop Moved* and what isn't.
