### ISSUE TITLE
Guide Principle rewrite or clarification

### ISSUE THREAD

**Issue by jakestiles** [Zamiell/hanabi-conventions#470]
As written, guide principle does not tell Kyle it's safe to blind play slot 1 on turn 10 after https://hanab.live/shared-replay/401501#9

Thus, guide principle is currently written too specifically and needs to be written more generally. Perhaps by saying that Alice is cluing Red to Donald instead of to Cathy. (And also changing some other things)

**Comment by Zamiell** [comment]
i rewrote the section, you can let me know if this is sufficient

**Comment by jakestiles** [comment]
I still don't see how you can use guide principle as written to apply to Kyle in my example. Guide principle as written requires the finesse option to give the person with a valuable chop a card to play.

**Comment by jakestiles** [comment]
Proposed rewrite:

For example, in a 4-player game:
No cards are played on the stacks.
Alice clues red to Donald, touching a red 2 as a Play Clue.
Bob does not see any red 1's in anyone else's hand. Thus, Bob knows that Alice intends for him to blind-play a card.
From Bob's perspective, it can be either a Finesse (on exactly red 1) or a Bluff (on the 1 of any of the other suits).
Cathy has a critical 5 in chop.
Should Bob risk blind-playing or should he save the 5?
Normally, Bob would play it safe and save the 5. However, in this case, he knows that Guide Principle applies, and Alice is guiding him to play right now.
Bob blind-plays his Finesse Position card and it is the red 1.
Cathy does not discard since Alice saw something for Cathy to do.

**Comment by Zamiell** [comment]
ok
