### ISSUE TITLE
Delete White Compromise

### ISSUE THREAD

**Issue by EhDrone** [Zamiell/hanabi-conventions#471]
It seems like a very outdated and unneeded convention. I have played a large number of white games, and didn't even know that this convention existed until yesterday. 

Most of the people I have asked about have also agreed they basically never use it anymore with the increase in use of trash pushes, discharges, unecessary conventions, etc.

Thoughts?

**Comment by Zamiell** [comment]
fine

**Comment by hakha3** [comment]
I have used this several times

**Comment by EhDrone** [comment]
Just because you've used it doesn't mean its good or useful. I've "used" it a few times when I first learned of it's existence too because it exists in the document, but I still have never felt like it actually helped more than any other 5 clue I could give without it. So can you add that it was used and actually benefited your game more-so than the times you COULDNT clue a 5 because White Compromise existed?

**Comment by hakha3** [comment]
I mean you said "you basically never use it", so I just wanted to add, thats competely not my impression. Its not like it helped so much, but I neither had this "oh no I cant 5 pull or 5 cm bc others will misintrep it" being really problematic. I feel both pros and cons arent big and its not easy at least to me to compare them

**Comment by pianoblook** [comment]
Show me 10 examples of White Compromise being used, and I bet I can give at least 8 or 9 just as efficient alternative lines

**Comment by hakha3** [comment]
if there was feature to sort by variants I could try look

**Comment by pianoblook** [comment]
> if there was feature to sort by variants I could try look

there is! https://hanab.live/history/hakha3  just filter by variant

**Comment by EhDrone** [comment]
Hakha3 - my point is that I have played over 130 games of White variants (combinations of variants and plain white combined) BEFORE knowing that White Compromise existed, and I genuinely cannot recall a single time that I thought "Damn I wish I could give this white 5 a play clue right now instead of chop moving or saving".

The ONLY time that I used it was during Special Mix competition practice when Jake informed me that it existed at all - and it only came up because I gave a 5s clue that caused confusion due to him knowing it existed and me not knowing. And then after that first encounter with it - I never thought about it again because it just never came up again in our many practice games + competition games, and so frankly I forgot about it entirely once more. 

All of the above is just to say - just because a convention exists and is "used" because it already exists does not make it good - and "it exists and I used it because it exists" is not compelling enough evidence to keep it around. We can make a convention that says "if I clue you 2s on turn 1 you play slot 2", and it will get used all the time when slot 2 is playable and another player has a 2 - but that doesn't make it a good convention, right?

With all the great ways 5s are used now, I think most of the value of the compromise has been lost in a way that having the extra overhead of remembering its a thing, with the benefit of whatever limited situations it arises in (where another clue is 1) not available or 2) worse than the white compromise clue) makes it not worthwhile to keep around.

**Comment by pianoblook** [comment]
Example 1: this just works as a normal finesse - no White Compromise necessary. Even if it *was* one away from chop, just discarding would be great anyway.
Example 2: Reclue black as a SCDB, or bluff the black 2 w/ black and let frosty play their known r/w 5

Example 3: This works by convention too; e.g. if that was g5 then there's no other interpretation other than a finesse on it. Still, I'll admit that one is a bit more compelling since it's a double finesse that might not work cleanly otherwise.
Example 4: This works as a LPC anyway; the CM interpretation is known trash

**Comment by hakha3** [comment]
in example 1 its low score phase so no 5 play clues and sep interprets it as 5 pull. With other examples I agree
