### ISSUE TITLE
Convention Proposal: Unknown Trash Finesse

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#49]
I believe I have an interesting convention proposal
Cards played on the stack: None
Alice clue's bob 1's
Bob's Hand: y1 - y1 - g1 - x  - x
Bob plays G1 and his hand now looks like: y1 - y(1) - y(1) -x - x
Cathy clue's Bob Yellow picking up y1 as unknown Trash. 

Alice can safely play slot 1 to demonstrate it is trash
Bob will immediately know it’s trash because had Alice thought she had Y2, she would wait for Y1 to play first.

Potential Conflicts: 
Unknown Trash Discharge – Currently any unknown trash is a discharge

2nd Example:
Played : B2
Cathy's Hand : B2 - x - x – B(3)
Alice clue Blue to Cathy.
Bob will play Finesse Position

3rd Example
Played on the stacks: G1
Alice clues green to Cathy picking up G1
Cathy's Hand: x - (G)1 - x - x - x
Donald's Hand: x - x - x - G(2) - x
Bob will play Finesse Position

**Comment by aliblong** [comment]
Is there any advantage to this being play slot 1 rather than ejection/discharge for consistency's sake?

Also, the second y1 in Bob's original hand is irrelevant, right? And you're talking about a non-multicolor variant.

**Comment by Romain672** [comment]
Personnally I learn to answer by slot 1 if it's logical. Or slot 2 if slot 1 isn't logical.
It's consistency with that way of thinking.

**Comment by Zamiell** [comment]
I don't think this needs to be an explicit convention. If Alice sees that the natural fix clue is to re-clue number 1, then yellow will cause *Finesse Position* to be blind-played as a *Known Bluff*.

**Comment by Dr-Kakashi** [comment]
Known bluffs are for cards that are "good touched."  If that's the case, then if trash is picked up it should be a discharge, due to the Unknown Trash Discharge Convention?

**Comment by Zamiell** [comment]
It does not make sense for Bob to have the yellow 2, yellow 3, yellow 4, or yellow 5. If it was any of these cards, then Alice would not blind-play - she would wait for Bob to play the yellow 1 first, and **then** try to blind-play something.

Thus, since Alice blind-played, the brand new yellow card introduced must be a yellow 1.

**Comment by Dr-Kakashi** [comment]
Gotcha! Known bluff it is then
