### ISSUE TITLE
Convention Proposal: 8 Clue Lock Misplay

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#51]
![](https://cdn.discordapp.com/attachments/238379117794426881/636932885085028363/2019-10-24_0644_Forced_to_bomb.png)

8 Clue Lock Misplay:
Intentionally playing a card to draw the next playable card.  

Problems with Convention: 

- May look like positional misplay.  Players need to look around the table for context.
- This convention may be too rare.  Just posting this incase you would like to add to the doc.

**Comment by NoMercyO** [comment]
Anyone except Jeff can draw the null3 in your example and you still win. I 

It looks like the null4 and null5 are both globally known (as much as null cards can be) so even if this were necessary is should be self evident.

**Comment by Zamiell** [comment]
agree with mercy
