### ISSUE TITLE
Example Submission: Clandestine Pestilent Bluff

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#53]
![2019-10-24_0848](https://user-images.githubusercontent.com/48993588/67510552-039acc00-f64a-11e9-9d76-0fd68886ef6d.png)

Here scharkbite can clue 3's to asaelr.
Jeff will play finesse position.  R2 plays
Romain can see that Asaelr will play K3 as R3 since the card that played matches the clue that was given.  In essence, Asaelr's K3 is "diseased."
Romain follows the Disease Bluff convention.  First he looks around to see if R3 is in anyone's hand besides the clue giver.  Even though scharkbite has 2 R3's he can reason that it wasn't the intention of scharkbite.  Since there are no other R3's to clue in order to "heal" the problem.  He must play his finesse position to show Asaelr that he does not have R3.

2nd Example:
![2019-10-24_1129_(3_to_kyle)](https://user-images.githubusercontent.com/48993588/67515808-3ea1fd00-f654-11e9-9c61-27c828dd169a.png)
3's to Kyle

**Comment by NoMercyO** [comment]
To be clear you are posting useful examples of the already existing convention?

**Comment by Zamiell** [comment]
are you proposing any changes or did you want me to just add something to the doc?

**Comment by Dr-Kakashi** [comment]
Not proposing any changes.  This is just an example submission.  If you wish you can add these situations to the doc so players can have a better idea how to do the convention and/or identify it.

**Comment by Dr-Kakashi** [comment]
The examples with Alice, Bob, Cathy, Donald, etc. are just text based....I find it much more easier to learn and understand through pictures and seeing the situation unravel.

**Comment by Zamiell** [comment]
> Clandestine Pestilent Bluff

how is it a clandestine pestilent bluff? aren't both examples a "normal" pestilent bluff?

**Comment by Zamiell** [comment]
i added these examples here: https://github.com/Zamiell/hanabi-conventions/blob/master/examples/Pestilent%20Double%20Bluff.md

**Comment by Zamiell** [comment]
test

**Comment by Zamiell** [comment]
test2

**Comment by Zamiell** [comment]
test3

**Comment by Zamiell** [comment]
/stale since you haven't responded in 10 days
