### ISSUE TITLE
Update Requested: A Flowchart for Cluing 5's in the Early Game

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#54]
Since 5CE have been introduced a lot of changes to the way 5's are clued have occurred.  Can we get an update on this flowchart?

https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#a-flowchart-for-cluing-5s-in-the-early-game

**Comment by jakestiles** [comment]
It's missing Junk ejection and 5 pull ejection extensions of 5 cm and 5 pull, but I'm not sure we want to complicate the flow chart.

**Comment by Zamiell** [comment]
> Since 5CE have been introduced a lot of changes to the way 5's are clued have occurred.

The first line of the flowchart that you linked says:
"It is the Early Game and one or more 5's are clued with number 5."

5CE stands for 5 Color Ejection, which is when you (obviously) clue color to a 5.
Thus, it would not belong in this flowchart.

> It's missing Junk ejection and 5 pull ejection extensions of 5 cm and 5 pull, but I'm not sure we want to complicate the flow chart.

Indeed, I would rather not complicate the flowchart.
Furthermore, I have yet to see a Junk Ejection or a 5 Pull Ejection, so they are candidates for deletion in the future.
