### ISSUE TITLE
Convention Proposal: Disease Finesse

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#58]
Disease Finesse (Card played matches blind card):
![2019-10-23_0208_(Question_on_diseased_cards)](https://user-images.githubusercontent.com/48993588/67517890-6dba6d80-f658-11e9-9a6a-20d2503194d4.png)

I believe this is a form of Diseased finesse that should be added to the doc in some manner.

Valetta received 4's clue touching B4.  She considers it to be P4 as Dr_Kakashi is holding P3.  So she does something else.
Dr_Kakashi now knows that he has P3 on slot 2.  Dr_Kakashi also knows that if he plays P3 it will tell Valetta that her B4 is P4 and thus is "diseasing" it.  Dr_Kakashi play P3 anyways.
When it gets to asaelr's turn, he realizes that, if he does nothing, Valetta will bomb B4 instead of doing the B4 finesse.  Dr_Kakashi wouldn't of have put the team in this position without a reason.  So he plays his finesse position and plays P4. Healing the play exactly how Pestilent bluff works, except only 1 blind card plays. 

Disease Bluff (Blind play does not match card played):
![2019-10-08_0757_(question- pestilent bluff in pink)](https://user-images.githubusercontent.com/48993588/67521471-cb9e8380-f65f-11e9-9e02-00353bc53b8d.png)

Here's another form of Disease Bluff that's undefined
Dr_Kakashi clue's blue to Kyle making Kyle think he has B5.  Kyle plays finesse position and plays B4.
Jeff previously did not know where his i5 is located. 
He plays i5 from slot 5, showing that the clue Kakashi gave was a positional clue and tells Kyle that he does not have B5.

**Comment by aliblong** [comment]
Form 1: Kakashi can just have b2, and that is indeed the conventional interpretation.
Form 2: way too narrow to justify a convention.

**Comment by Dr-Kakashi** [comment]
Conventionally, due to Occam's Razor we have to do the simplest interpretation that has the fewest blind plays.  Because Valetta passed, it's obvious that she's expecting Kakashi to play P3.  Kakashi should also in turn not think he has B2 because a blind play is less likely than a simple prompt.  This is quite important as players are self-finessed, but they are unable to initiate Occam's Razor due to thinking it's on other player's hands.

**Comment by aliblong** [comment]
>Conventionally, due to Occam's Razor we have to do the simplest interpretation that has the fewest blind plays.

Your proposal is two blind plays... and this line of reasoning is a tacit admission that your "proposal" is not a proposal, but rather an illustration of what you think is a consequence of the existence conventions.

> Because Valetta passed, it's obvious that she's expecting Kakashi to play P3.

It's super-duper not obvious, because you having literally *any* playable on finesse will cause the same reaction.

> Kakashi should also in turn not think he has B2 because a blind play is less likely than a simple prompt.

*Any* player can have the other copy of b2. That is *not* less likely than Kakashi has p3 and asaelr has a playable on finesse.

**Comment by Dr-Kakashi** [comment]
My proposal is only 1 blind play?  The purpose was to show what should happen if I made Valetta think she has a card she doesn't have.  It isn't a consequence of the existing convention.  These two forms are literally undefined.  The closest we have to this sort of play is the pestilent bluff.

**Comment by Dr-Kakashi** [comment]
Sorry aliblong, I'm just having a hard time understanding how well you know our conventions.  I don't see you in our discord channel nor having a profile on the site.  Who are you?

**Comment by Dr-Kakashi** [comment]
I'm saying it is obvious as it involves hesitation.....but regardless of whether or not you know that.  I'm saying in a situation where a player knows the identity of their card, where playing that card would tell another player that they have a card they don't have and they would go on to misplay that card.  It should induce a blind play and/or heal clue per Disease bluff properties.

**Comment by Zamiell** [comment]
aliblong is libster

**Comment by Zamiell** [comment]
> I'm saying in a situation where a player knows the identity of their card, where playing that card would tell another player that they have a card they don't have and they would go on to misplay that card. It should induce a blind play and/or heal clue per Disease bluff properties.

ok, but a better example would be nice, since the form 1 example screenshot that you posted in the OP seems to have some problems

**Comment by Dr-Kakashi** [comment]
Example #1 (Cathy initiates the Disease):
Played on the stacks:
All 2's played on the stacks

Alice: Clues 4 to Bob touching a G4 on slot 3 as a play clue
Bob's hand: x - x- G(4) - x - x
Bob discards
Cathy's hand:  x - x - (P3) - x - x

From Cathy's perspective, Bob hesitated for 2 reasons:
1. Cathy has a G3 on finesse position, thus Bob is allowing for a reverse finesse.
2. Bob thinks he has a 4 that matches one of her 3's.
Since Cathy has full view of the board, she knows it's either a finesse on her or on other players, Bob included.  Cathy also has full knowledge that she has P3 due to receiving Purple's and 3's clue previously.  Cathy also see's that Alice has a P4 in finesse position. 
Cathy plays P3.

Alice is confused as to why Cathy played P3 as Bob will go on to bomb G4 as P4
Alice also knows it's bad for Cathy to put her in such a situation to "burn" a clue in order to fix the impending misplay, so there must be a deeper meaning.
Alice plays her finesse position and plays P4

Bob in this situation is surprised because he thought he had P4 himself. 
This tells Bob that he does not have P4 and that Cathy did a form of disease bluff. 
Bob will retroactively go back to see which 4 he has and how it will play. 
1. If Cathy does not have G3, he will blind play his finesse position as a self-finesse.
2. If Cathy does have the G3, he will hesitate again, letting Cathy know that it's really still on her as a reverse finesse. 

Example #2 (Alice initiates the Disease):
Played on the stacks:
P2 G2

Donald clues 3 to Cathy
Alice clues 4 to Bob
Bob's Hand: G3 - x- G(4) - x - x
Bob discards
Cathy:  x - x - P(3) - x - x

Cathy thinks she has G3 as it's the only reason why Bob didn't self-finesse.  
Cathy plays P3

Donald can see that Bob's 4 is not P4 and will go on to misplay
Alice wouldn't put the team in this situation where a fix clue is needed to stop an impending misplay.
Donald plays finesse position and plays P4

When it gets to Bob's turn he will have to find some way for his 4 to play.  Since he see's that there are no other 3's in finesse position.  He blind plays his finesse and plays G3.

**Comment by Dr-Kakashi** [comment]
I just realized....this is not a bluff......what I'm proposing here is an actual finesse.  I've changed the title to reflect this

**Comment by Dr-Kakashi** [comment]
Talked with micerang about it.  It seems like it's something that doesn't really work.  The first example I've proposed is a priority.  The only way to make that example work is to include context to where they figure out what card they have on their own and they induce the play.  This goes against our priority rules as you cannot defer finesse's to do a priority with a card that's not globally known.

The 2nd example is just a normal regular finesse, so it doesn't work either.  Additionally, if we do get it to work somehow, what prevents someone from bluffing out the card that's "gotten?"  Like if there's 5 players and someone is inbetween Cathy and Donald, how's that person going to know if the card is gotten or what will stop them from finessing/bluffing out the card to begin with?  Due to that, it sounds like it's too much head space to propose something like this.

**Comment by Zamiell** [comment]
ok so it sounds like you are retracting the propsoal
/deny
