### ISSUE TITLE
The Bad Touch Finesse (For 2's)

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#62]
* Normally, if number 2 is clued to a chop card, it is considered to be a *Save Clue* (as the *2 Save* convention).
* However, it is possible for players to transform this *Save Clue* interpretation into a *Play Clue* interpretation if they violate *Good Touch Principle* and intentionally duplicate another 2.
* In this situation, the player who received the clue will know that the chop card matches.
  * If two 2's were clued, then the other 2 is obviously the exact same copy as the chop 2. In this situation, the left-most card can be played and the other card discarded as known trash.
  * If three or more 2's were clued, then any of the other cards could be the duplicated 2. In this situation, the chop card should be discarded and then *Elimination Notes* for that card written on the other 2's.
* For example, in a 3-player game:
  * Nothing is played on the stacks.
  * Alice clues number 2 to Cathy, touching a red 2 on slot 3 and a red 2 on slot 5 (her chop).
  * Bob knows that normally, this would be a *2 Save* on the red 2. However, Alice is violating *Good Touch Principle*, so she must be trying to communicate something extra.
  * Bob blind-plays his *Finesse Position* card and it is red 1.
  * Cathy knows that since a clue that looks like a *2 Save* got Bob to blind-play something, then both of the twos must be red 2. Cathy plays the left-most copy and then discards the other one later.
* The *Bad Touch Finesse* is contextual and does not always apply:
  * If the clue giver was an *Occupied*, then it is an *Occupied Play Clue* and the other 2's are not necessarily duplicated.
  * If the clue giver gave a *2 Save* early and had other *Play Clues* to give instead, the clue could be so bad that it would trigger a *Finesse* and the other 2's are not necessarily duplicated.

**Comment by Zamiell** [comment]
Also:

**The Bad Touch Bluff (For 2's)**

* In the same way as the *Bad Touch Finesse*, it is also possible to *Bad Touch Bluff* in order to get unrelated cards played from *Finesse Position*.
* For example, in a 3-player game:
  * Blue 2 and green 2 are played on the stacks.
  * Alice clues number 2 to Cathy, touching a red 2 on slot 3 and a red 2 on slot 5 (her chop).
  * Bob knows that normally, this would be a *2 Save* on the red 2. However, Alice is violating *Good Touch Principle*, so she must be trying to communicate something extra.
  * Bob blind-plays his *Finesse Position* card and it is blue 3.
  * Cathy knows that since a clue that looks like a *2 Save* got Bob to blind-play something, then a duplication occurred and both of the twos must be the same copy. Cathy discards the left-most copy and saves the other one for later.

**Comment by aliblong** [comment]
What's the proposal exactly? That a 2s clue to chop that finesses implies dupe 2s? I'm not even sure that's generally true given other context that can exist (maybe the 2 clue was prioritized ahead of a clearly better clue in the hand of the player holding the 2s?).

If the conclusion is that a player can sometimes induce that the 2s are duped, that's just a consequence of existing conventions.

**Comment by Zamiell** [comment]
its not really a new proposal, more of documentation of an existing move

**Comment by Zamiell** [comment]
the only time when this style of a clue not does indicate dupe 2's is when it is done super early (and usually in a hard-variant). that move is currently undocumented, probably can stay that way tbh

**Comment by aliblong** [comment]
If it's worth documenting this, it should probably come with all the qualifiers like: the clue wasn't OPC, it wasn't unduly urgent, it clearly can't be a suboptimal save.

**Comment by Zamiell** [comment]
```
* The *Bad Touch Finesse* is contextual and does not always apply. For example, if the clue giver was an *Occupied*, then it is an *Occupied Play Clue* and the 2's are not necessarily duplicated.
```

>it wasn't unduly urgent

is this in reference to the "super-early"-style 2's clue?

**Comment by aliblong** [comment]
That's one way of putting it. Considering the urgent 2s finesse happens more often than the dupe 2s finesse IME, it seems weird to want to document the latter but not the former.

There are still more cases to consider, however. What if the hand is two 5s and two 2s? Cluing the chop 2 first is a suboptimal way to save it, so it should indicate a finesse, despite the other 2 being good.

**Comment by Zamiell** [comment]
> it seems weird to want to document the latter but not the former.

mostly it was due to wanting to document all of the bad touch finesses for completion purposes

> There are still more cases to consider, however. What if the hand is two 5s and two 2s? Cluing the chop 2 first is a suboptimal way to save it, so it should indicate a finesse, despite the other 2 being good.

ive never seen that move myself, it might not be worth documenting that

**Comment by Zamiell** [comment]
>  * If the clue giver gave a *2 Save* early and had other *Play Clues* to give instead, the clue could be so bad that it would trigger a *Finesse* and the other 2's are not necessarily duplicated.

**Comment by hanabirnoob** [comment]
Could be an useful convention. It makes a card play faster and with known duplicates it's easier to do priority play or trash order chop move (when two cards are clued at a time)
