### ISSUE TITLE
Order Ejection (deleted)

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#66]
* This convention is deleted, as it is hardly ever used.

Also:

**Reverse Order Ejection** (deleted)

* This convention is deleted, as it is hardly ever used.

**Comment by alercah** [comment]
I thought these were already deleted.

**Comment by Zamiell** [comment]
Just in case someone missed their chance to veto, I will let people comment here for the next 1-2 weeks or so.

**Comment by sjdrodge** [comment]
I would like to keep Reverse Order Ejection. The convention is very low headspace and has almost no chance to go wrong. I'm okay with the Order Ejection being deleted.

**Comment by alercah** [comment]
Reverse Order Ejection can get messed up though, can't say I'm a fan of it as a result. It fundamentally feels like a weird reverse bluff convention.

**Comment by Zamiell** [comment]
why would you want to delete the forward one and keep the reverse one, because it is more likely to only have 2 ones?

**Comment by sjdrodge** [comment]
I think I got the names backwards. I want to keep the version where Alice fails to chop move a critical card on Cathy's chop and therefore Bob ejects. The version where Alice fails to chop move Bob and therefore Cathy ejects should be burned and forgotten.

**Comment by Zamiell** [comment]
order ejection was announced on feb 21st 2019, and i have only seen it occur once
have you ever actually done this move?

**Comment by sjdrodge** [comment]
It has come up 2-3 times over the course of ~2k games.

**Comment by Zamiell** [comment]
ok i will only delete reverse order ejection for now

however if i do not see an order ejection in the next 2000 games or so we will need to re-examine whether or not it should be deleted
