### ISSUE TITLE
Trash Rank Trash Clue

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#68]
> for multi-fives: I think it was related to the fix clue I gave on turn 30 of 55197, but I can't recall what it was.
> micerang was going to play the y1 next into a layered gentleman's discard from early game, looking for exactly g2. But it needed a fix. I chose 1s to micerang and there was a lot of discussion generated from that
> since the 1 clue hit the 5 instead and it's not trash
> I think the convention I wanted to propose was that a rank clue is normally interpreted as cluing trash when all the cards of that rank have been played, unless context dictates otherwise
> (in particular, "context dictates otherwise" means "lategame when there won't be many ranks available")
> maybe limit it to 1s or 2s
> multi-5s already loses a bunch of conventions based on 5 rank clues
> also losing trash conventions because your 1s clues are interpreted as play clues on 5 seems garbage
> (no pun intended)
> there was some debate here as to whether I gave the correct clue, but the important point is whether g5 needs a fix
> or whether micerang should hold off on discarding it (or even hold off on discarding y1) because of that
> actually I think the same should maybe apply in pink/omni games as well
> trying to phrase it into something coherent:

**Comment by Zamiell** [comment]
```
* In a game with rank-wild cards (pink or omni suits or multi-fives), when a rank clue is given for 1s or 2s, and all cards of that rank have already been played or are clued (making the entire rank trash), then unless it is a valid 2 Save, it is interpreted as a clue to trash. 
* However, only the **rightmost** card which wasn't already known to be trash is promised to actually be trash. The remaining cards may not be, even if the convention being used normally promises that. This rule strikes a balance between allowing powerful trash clues to be used without rank-wild cards interfering too much by causing all potential trash clues to be interpreted as play clues, while also preventing the recipient of a trash clue from discarding non-trash cards.
** Example: Bob has pink 5 in slot 2 and pink 2 in slot 3. All 1s have been played, and pink has only been played up to rank 3. Alice clues 1s to Bob, hitting both of the pink cards. Because 1 is a trash rank, Bob interprets the clue as being to trash and is therefore a Trash Chop Move. He chop moves himself and marks the pink 2 as trash. He does not mark the pink 5 as trash because only the rightmost card is promised as trash.
** However, if Bob already knew that the pink 2 was trash, for instance because it had a 2 clue and all 2s had been played already, then this clue would promise that the pink 5 was also trash, and thus be illegal.
```

**Comment by Zamiell** [comment]
* A Fix Clue can be a Trash Rank Trash Clue. In this case, the promise of trash on the rightmost card still applies independently of the fix. The fixed card, if not the rightmost clued card, is not promised to be trash, but the rightmost clued card is promised to be trash even if a different card is being fixed. If the rightmost card is not trash, the clue is illegal.
* Trash Rank Trash Clues do not apply to ranks which are not entirely trash. Thus, if there are any 1s yet to be played or clued, a clue to a single trash 1 is interpreted normally, such as as a Trash Bluff or Unknown Trash Ejection. Thus a Trash Bluff still promises that all touched cards are trash.
* It is possible to lie and give a Trash Rank Trash Clue when the rightmost card is not trash. Such a lie will require a fix but may be useful, such as to Trash Push a difficult card.
* A 2 Save being validly used to save a non-2 takes priority over a Trash Rank Trash Clue interpretation, however, if the recipient knows that it cannot be save clue *and* that the clue giver knows this (for instance because all remaining 5s are in other players' hands in a multi-fives game, or because the Pink Promise prevents a 2s clue from being used to save a higher-ranked pink card), then it cannot be a 2 Save so it is a Trash Rank Trash Clue.

**Comment by Zamiell** [comment]
> Zamiel09/23/2019
> having that be an ejection doesn't really flow from first principles
> the way we play is that if a focus of a clue doesn't make sense, then it focus inverts

**Comment by Zamiell** [comment]
> alercah09/23/2019
> hm, true
> but it is rather contrived, and requires another player to demonstrate the inversion
> and to arrive there you have to get past "chop move on a bad card", which, at least when the bad card is trash, now usually signals an ejection
> which I think is simpler
> and there's a lot of subtle complications to having to demonstrate inversion of focus away from a card that's still guaranteed playable
> e.g.
> cathy has r4 clued 4 left of b4 clued b; r2, b2, g3 are played but r3, b3, g4 aren't, and cathy can't rule out the r4 being g4
> her chop is trash
> alice clues cathy 4s
> following the logic
> oh wait I think this doesn't quite work as stated, hm
> ah wait, it does
> it looks like a play clue on r4
> it doesn't get enough value to justify
> if it's actually g4
> two possibilities
> either it's actually r4 and will get a blind play
> to complete a finesse or demonstrate a bluff and justify it
> or it's actually g4, and looks like a tccm
> but if it's a bad tccm it's a dtpc
> so it's a play clue to b4
> and then bob should blind play b3
> if it's not b3, it was a bluff
> but cathy doesn't know which card was bluffed
> if it's actually r3 but cathy had g4 and not r4, it's worse
> because it looks like a finesse through to r4
> another similar situation
> rainbow game, left card is clued 4 and right card is clued r and negative 3, g.  r2 is played, m3 is not. reds clue to cathy. bob blind plays r3
> cathy can't tell which card is r4
> it could be the left card, with the right card being r5, or it could be the right card, with the left card being m4
> either way playing the wrong card is a misplay
> actually hang on
> this one doesn't work unless it could be a bluff on m4, darn
> was tring to make one that didn't require a bluff
> in any case, it requires a lot of schrodinger play from cathy
> for a relatively rare scenario
> and this is way more complicated than an ejection interpretation that follows naturally from "chop moving trash is an ejection"
> hm actually I think you could do it without a bluff in very ambiguous
> if s3, b2, n2 are played, and the first card could be a 4 from any suit
> and the clue makes b3 play
> oh wait, no, im bad
> doesn't help
> oh hang on
> yeah ok
> it requires a bluff
> you could ban buffs here but that seems not worth it

**Comment by Zamiell** [comment]
> ```
> ** Example: Bob has pink 5 in slot 2 and pink 2 in slot 3. All 1s have been played, and pink has only been played up to rank 3. Alice clues 1s to Bob, hitting both of the pink cards
> ```
> the example given seems pretty weird.
> 
> firstly, you dont include discussion of pink choice, which doesn't apply here because slot 1 is not a pink card.
> 
> secondly, the current configuration is that it would just be a fix clue on the leftmost pink card. from what i can gather you are proposing that all pink fix clues are also chop moves? that doesn't seem to flow from first principles. fix clues on other types of cards are not chop moves, so i dont see why fix clues on pink cards should be chop moves.
> 
> thirdly, the way we have been already playing is that leftmost is trash, not rightmost. why specifically is it optimal to promise rightmost when prompts call cards from left to right? i think that most of the time, the whole point of fixing a pink card is to get a prompt to work again.
> 
> fourth, for practical purposes we don't typically pink fix because we can just use pink choice to get a rightmost card, it is just a more direct way of solving the problem

**Comment by Zamiell** [comment]
>vetoed for now i guess since alercah never responded to my concerns

**Comment by Zamiell** [comment]
> NoMercyYesterday at 3:12 PM
> @alercah I could not follow the logic of the Fix Clue section of trash rank trash clue proposal. I think the first section has merit to discuss. 
> 
> Why are you proposing the clue promise rightmost be trash? That seems counter intuitive to the clue focus being the promised trash and typically for trash clues that would be leftmost.

**Comment by Zamiell** [comment]
> alercahYesterday at 3:14 PM
> I forget about that detail
> I'd have to go look at it again
> oh right
> because it goes with a TCM
> where the key trash card is the rightmost, since it's the one to the left of the CMed cards
> e.g. if you have p2-p5-x-x it feels weird for a TCM by a 1s clue to say that the p5 isn't trash, despite trash moving the two rightmost cards
> but I don't think there would be a problem with doing it the other way also
> it just becomes kind of wonky because then you can't TCM with p5-p2-x-x
> but it is inconsistent with UTD, so the consistency might be better
> for the fix section, here's the example:
> 
> y1 needs fixing because there's a layered gentleman's discard to g2
> and he's about to play it
> if I clue 1s, what am I promising is trash?
> My proposal is that the same convention applies
> in this case, it would promise only y1 being trash
> under the proposal as written though, it would also work if the fix was on g5
> as it wouldn't promise that the g5 was trash, but only that y1 was
> if we go with a focus-based rule
> then it would work for fixing y1, since it says that only y1 is trash
> it would not work for fixing g5, since it would signal that g5 is trash when it's not
> note: this is multi-5s variant, where 5s cannot be clued directly, but are hit by all rank clues
> the final alternative would be that there's no trash promised at all
> but then micerang has two clued, trash 1s that he can't discard
> because they might actually be 5s
>

**Comment by Zamiell** [comment]
> NoMercyYesterday at 4:39 PM
> @alercah. Understood on the fix clue example. This seems consistent with the way a color fix clue would work in a novariant game.
> 
> The arguement of p5 p2 X X seems to me mirrored with p2 p5 X X, so unless there is a strategic reason rightmost is clearly superior wihch im not seeing then clue focus left most is preferred. 
> 
> Seems to me the kernel of the arguement is less about left/right and more that indirectly number clued cards that could be their touched number and thus trash, or could not be and are useful pink/omni cards. I think the later is how we currently play....?

**Comment by Zamiell** [comment]
> alercahYesterday at 5:25 PM
> Yeah.
> Basically the logic for having it at all is that you can use another rank to give a play clue
> usually
> because if all the ones are down, TCM is a powerful move to have, but you can't have it if you just assume that it's a play clue on pink
> I proposed it working on 1s and 2s only, to ensure that there's always "room" to make play clues
> 1s only might work too
> actually
> trash on focus is the better convention then now that I think about it because you can't play clue
> if you have p4 p2 X X, you can just play clue to save the cards
> if you have p2 p4 X X, you can't, and you can't clue the 4 to play at all atm
> so having a 1s clue be a TCM promising that p2 is trash is ideal I think
> the reason I think fix clues should promise 1 trash is to still be able to make progress on fix clues by indicating trash
> in retrospect, I think the y1 is bad there because it bad touches r1 even with the proposed convention
> but it might be fine if it's useful to clue again to indicate that g5 is a 5, which would also fix the r1
> I think that promising trash on the fixed card might be the easier convention to remember
> since the fixed card is effectively the focus
> and then it lines up with UTD too

**Comment by Zamiell** [comment]
> alercahYesterday at 8:10 PM
> @NoMercy I think my main remaining concern with the fix case is whether there's still good/bad touch on the trash cards
> my feeling is that because fix clues don't promise good touch, it's allowed to make bad touches which will get disambiguated by a different rank clue later
> but the question I guess is how strong that should be
> like is it the usual "don't make a bad touch if you can avoid it" or should it be more lenient?
> given that the bad touch is fixed by any rank clue which could easily serve another purpose

**Comment by Zamiell** [comment]
> StephenYesterday at 8:56 PM
> fix clues do promise good touch afaik
>  
> alercahYesterday at 9:06 PM
> I thought they didn't because bad touch might be the only way to fix
>  
> StephenYesterday at 9:06 PM
> yo, I heard you like fix clues so...
>  
> NoMercyYesterday at 9:23 PM
> They do - to a point. Keep in mind omni and pink alread have relatively relaxed reads on good touch principle considering increased difficultly in adhereing to it without violating save principle.

**Comment by alercah** [comment]
Those first chat quotes are from discussion of a different proposal.

After the discussion with NoMercy, I think the convention should be that only the focus is promised trash, and the rest of the cards may or may not be.

**Comment by Zamiell** [comment]
which chat quotes

**Comment by alercah** [comment]
https://github.com/Zamiell/hanabi-conventions/issues/68#issuecomment-546180782 and the one after.

**Comment by Zamiell** [comment]
ok i deleted those comments

**Comment by Zamiell** [comment]
The way we currently play is as follows:

In a 3-player game:
* Pink 2 is played on the stacks.
* Bob has a pink 1 on slot 4 and a pink 4 on slot 5.
* Alice clues number 1 to Bob, touching slot 4 and slot 5.
* Bob knows that normally, when pink cards are re-clued with rank, it signifies *Pink Choice*, and that would mean that he has to play his slot 1.
* However, Bob also knows that *Pink Choice* can not be used to perform a *Self-Finesse*. Thus, this must be a *Fix Clue*, and his left-most pink card must be a pink 1 in order to match the 1 clue. (It is also possible for the card to be pink 2 - the main point is that it is a known trash card.)
* Bob discards his slot 4 card.

Does your convention change this example at all?

**Comment by alercah** [comment]
No, this example is in line with the convention: the touched card is promised trash, but no other card is.

**Comment by Zamiell** [comment]
> Example:
> * All 1s have been played, and pink has only been played up to rank 3.
> * Bob has pink 5 in slot 2 and pink 2 in slot 3.
> * Alice clues 1s to Bob, hitting both of the pink cards
> * Because 1 is a trash rank, Bob interprets the clue as being to trash and is therefore a Trash Chop Move. He chop moves himself and marks the pink 2 as trash.

Can you explain why Bob interprets number 1 as a *Chop Move* in this example but Bob interprets number 1 as a *Fix Clue* in my example?

**Comment by Zamiell** [comment]
closing this since alercah isn't responding
/deny
