### ISSUE TITLE
Rank Choice Ejection (with 2 and 5)

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#69]
* If a playable 2 (or 5) on chop is clued with rank instead of color, and it is the only 2 (or 5) and color in the player's hand; it is a signal as an ejection, and the next player should blind-play their Second Finessed Position as a Rank Choice Ejection.
* Question: Which slot you should respond?
  * If the card is one or more away from being playable, then you should blind-play nothing since it is just a Save Clue.
  * If the card is trash, then you should blind-play slot 1 as a trash bluff.
  * If the card is playable, then you should blind-play slot 2 as a rank choice ejection.

**Comment by Dr-Kakashi** [comment]
Is it possible to apply this convention/idea to all playable cards?  

Played on the stacks: R2
Cards in Trash: G3
Cathy's Hand: x-x-x-x-R3
Alice clues Cathy 3

What should Bob do?
Playing Slot 1: Tells Cathy that her 3 is not R3 nor G3
Playing Slot 2: Undefined
Playing Slot 3: Unknown Trash Discharge

**Comment by Zamiell** [comment]
@jeff seems good

One interesting thing is that since we moved UTE to UTD, it opens up the space for ejections since all "brand new card"-style clues do not conflict with anything anymore (with the exception of Junk Ejection, which seems rare).

> Does this apply only in cases where a 2 (or 5) clue does not already identify unique playability, typically due to all 2s, or at least all yet clued 2s being playable?

I think that this convention should **only** apply if you touch one card with the 2 clue / 5 clue. That way it is nice and clear. Often times we intentionally *2 Save* a playable 2 in order to get a 2-for-1 clue (getting efficiency at the cost of tempo).

**Comment by Zamiell** [comment]
> What should Bob do?
> Playing Slot 1: Tells Cathy that her 3 is not R3
> Playing Slot 2: Undefined
> Playing Slot 3: Unknown Trash Discharge
> 
> Since slot 2 is undefined we can have this convention play slot 2. If that's the case we can apply this convention to any playable card for consistency.

yeah i agree with this example.
however note that the ejection has to be triggered with a rank clue so that it does not look like a 5CE

**Comment by Zamiell** [comment]
**Rank Choice Ejection** (with a number 2 or a number 5) (by Jeff)

```
* Typically, when a number 2 clue or a number 5 clue is performed on a chop card, it will be treated as a *2 Save* or a *5 Save* and the card will not play.
* If a player performs a *2 Save* or a *5 Save* on a playable card and they could have easily used a normal color *Play Clue*, this is quite strange. They must be trying to communicate something extra.
* In this situation, they intend for an *Ejection* on the very next player.
* For example, in a 3-player game:
  * Red 1 is played on the stacks.
  * Cathy's hand is completely unclued and is as follows, from left to right: red 2, blue 4, blue 4, blue 3, blue 3
  * Alice clues number 2 to Cathy, touching the red 2 as a *2 Save*.
  * Bob sees that the obvious clue to give to Cathy was red, as it would actually get the red 2 played right now.
  * This move is so bad that it must be communicating something extra. Alice must be intending for a *Rank Choice Ejection*. Bob blind-plays his *Second Finesse Position* card and it is a blue 1 and successfully plays.
  * Cathy knows that since a number 2 clue cause Bob to blind-play his *Second Finesse Position*, this must be an *Ejection*. The only type of *Ejection* that matches this kind of clue is a *Rank Choice Ejection*, so Cathy knows that her 2 must be playable and that her 2 must be exactly the red 2. Cathy plays the red 2.
```

**Comment by Zamiell** [comment]
> yeah i agree with this example.
> however note that the ejection has to be triggered with a rank clue so that it does not look like a 5CE

i guess that this clue could also just be getting Bob to write elimination notes for green 3. if that were the case, it should not cause an ejection

**Comment by Zamiell** [comment]
so maybe it is better to keep it for 2's and 5's to start
