### ISSUE TITLE
Speculative priority plays

### ISSUE THREAD

**Issue by aliblong** [Zamiell/hanabi-conventions#7]
Sometimes a playable card has multiple possible identities. The only convention that addresses this is [Rank Priority Prompts/Finesses in Dual-Color Variants](https://github.com/Zamiell/hanabi-conventions#rank-priority-promptsfinesses-in-dual-color-variants), and I don't think it's clear or good in its current state. Here are some points:
* The logical basis of the priority plays convention *for globally known cards* is that it provides strictly positive efficiency. When applying this convention to *partially known cards*, it really only enables efficiency in situations where the player has some context that makes the card *at least very probably* one of the *n* identities, and the convention *loses* efficiency in situations where no such context exists and a player >1 away has the connecting card.
* The wording should be "in multicolor variants" since it applies just as much to rainbow variants.

I therefore propose the following:
* "Priority plays" of *not-globally-known* cards are now "speculation plays".
* A speculation play shall induce a blind-play or prompt only from the very next player, and only in situations where that player sees no card in any other player's (excluding the speculative player, of course) hands that connect to any of the possible identities of the played card. This has the upside of preserving "speculation bluffs".

**Comment by Zamiell** [comment]
i like this

**Comment by Zamiell** [comment]
libster i want you to speculation play me

**Comment by Zamiell** [comment]
does this delete the average rank thing or does it build on top of it

**Comment by aliblong** [comment]
It wouldn't build on top of it so much as flesh it out. But florrat typed something in #brainstorming that might be a better proposal. I'll post it below.

**Comment by aliblong** [comment]
In variants with a rainbow suit, if you know that a playable card in you hand is either (say) blue or rainbow, and you priority play it, it only priority finesses if it turns out to be blue.

**Comment by aliblong** [comment]
One might extend this to dual-color variants by making a list of "priority suits" (perhaps one for each color to preserve symmetry.

**Comment by Zamiell** [comment]
RE: Dual color priority
You can't just define a primary suit per color (e.g. blue clue --> green suit), because in a situation where a card is clued blue with negative yellow, then it would be either purple or navy. So we would need to know the more granular priority between purple and navy. How about this:

* Rainbow - The base color has priority. (Florrat's idea.)
* All other variants with multi-color suits - The suits have priority from left to right.

e.g. in Dual-color: green, purple, navy, etc.
e.g. in Dual-color and rainbow: teal, lime, orange, etc.

**Comment by aliblong** [comment]
Yeah, that was my original idea, but it's kind of ugly in that it's asymmetric. Arbitrarily left suits become more efficient than right ones, so a new element of valuation is introduced (albeit with a small impact).

**Comment by Zamiell** [comment]
lib should i close this now?
