### ISSUE TITLE
Form of Trash Double Bluff Proposal

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#70]
![2019-10-25_0514](https://user-images.githubusercontent.com/48993588/67570569-9d17bb80-f6e6-11e9-98f0-4f9ef023c65a.png)

By current definitions, Trash Bluffs must only touch 1 card and Trash Double Bluffs must touch 2 

I believe this is an extension of Pestilent Bluff only with Trash.
Venusaur gives yellow to Charizard touching a single trash card Y3.
Mewtwo blind plays Y4 which matches the clue given to Charizard
Pikachu see's that, if he does nothing, Charizard will go on to misplay Y3 as Y5
Pikachu plays finesse position to heal the situation

**Comment by Dr-Kakashi** [comment]
Problems with this convention:
In the example above, Mewtwo only has 1 unclued card, so he was forced to play that card.  What about in a situation where a player's hand has no clued cards?  Currently, with our definitions, Mewtwo should immediately do an UTD.  

If we define this, then Mewtwo will have to look at Pikachu's finesse position to see if there's a playable card.  If there is, then blind play finesse position.  If there isn't, then do UTD.  

Issues with this: Players will be unable to do a UTD if the next player has a playable card in finesse position.

**Comment by Zamiell** [comment]
as you say, this proposal would add Headspace Convention overhead to every UTD that is given.
not a fan of that personally.

tangentially, i have not seen a single UTD since the recent reconfiguration, do people even do this move anymore?

**Comment by sjdrodge** [comment]
RE: the tangent, I've seen UTD come up several times in 3 player player games.

**Comment by Zamiell** [comment]
link the games

**Comment by sjdrodge** [comment]
That strikes me as a considerable amount of work for not much gain. I invite you to look through my play history if you feel otherwise.

**Comment by Zamiell** [comment]
i also saw two UTD yesterday as well

**Comment by Zamiell** [comment]
> If we define this, then Mewtwo will have to look at Pikachu's finesse position to see if there's a playable card. If there is, then blind play finesse position. If there isn't, then do UTD.

This algorithm doesn't jive with how we recently clarified 5CE to take precedence over triple bluff.
So lets not implement this for now.
/deny
