### ISSUE TITLE
Example Submission: Pink Elimination Finesse

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#71]
![2019-10-25_0825_(Pink_Elimination_Finesse)](https://user-images.githubusercontent.com/48993588/67583809-2b00a000-f701-11e9-9185-f5c322b9525b.png)

**Comment by Zamiell** [comment]
what is this, you just want me to add the screenshot to the doc or something?

**Comment by Dr-Kakashi** [comment]
Just an example submission, if you like it, you can add it to the doc for a visual tool.

**Comment by Zamiell** [comment]
i dont think this is a very good example for an elimination finesse since it requires knowledge of unrelated ancillary conventions, e.g. Pink Promise and the 5's Chop Move

**Comment by Zamiell** [comment]
feel free to submit an example that doesn't involve Pink Promise / the 5's Chop Move
/deny
