### ISSUE TITLE
Example Submission: Double 5 Pull

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#72]
![2019-10-26_1836_(Double_5_pull)](https://user-images.githubusercontent.com/48993588/67628283-ca1bb980-f81f-11e9-9a93-2a6bdd604737.png)

**Comment by Zamiell** [comment]
i added this: https://github.com/Zamiell/hanabi-conventions/blob/master/examples/5%20Double%20Pull.md
