### ISSUE TITLE
Delete the Weak Prompt

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#73]
it never works, fucking kill it

**Comment by sjdrodge** [comment]
I vote against this. Is it worth trying to avoid weak prompt situations? Yes. Do they sometimes come up anyway? Also yes. Is it true that they "never work?" Definitely not. I have successfully navigated weak prompt scenarios on both sides of the clue before.

**Comment by Zamiell** [comment]
Q: What is the **benefit** of the *Weak Prompt*?
A: It allows us to easily give save cards that are currently playable and about to be discarded. Without *Weak Prompts*, the team would have to sometimes let playable cards die. Letting playable cards die is unfortunate, but not *necessarily* a big problem, unless the other copy happens to be on the bottom of the deck. Thus, the cash value of **Weak Prompts* is it *prevents some percentage of bottom-deck losses**.

Q: Every convention has a benefit and a cost. What is the **cost** of the *Weak Prompt*?
A: The cost is three-fold:

1) Loss of tempo
* With *Weak Prompts* turned on, cards will not necessarily play right away from a *Prompt*.
* Not only does the team lose tempo in situations where a real *Weak Prompt* has occurred, but they also lose tempo if a **perceived** *Weak Prompt* has occurred.

2) High cognitive load
* Since **any** *Prompt* has the potential to be a *Weak Prompt*, players have to always keep this convention in the forefront of their minds. We refer to this as a *[Headspace Convention](https://github.com/Zamiell/hanabi-conventions/blob/master/misc/Meta.md)*. (In fact, the *Weak Prompt* is the thing that I chose to type up as the **primary example** of a *Headspace Convention* when I first invented these concepts back in March.)

3) High potential for mistakes
* Since *Weak Prompts* are so rare (more on that later), it is common for even experienced players to forget that they exist, assuming a normal *Prompt* and bombing a clued card.
* Separately, another thing to consider is when a **normal** *Prompt* happens that looks like a *Weak Prompt* - this has a huge potential for confusion.
  * For example, imagine that Bob plays red 3 into Cathy's red 4, and then Cathy discards. From Cathy's perspective, she is entertaining a *Weak Prompt*.
  * However, from other players on the team who don't see that intricacies of the situation, Cathy's discard looks like a *Scream Discard*. Now, the entire team becomes desynchronized and the cascading failure can lead to a loss.
* Yet another failure mode of the convention is when players do not account for the "last resort" component of a *Weak Prompt*:
  * When players are *Occupied*, it transforms a *Weak Prompt* into a normal *Prompt*.
  * Similarly, when the clue receiver is *Loaded*, it transforms a *Weak Prompt* into a normal *Prompt*.
  * Both of these contingencies are easy to miss. For example, after getting her chop clued and *Prompting* Bob to play a red 3, Cathy (luckily) remembers about the rare convention called the *Weak Prompt*. She mindfully does not play any of her cards and discards instead. But Cathy missed the fact that the clue was not a last resort, so it was a normal *Prompt* after all.

Q: How rare are *Weak Prompts*? In what percentage of games does the "payout" from the cost-investment occur?
A: *Weak Prompts* are rare - they only happen one in every 100-200 games.

Q: That is quite rare. Overall, is the *Weak Prompt* worth the cost?
A: *Headspace Conventions* that **also** happen to be rare are a fairly big red flag. We don't want to introduce a high level of cognitive load unless the convention has a lot of bang for the buck. In the rare cases where *Weak Prompts* provide value to the group, do they provide *enough* value in order to justify the complexity cost for all the other times? It is unclear, but the more and more games that I play, the answer seems to be trending further towards **no**. Even in the rare situation where a *Weak Prompt* can finally shine, the success rate of it working is extremely low (even with experienced players), because players forget that the move exists.

Q: Why was the *Weak Prompt* invented?
A: When Hyphen-ated invented the *Weak Prompt*, the group was **exclusively** playing No Variant and Rainbow. As you know, these variants are fairly easy, and our win rate was extremely high, somewhere around 90%. The goal of the group was to push the win rate as high as humanly possible. By incorporating *Weak Prompts*, it helped us increase the win rate a few percentage points by preventing some bottom-deck losses.

Q: How is the situation now different than when the *Weak Prompt* was invented?
A: In a few different ways:

1) The variants
* Nowadays, we play a slew of much more difficult variants than just No Variant and Rainbow. Subsequently, the goal of the convention framework has also shifted. We no longer need to optimize the convention framework for a few-more-percentage-points of win-rate in trivial variants.

2) The framework complexity
* Nowadays, we have about five times the total amount of moves that we did back then. *Weak Prompts* are not so bad if all you play with is basic *Finesses* and *Bluffs*. In our current environment with *Priority Finesses*, *Scream Discards*, and *5 Color Ejections*, it is a whole different story.

3) The skill level of the group
* Nowadays, the group hosts a wide range of skill levels. We have plenty of fresh beginners and most of the players are intermediate. Expert play is uncommon / rare.
* The framework should adjust accordingly. If we are on the fence about deleting a convention or simplifying a way of doing things, then we need to tend towards the side of simplifying. The exception is when a convention is common and provides a lot of value. For example, *5 Stalls* have been proposed as something to consider deleting, but 1) they happen in almost every single game, 2) they get a huge amount of observable value. Notice that these two points do **not** apply to the *Weak Prompt*.

**Comment by Zamiell** [comment]
Q: What does play look like with *Weak Prompts* turned off / deleted?
A: Several things:

1) If the card is a playable 4, players can simply let it die. This is something that we do already in hard variants (since *Weak Prompts* are already turned off in hard variants). 4's suck and it is not worth bending over backwards for this shit.
2) If it can be seen that the red 3 is trapped behind an unplayable card and the red 4 will be discarded soon, players can plan ahead and give a tempo clue to the red 3 early.
3) Players can utilize one of our many *Chop Moves* to save the playable card indirectly. Note that the total amount of *Chop Moves* that exist in the framework is much more numerous than when the *Weak Prompt* was initially invented.
4) In some situations, other players on the team can help with a post-*Prompt* fix. For example:
  * Alice uses the last clue to clue Bob's red 4 on chop.
  * Bob discards.
  * Cathy sees that this will *Wrong Prompt* Donald, so Cathy gives a red *Fix Clue*.
5) Notice that in some other situations, even Bob can do a post-*Prompt* fix. For example:
  * Alice uses the 2nd to last clue to clue Bob's red 4 on chop.
  * Bob knows from context he has the red 4.
  * Bob sees that this will *Wrong Prompt* Donald, so Bob gives a red *Fix Clue*.

**Comment by sjdrodge** [comment]
You've convinced me. However, as a general point, if the only concerns were about cognitive load and group skill level, a strong alternative solution would be to simply recategorize the convention to a higher "level" in the docs.

The argument(s) that this rarely-used convention does not offer significant enough benefit in the most commonly played variants these days is convincing.

**Comment by alercah** [comment]
The levels are basically meaningless at the moment. It might be nice to reorganize the doc to allow them to be something like "let's play level 3 only", but that would require it to be fairly straightforward to remember which level conventions are. At the moment, there are too many inconsistencies. A few examples: 5CE is "rarely used" based on being in level 5, and layered finesses are level 2 but layered GDs are level 4 for some reason. That should probably be a separate conversation, though.

**Comment by Zamiell** [comment]
> The levels are basically meaningless at the moment.

Sounds like a hyperbole to me. Just because you think some particular sections are mismatched doesn't mean that all of the levels are "meaningless". I've painstakingly separated each section in what I believe to be the correct level. If you think that a section needs to be moved, you can submit an issue.

>  "let's play level 3 only"

This is something we already do every time we play with a beginner, agreeing to only play with conventions that are in the beginner doc, or only agreeing to play with level 2 conventions, etc.
