### ISSUE TITLE
Redo Positional Clues with 5CE Logic

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#74]
You can now *Double Finesse* / *Triple Finesse* / *Quadruple Finesse* in a variant with a null suit, as long as each player would only have to blind play 1 card.

**Comment by sjdrodge** [comment]
We should be careful with this one. Null is very hard to solve without a high availability of positional clues, and we should therefore not be as restrictive as we are with 5CE.

**Comment by Zamiell** [comment]
> * Any clue that looks like one of the following is now a *Positional Clue* instead:
>   * a *Double Finesse* or a *Triple Finesse* where one player has to blind-play **two or more** cards
>   * a *Double Bluff* or a *Triple Bluff*
>   * an *Ejection* or a *Discharge*
>   * a *Rank Choice Finesse* or a *Rank Choice Bluff*
>   * a *5 Pull* or a *Trash Pull*
>   * a *Trash Push*
>   * a clue that has no "normal" conventional interpretation
