### ISSUE TITLE
Proposal: Reword double discard avoiding situation section.

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-conventions#76]
Currently, it's:

> If the player before you just discarded a card (say the red 4), and you don't see that card in anyone else's hand, there is a possibility that you could have that same card on your chop. 

However, a better wording would be:

>If the player before you discarded or misplayed an unplayed card (say the red 4), then you are not allowed to discard if there is a possibility that you could be discarding a copy of that card. 

Perhaps with a bit better wording. But the updated definition takes care of the situations when player has known safe discards, knows if they have a copy of that card, or has sufficient negative information about their chop.

**Comment by Zamiell** [comment]
i rewrote this section now
