### ISSUE TITLE
Free Choice

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#79]
* *Free Choice* is defined as when a player has two or more options to clue a card and all of the options would **only** touch the same card(s).
* For example, in a no variant game:
  * Bob's hand is, from left to right: red 1, blue 4, blue 4, yellow 4, yellow 4
  * If Alice wants to give a *Play Clue* to the red 1, Alice is said to have a *Free Choice* between red and number 1, since both of those clue types would **only** touch the red 1.
* Since rainbow cards are touched by any color, players will often have a *Free Choice* on how to clue a rainbow card.
* For example, in a rainbow game with 6 suits:
  * Bob hand is, from left to right: rainbow 1, blue 4, yellow 4, green 4, yellow 4
  * If Alice wants to give a *Play Clue* to the rainbow 1, Alice is said to have a *Free Choice* between red, purple, and number 1, since all of those clue types would **only** touch the rainbow 1.

**Comment by alercah** [comment]
What's this proposing to change? Is this just a new definition?

**Comment by Zamiell** [comment]
its a section i added to the doc today. it doesn't change anything

**Comment by alercah** [comment]
I'm a tad confused, what's the point of an issue if the change has been made? Shouldn't it be mostly for discussing change proposals/desired changes?

**Comment by Zamiell** [comment]
in case i made a typo or i missed anything

**Comment by alercah** [comment]
When will you close the issue off as done?

**Comment by Zamiell** [comment]
after it is open for a while
