### ISSUE TITLE
The Phantom Finesse (added to the deleted conventions page)

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#82]
### Implied Color Truth

* This convention only applies to variants with a rainbow suit.
* By default, players assume that color clues indicate non-rainbow cards.
* For example, in a 3-player game:
  * All of the 1's are played and there are no cards in the trash.
  * Alice clues blue to Bob, touching a blue card on his slot 1 as a *Play Clue*.
  * Bob knows that technically, this could be a *Play Clue* on a blue 2 or a rainbow 2, but in general he can assume that it is a blue 2.
  * Cathy has a blue 3 on chop and is in danger of discarding it.
  * Thus, Bob assumes that he has a blue 2 and clues blue to Cathy as a *Play Clue* on the blue 3.
* The Hyphen-ated group has never actually used this convention, but it is documented here since it is played with on Board Game Arena.

### The Phantom Finesse

* This convention only applies to variants with a rainbow suit.
* Sometimes, players will have a card to play and see that a *Finesse* is available to perform. However, if they play the card, then the *Finesse* will go away. In these situations, players perform the *Finesse* and then play their own card later.
* Rarely, players can even do this kind of a *Finesse* on **the same suit that they have in their own hand**.
* For example, in a 3-player no variant game:
  * All of the 1's are played on the stacks.
  * Alice clues red to Bob, touching a red 2 on his slot 1 as a *Play Clue*.
  * Bob knows that he has the red 2 and could play it right now.
  * Bob sees that Cathy has the red 3 on her *Finesse Position* and that Alice has the red 4.
  * Bob clues red to Alice, touching the red 4 as a *Finesse* on the red 3.
  * Cathy discards.
  * Alice discards.
  * Bob plays the red 2.
  * Cathy blind-plays the red 3.
  * Alice plays the red 4.
* In a rainbow variant, if the group is playing with *Implied Color Truth*, then this style of *Finesse* has the potential to fail if the player initiating the *Finesse* actually has a rainbow card.
* If this occurs, it is called a *Phantom Finesse*. The *Finesse* will still work but the leading card does not actually exist.
* For example, in a 3-player rainbow game:
  * All of the 1's are played on the stacks.
  * Alice clues red to Bob, touching a red 2 on his slot 1 as a *Play Clue*.
  * Bob knows that he has either the red 2 or the rainbow 2. Both are playable and could play it right now.
  * Bob sees that Cathy has the red 3 on her *Finesse Position* and that Alice has the red 4.
  * Bob uses *Implied Color Truth* to assume that he has the red 2. Subsequently, Bob clues red to Alice, touching the red 4 as a *Finesse* on the red 3.
  * Cathy discards.
  * Alice discards.
  * Bob plays his red card and it turns out to be the rainbow 2.
  * Cathy knows that Bob was using *Implied Color Truth* to assume that he had the red 2. Thus, since red 4 was clued, Cathy knows that at the time of the clue, she must have had a red 3 in her *Finesse Position*. She marks it as such and discards.
  * Alice also knows that Bob was using *Implied Color Truth*. It would not make sense for Bob to defer playing the red 2 in order to clue the red 3 himself. Thus, her red card must be a red 4 and Bob was trying to *Finesse* Cathy's red 3. Alice marks the card as such as discards.
* The Hyphen-ated group has never actually used this convention, but it is documented here since it is played with on Board Game Arena.

**Comment by NoMercyO** [comment]
Looks good. I can see this being used in 1 in 1000 games, so it is best off in deleted or Rarely used/lvl5. (though i guess thats what deleted really means now).

**Comment by Zamiell** [comment]
i think you misunderstand - no-one in our group is ever meant to perform a phantom finesse. this is just documenting the way that BGA plays, not the way that we play.

deleted means that it is undefined and/or expressly illegal

**Comment by NoMercyO** [comment]
Because noone would ever do something illegal.

In cases where failing to invoke implied color truth would violate save principle i would do so. This is far safer than some sort of speculating color truth scream, and superior to violating save principle.

Example 3 player rainbow.
Alice clues Bob slot 3 red (r2/m2)
Bob sees Cathy's chop is r3, no other r3 and no clues for Cathy to likely give. 

Bob lacks game context to infer if cannot be r2 (eg r1 came down quite recently from Alices hand,  Cathy has been busy doing things beyond cluing a line r2 play clue). So while Bob sees he could have m2, he invokes the sanctity of save principle and uses implied color truth. 

There is a reason we allow this in 2 player. The cases where it applies with more players is miniscule in comparison but the same logic can exist.

**Comment by Zamiell** [comment]
> In cases where failing to invoke implied color truth would violate save principle i would do so.

Conventionally I think you should not.
The precise example that you just typed out is already documented here: https://github.com/Zamiell/hanabi-conventions/issues/80
In this example, I have tentatively specified that Bob should just play and not worry about the card on the next person's chop.

Reasons why not:
* The *Unnecessary Generation Discard* is a documented thing. So I see how that style of thinking could be extended to this situation. (But in that situation Alice would be discarding instead of cluing the card directly, so I feel it is different.)

Reasons why:
* Alice could just *Chop Move* the red 3 somehow, let Bob discard, and then someone else would clue the red 2 later.
* As you say, the cases where it applies with more players is minuscule in comparison. So, it is not worth the confusion of Cathy **always** having to consider that this style of clue is being given, just in order to get a fraction better win% in a minuscule amount of games.
