### ISSUE TITLE
Delete Reverse Finesse Exception for 5CE

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#83]
If we deleted it, then the following becomes possible:

* Alice clues red to Cathy (touching a red 5)
* Bob blind-plays blue 1 as 5CE
* Cathy clues red to Emily (touching a red 2)
* Donald blind-plays red 1 as a *Finesse*

In the current configuration, this sequence would not work, because Bob would wait for Donald to blind-play the red 1 as a big *Reverse Finesse*.

**Comment by alercah** [comment]
I included this as part of #84; I think we should have that as one discussion.
