### ISSUE TITLE
5CE Reverse Finesse Exception: Expand, Clarify, or Delete

### ISSUE THREAD

**Issue by alercah** [Zamiell/hanabi-conventions#84]
**Option :+1: :** The current 5CE exception for *Reverse Finesse* is clarified that it applies whenever Bob will not be the first player blind-playing.
**Option :eyes: :** The current 5CE exception for *Reverse Finesse* is clarified that it applies only when the first player blind-playing.
**Option :-1: :** The current 5CE exception for *Reverse Finesse* is deleted.

Current 5CE text says that it is not a 5CE if the clue that initiates it looks like a *Reverse Finesse*. Example:

> Alice clues purple to Cathy, touching her p5. Bob sees that p1 is played and Donald has p2 on *Finesse Position.*
>
> Although Bob would have to blind-play the p3 and p4, because the clue looks like a *Reverse Finesse*, it is a *Reverse Finess* and not a *5-Color Ejection*.

If Donald and Cathy's positions are swapped, this is not a *Reverse Finesse* because Cathy will now blind-play before Donald's turn. Thus Bob must blind-play from *Second Finesse Position*.

When I asked for clarification about an issue in IRC, (see below) Stephen pointed out that this was not the intent of the exception, at least from his point of view:

> Stephen: that is not the intended formulation, no
> Stephen: iirc NoMercy and myself are the ones who lobbied for the "exception" about the blind plays starting with a player other than Bob
> Stephen: at some point in writing the actual convention wording this got translated into "reverse finesse"
> Stephen: I felt it was equivalent, but if it is not, then it should be reworded

> Stephen: I much prefer the formulation that it's only an ejection if both conditions are met 1) the blind plays would start with Bob 2) Bob would have to provide 2+ blind plays

This was the example I had asked about, because the term "*Reverse Finesse*" is not well-defined for *Multiple Finesses*:

> Alice clues purple to Donald, touching his p5. Bob sees that no purple cards have been played, Cathy has p1 on *Finesse Position*, and Evelyn has p2 on *Finesse Position*.
>
> Bob sees that it could possibly be a *Quadruple Finesse* where Cathy plays p1, Evelyn plays p2, and then he plays p3 and p4. But he is unsure about whether it counts as a *Reverse Finesse* because Donald needs to wait for Evelyn to play before playing the p5.

After further discussion, though, I realized that this interpretation would mean that any *Finesse* requiring Bob to blind-play 2+ cards would count as *Reverse*, since the clue recipient will have to wait to for Bob's second blind-play, so this would mean that there is no *5CE*, which is absurd.

So the only sensible way to interpret the current text is that you only look at the first component to decide if the exception applies. If the first blind-play comes before the clue-recipient, it can be *5CE*. Otherwise, it cannot. This is option :eyes:. 

Option :+1: is to match Stephen's intent, that *5CE* does not apply unless the player who's playing next is going to immediately blind-play.

When this was brought up, Zamiel suggested deleting it entirely, which is option :-1:.

> it would be nice for
> - alice clues red to cathy (touching a red 5)
> - bob blind plays blue 1 as 5CE
> - cathy clues red to emily (touching a red 2)
> - donald blind plays red 1 as a finesse
>
> this sequence would not work in the current configuration because bob would wait for donald to play red 1

**Comment by Zamiell** [comment]
i'd prefer that we avoid "voting with emojis" style posts in the future, it seems silly. someone who bothers typing the way they feel (along with justification) should be given exponentially more weight than someone who just cruised by a clicked a button. furthermore, only a handful of people read these issues, so tallying up the way people feel manually is trivial.

more to the point, if we delete the Reverse Finesse Exception, then the following becomes possible:

* Alice clues red to Cathy (touching a red 5)
* Bob blind-plays blue 1 as 5CE
* Cathy clues red to Emily (touching a red 2)
* Donald blind-plays red 1 as a *Finesse*

In the current configuration, this sequence would not work, because Bob would wait for Donald to blind-play the red 1 as a big *Reverse Finesse*.

Stephen says:
> iirc NoMercy and myself are the ones who lobbied for the "exception" about the blind plays starting with a player other than Bob

I don't remember the related discussion, perhaps mercy and stephen can remember

**Comment by NoMercyO** [comment]
If people were looking at me to turn the tides then prepare to be dissapointed. I'm in two minds, between thumb up and down.

Main reason for thumbs up:
- preserving big finesses is good is the downside is minimal
- it has seemed to far pretty common (roughly 50/50) that when performing 5CE there is more than one 5 to choose from. 

Main reason for thumbs down
- most times a finesse to 5 is blocked by a 5CE a finesse to 4 is available so the loss is minor
- a decent number of ejections seem to be for good reasons beyond just a 2-for-1, as the ejected card is hard to 1-for-1. 
- Practically speaking this will block more ejections than it allows big finesses on a purely likelihood of card configuration. 

I think ultimately for now i prefer thumbs up. 
It follows from the same principles that governs typical bluff vs finesse logic, and there should be a different, perhaps less optimal 5CE to pick that isnt blocked some number of the time. 
If practically we find too many 5CEs are getting blocked then this can be revisited.

**Comment by Zamiell** [comment]
other notable reason for thumbs down is that it is a simplification
e.g. less rules, less exceptions, less words in the doc

**Comment by NoMercyO** [comment]
I dont think that truly applies in cases, such as this, of a convention that directly conflicts with another. A line between the conflict has to be drawn somewhere and either end is obviously not possible as that is the same as deleting one of the conventions. 

I dont agree that one line here is simpler than the other. Or to put it another way, if we were to NOt allow and reverse finesse consideration that is important enough distinction from my intuition that it would probably need to be clarified in the doc anyways.

**Comment by Zamiell** [comment]
right now the doc is written as:

> * If the very next player sees that they would have to blind-play two or more cards in their hand to fulfill the Finesse, then a Finesse is unlikely. Instead, players agree that this signals an Ejection and that the next player should play their Second Finesse Position.
>   * The exception for the "two or more blind plays" rule is when the next player sees that it could be a Reverse Finesse. The normal rule of "if it could be a Reverse Finesse, it is" always applies, even if a player would have to blind-play two or more cards.

if we delete the second bullet point, *nothing needs to be clarified*. you just always do the "2+ blind plays" rule exactly as written

**Comment by alercah** [comment]
*5CE* is a [*Callout Bluff*](https://github.com/Zamiell/hanabi-conventions/blob/master/misc/Bluff_Types.md). It's a lie to Cathy, not to Bob. This is why Bob doesn't need to be set up to play already.

When Alice clues Cathy to trigger a potential 5CE, Bob's thought process can be something like this, and this works naturally:

* That's a green colour clue to a 5. It looks like a *Play Clue*, so it's a *Finesse* probably.
* I see that g1 is played and Donald has g3 on *Finesse Position*. So this looks like I have g2 and g4 on *Finesse Position*.
* But this would require me to blind-play two cards, and it was a colour clue to a 5, so it's actually a *5CE*.
* *(If we agree to the exception):* But I'm not the first person to play, so it's actually a *Finesse*.

I suppose that the thought pattern could be something like:

* That's a green colour clue to a 5. It looks like a *Play Clue*, so it's a *Finesse* probably.
* I see that g1 is played and Donald has g3 on *Finesse Position*. So this looks like I have g2 and g4 on *Finesse Position*.
* I have g2, so I need to blind-play.
* But actually I need to blind-play two cards and it's a colour clue to a 5, so it's actually a *5CE*.

This line of thinking doesn't work if we don't have the exception, because Bob is considering *5CE* in the wrong place. Personally, I find the first line more natural and intuitive, but I can understand that others might not.

**Comment by Zamiell** [comment]
i think the second is more intuitive, but i would word it like this:

* That's a green colour clue to a 5. It looks like a Play Clue, so it's a Finesse probably.
* I see that g1 is played and Donald has g3 on Finesse Position. So this looks like I have g2 and g4 on Finesse Position.
* 2>1, so its 5CE

**Comment by sjdrodge** [comment]
I don't think there's a significant difference in complexity when the "exception" is instead framed simply as one of two criteria for determining finesse vs. ejection. i.e. When Alice gives a color clue to a 5, if Bob would be: 
- blind-playing immediately
- providing 2+ blind-plays

Bob ejects instead.

Because I think the complexity difference is trivial, I think we should simply let the merits of the two approaches decide the issue.

The original justifications for the two criteria formulation were:
1. To preserve more big finesses
2. To have the player thought pattern operate similarly to the bluff vs. finesse thought pattern involved in other conventions

After playing more with the convention, I think the single criterion formulation is probably the better one. That said, a strong compromise position may exist. If multiple 5CEs are available, and a player deliberately chooses one that has more matching cards in finesse position (and the choice does not have some other obvious upside like setting up a follow-up clue, touching a 5 that is already on chop, or touching additional useful cards), then a context read should be made that a finesse is intended instead of an ejection. I think we originally shied away from this solution on the grounds that it involves too much grey area, but it's worth reconsidering the idea now that we have more practical experience with the convention.

**Comment by Zamiell** [comment]
> KyleToday at 6:27 PM
> Why the exception to reverse finesses with 5CE?
> It seems equally unlike of being a reverse finesse if it calls for 2 or more blind plays.

i'm inclined to agree, the logic is more or less the same

**Comment by sjdrodge** [comment]
The reasoning is that this gives us a simple rule for navigating situations where there is a choice of multiple 5CE while maintaining as many big true finesses as possible. Imagine that all the 1's are played on the stacks and Alice has a choice of using Donald's r5 or b5 for a 5CE on Bob. If Cathy has an r2 in finesse position, then it more likely that a true finesse on the reds exists than it is a true finesse on the blues exists. As a consequence of disallowing the use of r5 for a 5CE due to the presence of r2, we allow ourselves to give the true finesse if it exists in this scenario. Is this the only possible solution to try to get the best of both worlds? Not at all, but it is a simple way to do so.

**Comment by Zamiell** [comment]
> That said, a strong compromise position may exist. If multiple 5CEs are available, and a player deliberately chooses one that has more matching cards in finesse position (and the choice does not have some other obvious upside like setting up a follow-up clue, touching a 5 that is already on chop, or touching additional useful cards), then a context read should be made that a finesse is intended instead of an ejection. I think we originally shied away from this solution on the grounds that it involves too much grey area, but it's worth reconsidering the idea now that we have more practical experience with the convention.

please no, lets keep things simple

**Comment by Zamiell** [comment]
> The reasoning is that this gives us a simple rule for navigating situations where there is a choice of multiple 5CE's in a way that maintains our ability to give the true finesse that is most likely to be available. For example, suppose all the 1's are played on the stacks and Alice has a choice of using Donald's r5 or b5 for a 5CE on Bob. If Cathy has an r2 in finesse position, then it more likely that a true finesse on the reds exists than it is for blues. As a consequence of disallowing the use of r5 for a 5CE due to the presence of r2, we get to give the true finesse if it exists.

this argument seems fairly convincing to me, which is slightly confusing since you favor the thumbs down option overall

**Comment by Zamiell** [comment]
also as a semantic aside, a move that has two criterion must be more complex than a move that has one criterion (literally twice more complex), so i'm not sure i understand your contention that there is no appreciable different in the complexity between the two options

**Comment by sjdrodge** [comment]
> as a semantic aside, a move that has two criterion must be more complex than a move that has one criterion - literally twice more complex. so i'm not sure i understand your contention that there is no appreciable difference in the complexity between the two options

I simply mean there's no appreciable difference for me in mental load between a one item and two item checklist, particularly when both items are easy to check and are frequently checked during the use of other conventions. I believe framing it as a main principle with an exception tends to create "artificial" mental load compared to thinking of it simply as a two item checklist. Perhaps this is peculiar to my own psychology, however.

**Comment by sjdrodge** [comment]
Another candidate for compromise: if two 5CE's are available, Alice must choose the one that has the fewest matching cards in finesse position (in the set of cards mutually visible between Alice and Bob). This means that in my previous example, if Donald's finesse position includes any of r2, r3, or r4 (not just r2), then Alice must choose to use b5 for a 5CE, and if she chooses r5 instead, it is a true finesse.

**Comment by Zamiell** [comment]
> Another candidate for compromise: if two 5CE's are available, Alice must choose the one that has the fewest matching cards in finesse position (in the set of cards mutually visible between Alice and Bob).

yeah but what if one 5 is on slot 1 and one 5 is on slot 5 (chop).
im (obviously) going to want to do the 5CE on the chop 5, and now i can get fucked if there is a matching 1. obviously that is the worst case scenario but im just pointing that out

> and the major downside is that this check is complicated and not present in any other conventions

https://www.youtube.com/watch?v=ZhIsAZO5gl0

**Comment by aliblong** [comment]
I think we're already way in the weeds on this convention. I'm in favor of a simpler reformulation as follows:

**If the player before you play clues a 5, and it requires at least *three* plays from you, at least *two* of which are blind plays, it's 5ce.**

I believe this better approximates the "unlikeliness" estimation that turns a finesse into something else, and I don't think it needs to have any of the current 5ce exceptions (reverse finesse exception, recluing a 5 exception).

**Comment by Zamiell** [comment]
we already decided against the "3 blind plays" in favor of the "2 blind plays" rule back in september iirc

**Comment by aliblong** [comment]
Well, if you read closely, my post does not say "3 blind plays". Let's maybe see what people think of it.

**Comment by aliblong** [comment]
> Another problem with the fix clue, are they totally off when counting the blind play?

If the lie would be a good lie (and such a lie usually would be), then it should be considered on even footing with a configuration where there's no lie. So in your examoles, Bob should treat them as regular finesses.

**Comment by sjdrodge** [comment]
I think 5CE on already clued 5's should either be disallowed or the requirements should be higher. Disallowing natural 2-for-1 clues in favor of 1-for-1 ejections is not where we want to be. As for the rest of it, I'm still totally fine with the single criterion 5CE formulation over the multiple criteria ones.

**Comment by aliblong** [comment]
> I think 5CE on already clued 5's should either be disallowed or the requirements should be higher. Disallowing natural 2-for-1 clues in favor of 1-for-1 ejections is not where we want to be.

I think losing finesses or double bluffs in this way would be quite rare with my definition since it requires an additional blind play or prompt, so I'd still lean toward not complicating things with an exception. But it's not a big deal either way.

**Comment by alercah** [comment]
I don't think losing a 2-for-1 to a 5CE is likely to be that common. A single player must need to blind-play two cards towards the 5 for it to count as 5CE, and they need to be in order. While certainly can happen, it's far more common that the cards to be blind-played are distributed among players. Even in 3 players, it's only 1/4 chance that a given two missing cards are going to be both held by the same player and in the right order. There's some small chance that you could clue the 4 (usually a *Self-Finesse* unless there is a *Prompt* involved too) instead and let the 5 get played later by deduction. But more importantly, in 4+ player games, there's another implicit condition to consider, which is that there may be multiple players capable of giving the *Finesse* clue, in which case you only lose the finesse when it's not possible for someone else to give the clue.

I'm starting to agree with Zamiel that we should lean towards simplicity unless and until we see a pattern of losing significant value (not just one game) to this.

**Comment by alercah** [comment]
Oh, I forgot to put in my other thought: All that said, I think there's another argument against allowing 5CE on reclues: recluing requires that we have had the 5 clued in the first place, and there to be no other cards that could take focus, so it's less common and more likely to happen later in the game. But later in the game, ejections are also less useful because good cards are less likely to make it past finesse position.

**Comment by Zamiell** [comment]
looking like the consensus is thumbs down, meaning:
* delete the reverse finesse "exception"
* keep the "exception" where 5CE only applies on brand new touched cards

**Comment by Zamiell** [comment]
**5's Color Ejection (5CE)** (change)

```
* The "*Reverse Finesse*" exception is deleted. Now, when a brand new 5 is touched and you need to determine whether or not it is a 5CE, all you have to do is count the number of blind-plays that you would have to play out of your own hand.
```
