### ISSUE TITLE
Finesse terminology clarification

### ISSUE THREAD

**Issue by alercah** [Zamiell/hanabi-conventions#86]
It's often the case that we speak informally of a "*Finesse* to Cathy through Donald's hand" or similar, but I always get confused about who actually plays which role here, and probably use the terms inconsistently. It would be nice to adopt standard terminology to let us speak more efficiently of complex clues.

I always assumed that the term "finesse" is from Bridge, where you speak of "a finesse to the Dummy" in order to let the Dummy (in this case) win a trick with a card that couldn't win otherwise. In Hanabi, the most obvious equivalent would be that if Alice gets Bob to play with a clue to Cathy, this is a "*Finesse* to Bob" as it gets Bob to play a card that otherwise wouldn't play. But this is awkward as the clue is already "to" Cathy.

An alternative might be to call it a "*Finesse* on Bob", so then you can say "a *Finesse* on Bob to Cathy", which lines up nicely with the fact that Cathy makes the last play.

I don't really have a strong opinion though, I just want standard language that we can all agree on.

**Comment by Zamiell** [comment]
> An alternative might be to call it a "Finesse on Bob"

this is already the terminology we use.

when alice causes bob to blind play a card from a *Finesse*, we say that bob was *Finessed*, so the finesse was ON bob

when alice causes bob to blind play a card from a *Bluff*, we say that bob was *Bluffed*, so the bluff was ON bob

**Comment by sjdrodge** [comment]
In Bridge, one "finesses" the player who is hoped (or known) to have the missing card. "A finesse to the Dummy" is not part of the common parlance. It therefore seems quite natural in Hanabi to speak of finessing the player who blind-plays, and this matches the usage I see in the document as well as our community at large.

**Comment by Zamiell** [comment]
closing this since alercah isn't responding
/idle
