### ISSUE TITLE
Very Ambiguous (3 Suits)

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-conventions#88]
* This convention only applies to Very Ambiguous (3 Suits).
* A blue color clue means to play the *Second Finesse Position* (as before the blue color clue was given).
* Blue color clues are only to be used as a last resort, meaning that if it is possibly to cleanly clue the Second Finesse Position with a number clue, then players must do so.
* Cards touched with blue do not count as being touched for the purposes of discarding, *Good Touch Principle*, and so forth.

**Comment by jakestiles** [comment]
Perhaps also add:

Unnecessary Blue Clue Finesse:
If Alice uses Blue to get second finesse from Cathy's hand, when Alice could have used a number clue, Bob blind plays finesse position one. 
Cathy will trust that it is a finesse, will still play second finesse, then will realize it was an unnecessary blue clue finesse.

**Comment by Zamiell** [comment]
well that isn't a *Finesse*, that is a bluff

**The Unnecessary Blue Bluff* (by Jake)

* Blue color clues are only to be used as a last resort, meaning that if it is possibly to cleanly clue the *Second Finesse Position* with a number clue, then players must do so.
* Subsequently, if a blue color clue is used when a number clue was available, the clue giver must be trying to communicate something extra.
* In this situation, the next player should blind-play their *Finesse Position* card as a *Known Bluff*.
* The next player after that will assume that a *Finesse* occurred. However, once they their *Second Finesse Position* card and see that it is an unrelated suit, then they will know that an *Unnecessary Blue Bluff* occurred.
