### ISSUE TITLE
Double Play Self Ejection & Double Play Reversed Ejection

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#89]
- Like a normal Double Play Ejection, if the next player received another clue (always a fill-in clue) on the known playable card, it is a signal as an Ejection; then he should blind-play his Second Finessed Position as a Double Play Self Ejection.

- However, if the next player (Bob) sees his next player (Cathy) has a playable card on her Second Finessed Position, then he should assume the Ejection is on Cathy and play his double clued card as normal. On Cathy's turn, she is surprised Bob blind-played nothing on his turn, and then she realizes it is a Double Play Reversed Ejection and blind-plays her Second Finessed Position (even Bob has a playable card on his Second Finessed Position, since DPRE takes precedence over DPSE).

**Comment by Zamiell** [comment]
seems fine, kind of flows naturally from how OOP works

**Comment by jakestiles** [comment]
Has to be a fill in (as you already said) or it conflicts with double tempo clue inversion. Not that I ever see double tempo clue inversion.

**Comment by Zamiell** [comment]
double tempo clue inversion is only when something is clued twice in a row, so that seems unrelated

**Comment by Zamiell** [comment]
it is unclear to me if this is worth documenting

**Comment by Zamiell** [comment]
seems kind of rare, i dont know if it is worth putting it in the doc, we can document this in the future if it actually becomes used at a decent frequency
/deny
