### ISSUE TITLE
Double Play Double Bluff (or Double Ejection) & Double Play Ejection clarification

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#90]
- (Clarification) Double Play Ejection is defined as if **only** one playable is retouched by another clue.

- If two or more playable cards are retouched by another clue, then it is a signal as a Double Bluff (or defined as Double Ejection).

![double play double bluff](https://user-images.githubusercontent.com/50160641/68071518-2a79a080-fdb6-11e9-881e-7de6964fba61.png)

If IAMJEFF gives blue clue to Zamiel, and then it triggers a (Reversed) Double Play Double Bluff in this case. (ID: 62193)

**Comment by Zamiell** [comment]
It is clear in this case because Jeff has the ability to clue number 2 to initiate RDPE.
However, it seems pretty edge-casey and rare.

**Comment by iamwhoiamhahaha** [comment]
what is RDPE?

**Comment by Zamiell** [comment]
reverse double play ejection

**Comment by iamwhoiamhahaha** [comment]
ohh so you dont like the definition of DPE with touching only one card?

**Comment by Zamiell** [comment]
I'm undecided, it seems relatively not very useful though

**Comment by Zamiell** [comment]
I guess it would flow naturally from the new Trash Double Bluff formulation though

**Comment by iamwhoiamhahaha** [comment]
Yeah that's the point. Both trash double bluff and double play double bluff are 1 for 0 clue if players blind-play nothing. They works with the same function I think

**Comment by Zamiell** [comment]
is this worth documenting?
the situations in which a player has 2 or more playable cards in their hand AND there is a single clue that can touch both cards at the same time has got to be extremely rare, right?

**Comment by Zamiell** [comment]
since this seems kind of rare, i dont know if it is worth putting it in the doc
we can document this in the future if it actually becomes used at a decent frequency
/deny

**Comment by iamwhoiamhahaha** [comment]
O I just realized I "invented" *Replay Double Ignitions* in 2019 lol
https://github.com/hanabi/hanabi.github.io/issues/460
