### ISSUE TITLE
Positional Clue for Brown Suits Examples

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#91]
![brown positional clue 1](https://user-images.githubusercontent.com/50160641/68084092-04aed300-fe6c-11e9-814f-6c6f9a81208a.png)

![brown positional clue 2](https://user-images.githubusercontent.com/50160641/68084093-07a9c380-fe6c-11e9-8fd6-6a3b3f64d48b.png)

**Comment by Zamiell** [comment]
can you post it in the right thread?

**Comment by Zamiell** [comment]
this one https://github.com/Zamiell/hanabi-conventions/issues/56
