### ISSUE TITLE
Clarification: Prompts in Multi-Color Variants

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#93]
![](https://cdn.discordapp.com/attachments/456214043351580674/641240246507405312/2019-11-05_11-26-39.png)

![](https://cdn.discordapp.com/attachments/456214043351580674/641240253000318986/2019-11-05_11.26.47.png)

> In the actual example above, our conventions specify that slot 4, the true red card, is prompted.
Right?

wrong. the leftmost red card is prompted, because players do not use negative clues for the purposes of determining which card to play into a prompt

We had this happen today:
![2019-11-08_0055](https://user-images.githubusercontent.com/48993588/68463434-77e57b80-01c3-11ea-85f8-8a0083275c56.png)
![2019-11-08_0055_001](https://user-images.githubusercontent.com/48993588/68463444-7ae06c00-01c3-11ea-9850-94cae209a041.png)

So Fireheart should play slot 2 according to what Zam said.  Can we have some sort of clarification added to the doc on this?

**Comment by Zamiell** [comment]
I added the following to the doc:

> (Players are **not** supposed to use information from negative clues.)

**Comment by aliblong** [comment]
Fireheart should play slot 4 here. A 1 clue says to play the yellow suit down, so y5 is now trash, and slot 4 is therefore y24. Fireheart sees that Valetta gave the clue while Kakashi has y2 on finesse position, so the interpretation where Fireheart has y4 on slot 4 and any rainbow on slot 2 should be preferred to the interpretation where Fireheart has exactly y4 and the other copy of y2 on slots 2 and 4, respectively.

**Comment by alercah** [comment]
Prompts take priority over finesses. The fact that there is a y2 visible on finesse position is irrelevant if there is a prompt interpretation, which there is here.

I like the addition, but I think it should be added as an example:

- The amount of negative information is not taken into account.
    - Red 1 is on the stacks.
    - Bob knows that his second and third cards are red, because of a red clue that touched those cards.
    - He also knows that his third card is not rainbow, because of a yellow clue that he received before he drew the second card.
    - Alice clues 3 to Cathy, touching red 3 as a *Play Clue*.
    - Since both Bob's second and third cards have equal amounts of positive information, Bob should play the leftmost one. Bob plays the red 2 from his second slot.
    - It would be incorrect for Bob to think that, because the third card is more likely to be red 2, it should be played. Even though he knows it is exactly red, he does not take the negative information into account.

**Comment by Zamiell** [comment]
i added an example to the doc
/accept
