### ISSUE TITLE
Positional Double Bluff (for Null)

### ISSUE THREAD

**Issue by jakestiles** [Zamiell/hanabi-conventions#94]
This is a new convention proposal.

Current framework: Positional Clues are only allowed to get Null cards, and Positional play Clues may be layered.

New convention: If Alice gives a positional play clue, that causes Bob to play the requested position, and it is not the next Null card in the sequence, and Carol can see that Bob does not have the next null card layered in their hand, then Carol must heal the clue by blind playing Finesse Position 1 as a Null Pestilent Double Bluff.

Possible Problem: Unlike the Pestilent Double Bluff (Standard form), I think there should be no Disease Bluff equivalent, since null cards are harder to clue and thus harder to heal.

Example Null Pestilent Double Bluff, turn 1 of a 3 player game:

Alice clues 4 to Bob touching a 4 on slot 1. 
Bob knows that 4 Double Bluff's are turned off in Null variants so this cannot be a double bluff. Furthermore, Carol does not have Null 1 in their slot 4. So this is a positional clue on Bob, and Bob plays a non-null 1. He is surprised that was not the Null 1, but marks slot 5 in his hand as the layered Null 1.
Carol sees that Bob is not going to be able to play null 1 (because Bob doesn't have null 1). Carol blind plays slot 1 as any playable card.

Bob erases his note and no longer looks for null 1. Bob and Carol now both know the purpose of the clue was as a Null Double Bluff.

**Comment by jakestiles** [comment]
Actually should probably just be called a Postional Double Bluff (or Null Positional Double Bluff if it doesn’t work in Pink variants with pink positional). No reason to bring the Pestilent name into it since that implies a Disease equivalent which I believe should be illegal.

**Comment by Zamiell** [comment]
seems fine

**Comment by aliblong** [comment]
>Carol blind plays slot 1 as any playable card (could even be null 1).

I think if the 4 clue puts n1 on finesse, I'm waiting to play n2 on slot 4 as Bob. That's how null finesses work, right?

Also, you should apologize to Cathy for mistaking her name

**Comment by jakestiles** [comment]
Ok you’re right. Remove the “(could even be null 1)” portion of my explanation.

**Comment by Zamiell** [comment]
problem: Bob can defer blind-playing the null card and *Bluff* Cathy's *Finesse Position* card, leading to cascading failure

**Comment by Zamiell** [comment]
i change my vote to thumbs down

**Comment by jakestiles** [comment]
Are you allowed to defer playing null?

**Comment by Zamiell** [comment]
Yes, because they are "guaranteed" to be a null card so you can just do a *Finesse* or *Bluff* and play the null card later.

**Comment by jakestiles** [comment]
And no one else will think the positional was on them?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Zamiell** [comment]
In this hypothetical, from Bob's perspective, Cathy sees that Bob has the null card on the slot, so Bob is not worried. Cathy will not think that she has the null card **if** Bob is doing a *Finesse* or *Bluff* of his own.

**Comment by Zamiell** [comment]
basically i think it makes sense to not have this for the same reason that we don't have *Reverse Bluffs*.

doing this move is completely fine if the team is at 0 clues though, because then the next player will never stop to *Finesse* or *Bluff* the next card.
however, since it seems kind of edge-casey and rare, it might not be worth adding it to the doc
