### ISSUE TITLE
Clarification: Triple Bluff

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-conventions#95]
![2019-11-08_1844_(Question_triple_bluff)](https://user-images.githubusercontent.com/48993588/68521646-f2f87180-0257-11ea-9ba2-10f24be4ac55.png)

Had a review where Libster told us that browns to TheWildCard is not a triple bluff.  Zam and I at one point had to rework the triple bluff convention.  I'm putting this here so players can discuss this further.

**Comment by Dr-Kakashi** [comment]
Had some clarification:
- it is not possible to do a triple bluff with a clue that "picks-up" a 5
- 5's must already be clued to initiate a triple bluff

**Comment by Romain672** [comment]
Ok, after writing a lot, I finally isolate the problem.
Start of game.
Alice clue 4 to Donald as a double bluff.
Bob know he could have r1 in slot 1, but think the risk of this clue is worth it. He clue red to Alice as a finesse on Cathy's hand : b1-b2-r1-x.

Is Bob clue good? Same question if Donald finesse position is g1.

I think the problem of the screen is Libster who clue red to Jeff. If it isn't the case, correct me.

**Comment by Zamiell** [comment]
> * it is not possible to do a triple bluff with a clue that "picks-up" a 5
> * 5's must already be clued to initiate a triple bluff

Ok but I don't think that that is the important part. Read the first bullet point in the doc under *Triple Bluff* and it says:

> * In some situations, cluing a 5 with color initiates a special move called a *5 Color Ejection*. And in some situations, cluing a 5 with rank initiates a special move called a *5 Pull* or a *5's Chop Move*. However, if players are in a situation where none of these moves would apply, then it is possible to perform a *Triple Bluff* by giving a *Play Clue* to a 5 (with either color or number).

So thats really **all you need to know**. If you read that bullet point, and then you look at the screenshot in the OP, then you would know that 5CE > Triple Bluff, and you would know that Libster would play slot 2.

So I dont think I really need to add anything **else** to the doc here, correct me if I am wrong.

**Comment by Zamiell** [comment]
> Start of game.
> Alice clue 4 to Donald as a double bluff.
> Bob know he could have r1 in slot 1, but think the risk of this clue is worth it. He clue red to Alice on r2 as a finesse on Cathy's hand : b1-b2-r1-x.
> 
> Is Bob clue good? Same question if Donald finesse position is g1.

its probably bad because it could cause the team to get desynced. but it depends on the game, maybe it is clear what is happening and no bombs will happen. i do not think that the question is really relevant to this discussion though

**Comment by aliblong** [comment]
>Had a review where Libster told us that browns to TheWildCard is not a triple bluff. Zam and I at one point had to rework the triple bluff convention. I'm putting this here so players can discuss this further.

This is a misrepresentation of what I said. What I said is that I wasn't aware of a special case to 5CE that turns it into a triple bluff, and neither were any of the other players in the review, and that that might indicate it's not a good clause. Sounds like my intuition was correct, because that clause doesn't actually exist.

**Comment by alercah** [comment]
I personally don't see any issue with the doc here; I think it's clear that when *5CE* is used, this clue would initiate a 5CE and not a triple bluff.

**Comment by Zamiell** [comment]
closing this because kakashi isn't responding

/stale
