### ISSUE TITLE
5 Pull Ejection Convention Change

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-conventions#98]
[5 Pull Ejection Convention Change]

Two reasons we've never seen a single 5PE after it was officially approved:
1. There are few people know this convention.
2. We have a more versatile and powerful convention: 5CE.

Proposal A:
5 Pull Ejection → 5 Pull Discharge
Now you can easily call a card from slot 2 with a 5CE and slot 3 with a 5PD by touching a 5 with color or number.

Proposal B:
5 Pull Ejection → 5 Pull Double Ejection
Might not be common but could be the first double ejection in our conventions. That'll be cool.

Version 1: The pulled card is two or more away from being playable. And you should Chop Move the pulled card.

Version 2: The pulled card is either two or more away from playable or trash. (More flexible, probably)

**Comment by jakestiles** [comment]
I like A1. And I like it more than the current 5PE framework (since as you said it hasn’t been used).

**Comment by Zamiell** [comment]
A2 seems fine.
and note that this would only apply in the early game.
there is some synergy here, because discharges are probably more useful in the opening hands than in the mid-game

**Comment by Zamiell** [comment]
please consolidate discussion in #92, as this is related

**Comment by iamwhoiamhahaha** [comment]
because discharges are probably more useful in the opening hands than in the mid-game

Yeah, that's one of the reason to change to 5PD

**Comment by Zamiell** [comment]
closing this in favor of the other issue
