### ISSUE TITLE
Change "Hard and Easy Variants" to "Consistency Conventions"

### ISSUE THREAD

**Issue by alercah** [Zamiell/hanabi-conventions#99]
I have two issues with "Hard" and "Easy" variant conventions as they currently stand:

1. The "Easy" conventions are actually harder, because they add a number of headspace conventions (*Double Discard Avoidance*, *5 Stall* and other *Early Game* conventions).
2. The harder "Easy" conventions are the ones that get played with when introducing new players usually, because that tends to be on easier variants.

The history here is that these conventions were developed to increase win consistency by mitigating the risk of losing critical cards, at the cost of some clue efficiency. But in variants that require higher efficiency, they actually reduce the win rate because the efficiency cost is too high, so it evolved that those variants drop these conventions.

Thus, I suggest the following changes:

1. Remove the concept of "Easy" and "Hard" variants.
2. Move the existing "Easy Variant" conventions to a new section, entitled "Consistency Conventions".
3. Make Consistency Conventions explicitly opt-in for the group, with some notes about which variants they are likely to be played in.

**Comment by Zamiell** [comment]
"consistency" conventions are only turned off for a player's first 0-20 games. the mast majority of games are not with absolute noobs, so changing them to be opt-in by default doesn't really make sense

**Comment by alercah** [comment]
Why should they only be turned off for the first however many games, though? Given the way the group plays currently with wild variants, I think it makes more sense to "Graduate" a player into harder variants, rather than into new conventions that will be useless as soon as they start playing the harder ones anyway.

**Comment by Zamiell** [comment]
the group plays a mix of both easy and hard variants in roughly an equal manner, so if you think that easy conventions become useless then that is a misconception

**Comment by alercah** [comment]
That's a fair argument. I think the terminology change is still worthwhile even if we leave the rules for when to play with them the same.

**Comment by Zamiell** [comment]
"easy" and "hard" are fairly mnemonic
not a fan of saying words with a ton of syllables over just something simple

**Comment by alercah** [comment]
Except they're not because the easy variant conventions are the hard ones.

**Comment by Zamiell** [comment]
well no-one else seems to have chimed in so lets keep it the way that it is for now
/deny
